### ISSUE TITLE
Add missing playstate "0"

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#115]
With tvOS 11, it seems like playstate "0" is used. Not sure what it represents, but it needs to be added because it causes exceptions:
```
2017-09-20 14:10:29 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File “/usr/lib/python3.6/asyncio/tasks.py”, line 179, in _step
result = coro.send(None)
File “/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py”, line 239, in async_update_ha_state
state = self.state
File “/usr/lib/python3.6/site-packages/homeassistant/components/media_player/apple_tv.py”, line 98, in state
state = self._playing.play_state
File “/usr/lib/python3.6/site-packages/pyatv/internal/apple_tv.py”, line 245, in play_state
return convert.playstate(state)
File “/usr/lib/python3.6/site-packages/pyatv/convert.py”, line 48, in playstate
raise exceptions.UnknownPlayState('Unknown playstate: ’ + str(state))
pyatv.exceptions.UnknownPlayState: Unknown playstate: 0
```

**Comment by postlund** [comment]
Fixed now. It will be part of 0.3.5 that I hopefully get out tomorrow.

**Comment by jeliasson** [comment]
0.54.0
```py
ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 239, in async_update_ha_state
    state = self.state
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/media_player/apple_tv.py", line 98, in state
    state = self._playing.play_state
  File "/srv/homeassistant/lib/python3.5/site-packages/pyatv/internal/apple_tv.py", line 245, in play_state
    return convert.playstate(state)
  File "/srv/homeassistant/lib/python3.5/site-packages/pyatv/convert.py", line 48, in playstate
    raise exceptions.UnknownPlayState('Unknown playstate: ' + str(state))
pyatv.exceptions.UnknownPlayState: Unknown playstate: 0
```

**Comment by postlund** [comment]
You will have to wait until next release, run from dev or apply content from this PR: https://github.com/home-assistant/home-assistant/pull/9586

**Comment by jeliasson** [comment]
Thanks @postlund!
