### ISSUE TITLE
Work-around for unstable installations in tox

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#1174]
**Short feature/function description**
Pretty often builds fail due to a dependency not being installed correctly, most because the cache is either broken or the file did not download properly for some reason. I've only seen this on GitHub Actions. One example might look like this:

```raw
...
021-06-24T10:46:59.7774887Z Building wheels for collected packages: bitarray, bitstruct, netifaces, pendulum
2021-06-24T10:46:59.7775783Z   Building wheel for bitarray (setup.py): started
2021-06-24T10:46:59.7776538Z   Building wheel for bitarray (setup.py): finished with status 'done'
2021-06-24T10:46:59.7778028Z   Created wheel for bitarray: filename=bitarray-2.1.3-cp39-cp39-win_amd64.whl size=88059 sha256=9e7b212f1ea2435ade79c40e844bea0d9eab8c73e0abfcb241169afd83cd790c
2021-06-24T10:46:59.7779783Z   Stored in directory: c:\users\runneradmin\appdata\local\pip\cache\wheels\2f\9f\38\49634590b5fa098c6461a8afb07bfb8e34c8ab9c106171313d
2021-06-24T10:46:59.7781086Z   Building wheel for bitstruct (setup.py): started
2021-06-24T10:46:59.7781949Z   Building wheel for bitstruct (setup.py): finished with status 'done'
2021-06-24T10:46:59.7783512Z   Created wheel for bitstruct: filename=bitstruct-8.11.1-cp39-cp39-win_amd64.whl size=23832 sha256=0dc7962f510e5e490ac628f5c7bf9aa840937a15ef89ee0eb5d9733040847814
2021-06-24T10:46:59.7785733Z   Stored in directory: c:\users\runneradmin\appdata\local\pip\cache\wheels\bc\f2\ee\0b2b46de7328887e333dd4b64c148b7ccb7ab8c763bae5dc14
2021-06-24T10:46:59.7787003Z   Building wheel for netifaces (setup.py): started
2021-06-24T10:46:59.7787877Z   Building wheel for netifaces (setup.py): finished with status 'done'
2021-06-24T10:46:59.7865118Z   Created wheel for netifaces: filename=netifaces-0.11.0-cp39-cp39-win_amd64.whl size=16532 sha256=9dc9135a86b437147c2cd2f040484b022792c0a03e8f5346e41bec984673502f
2021-06-24T10:46:59.7880703Z   Stored in directory: c:\users\runneradmin\appdata\local\pip\cache\wheels\4f\77\60\d721ffbafc28e5021f94207ac09dbc23ecde96b4f74a324106
2021-06-24T10:46:59.7907528Z ERROR: Exception:
2021-06-24T10:46:59.8142701Z Traceback (most recent call last):
2021-06-24T10:46:59.8165002Z   File "D:\a\pyatv\pyatv\.tox\docs\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
2021-06-24T10:46:59.8167630Z     status = self.run(options, args)
2021-06-24T10:46:59.8175608Z   File "D:\a\pyatv\pyatv\.tox\docs\lib\site-packages\pip\_internal\cli\req_command.py", line 204, in wrapper
2021-06-24T10:46:59.8179601Z     return func(self, options, args)
2021-06-24T10:46:59.8183408Z   File "D:\a\pyatv\pyatv\.tox\docs\lib\site-packages\pip\_internal\commands\install.py", line 345, in run
2021-06-24T10:46:59.8211657Z     _, build_failures = build(
2021-06-24T10:46:59.8227988Z   File "D:\a\pyatv\pyatv\.tox\docs\lib\site-packages\pip\_internal\wheel_builder.py", line 336, in build
2021-06-24T10:46:59.8398498Z     wheel_file = _build_one(
2021-06-24T10:46:59.8399784Z   File "D:\a\pyatv\pyatv\.tox\docs\lib\site-packages\pip\_internal\wheel_builder.py", line 228, in _build_one
2021-06-24T10:46:59.8405374Z     _verify_one(req, wheel_path)
2021-06-24T10:46:59.8406743Z   File "D:\a\pyatv\pyatv\.tox\docs\lib\site-packages\pip\_internal\wheel_builder.py", line 177, in _verify_one
2021-06-24T10:46:59.8408033Z     dist = get_wheel_distribution(wheel_path, canonical_name)
2021-06-24T10:46:59.8409364Z   File "D:\a\pyatv\pyatv\.tox\docs\lib\site-packages\pip\_internal\metadata\__init__.py", line 43, in get_wheel_distribution
2021-06-24T10:46:59.8410731Z     return Distribution.from_wheel(wheel_path, canonical_name)
2021-06-24T10:46:59.8412169Z   File "D:\a\pyatv\pyatv\.tox\docs\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 23, in from_wheel
2021-06-24T10:46:59.8413600Z     with zipfile.ZipFile(path, allowZip64=True) as zf:
2021-06-24T10:46:59.8414845Z   File "c:\hostedtoolcache\windows\python\3.9.5\x64\lib\zipfile.py", line 1257, in __init__
2021-06-24T10:46:59.8416495Z     self._RealGetContents()
2021-06-24T10:46:59.8435362Z   File "c:\hostedtoolcache\windows\python\3.9.5\x64\lib\zipfile.py", line 1324, in _RealGetContents
2021-06-24T10:46:59.8436512Z     raise BadZipFile("File is not a zip file")
2021-06-24T10:46:59.8438426Z zipfile.BadZipFile: File is not a zip file
2021-06-24T10:46:59.8439272Z 
2021-06-24T10:46:59.8440104Z =================================== log end ===================================
2021-06-24T10:46:59.8441339Z 
2021-06-24T10:46:59.8458898Z =================================== log end ===================================
2021-06-24T10:49:23.9102903Z \u2716 FAIL docs in 1 minute, 14.75 seconds\r\n\u2714 OK generated in 1 minute, 12.478 seconds\r\n\u2714 OK codestyle in 46.738 seconds\r\n\u2714 OK pylint in 1 minute, 21.735 seconds\r\n\u2714 OK typing in 48.622 seconds\r\n\u2714 OK py39 in 47.885 seconds\r\n\u2714 OK report in 5.999 seconds\r\n___________________________________ summary ___________________________________
2021-06-24T10:49:23.9104834Z   clean: commands succeeded
2021-06-24T10:49:23.9105507Z ERROR:   docs: parallel child exit code 1
2021-06-24T10:49:23.9106230Z   generated: commands succeeded
2021-06-24T10:49:23.9106985Z   codestyle: commands succeeded
2021-06-24T10:49:23.9107621Z   pylint: commands succeeded
2021-06-24T10:49:23.9108280Z   typing: commands succeeded
2021-06-24T10:49:23.9109499Z   py39: commands succeeded
2021-06-24T10:49:23.9110089Z   report: commands succeeded
2021-06-24T10:49:26.8862275Z \u2714 OK clean in 1.15 seconds\r\nERROR: invocation failed (exit code 1), logfile: D:\a\pyatv\pyatv\.tox\docs\log\docs-4.log
2021-06-24T10:49:26.8864175Z ================================== log start ==================================
2021-06-24T10:49:26.8865350Z Traceback (most recent call last):
2021-06-24T10:49:26.8901666Z   File "D:\a\pyatv\pyatv\.tox\docs\lib\site-packages\pdoc\__init__.py", line 225, in import_module
2021-06-24T10:49:26.8910787Z     module = importlib.import_module(module_path)
2021-06-24T10:49:26.8927962Z   File "c:\hostedtoolcache\windows\python\3.9.5\x64\lib\importlib\__init__.py", line 127, in import_module
2021-06-24T10:49:26.9712911Z     return _bootstrap._gcd_import(name[level:], package, level)
2021-06-24T10:49:26.9723037Z   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2021-06-24T10:49:26.9727128Z   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2021-06-24T10:49:26.9787278Z   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2021-06-24T10:49:26.9813933Z   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2021-06-24T10:49:26.9914811Z   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
2021-06-24T10:49:26.9997078Z   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2021-06-24T10:49:27.0129132Z   File "D:\a\pyatv\pyatv\pyatv\__init__.py", line 11, in <module>
2021-06-24T10:49:27.0140709Z     from pyatv import conf, exceptions, interface
2021-06-24T10:49:27.0143980Z   File "D:\a\pyatv\pyatv\pyatv\conf.py", line 15, in <module>
2021-06-24T10:49:27.0156115Z     from pyatv.interface import BaseService, DeviceInfo
2021-06-24T10:49:27.0163442Z   File "D:\a\pyatv\pyatv\pyatv\interface.py", line 37, in <module>
2021-06-24T10:49:27.0170546Z     from pyatv.support.http import ClientSessionManager
2021-06-24T10:49:27.0174110Z   File "D:\a\pyatv\pyatv\pyatv\support\http.py", line 17, in <module>
2021-06-24T10:49:27.0217336Z     from pyatv.support.net import unused_port
2021-06-24T10:49:27.0234086Z   File "D:\a\pyatv\pyatv\pyatv\support\net.py", line 10, in <module>
2021-06-24T10:49:27.0348505Z     import netifaces
2021-06-24T10:49:27.0360702Z ModuleNotFoundError: No module named 'netifaces'
2021-06-24T10:49:27.0381417Z 
2021-06-24T10:49:27.0476852Z During handling of the above exception, another exception occurred:
2021-06-24T10:49:27.0482243Z 
2021-06-24T10:49:27.0488382Z Traceback (most recent call last):
2021-06-24T10:49:27.0491921Z   File "D:\a\pyatv\pyatv\scripts\api.py", line 106, in <module>
2021-06-24T10:49:27.0508838Z     sys.exit(main())
2021-06-24T10:49:27.0510840Z   File "D:\a\pyatv\pyatv\scripts\api.py", line 100, in main
2021-06-24T10:49:27.0517382Z     return verify()
2021-06-24T10:49:27.0520574Z   File "D:\a\pyatv\pyatv\scripts\api.py", line 66, in verify
2021-06-24T10:49:27.0563915Z     for output_file, html in _api_modules():
2021-06-24T10:49:27.0579790Z   File "D:\a\pyatv\pyatv\scripts\api.py", line 40, in _api_modules
2021-06-24T10:49:27.0675327Z     modules = [
2021-06-24T10:49:27.0696119Z   File "D:\a\pyatv\pyatv\scripts\api.py", line 41, in <listcomp>
2021-06-24T10:49:27.0789770Z     pdoc.Module(mod, context=context, docfilter=_filter_func) for mod in modules
2021-06-24T10:49:27.0800875Z   File "D:\a\pyatv\pyatv\.tox\docs\lib\site-packages\pdoc\__init__.py", line 609, in __init__
2021-06-24T10:49:27.0804590Z     module = import_module(module)
2021-06-24T10:49:27.0822208Z   File "D:\a\pyatv\pyatv\.tox\docs\lib\site-packages\pdoc\__init__.py", line 227, in import_module
2021-06-24T10:49:27.0829094Z     raise ImportError('Error importing {!r}: {}: {}'
2021-06-24T10:49:27.0832817Z ImportError: Error importing 'pyatv': ModuleNotFoundError: No module named 'netifaces'
2021-06-24T10:49:27.0863051Z ##[group]tox: docs
2021-06-24T10:49:27.0864363Z ERROR: InvocationError for command 'D:\a\pyatv\pyatv\.tox\docs\Scripts\python.EXE' scripts/api.py verify (exited with code 1)
2021-06-24T10:49:27.0865950Z ##[endgroup]
...
```

It would be convenient to try again, as all other jobs fail and the entire workflow must be restarted when this happens.

**What needs to be done?**
I have previously tried to just re-start tox on failure but that didn't work. I guess that the broken file was cached and caused the problem again. One idea I have is to force re-downloading packages the second run, in case the first one failed. It's supposed to be possible to change the `pip` command using `install_command`, so I can just throw `--no-cache-dir` in there in that case. I would need an option for that though, so it's not always enabled.

**Is this a breaking change?**
No

**Anything else worth knowing?**
No

**Comment by postlund** [comment]
The reason for this might be that the environments share the same cache and run in parallel, with no knowledge of each other. So there's a small risk that they overwrite each others packages, possibly breaking them. It's a theory at least, not sure why it would happen so often on Actions but not locally though.

**Comment by postlund** [comment]
I believe the changes I've made has improved the main case here, but I do seem to have a few unstable tests. So I will have to look into that, but will do that separately.
