### ISSUE TITLE
atvremote play_url error

### ISSUE THREAD

**Issue by leokwu** [postlund/pyatv#1188]
**What's on your heart?**
1、atvremote --debug scan

Scan Results
========================================
       Name: 12345678
   Model/SW: Gen3 Unknown OS
    Address: 172.16.9.13
        MAC: 44:E0:0A:78:61:9E
 Deep Sleep: False
Identifiers:
 - 44e00a78619e
 - 44:e0:0a:78:61:9e
Services:
 - Protocol: RAOP, Port: 52244, Credentials: None
 - Protocol: AirPlay, Port: 52244, Credentials: None

       Name: HAGiBiS-ac64cf540420-ITV
   Model/SW: Gen3 Unknown OS
    Address: 192.168.49.1
        MAC: AC:64:CF:54:04:20
 Deep Sleep: False
Identifiers:
 - AC:64:CF:54:04:20
 - AC64CF540420
Services:
 - Protocol: AirPlay, Port: 5000, Credentials: None
 - Protocol: RAOP, Port: 5000, Credentials: None

2、atvremote --debug -i AC64CF540420 play_url=/home/wuli/test.mp4

2021-07-01 16:33:25 DEBUG [pyatv.support.net]: Binding on *:5353
2021-07-01 16:33:25 DEBUG [pyatv.support.net]: Binding on 127.0.0.1:0
2021-07-01 16:33:25 DEBUG [pyatv.support.net]: Binding on 172.16.9.212:0
2021-07-01 16:33:25 DEBUG [pyatv.support.net]: Binding on 192.168.29.1:0
2021-07-01 16:33:25 DEBUG [pyatv.support.net]: Binding on 172.16.108.1:0
2021-07-01 16:33:25 DEBUG [pyatv.support.net]: Binding on 192.168.49.20:0
2021-07-01 16:33:25 DEBUG [pyatv.support.scan]: Auto-discovered HAGiBiS-ac64cf540420-ITV at 192.168.49.1:5000 (Protocol.AirPlay)
2021-07-01 16:33:25 DEBUG [pyatv.support.scan]: Auto-discovered HAGiBiS-ac64cf540420-ITV at 192.168.49.1:5000 (Protocol.RAOP)
2021-07-01 16:33:25 INFO [root]: Auto-discovered HAGiBiS-ac64cf540420-ITV at 192.168.49.1
2021-07-01 16:33:25 DEBUG [pyatv.airplay]: No AirPlay credentials loaded
2021-07-01 16:33:25 DEBUG [pyatv]: Adding protocol Protocol.AirPlay
2021-07-01 16:33:25 DEBUG [pyatv]: Adding protocol Protocol.RAOP
2021-07-01 16:33:25 DEBUG [pyatv.airplay]: URL /home/wuli/test.mp4 is a local file, setting up web server
2021-07-01 16:33:25 DEBUG [pyatv.support.http]: Starting AirPlay file server on port 33505
2021-07-01 16:33:25 DEBUG [pyatv.support.http]: Connected to 192.168.49.1
2021-07-01 16:33:25 DEBUG [pyatv.airplay.player]: Starting to play http://192.168.49.20:33505/test.mp4
2021-07-01 16:33:25 DEBUG [pyatv.support.http]: Sending HTTP/1.1 message: b'POST /play HTTP/1.1\r\nContent-Length: 188\r\nUser-Agent: MediaControl/1.0\r\nContent-Type: application/x-apple-binary-plist\r\n\r\nbplist00\xd3\x01\x02\x03\x04\x05\x06_\x10\x10Content-Location^Start-Position_\x10\x12X-Apple-Session-ID_\x10#http://192.168.49.20:33505/test.mp4\x10\x00_\x10$0013a36f-6cd7-4652-bdc2-bf17805d04a1\x08\x0f"1Fln\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x95'
2021-07-01 16:33:26 DEBUG [pyatv.support.http]: Connection closed
2021-07-01 16:33:29 DEBUG [pyatv.support.http]: Closing local AirPlay web server
Traceback (most recent call last):
  File "/home/wuli/work/smart/ios/pyatv/pyatv/support/http.py", line 369, in send_and_receive
    await asyncio.wait_for(event.wait(), timeout=4)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wuli/work/smart/ios/pyatv/pyatv/scripts/atvremote.py", line 698, in _run_application
    return await cli_handler(loop)
  File "/home/wuli/work/smart/ios/pyatv/pyatv/scripts/atvremote.py", line 487, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/home/wuli/work/smart/ios/pyatv/pyatv/scripts/atvremote.py", line 596, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/home/wuli/work/smart/ios/pyatv/pyatv/scripts/atvremote.py", line 638, in _handle_device_command
    return await _exec_command(atv.stream, cmd, True, *cmd_args)
  File "/home/wuli/work/smart/ios/pyatv/pyatv/scripts/atvremote.py", line 664, in _exec_command
    value = await tmp(*args)
  File "/home/wuli/work/smart/ios/pyatv/pyatv/support/facade.py", line 326, in play_url
    await self.relay("play_url")(url, **kwargs)
  File "/home/wuli/work/smart/ios/pyatv/pyatv/airplay/__init__.py", line 105, in play_url
    return await self._play_task
  File "/home/wuli/work/smart/ios/pyatv/pyatv/airplay/player.py", line 46, in play_url
    allow_error=True,
  File "/home/wuli/work/smart/ios/pyatv/pyatv/support/http.py", line 341, in post
    "POST", path, headers=headers, body=body, allow_error=allow_error
  File "/home/wuli/work/smart/ios/pyatv/pyatv/support/http.py", line 372, in send_and_receive
    raise TimeoutError(f"no response to {method} {uri} ({protocol})") from ex
TimeoutError: no response to POST /play (HTTP/1.1)

>>> An error occurred, full stack trace above

Iphones can be connected via airplay，but there is an appeal error when connecting and sending video stream with pyatv.
Has anyone encountered the same problem？ Can you please help me check the problem?

thks.

**Comment by postlund** [comment]
What kind of devices are those? Doesn't look like Apple TVs as they lack any of the relevant protocols.

**Comment by postlund** [comment]
Ping
