### ISSUE TITLE
Latest TVOS  "playing" issue

### ISSUE THREAD

**Issue by raufis27** [postlund/pyatv#120]
Here is output :

atvremote --address ..... --login_id ..... playing
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyatv/__main__.py", line 420, in _run_application
    return (yield from cli_handler(loop))
  File "/usr/local/lib/python3.5/dist-packages/pyatv/__main__.py", line 257, in cli_handler
    return (yield from _handle_commands(args, loop))
  File "/usr/local/lib/python3.5/dist-packages/pyatv/__main__.py", line 331, in _handle_commands
    ret = yield from _handle_device_command(args, cmd, atv, loop)
  File "/usr/local/lib/python3.5/dist-packages/pyatv/__main__.py", line 362, in _handle_device_command
    atv.metadata, cmd, True, *cmd_args))
  File "/usr/local/lib/python3.5/dist-packages/pyatv/__main__.py", line 392, in _exec_command
    _pretty_print(value)
  File "/usr/local/lib/python3.5/dist-packages/pyatv/__main__.py", line 410, in _pretty_print
    print(data)
  File "/usr/local/lib/python3.5/dist-packages/pyatv/interface.py", line 135, in __str__
    convert.playstate_str(self.play_state)))
  File "/usr/local/lib/python3.5/dist-packages/pyatv/internal/apple_tv.py", line 245, in play_state
    return convert.playstate(state)
  File "/usr/local/lib/python3.5/dist-packages/pyatv/convert.py", line 48, in playstate
    raise exceptions.UnknownPlayState('Unknown playstate: ' + str(state))
pyatv.exceptions.UnknownPlayState: Unknown playstate: 0

>>> An error occurred, full stack trace above

**Comment by raufis27** [comment]
Updated to latest release. PlayState 0 problem solved. But here is output:

Media type: Unknown
Play state: Unsupported
    Repeat: Off
   Shuffle: False

**Comment by postlund** [comment]
Did you run from dev branch or did you just bump the pyatv version?

**Comment by postlund** [comment]
Oh, this was from atvremote. Can you run again with --debug and paste the result?

**Comment by postlund** [comment]
Yeah, I can see that I forgot to add the string conversion. I’ll fix that. This however does not affect home assistant, so you should be fine there.

**Comment by raufis27** [comment]
Thank you for quick reply. I use OpenHab and run command in terminal to get “what is playing”.

**Comment by postlund** [comment]
Ah, ok, I understand. I’m gonna have a few hours on a bus now so I’ll see if I can make a release on-the-go.

**Comment by postlund** [comment]
Release 0.3.6 is out now with a fix. Please give it a spin!

**Comment by raufis27** [comment]
All good. Thank you!

**Comment by postlund** [comment]
Cool, cool! I’ll close the issue.
