### ISSUE TITLE
Apple has removed service used by Companion in tvOS 15

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#1227]
**Describe the bug**
Based on tests in #1168, Apple seems to have removed the `com.apple.tvremoteservices` service which makes Companion fail to initialize. Hopefully that can be sorted out in that issue, just using this as place holder.

**To Reproduce**
Perform any action via companion, e.g. turn_off, towards a device running tvOS 15 beta. Will yield something like this:

```log
$ atvremote --debug -s 192.168.2.57 --scan-protocols companion,airplay --companion-credentials xxx:xxx:xxx:xxx turn_off
2021-07-20 12:44:11 DEBUG [pyatv.support.knock]: Knocking at ports [3689, 7000, 49152, 32498] on 192.168.2.57
2021-07-20 12:44:11 DEBUG [pyatv.support.scan]: Auto-discovered Lounge TV at 192.168.2.57:49153 via Protocol.Companion ({'rpmac': '2', 'rphn': '0db8852909ab', 'rpfl': '0xB6782', 'rpha': '81293fa443eb', 'rpmd': 'AppleTV11,1', 'rpvr': '300.56', 'rpad': 'a148c38c5c6b', 'rphi': 'db1935087fe2', 'rpba': '11:03:AE:BF:59:8B', 'rpmrtid': '51F9F01D-BD50-44B6-AB2B-E70D043F4B36'})
2021-07-20 12:44:11 DEBUG [pyatv.support.scan]: Auto-discovered Lounge TV at 192.168.2.57:7000 via Protocol.AirPlay ({'acl': '0', 'btaddr': '58:D3:49:EA:0E:55', 'deviceid': '58:D3:49:E9:3B:82', 'fex': '1d9/St5/Fbw', 'features': '0x4A7FDFD5,0xBC157FDE', 'flags': '0x18644', 'gid': '45EE8938-2CDE-4291-B05E-568CADAD7FC0', 'igl': '1', 'gcgl': '1', 'model': 'AppleTV11,1', 'protovers': '1.1', 'pi': 'ce895475-1870-4861-a148-fa06346fde9b', 'psi': '51F9F01D-BD50-44B6-AB2B-E70D043F4B36', 'pk': 'e88b266050c28b2206d48275e373eb72fb2c1f03c133a54810d0da2c49ea44bb', 'srcvers': '566.15.1', 'osvers': '15.0', 'vv': '2'})
2021-07-20 12:44:11 INFO [root]: Auto-discovered Lounge TV at 192.168.2.57
2021-07-20 12:44:11 DEBUG [pyatv]: Adding protocol Protocol.Companion
2021-07-20 12:44:11 DEBUG [pyatv.airplay]: No AirPlay credentials loaded
2021-07-20 12:44:11 DEBUG [pyatv]: Adding protocol Protocol.AirPlay
NOTE: Push updates are not supported in this configuration
2021-07-20 12:44:11 DEBUG [pyatv.companion]: Connect to Companion from API
2021-07-20 12:44:11 DEBUG [pyatv.companion.connection]: Connected to companion device 192.168.2.57:49153
2021-07-20 12:44:11 DEBUG [pyatv.companion.protocol]: Companion credentials: xxx:xxx:xxx:xxx
2021-07-20 12:44:11 DEBUG [pyatv.companion.protocol]: Send OPACK: {'_pd': b'\x06\x01\x01\x03 \xd9U\xb0\xdf\x8a\xffF\xfd\x19\xd59Hj\xd3\xfb2\xc6\xd0\xfb\xb6w\x10R\xb1\x08\xdc\x1d\xfdi\x8a\xa5\x0c', '_auTy': 4}
2021-07-20 12:44:11 DEBUG [pyatv.companion.connection]: >> Send data (Data=e2435f706491250601010320d955b0df8aff46fd19d539486ad3fb32c6d0fbb6771052b108dc1dfd698aa50c455f617554790c, FrameType=05)
2021-07-20 12:44:11 DEBUG [pyatv.companion.connection]: Received data (Data=060000a6e1435f7064919f0578a75d998d670dfe478fa6e4e02e48b351d4c283dcab999db6ccc74f507a60e281e2ef77a3b99d2dd5d58c74121c56c9ef5351fa8bb2ce35eb96d2f568b97152014433421b53bf4ed23ea10158c7b6e531dfea9173eeb181ea798c8b754e9630055076604f475939ee87ffda2988708a55a0f173cc4eb8cf7106010203207bce874d37c83d23a592e1659afd3b16bc7e2d28eccaba1b2bd7e074174d0c10)
2021-07-20 12:44:11 DEBUG [pyatv.companion.connection]: Recv data (Data=060000a6e1435f7064919f0578a75d998d670dfe478fa6e4e02e48b351d4c283dcab999db6ccc74f507a60e281e2ef77a3b99d2dd5d58c74121c56c9ef5351fa8bb2ce35eb96d2f568b97152014433421b53bf4ed23ea10158c7b6e531dfea9173eeb181ea798c8b754e9630055076604f475939ee87ffda2988708a55a0f173cc4eb8cf7106010203207bce874d37c83d23a592e1659afd3b16bc7e2d28eccaba1b2bd7e074174d0c10)
2021-07-20 12:44:11 DEBUG [pyatv.companion.protocol]: Receive OPACK: {'_pd': b'\x05x\xa7]\x99\x8dg\r\xfeG\x8f\xa6\xe4\xe0.H\xb3Q\xd4\xc2\x83\xdc\xab\x99\x9d\xb6\xcc\xc7OPz`\xe2\x81\xe2\xefw\xa3\xb9\x9d-\xd5\xd5\x8ct\x12\x1cV\xc9\xefSQ\xfa\x8b\xb2\xce5\xeb\x96\xd2\xf5h\xb9qR\x01D3B\x1bS\xbfN\xd2>\xa1\x01X\xc7\xb6\xe51\xdf\xea\x91s\xee\xb1\x81\xeay\x8c\x8buN\x960\x05Pv`OGY9\xee\x87\xff\xda)\x88p\x8aU\xa0\xf1s\xccN\xb8\xcfq\x06\x01\x02\x03 {\xce\x87M7\xc8=#\xa5\x92\xe1e\x9a\xfd;\x16\xbc~-(\xec\xca\xba\x1b+\xd7\xe0t\x17M\x0c\x10'}
2021-07-20 12:44:11 DEBUG [pyatv.companion.auth]: Device (Encrypted=a75d998d670dfe478fa6e4e02e48b351d4c283dcab999db6ccc74f507a60e281e2ef77a3b99d2dd5d58c74121c56c9ef5351fa8bb2ce35eb96d2f568b97152014433421b53bf4ed23ea10158c7b6e531dfea9173eeb181ea798c8b754e9630055076604f475939ee87ffda2988708a55a0f173cc4eb8cf71, Public=xxx)
2021-07-20 12:44:11 DEBUG [pyatv.companion.protocol]: Send OPACK: {'_pd': b'\x06\x01\x03\x05x\xbc"\xfe\xac\x18f\x00\xa4*.n\x82r\xa9rvMp\xc2g\xabx\xee\xe6U\xf8\xa6#\x12Sg\xab\x14k\x80\x84\xac\xaa\x8cX6\xec\xee`\xf8b`g+\x1f\x1d\xe8"\xad\x8c\xc7\xb4\x06\xacd\x80\xe1"\x86\x06P\xb2d\x02\xd7\xccRr\xcd\xe5$GGg\xfeS\xd0\xac\xe4\xd7Cw\xfc\xa8R\x02\xeai\xcf\x171|.[\t\x94\xbar\x94\x81\x03\xd4\x7ft\xeb\x95\xb7\xc96;\xf3}\xdfD\xc6'}
2021-07-20 12:44:11 DEBUG [pyatv.companion.connection]: >> Send data (Data=e1435f7064917d0601030578bc22feac186600a42a2e6e8272a972764d70c267ab78eee655f8a623125367ab146b8084acaa8c5836ecee60f86260672b1f1de822ad8cc7b406ac6480e122860650b26402d7cc5272cde524474767fe53d0ace4d74377fca85202ea69cf17317c2e5b0994ba72948103d47f74eb95b7c9363bf37ddf44c6, FrameType=06)
2021-07-20 12:44:11 DEBUG [pyatv.companion.connection]: Received data (Data=06000009e1435f706473060104)
2021-07-20 12:44:11 DEBUG [pyatv.companion.connection]: Recv data (Data=06000009e1435f706473060104)
2021-07-20 12:44:11 DEBUG [pyatv.companion.protocol]: Receive OPACK: {'_pd': b'\x06\x01\x04'}
2021-07-20 12:44:11 DEBUG [pyatv.support.hap_srp]: Keys (Input=84999eccada26934f7930739a81c311107ecc4016d9640f6aa6ee00965147252, Output=45db819df2be47df1a3e077328ba2e6625f97938ce8b7451bdc99d390a2931f8)
2021-07-20 12:44:11 DEBUG [pyatv.companion.protocol]: Send OPACK: {'_i': '_sessionStart', '_x': 12356, '_t': '2', '_c': {'_srvT': 'com.apple.tvremoteservices', '_sid': 129352063}}
2021-07-20 12:44:11 DEBUG [pyatv.companion.connection]: >> Send data (Data=e4425f694d5f73657373696f6e5374617274425f78314430425f744132425f63e2455f737276545a636f6d2e6170706c652e747672656d6f74657365727669636573445f736964327fc1b507, FrameType=08)
2021-07-20 12:44:11 DEBUG [pyatv.companion.connection]: >> Send (Encrypted=2fd67a56cd0f6d192dc2487259150354a75490a0b66959b3f7595b13fef2fafe2d97afee257b4694c7f0f4dc9339e925a146537118e57bbe8a88b28c356c7bc47c59ee984e83169fa42da45cedd7a7e38beed3baa52720cf1d62f0c2, Header=0800005c)
2021-07-20 12:44:11 DEBUG [pyatv.companion.connection]: Received data (Data=080000570a7a4d3e4938c0163e7a5efaf4c3d7c2fe7962645de78babdfad44ea219697755e03464779c2951335fd583522591579691b5258554a0ea5e20df6a1b3976ee1e1342ab665afbbddfe1ed190cc5f144976bd8c0508a646)
2021-07-20 12:44:11 DEBUG [pyatv.companion.connection]: Recv data (Data=080000570a7a4d3e4938c0163e7a5efaf4c3d7c2fe7962645de78babdfad44ea219697755e03464779c2951335fd583522591579691b5258554a0ea5e20df6a1b3976ee1e1342ab665afbbddfe1ed190cc5f144976bd8c0508a646)
2021-07-20 12:44:11 DEBUG [pyatv.companion.connection]: << Receive data (Decrypted=e6425f78314430435f656d58556e737570706f7274656420736572766963652074797065435f65633203eafeff435f65644d52504572726f72446f6d61696e425f63e0425f740b, Header=08000057)
2021-07-20 12:44:11 DEBUG [pyatv.companion.protocol]: Receive OPACK: {'_x': 12356, '_em': 'Unsupported service type', '_ec': 4294896131, '_ed': 'RPErrorDomain', '_c': {}, '_t': 3}
Traceback (most recent call last):
  File "/home/mike/tmp/pyatv/venv/lib/python3.9/site-packages/pyatv-0.8.1-py3.9.egg/pyatv/scripts/atvremote.py", line 708, in _run_application
    return await cli_handler(loop)
  File "/home/mike/tmp/pyatv/venv/lib/python3.9/site-packages/pyatv-0.8.1-py3.9.egg/pyatv/scripts/atvremote.py", line 497, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/home/mike/tmp/pyatv/venv/lib/python3.9/site-packages/pyatv-0.8.1-py3.9.egg/pyatv/scripts/atvremote.py", line 606, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/home/mike/tmp/pyatv/venv/lib/python3.9/site-packages/pyatv-0.8.1-py3.9.egg/pyatv/scripts/atvremote.py", line 641, in _handle_device_command
    return await _exec_command(atv.power, cmd, True, *cmd_args)
  File "/home/mike/tmp/pyatv/venv/lib/python3.9/site-packages/pyatv-0.8.1-py3.9.egg/pyatv/scripts/atvremote.py", line 674, in _exec_command
    value = await tmp(*args)
  File "/home/mike/tmp/pyatv/venv/lib/python3.9/site-packages/pyatv-0.8.1-py3.9.egg/pyatv/support/facade.py", line 308, in turn_off
    await self.relay("turn_off", priority=self.OVERRIDE_PRIORITIES)(
  File "/home/mike/tmp/pyatv/venv/lib/python3.9/site-packages/pyatv-0.8.1-py3.9.egg/pyatv/companion/__init__.py", line 247, in turn_off
    await self.api.sleep()
  File "/home/mike/tmp/pyatv/venv/lib/python3.9/site-packages/pyatv-0.8.1-py3.9.egg/pyatv/companion/__init__.py", line 168, in sleep
    await self._hid_command(False, HidCommand.Sleep)
  File "/home/mike/tmp/pyatv/venv/lib/python3.9/site-packages/pyatv-0.8.1-py3.9.egg/pyatv/companion/__init__.py", line 175, in _hid_command
    await self._send_command(
  File "/home/mike/tmp/pyatv/venv/lib/python3.9/site-packages/pyatv-0.8.1-py3.9.egg/pyatv/companion/__init__.py", line 127, in _send_command
    await self._connect()
  File "/home/mike/tmp/pyatv/venv/lib/python3.9/site-packages/pyatv-0.8.1-py3.9.egg/pyatv/companion/__init__.py", line 115, in _connect
    await self._session_start()
  File "/home/mike/tmp/pyatv/venv/lib/python3.9/site-packages/pyatv-0.8.1-py3.9.egg/pyatv/companion/__init__.py", line 150, in _session_start
    resp = await self._send_command(
  File "/home/mike/tmp/pyatv/venv/lib/python3.9/site-packages/pyatv-0.8.1-py3.9.egg/pyatv/companion/__init__.py", line 132, in _send_command
    resp = await self._protocol.exchange_opack(
  File "/home/mike/tmp/pyatv/venv/lib/python3.9/site-packages/pyatv-0.8.1-py3.9.egg/pyatv/companion/protocol.py", line 84, in exchange_opack
    raise exceptions.ProtocolError(f"Command failed: {unpacked_object['_em']}")
pyatv.exceptions.ProtocolError: Command failed: Unsupported service type

>>> An error occurred, full stack trace above
```

**Expected behavior**
Action should do what is expected without error.

**System Setup (please complete the following information):**
 - OS: any
 - Python: any
 - pyatv: bdaf12a448daeb430013ca5a2702e35e0fbd3f35 (basically master)
 - Apple TV: tvOS 15 beta 3(?)

**Additional context**
#1168

**Comment by postlund** [comment]
Problem seems to exist with iOS 15 as well and the shortcut to launch apps (or rather to list apps, that we know for now) doesn't even work. So this might be a bug in tvOS if we are lucky.

**Comment by notabene00** [comment]
Still not working on `19J5314e` - `tvOS 15.0 beta 4`

**Comment by postlund** [comment]
Are you running matching version of iOS as well? Would be terrible if iOS 14 didn't work with a tvOS 15 device in this regard, but still.

**Comment by notabene00** [comment]
Yep, `19A5307g` - beta 4
![image](https://user-images.githubusercontent.com/9576189/127223228-67869941-37a4-4f91-8e8a-c6e43def0b31.png)

**Comment by postlund** [comment]
Thanks! Either Apple is dropping support for some shortcuts or they have no QA whatsoever. Or nobody is using that feature and reporting it as a bug...

**Comment by oxplot** [comment]
> Thanks! Either Apple is dropping support for some shortcuts or they have no QA whatsoever. Or nobody is using that feature and reporting it as a bug...

I've reported it.

**Comment by postlund** [comment]
Thank you @oxplot! Keep us updated!

**Comment by mschwartz** [comment]
is the remote app in iOS 15 new?  Screenshot and article link.

https://i0.wp.com/9to5mac.com/wp-content/uploads/sites/6/2021/06/ios-15-tidbits.jpg?w=2500&quality=82&strip=all&ssl=1 

https://9to5mac.com/2021/06/07/ios-15-apple-tv-remote-photos-more/

**Comment by mschwartz** [comment]
If the new remote works with tvOS 15, maybe WireShark can help…

**Comment by postlund** [comment]
That's just an uplift of the remote widget in control center. It's basically what the Companion protocol does and most of that is already implemented.

**Comment by notabene00** [comment]
`19J5325f` still no
