### ISSUE TITLE
[RAOP] Streaming not working with shairport-sync

### ISSUE THREAD

**Issue by Schlaubischlump** [postlund/pyatv#1229]
**Describe the bug**
Edit: The "bug" only occurs if an application that exposes a dmap service is running on the same machine as shairport-sync and no credentials for the dmap service are provided. 

Trying to stream an audio file using pyatv is currently not working. 

```
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/pyatv/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 698, in _run_application
    return await cli_handler(loop)
  File "/usr/local/anaconda3/envs/pyatv/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 487, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/usr/local/anaconda3/envs/pyatv/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 586, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol)
  File "/usr/local/anaconda3/envs/pyatv/lib/python3.8/site-packages/pyatv/__init__.py", line 96, in connect
    await atv.connect()
  File "/usr/local/anaconda3/envs/pyatv/lib/python3.8/site-packages/pyatv/support/facade.py", line 412, in connect
    await protocol_connect()
  File "/usr/local/anaconda3/envs/pyatv/lib/python3.8/site-packages/pyatv/dmap/__init__.py", line 614, in _connect
    await requester.login()
  File "/usr/local/anaconda3/envs/pyatv/lib/python3.8/site-packages/pyatv/dmap/daap.py", line 99, in login
    resp = await self._do(_login_request, is_login=True)
  File "/usr/local/anaconda3/envs/pyatv/lib/python3.8/site-packages/pyatv/dmap/daap.py", line 130, in _do
    resp, status = await action()
  File "/usr/local/anaconda3/envs/pyatv/lib/python3.8/site-packages/pyatv/dmap/daap.py", line 92, in _login_request
    url = self._mkurl("login?[AUTH]&hasFP=1", session=False, login_id=True)
  File "/usr/local/anaconda3/envs/pyatv/lib/python3.8/site-packages/pyatv/dmap/daap.py", line 157, in _mkurl
    if re.match(r"0x[0-9A-Fa-f]{16}", self._login_id):
  File "/usr/local/anaconda3/envs/pyatv/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```
**To Reproduce**
1. Setup a new clean conda envirnoment with python3.8
2. pip install pyatv
3. Start `shairport-sync`
3. Execute: `atvremote --id XXX stream_file=sample.mp3`

**Expected behavior**
The file should play.

**System Setup (please complete the following information):**
 - OS: [e.g. Debian] MacOS Big Sur 11.4
 - Python: [e.g. 3.6.2] 3.8.10
 - pyatv: [e.g. 0.3.10]  0.8.1
 - Apple TV: [e.g. Apple TV 4K tvOS 13.4] Shairport-sync 3.3.8d7

**Additional context**
This was working fine at least until a23c144d6b062d421afab1cc330883bc92370b2a.  Could somebody else please verify this behaviour on another machine ? Shairport-sync is working fine. Streaming from the Music.app is working without a problem.

**Comment by Schlaubischlump** [comment]
I repeated the setup above for a second time and this time it is working. Maybe something strange with my operating system was going on... I'm closing this for now

**Comment by postlund** [comment]
Can you check which zeroconf services shairport-sync exposes? Based on the error, it looks like the credentials is probably `None`. That is the normal case when no credentials are provided (`--dmap-credentials`) and service is discovered via `_touch-able._tcp.local`. If Home Sharing is enabled, then credentials will be discovered via `hG` in `_appletv-v2._tcp.local`. If shairpoort-sync emulates both of these services, then I'm pretty certain that only the former service is found => no credentials. This should anyway have a better error message as it's hard to tell since we don't know the value of the credentials used.

**Comment by Schlaubischlump** [comment]
`_raop._tcp` is the only service shairport-sync exposes.

The error

**Comment by postlund** [comment]
By default, pyatv will always scan for all interesting services. So if a device expose both RAOP and DMAP, then pyatv will pick both up and use them. In general, this should be pretty sane behavior. When you run two independent software pieces on the same host, like you do know, it will become a problem though.

This is however an implementation detail, so you can change the behavior depending on what your application does. To simplify things, I added a `--scan-protocols` flags to atvremote so you can scan for specific protocols only. So you can just do:

    $ atvremote -s <ip> --scan-protocols raop stream_file=rickroll.mp3

And never end up in the situation you did. It also works with scan:

    $ atvremote --scan-protocols raop scan

Will only show devices with RAOP and only the RAOP service for these devices, even if they support other protocols.

**Comment by Schlaubischlump** [comment]
That makes perfect sense ! Thanks for the detailed reply. Under this circumstances this is not really a bug. I will close the issue again.
