### ISSUE TITLE
Unable to Pair after tvOS 15

### ISSUE THREAD

**Issue by martinorob** [postlund/pyatv#1319]
### Describe the bug

Hi,
I'm unable to pair after tv os 15
this is the debug log

anyone in the same situation?

thanks

### Error log

```
#python3.8 ./atvremote --id C8:69:CD:6E:43:86 --debug --protocol mrp pair                                                             

2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on *:5353
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 127.0.0.1:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 192.168.3.50:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 10.6.0.1:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 172.17.0.1:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 172.18.0.1:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.106.191:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 172.19.0.1:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.212.86:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.137.157:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.87.17:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.27.248:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.164.68:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.115.210:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.68.16:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.194.30:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.252.202:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.11.41:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.114.190:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.86.151:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.51.74:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.157.162:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.190.232:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.139.168:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.150.81:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.140.160:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.35.83:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.246.88:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.175.35:0
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Binding on 169.254.75.176:0
2021-09-21 15:20:02 DEBUG [pyatv.core.mdns]: Error during MDNS lookup: [Errno 126] Required key not available
2021-09-21 15:20:02 DEBUG [pyatv.core.mdns]: Error during MDNS lookup: [Errno 126] Required key not available
2021-09-21 15:20:02 DEBUG [pyatv.core.mdns]: Error during MDNS lookup: [Errno 126] Required key not available
2021-09-21 15:20:02 DEBUG [pyatv.core.mdns]: Error during MDNS lookup: [Errno 126] Required key not available
2021-09-21 15:20:02 DEBUG [pyatv.core.scan]: Auto-discovered AppleTV at 192.168.3.52:49153 via Protocol.Companion ({'rpmac': '1', 'rphn': '97ee4cdb40e0', 'rpfl': '0x367AA', 'rpha': '5c632ebb4c3f', 'rpmd': 'AppleTV5,3', 'rpvr': '300.66', 'rpad': 'f5d5077c17d3', 'rphi': '468b8a4b089c', 'rpba': 'AB:18:6A:98:FC:BC', 'rpmrtid': 'F81B0864-E26B-40BA-BB2C-163ED5F200BE'})
2021-09-21 15:20:02 DEBUG [pyatv.core.scan]: Auto-discovered AppleTV at 192.168.3.52:7000 via Protocol.AirPlay ({'acl': '0', 'btaddr': 'C8:69:CD:6E:43:85', 'deviceid': 'C8:69:CD:6E:43:86', 'fex': '1d9/Wt5fFbwI', 'features': '0x5A7FDFD5,0xBC155FDE', 'flags': '0x4c4', 'gid': 'BCC9B9F3-4A12-4504-A3DD-4648CA083D74', 'igl': '1', 'gcgl': '1', 'model': 'AppleTV5,3', 'protovers': '1.1', 'pi': '91688c86-df11-4c30-a35d-20c8bf8dd54d', 'psi': 'F81B0864-E26B-40BA-BB2C-163ED5F200BE', 'pk': 'f096f8e419ca6a0a76d3fafed380afe4b8f54dc4888980eb25c634ed746d92c5', 'srcvers': '566.25.43', 'osvers': '15.0', 'vv': '2'})
2021-09-21 15:20:02 DEBUG [pyatv.core.scan]: Auto-discovered AppleTV at 192.168.3.52:49152 via Protocol.MRP ({'modelname': 'Apple TV', 'allowpairing': 'YES', 'bluetoothaddress': "b'\\xc8i\\xcdnC\\x85'", 'macaddress': 'c8:69:cd:6e:43:86', 'name': 'AppleTV', 'uniqueidentifier': '8CD254F3-CA9C-4B4C-AEBD-113FC050DD45', 'systembuildversion': '19J346', 'localairplayreceiverpairingidentity': 'F81B0864-E26B-40BA-BB2C-163ED5F200BE'})
2021-09-21 15:20:02 DEBUG [pyatv.core.scan]: Auto-discovered C869CD6E4386@AppleTV at 192.168.3.52:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x5A7FDFD5,0xBC155FDE', 'sf': '0x4c4', 'md': '0,1,2', 'am': 'AppleTV5,3', 'pk': 'f096f8e419ca6a0a76d3fafed380afe4b8f54dc4888980eb25c634ed746d92c5', 'tp': 'UDP', 'vn': '65537', 'vs': '566.25.43', 'ov': '15.0', 'vv': '2'})
2021-09-21 15:20:02 DEBUG [pyatv.protocols.mrp.connection]: Connection made to device
2021-09-21 15:20:02 DEBUG [pyatv.support.net]: Configured keep-alive on <asyncio.TransportSocket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.3.50', 54906), raddr=('192.168.3.52', 49152)> (Linux)
2021-09-21 15:20:02 DEBUG [pyatv.protocols.mrp.connection]: 192.168.3.50:54906<->192.168.3.52:49152  Connection established
2021-09-21 15:20:02 DEBUG [pyatv.protocols.mrp.connection]: 192.168.3.50:54906<->192.168.3.52:49152 >> Send (Data=080f122438433344383331392d313934412d343441372d383739432d4643413144353531463942342000a20183010a2436633331356166382d343165312d343834312d393339302d663235363766323237316239120570796174761a066950686f6e6522063138413339332a12636f6d2e6170706c652e545652656d6f746532063334342e32383801406c480150016211636f6d2e6170706c652e54564d75736963680170017801880102a80101b00101aa052437463645383637392d433038462d343630372d423233322d333046363732443346333132)
2021-09-21 15:20:02 DEBUG [pyatv.protocols.mrp.connection]: 192.168.3.50:54906<->192.168.3.52:49152 >> Send: Protobuf: type: DEVICE_INFO_MESSAGE
identifier: "8C3D8319-194A-44A7-879C-FCA1D551F9B4"
errorCode: NoError
[deviceInfoMessage] {
  uniqueIdentifier: "6c315af8-41e1-4841-9390-f2567f2271b9"
  name: "pyatv"
  localizedModelName: "iPhone"
  systemBuildVersion: "18A393"
  applicationBundleIdentifier: "com.apple.TVRemote"
  applicationBundleVersion: "344.28"
  protocolVersion: 1
  lastSupportedMessageType: 108
  supportsSystemPairing: true
  allowsPairing: true
  systemMediaApplication: "com.apple.TVMusic"
  supportsACL: true
  supportsSharedQueue: true
  supportsExtendedMotion: true
  sharedQueueVersion: 2
  deviceClass: iPhone
  logicalDeviceCount: 1
}
uniqueIdentifier: "7F6E8679-C08F-4607-B232-30F672D3F312"
2021-09-21 15:20:07 DEBUG [pyatv.protocols.mrp.connection]: 192.168.3.50:54906<->192.168.3.52:49152  Closing connection
2021-09-21 15:20:07 ERROR [pyatv.scripts.atvremote]: Pairing failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyatv/support/__init__.py", line 33, in error_handler
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/mrp/auth.py", line 40, in start_pairing
    await self.protocol.start(skip_initial_messages=True)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/mrp/protocol.py", line 134, in start
    self.device_info = await self.send_and_receive(msg)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/mrp/protocol.py", line 234, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/mrp/protocol.py", line 242, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyatv/scripts/atvremote.py", line 172, in pair
    await self._perform_pairing(pairing)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/scripts/atvremote.py", line 182, in _perform_pairing
    await pairing.begin()
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/mrp/pairing.py", line 51, in begin
    return await error_handler(
  File "/usr/local/lib/python3.8/dist-packages/pyatv/support/__init__.py", line 35, in error_handler
    raise exceptions.ConnectionFailedError(str(ex)) from ex
pyatv.exceptions.ConnectionFailedError
2021-09-21 15:20:07 DEBUG [pyatv.protocols.mrp.connection]: 192.168.3.50:54906<->192.168.3.52:49152  Closing connection
2021-09-21 15:20:07 DEBUG [pyatv.protocols.mrp.connection]: 192.168.3.50:54906<->192.168.3.52:49152  Disconnected from device: None


```

### How to reproduce the bug?

python3.8 ./atvremote --id C8:69:CD:6E:43:86 --protocol mrp pair
2021-09-21 15:18:53 ERROR [pyatv.scripts.atvremote]: Pairing failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyatv/support/__init__.py", line 33, in error_handler
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/mrp/auth.py", line 40, in start_pairing
    await self.protocol.start(skip_initial_messages=True)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/mrp/protocol.py", line 134, in start
    self.device_info = await self.send_and_receive(msg)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/mrp/protocol.py", line 234, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/mrp/protocol.py", line 242, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyatv/scripts/atvremote.py", line 172, in pair
    await self._perform_pairing(pairing)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/scripts/atvremote.py", line 182, in _perform_pairing
    await pairing.begin()
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/mrp/pairing.py", line 51, in begin
    return await error_handler(
  File "/usr/local/lib/python3.8/dist-packages/pyatv/support/__init__.py", line 35, in error_handler
    raise exceptions.ConnectionFailedError(str(ex)) from ex
pyatv.exceptions.ConnectionFailedError

### What is expected behavior?

pair successful 

### Operating System

Ubuntu 20.04

### Python

3.8

### pyatv

0.8.2

### Device

Apple TV HD

### Additional context

no additional context.

**Comment by postlund** [comment]
Yep, please see these:

https://github.com/postlund/pyatv/issues/1168
https://github.com/postlund/pyatv/issues/1298

I hope to release 0.9.0 officially tonight.

**Comment by martinorob** [comment]
Same problem event after last update

`sudo atvremote --id C8:69:CD:6E:43:86 --protocol mrp pair                                                                            3 ⨯
[sudo] password for martinoroberto:
2021-09-22 12:36:05 ERROR [pyatv.scripts.atvremote]: Pairing failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyatv/support/__init__.py", line 33, in error_handler
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/mrp/auth.py", line 40, in start_pairing
    await self.protocol.start(skip_initial_messages=True)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/mrp/protocol.py", line 134, in start
    self.device_info = await self.send_and_receive(msg)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/mrp/protocol.py", line 234, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/mrp/protocol.py", line 242, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyatv/scripts/atvremote.py", line 172, in pair
    await self._perform_pairing(pairing)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/scripts/atvremote.py", line 182, in _perform_pairing
    await pairing.begin()
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/mrp/pairing.py", line 51, in begin
    return await error_handler(
  File "/usr/local/lib/python3.8/dist-packages/pyatv/support/__init__.py", line 35, in error_handler
    raise exceptions.ConnectionFailedError(str(ex)) from ex
pyatv.exceptions.ConnectionFailedError
`

**Comment by postlund** [comment]
You should not use `mrp` as that is deprecated. Use `airplay` instead.

**Comment by martinorob** [comment]
Great! Now i have an “Enter PIN on screen:”.. but no pin is showing on my apple tv.. 🙁 

`atvremote --id C8:69:CD:6E:43:86 --protocol airplay pair --debug
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on *:5353
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 127.0.0.1:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 192.168.3.50:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 10.6.0.1:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 172.17.0.1:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 192.168.176.1:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.128.144:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 192.168.192.1:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.30.25:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.167.103:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.75.107:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.162.52:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.215.233:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.14.70:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.186.209:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.47.78:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.1.97:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.222.238:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.155.171:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.136.106:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.95.192:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.164.30:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.121.220:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.78.109:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.166.20:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.91.163:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.57.226:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.51.108:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.114.236:0
2021-09-22 13:05:57 DEBUG [pyatv.support.net]: Binding on 169.254.144.57:0
2021-09-22 13:05:57 DEBUG [pyatv.support.mdns]: Error during MDNS lookup: [Errno 126] Required key not available
2021-09-22 13:05:57 DEBUG [pyatv.support.mdns]: Error during MDNS lookup: [Errno 126] Required key not available
2021-09-22 13:05:57 DEBUG [pyatv.support.mdns]: Error during MDNS lookup: [Errno 126] Required key not available
2021-09-22 13:05:57 DEBUG [pyatv.support.mdns]: Error during MDNS lookup: [Errno 126] Required key not available
2021-09-22 13:05:57 DEBUG [pyatv.support.scan]: Auto-discovered AppleTV at 192.168.3.52:7000 via Protocol.AirPlay ({'acl': '0', 'btaddr': 'C8:69:CD:6E:43:85', 'deviceid': 'C8:69:CD:6E:43:86', 'fex': '1d9/Wt5fFbwI', 'features': '0x5A7FDFD5,0xBC155FDE', 'flags': '0x4c4', 'gid': 'C87AD4D2-8E40-49A6-8C0F-DF0D3FE982BC', 'igl': '1', 'gcgl': '1', 'model': 'AppleTV5,3', 'protovers': '1.1', 'pi': '91688c86-df11-4c30-a35d-20c8bf8dd54d', 'psi': 'F81B0864-E26B-40BA-BB2C-163ED5F200BE', 'pk': 'f096f8e419ca6a0a76d3fafed380afe4b8f54dc4888980eb25c634ed746d92c5', 'srcvers': '566.25.43', 'osvers': '15.0', 'vv': '2'})
2021-09-22 13:05:57 DEBUG [pyatv.support.scan]: Auto-discovered AppleTV at 192.168.3.52:49153 via Protocol.Companion ({'rpmac': '1', 'rphn': 'c86c79fd7cde', 'rpfl': '0x367AA', 'rpha': '0d7ba27493a9', 'rpmd': 'AppleTV5,3', 'rpvr': '300.66', 'rpad': 'e44e8bc3dead', 'rphi': '11b6cc108c27', 'rpba': '32:82:03:22:0D:00', 'rpmrtid': 'F81B0864-E26B-40BA-BB2C-163ED5F200BE'})
2021-09-22 13:05:57 DEBUG [pyatv.support.scan]: Auto-discovered AppleTV at 192.168.3.52:49152 via Protocol.MRP ({'modelname': 'Apple TV', 'allowpairing': 'YES', 'bluetoothaddress': "b'\\xc8i\\xcdnC\\x85'", 'macaddress': 'c8:69:cd:6e:43:86', 'name': 'AppleTV', 'uniqueidentifier': '8CD254F3-CA9C-4B4C-AEBD-113FC050DD45', 'systembuildversion': '19J346', 'localairplayreceiverpairingidentity': 'F81B0864-E26B-40BA-BB2C-163ED5F200BE'})
2021-09-22 13:05:57 DEBUG [pyatv.support.scan]: Auto-discovered C869CD6E4386@AppleTV at 192.168.3.52:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x5A7FDFD5,0xBC155FDE', 'sf': '0x4c4', 'md': '0,1,2', 'am': 'AppleTV5,3', 'pk': 'f096f8e419ca6a0a76d3fafed380afe4b8f54dc4888980eb25c634ed746d92c5', 'tp': 'UDP', 'vn': '65537', 'vs': '566.25.43', 'ov': '15.0', 'vv': '2'})
2021-09-22 13:05:57 DEBUG [pyatv.airplay.pairing]: Starting AirPlay pairing with credentials 080AC13F5DA6BBFF:DF9A327D11F31F07D49C938F2582FBDB3B74D8A99BCDAB1B60E47568D1E931A9
2021-09-22 13:05:57 DEBUG [pyatv.airplay.srp]: Authentication keys (Private=df9a327d11f31f07d49c938f2582fbdb3b74d8a99bcdab1b60e47568d1e931a9, Public=915aaa108370edb4f204b52d4c143fccd05bb7e23fadbac9ceba5f28f9365c4a)
2021-09-22 13:05:57 DEBUG [pyatv.support.http]: Connected to 192.168.3.52
2021-09-22 13:05:57 DEBUG [pyatv.support.http]: Sending HTTP/1.1 message: b'POST /pair-pin-start HTTP/1.1\r\nUser-Agent: AirPlay/320.20\r\nConnection: keep-alive\r\n\r\n'
2021-09-22 13:05:57 DEBUG [pyatv.support.http]: Received: b'HTTP/1.1 200 OK\r\nDate: Wed, 22 Sep 2021 11:05:57 GMT\r\nContent-Length: 0\r\nServer: AirTunes/566.25.43\r\n\r\n'
2021-09-22 13:05:57 DEBUG [pyatv.support.http]: Got HTTP response: HttpResponse(protocol='HTTP', version='1.1', code=200, message='OK', headers={'date': 'Wed, 22 Sep 2021 11:05:57 GMT', 'content-length': '0', 'server': 'AirTunes/566.25.43'}, body=''):
Enter PIN on screen:
`

**Comment by postlund** [comment]
Verify this:
https://pyatv.dev/support/troubleshooting/#the-exception-pyatvexceptionsdeviceauthenticationerror-pair-start-failed-is-thrown-when-i-try-to-pair-with-airplay

**Comment by martinorob** [comment]
yeah! I had set my own password.. now without it, apple tv show me 4 digit pin. 
Thanks

**Comment by postlund** [comment]
Yeah, I kinda expected that. I'm still wondering if it's possible to detect this situation somehow...
