### ISSUE TITLE
Apple TV Beta Component Device Found but not working

### ISSUE THREAD

**Issue by geekofweek** [postlund/pyatv#1335]
### Describe the bug

When adding in a tvOS 15 Apple TV it will go through the process, fail after attempting to connect via MRP, then connect on the second pass.  However the device shows up in an unknown or off state.  

### Error log

```log
2021-09-24 09:52:02 DEBUG (MainThread) [custom_components.apple_tv] Failed to find device 0E0C0900-8067-402A-8B7D-626694C20840, trying later
2021-09-24 09:52:02 DEBUG (MainThread) [custom_components.apple_tv] Reconnecting in 3 seconds
2021-09-24 09:52:05 DEBUG (MainThread) [custom_components.apple_tv] Discovering device 0E0C0900-8067-402A-8B7D-626694C20840
2021-09-24 09:52:05 DEBUG (MainThread) [pyatv.support.knock] Knocking at ports [3689, 7000, 49152, 32498] on 192.168.101.102
2021-09-24 09:52:05 DEBUG (MainThread) [pyatv.core.scan] Auto-discovered Aaron’s Office Apple TV at 192.168.101.102:49153 via Protocol.Companion ({'rpmac': '2', 'rphn': 'deb8e651221a', 'rpfl': '0x36782', 'rpha': '81a561441c3d', 'rpmd': 'AppleTV5,3', 'rpvr': '300.66', 'rpad': '0d1dcee80ed1', 'rphi': '3b03ae3df964', 'rpba': 'AA:C0:F5:90:11:FE', 'rpmrtid': '27BE55E3-3D19-4FDA-AC4C-2702E803D7C8'})
2021-09-24 09:52:05 DEBUG (MainThread) [pyatv.core.scan] Auto-discovered Aaron’s Office Apple TV at 192.168.101.102:7000 via Protocol.AirPlay ({'acl': '0', 'btaddr': 'C8:69:CD:6E:59:98', 'deviceid': 'C8:69:CD:6E:59:99', 'fex': '1d9/Wt5fFbwI', 'features': '0x5A7FDFD5,0xBC155FDE', 'flags': '0x18644', 'gid': 'E2D924C4-DB86-4450-BC3F-809BE32D3212', 'igl': '1', 'gcgl': '1', 'model': 'AppleTV5,3', 'protovers': '1.1', 'pi': '6c5b37d1-077c-4fe4-b776-38e088923c88', 'psi': '27BE55E3-3D19-4FDA-AC4C-2702E803D7C8', 'pk': 'dbfa4c99cdcdbbdfc93acb2717ab51d43d615b06910648e361c6269190308cdd', 'srcvers': '566.25.43', 'osvers': '15.0', 'vv': '2'})
2021-09-24 09:52:05 DEBUG (MainThread) [pyatv.core.scan] Auto-discovered C869CD6E5999@Aaron’s Office Apple TV at 192.168.101.102:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x5A7FDFD5,0xBC155FDE', 'sf': '0x18644', 'md': '0,1,2', 'am': 'AppleTV5,3', 'pk': 'dbfa4c99cdcdbbdfc93acb2717ab51d43d615b06910648e361c6269190308cdd', 'tp': 'UDP', 'vn': '65537', 'vs': '566.25.43', 'ov': '15.0', 'vv': '2'})
2021-09-24 09:52:05 DEBUG (MainThread) [custom_components.apple_tv] Failed to find device 0E0C0900-8067-402A-8B7D-626694C20840 with address 192.168.101.102, trying to scan
2021-09-24 09:52:05 DEBUG (MainThread) [pyatv.support.net] Binding on *:5353
2021-09-24 09:52:05 DEBUG (MainThread) [pyatv.support.net] Binding on 127.0.0.1:0
2021-09-24 09:52:05 DEBUG (MainThread) [pyatv.support.net] Binding on 192.168.101.240:0
```

If I attempt to "Turn On" the device
```log
2021-09-24 09:54:45 DEBUG (MainThread) [custom_components.apple_tv] Not starting connect loop (True, True)
```

### How to reproduce the bug?

Integrate device via Beta Component

### What is expected behavior?

Device functions with media states, etc.

### Operating System

Docker

### Python

3.9

### pyatv

0.9

### Device

Apple TV 4 tvOS 15

### Additional context

Same behavior on additional Apple TVs tested on

**Comment by geekofweek** [comment]
tvOS 14 devices work beautifully though, just and FYI.

**Comment by postlund** [comment]
Is that a device that was added from before? If it is, does it work if you remove it first and add it again?

One problem I have is that I save one of the unique identifiers from the device (in the config entry) which is then used to find the device when connecting. This obviously becomes problematic when the MRP services no longer exists and the identifier happened to come from MRP. I'm not entirely sure how to handle that. In hindsight, it would have been better to cache all identifiers. That way I could have fixed this.

**Comment by geekofweek** [comment]
No, I removed all devices first and added it new

**Comment by gloaysa** [comment]
Same happening here. The homepods (mini) work beautifully, tho.
Had the apple tv added a couple of months ago before I made the mistake to update to 15 beta version, but it's been removed since then.

**Comment by postlund** [comment]
@geekofweek You mentioned MRP... We have seen cases where upgraded tvOS 15 devices for some reason announce a non-working MRP service. I can see this become a problem as the unique id saved and used to later discover a device is the one from MRP. This will work poorly once the service is removed as the device won't be found anymore, which looks like the situation you have right now.

I think I will do it like this... I will extend `pyatv.scan` to support scanning for a list of identifiers (instead of just one) and also save *all* identifiers to the config entry when adding a new device. That way I can scan for all identifiers used by a device. That is much more future proof and will solve this problem in particular. Will get on it as soon as I can, hang tight! 👊

(same applies to you, too, @gloaysa)

**Comment by gloaysa** [comment]
Thanks for all your efforts. I have noticed something else, don't know if reporting it here is enough or you prefer that I open a new ticket. 
The problem is that after pairing the HomePods, each time that I restart Home Assistant they get "rediscovered". 

I ignore them because the current integration keeps working, but I thought you should know.

**Comment by postlund** [comment]
It sounds like a similar issue, hopefully that will be resolved by my changes mentioned above.

**Comment by postlund** [comment]
Just pushed an update, please try it out and let me know of any problems!

**Comment by geekofweek** [comment]
Disregard my previous comment, someone else pointed out the version was missing hence it wasn't actually loading the custom component.  I fixed that and everything seems to be functioning now.  Was able to pair a tvOS 15 device without issue.

**Comment by postlund** [comment]
Yeah, I managed to leave those changes out. I have pushed an update now.

**Comment by gloaysa** [comment]
After updating the devices already added don't show up anymore, but the Apple TV (not added) doesn't show up either.

When trying to set it up manually (from Integrations/add integration button) it discovers all the devices with their IP address and name, but can't connect to Apple TV.

Here are the logs thrown:

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/apple_tv/config_flow.py:111
Integration: Apple TV
First occurred: 9:39:28 (24 occurrences)
Last logged: 9:48:33

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 179, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/apple_tv/config_flow.py", line 177, in async_step_zeroconf
    return await self.async_find_device_wrapper(self.async_found_zeroconf_device)
  File "/config/custom_components/apple_tv/config_flow.py", line 203, in async_find_device_wrapper
    return await next_func()
  File "/config/custom_components/apple_tv/config_flow.py", line 181, in async_found_zeroconf_device
    await self.async_set_unique_id(self.device_identifier)
  File "/config/custom_components/apple_tv/config_flow.py", line 111, in device_identifier
    if self.atv.identifier in entry.data[CONF_IDENTIFIERS]:
KeyError: 'identifiers'

```

```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/apple_tv/config_flow.py:111
Integration: Apple TV
First occurred: 9:41:31 (1 occurrences)
Last logged: 9:41:31

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 89, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 202, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/apple_tv/config_flow.py", line 150, in async_step_user
    self.device_identifier, raise_on_progress=False
  File "/config/custom_components/apple_tv/config_flow.py", line 111, in device_identifier
    if self.atv.identifier in entry.data[CONF_IDENTIFIERS]:
KeyError: 'identifiers'
```

Hope it helps.

**Comment by postlund** [comment]
Ok, I can see the problem but very annoying that Home Assistant doesn't guard this better. I pushed an update, bumping the config entry to a new version. This should hopefully make all devices appear in the Integration page again, albeit disabled. Just remove them before adding a new device again, hopefully that works.

**Comment by gloaysa** [comment]
You rock.

After removing all devices that were working (Homepods) and resetting Home Assistant, all the devices show up again and was able to pair the Apple TV.

Now even the Sonos speakers show up.

**Comment by postlund** [comment]
Awesome! 👍 Yeah, newer versions of Sonos speakers that support AirPlay will probably show up now.

**Comment by deviantintegral** [comment]
Thanks for the work on this. I only realized that tvOS had updated when it started showing notifications from my HomeKit bridge!

I had to both update to the beta release and remove / repair the device. It would be nice if you didn't have to re-pair, but I suppose that's going to be very painful to test given you can't downgrade a device.

**Comment by postlund** [comment]
I would have preferred to not have to re-pair either, but there are technical restrictions that gives no other choice (i.e. it's impossible to not solve), unfortunately.
