### ISSUE TITLE
2nd Apple TV not discovered, unable to add.

### ISSUE THREAD

**Issue by platvoet12** [postlund/pyatv#1380]
### Describe the bug

first, thank you for your work so far on making TVOS 15 work again.

my first Apple tv works fine (4K2021) but my second is not discovered, when i try to add it manually it tries to set the ip to another device(appletv full HD) and tells me that the device is already configured.

### Error log

2021-10-08 15:21:57 ERROR (MainThread) [custom_components.apple_tv.config_flow] Unexpected exception
Traceback (most recent call last):
File "/config/custom_components/apple_tv/config_flow.py", line 324, in async_step_pair_with_pin
return await self.async_pair_next_protocol()
File "/config/custom_components/apple_tv/config_flow.py", line 254, in async_pair_next_protocol
return await self._async_get_entry()
File "/config/custom_components/apple_tv/config_flow.py", line 392, in _async_get_entry
self.device_identifier, raise_on_progress=False
File "/config/custom_components/apple_tv/config_flow.py", line 111, in device_identifier
if self.atv.identifier in entry.data[CONF_IDENTIFIERS]:
KeyError: 'identifiers'

### How to reproduce the bug?

First set up the first Apple TV (A 4K one) then a second (full HD one) that isnt discovered.

### What is expected behavior?

allow me to add the second Apple TV :)

### Operating System

Home assistant OS

### Python

Other

### pyatv

0.9.2

### Device

Apple TV 4K + Apple TV Full HD both on TV OS 15.

### Additional context

.

**Comment by platvoet12** [comment]
i've deleted the old entity in the core.config_entries but the same error message comes up.
2021-10-15 10:32:40 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration apple_tv which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-15 10:32:44 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2021-10-15 10:32:44 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=10 from 2021-10-12 19:50:44.385852)
2021-10-15 10:32:53 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry joost.1990@outlook.com for tuya
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore

**Comment by postlund** [comment]
Please include the entire stack trace, it is cut mid-through.

**Comment by postlund** [comment]
That means you still have at least one old entity that you didn't remove, you need to remove all of them.

**Comment by postlund** [comment]
Did you manage to verify this?

**Comment by postlund** [comment]
I suspect this was resolved.
