### ISSUE TITLE
Not receiving disconnect or poweroff

### ISSUE THREAD

**Issue by sergem155** [postlund/pyatv#1405]
### Describe the bug

I am trying to make a script that always tracks what is being played on my Apple TV, but I am having a hard time handling sleeps and reconnects.

I connect using credentials obtained for Airplay, set listeners for playback, connection and power events. I get playback events, but if left alone, several hours later I get the exception.

The code I use:

```
class MyPushListener(interface.PushListener, interface.DeviceListener, interface.PowerListener):
	def connection_lost(self, exception):
		print("Lost connection:", str(exception))
	def playstatus_update(self, updater, playstatus):
                pass
	def playstatus_error(self, updater, exception):
		print("status error")
	def connection_closed(self):
		print("Connection closed!")
	def powerstate_update(self, old_state, new_state):
		print('Power state changed from {0:s} to {1:s}'.format(old_state, new_state))
# ...	
 	listener = MyPushListener()
 	atv.push_updater.listener = listener
	atv.push_updater.start()
	atv.listener = listener
	atv.power.listener = listener
```

### Error log

```Device state: Paused
       Title: Avatar
    Position: 12/9714s (0.1%)
      Repeat: Off
     Shuffle: Off
stop: 12
Got response without having a request: HttpResponse(protocol='RTSP', version='1.0', code=200, message='OK', headers={'date': 'Thu, 14 Oct 2021 05:02:17 GMT', 'content-length': '55', 'content-type': 'application/x-apple-binary-plist', 'server': 'AirTunes/566.25.43', 'cseq': '4918'}, body=b'bplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14')
Heartbeat 4915 failed after 2 tries (AirPlay:192.168.1.237)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyatv/support/rtsp.py", line 281, in exchange
    await asyncio.wait_for(self.requests[cseq][0].wait(), 4)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyatv/core/protocol.py", line 36, in heartbeater
    await sender_func(message)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/protocols/airplay/remote_control.py", line 75, in _send_feedback
    await self.rtsp.feedback()
  File "/usr/local/lib/python3.7/dist-packages/pyatv/support/rtsp.py", line 221, in feedback
    return await self.exchange("POST", uri="/feedback", allow_error=allow_error)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/support/rtsp.py", line 286, in exchange
    ) from ex
TimeoutError: no response to CSeq 4918 (/feedback)
Lost connection: no response to CSeq 4918 (/feedback)
```

### How to reproduce the bug?

connect, play something on Apple TV, leave script running.

### What is expected behavior?

Not getting exceptions.
Receiving disconnect or power events that I could handle.

### Operating System

Raspbian

### Python

3.7

### pyatv

0.9.2+

### Device

Apple TV 4K TVOS15

### Additional context

pyatv is from a recent git build

**Comment by postlund** [comment]
This is two-fold I would say. Connection problems will happen from time to time for various reasons, be it a device reboot, going to sleep or due to a bug. You need to be resilient against that and handle re-connects according to your requirements. However... if there are bugs in pyatv that I can fix, then of course I do want to fix them. I do expect random unexpected disconnects from time to time as we have no idea how the device behaves with a long-lived connection like this. It's very likely that it's not something Apple has designed for. In some cases I can look at the logs and try to figure it out from there. The problem though is that the logs can be pretty big since you need to run a long time. If you can reproduce this with logging enabled and just attach the last 100 lines of the log or so, that would be great. Also, where does the exception come from? Is it one of your callbacks or is it from the event loop? As I don't have the code in front of me now, I suspect this can be one of those tricky cases... The feedback loop that fails in your case, is the "heartbeat" mechanism that sends a message every two seconds to make sure the connection works. It's done from a background task. The problem is that when sending feedback fails, I don't have a natural way of indicating an error. Now that I'm seeing this, I would expect that it is just propagated to `connection_lost` instead of logged. I will have a look and see if I can fix that.
