### ISSUE TITLE
[HassOS] Must manually turn on/off media player to receive state updates

### ISSUE THREAD

**Issue by aristizabal95** [postlund/pyatv#1412]
### Describe the bug

Hello!
Ever since I was able to add my apple tv to home assistant (thanks for that btw, amazing work!) I've been noticing some sync issues. Sometimes, Home Assistant would receive no state updates from the apple tv. After playing some more tonight, I noticed that it doesn't even receive the turn on/off state.

 I decided then to manually turn on the media player on my home assistant, and after that I was able to receive state updates from the apple tv. The turn off state still doesn't show automatically on home assistant, so I also have to manually turn off the media player for automations to kick in.

### Error log

No logs relevant here

### How to reproduce the bug?

Simply turn on the apple tv device and then check the media state with the developer tools. The state won't change at all unless one turns on the media player on the home assistant dashboard. Same for turning off the device.

### What is expected behavior?

Turning on or off the apple tv device should automatically send state updates to home assistant, I presume that once that happens, all other available states will respond too.

### Operating System

HassOS

### Python

3.8

### pyatv

1.4.0

### Device

AppleTV 4K tvOS 15.0

### Additional context

I wasn't able to find out what python version I'm using exactly. I just guessed based on the code I've written with pyscript. Any help on finding that would be really appreciated.

Just noticed this while looking for the tvOS version. The device indicates that the home setup isn't complete, and asks me to bring an iphone or another apple device with bluetooth on near the apple tv. This won't work for me because I have an android. Any clue if this is expected behavior?

**Comment by rdgerken** [comment]
I'm having an issue that might be somewhat related. I'm trying to monitor the state of an Apple TV 4K; very simply, I'm just monitoring if the device is powered on (aka "not in standby") and when it's powered off (aka "in standby"). When I power the device off using the remote, the state in HA is standby as one would expect. However, when I power the device on (again, using the remote), quite often the state in HA will flip between "paused" and "standby" - every few seconds. When I'm using the device thereafter, it seems to maintain the correct state - but for some reason, it seems when I first turn the device on, I get this strange "state flipping" between the actual state and "standby".

**Comment by postlund** [comment]
@rdgerken That sounds a bit strange. Do you see anything in the logs for starters?

**Comment by postlund** [comment]
@aristizabal95 Did you try if the latest update of the component works more along the line of how you expect it to work?

**Comment by aristizabal95** [comment]
@postlund Couldn't use 2.0.0 nor 2.1.0 due to #1501 . Using 1.9.1 I'm seeing more problems with the state. Previously I could get states synchronized if I had already turned on the AppleTV and then pressed the power button on the media card. Now that's not the case.

After setting up the integration, I was receiving the state correctly, and when I set the AppleTV to sleep mode through the remote I got the `standby` state. But after that I couldn't get any more state updates.

I got this error log:

```
2021-12-07 22:33:19 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548405948816]
Traceback (most recent call last):
File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire
await fut
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
fut.result()
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 667, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 863, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 704, in _handle_entity_call
await result
File "/config/custom_components/apple_tv/media_player.py", line 355, in async_media_play
await self.atv.remote_control.play()
File "/usr/local/lib/python3.9/site-packages/pyatv/core/facade.py", line 64, in play
return await self.relay("play")()
File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 337, in play
await self._send_command(CommandInfo_pb2.Play)
File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 306, in _send_command
resp = await self.protocol.send_and_receive(messages.command(command, **kwargs))
File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 234, in send_and_receive
return await self._receive(identifier, timeout)
File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 242, in _receive
await asyncio.wait_for(semaphore.acquire(), timeout)
File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2021-12-07 22:33:25 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548405948816]
Traceback (most recent call last):
File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire
await fut
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
fut.result()
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 667, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 863, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 704, in _handle_entity_call
await result
File "/config/custom_components/apple_tv/media_player.py", line 355, in async_media_play
await self.atv.remote_control.play()
File "/usr/local/lib/python3.9/site-packages/pyatv/core/facade.py", line 64, in play
return await self.relay("play")()
File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 337, in play
await self._send_command(CommandInfo_pb2.Play)
File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 306, in _send_command
resp = await self.protocol.send_and_receive(messages.command(command, **kwargs))
File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 234, in send_and_receive
return await self._receive(identifier, timeout)
File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 242, in _receive
await asyncio.wait_for(semaphore.acquire(), timeout)
File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```
hope this helps

**Comment by aristizabal95** [comment]
Reloading the integration temporarily fixes the issue until I set the device to sleep

**Comment by postlund** [comment]
@aristizabal95 This problem might happen because power state isn't updated properly. I'm working on a "fix" that will change power state to on whenever something starts to play as a workaround (even if power state is reported as off). One thing you could try, just to test, is to call the `turn_on` service manually and see if the state updates.

**Comment by aristizabal95** [comment]
@postlund I did see that other issue #1500 and thought they could be related. Makes sense to monitor if something is playing as a fallback for aligning the power state.

I tried calling both the `turn_on` and `turn_off` services but to no effect. The state of the device stayed on `standby`

**Comment by postlund** [comment]
@aristizabal95 I have changed so that `device_state` override `power_state` whenver it is not set to `idle`. This makes sure that `power_state` is never `off` in case something is playing (paused, etc). It should generally take the device out of standby, but we have seen some other potential problems. One being that apps can get "stuck" (often the music app) in paused state, which makes the device considered to be on all the time. I still think this is better then before, but we will have to evaluate.

**Comment by postlund** [comment]
I will make a new release and bump this for testing, likely today or tomorrow.

**Comment by aristizabal95** [comment]
Awesome! I'll be happy to try it out! Will this new release follow 2.1.0? If that's the case I still think I won't be able to test it

**Comment by postlund** [comment]
Yeah, it will be part of 2.2.0 and I will hopefully merge things back soon and make a new release.

**Comment by postlund** [comment]
I forgot to mention that 2.2.0 is out, so feel free to test it now.

**Comment by aristizabal95** [comment]
Hi @postlund sorry for the late reply. I was only able to try things out today. I updated everything and can confirm that it now works flawlessly! I'm not sure what changes you made, but the `power_state` is being updated as soon as I turn on/off the device. This is absolutely amazing! Thanks for all your work!
