### ISSUE TITLE
Recurring error in Home Assistant log

### ISSUE THREAD

**Issue by felix63** [postlund/pyatv#1413]
### Describe the bug

Task exception was never retrieved showing up in log

### Error log

```log
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/apple_tv/config_flow.py:105 
Integration: Apple TV 
First occurred: 01:09:16 (29 occurrences) 
Last logged: 01:39:26

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 151, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 177, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 256, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/apple_tv/config_flow.py", line 165, in async_step_zeroconf
    return await self.async_find_device_wrapper(self.async_found_zeroconf_device)
  File "/config/custom_components/apple_tv/config_flow.py", line 225, in async_find_device_wrapper
    return await next_func()
  File "/config/custom_components/apple_tv/config_flow.py", line 203, in async_found_zeroconf_device
    await self.async_set_unique_id(self.device_identifier)
  File "/config/custom_components/apple_tv/config_flow.py", line 105, in device_identifier
    if identifier in entry.data[CONF_IDENTIFIERS]:
KeyError: 'identifiers'

```

### How to reproduce the bug?

n.a.

### What is expected behavior?

n.a.

### Operating System

x86_64

### Python

3.9

### pyatv

unknown

### Device

Apple TV iOS 15

### Additional context

n.a.

**Comment by postlund** [comment]
You need to manually remove Apple TV entries from `.storage/core.config_entries` for now.
