### ISSUE TITLE
Breaks with tvOS 15.1.1

### ISSUE THREAD

**Issue by mschwartz** [postlund/pyatv#1449]
### Describe the bug

ATV automatically updated.

pyatv fails.  Here's the log
```
Traceback (most recent call last):
  File "/home/app/./pyatv-microservice.py", line 379, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/app/./pyatv-microservice.py", line 220, in main
    atv = await pyatv.connect(device['appletv'], loop)
  File "/usr/local/lib/python3.9/site-packages/pyatv/__init__.py", line 90, in connect
    for setup_data in proto_methods.setup(
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/airplay/__init__.py", line 218, in setup
    if not remote_control.is_supported(service):
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/airplay/remote_control.py", line 48, in is_supported
    return float(version) >= 13.0
ValueError: could not convert string to float: '15.1.1
```

### Error log

```log
Traceback (most recent call last):
  File "/home/app/./pyatv-microservice.py", line 379, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/app/./pyatv-microservice.py", line 220, in main
    atv = await pyatv.connect(device['appletv'], loop)
  File "/usr/local/lib/python3.9/site-packages/pyatv/__init__.py", line 90, in connect
    for setup_data in proto_methods.setup(
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/airplay/__init__.py", line 218, in setup
    if not remote_control.is_supported(service):
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/airplay/remote_control.py", line 48, in is_supported
    return float(version) >= 13.0
ValueError: could not convert string to float: '15.1.1```


### How to reproduce the bug?

Update your Apple TV to 15.1.1


### What is expected behavior?

This is a silly error that's trivial to fix.



### Operating System

Linux

### Python

3.6

### pyatv

Whatever pip installs

### Device

Apple TV tvOS 15.1.1

### Additional context

This is running in a Docker container.

This is the Dockerfile

```
FROM python:3
ENV TZ=America/Los_Angeles
RUN apt-get -y update && apt-get -y install telnet build-essential neovim avahi-utils avahi-daemon avahi-discover libnss-mdns libavahi-compat-libdnssd-dev  npm
ADD avahi-daemon.conf /etc/avahi/avahi-daemon.conf
ADD nsswitch.conf /etc/nsswitch.conf
RUN pip3 install pyatv pymongo pillow paho-mqtt
RUN npm install -g pm2 forever nodemon
RUN useradd --user-group --create-home --shell /bin/false app
ENV HOME=/home/app
WORKDIR /home/app
COPY . /home/app
CMD ["./loop.sh"]

**Comment by mschwartz** [comment]
I think this might be an issue of Docker using a cached older version of pyatv.  I'm doing a force rebuild, and may just close this if it works.

However, you might want to look for any conversion of something like 15.1.1 from string to float.  That's a time bomb kind of bug :)

**Comment by mschwartz** [comment]
Indeed that was the problem.

Sorry to trouble you.

**Comment by crxporter** [comment]
I want to say thanks for posting this issue. I had the same `ValueError: could not convert string to float: '15.1.1'` as you saw - turns out `0.9.0` isn't the newest any more... 

Your comment of having an older version helped me figure out I just need to update and all is well again.

Thanks!

**Comment by mschwartz** [comment]
👍
