### ISSUE TITLE
ValueError: could not convert string to float: '15.1.1'

### ISSUE THREAD

**Issue by alteum-Fib** [postlund/pyatv#1460]
### Describe the bug

Hi !

For all my commands (launching apps, power on, power off, etc...), I suddenly get the same error.
Below an example with turn_off and details given in Error log.

atvremote --id 50:DE:06:9E:50:7C --airplay-credentials "f3feb76354a4d5fc40465eb0e62cd3771f945c334112e43db2049da510cc7feb:1e05b338af74c2589bea18347fc4fbe11611497a6d427bb76534b1cb120f1b92:43434242323538452d393738432d344144332d413232332d364135353433373043323337:37616364396565302d646339652d343866332d393565322d336132396664626563636264" turn_off
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyatv/scripts/atvremote.py", line 716, in _run_application
    return await cli_handler(loop)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/scripts/atvremote.py", line 510, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/scripts/atvremote.py", line 601, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/__init__.py", line 92, in connect
    loop, config, service, atv, session_manager
  File "/usr/local/lib/python3.7/dist-packages/pyatv/protocols/airplay/__init__.py", line 219, in setup
    if not remote_control.is_supported(service):
  File "/usr/local/lib/python3.7/dist-packages/pyatv/protocols/airplay/remote_control.py", line 48, in is_supported
    return float(version) >= 13.0
ValueError: could not convert string to float: '15.1.1'

>>> An error occurred, full stack trace above

### Error log

atvremote --id 50:DE:06:9E:50:7C --airplay-credentials "f3feb76354a4d5fc40465eb0e62cd3771f945c334112e43db2049da510cc7feb:1e05b338af74c2589bea18347fc4fbe11611497a6d427bb76534b1cb120f1b92:43434242323538452d393738432d344144332d413232332d364135353433373043323337:37616364396565302d646339652d343866332d393565322d336132396664626563636264" turn_off --debug
2021-11-11 11:27:58 DEBUG [pyatv.support.net]: Binding on *:5353
2021-11-11 11:27:58 DEBUG [pyatv.support.net]: Binding on 127.0.0.1:0
2021-11-11 11:27:58 DEBUG [pyatv.support.net]: Binding on 192.168.1.15:0
2021-11-11 11:27:58 DEBUG [pyatv.core.scan]: Auto-discovered Séjour at 192.168.1.3:49152 via Protocol.Companion ({'rpmac': '2', 'rphn': 'd493e69c68c3', 'rpfl': '0xB6782', 'rpha': '7d3e1c4be5c1', 'rpmd': 'AppleTV6,2', 'rpvr': '310.7', 'rpad': '175e4e3853ea', 'rphi': 'e17853b73d76', 'rpba': '54:41:20:E6:1B:BE', 'rpmrtid': 'CCBB258E-978C-4AD3-A223-6A554370C237'})
2021-11-11 11:27:58 DEBUG [pyatv.core.scan]: Auto-discovered Séjour at 192.168.1.3:7000 via Protocol.AirPlay ({'acl': '0', 'btaddr': '50:DE:06:A1:DC:C6', 'deviceid': '50:DE:06:9E:50:7C', 'fex': '1d9/St5/FbwI', 'features': '0x4A7FDFD5,0xBC157FDE', 'flags': '0x644', 'gid': 'AEAE89A2-C8DD-4B1B-986C-638ECF028125', 'igl': '1', 'gcgl': '1', 'model': 'AppleTV6,2', 'protovers': '1.1', 'pi': '74b61028-7078-4e05-9fa7-d7d10c6e8d22', 'psi': 'CCBB258E-978C-4AD3-A223-6A554370C237', 'pk': 'b3702384ff75e79216ffe35fa00bc41b1cf6b8ad99337bb54c33f5738e59239c', 'srcvers': '595.15.41', 'osvers': '15.1.1', 'vv': '2'})
2021-11-11 11:27:58 DEBUG [pyatv.core.scan]: Auto-discovered 50DE069E507C@Séjour at 192.168.1.3:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x4A7FDFD5,0xBC157FDE', 'sf': '0x644', 'md': '0,1,2', 'am': 'AppleTV6,2', 'pk': 'b3702384ff75e79216ffe35fa00bc41b1cf6b8ad99337bb54c33f5738e59239c', 'tp': 'UDP', 'vn': '65537', 'vs': '595.15.41', 'ov': '15.1.1', 'vv': '2'})
2021-11-11 11:27:58 INFO [pyatv.scripts.atvremote]: Auto-discovered Séjour at 192.168.1.3
2021-11-11 11:27:58 DEBUG [pyatv.core.facade]: Adding handler for protocol Protocol.AirPlay
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyatv/scripts/atvremote.py", line 716, in _run_application
    return await cli_handler(loop)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/scripts/atvremote.py", line 510, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/scripts/atvremote.py", line 601, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/__init__.py", line 92, in connect
    loop, config, service, atv, session_manager
  File "/usr/local/lib/python3.7/dist-packages/pyatv/protocols/airplay/__init__.py", line 219, in setup
    if not remote_control.is_supported(service):
  File "/usr/local/lib/python3.7/dist-packages/pyatv/protocols/airplay/remote_control.py", line 48, in is_supported
    return float(version) >= 13.0
ValueError: could not convert string to float: '15.1.1'

### How to reproduce the bug?

---

### What is expected behavior?

----

### Operating System

Linux

### Python

3.7

### pyatv

last

### Device

tvOS 15.1

### Additional context

None

**Comment by postlund** [comment]
You are using an old version of pyatv, upgrade to at least 0.9.3 and it should work.

**Comment by alteum-Fib** [comment]
solde by reinstalling peat

**Comment by alteum-Fib** [comment]
Indeed sol de

Envoyé de mon iPad
