### ISSUE TITLE
hass-atv-beta 2.0.0 requires Home Assistant 2021.12.0 or later

### ISSUE THREAD

**Issue by gvssr** [postlund/pyatv#1501]
### Describe the bug

Updating to v2.0.0 marks entities as unavailable and the integration as not loaded.

### Error log

```log
Logger: homeassistant.bootstrap
Source: custom_components/apple_tv/config_flow.py:149
Integration: Apple TV
First occurred: 12:58:11 (1 occurrences)
Last logged: 12:58:11

Error setting up integration apple_tv - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 104, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 287, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 283, in async_setup
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/apple_tv/config_flow.py", line 59, in <module>
    class AppleTVConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
  File "/config/custom_components/apple_tv/config_flow.py", line 149, in AppleTVConfigFlow
    self, discovery_info: zeroconf.ZeroconfServiceInfo
AttributeError: module 'homeassistant.components.zeroconf' has no attribute 'ZeroconfServiceInfo'
```

### How to reproduce the bug?

Update to v2.0.0

### What is expected behavior?

Loaded integrations and working entities

### Operating System

Home Assistant OS 2021.11.5

### Python

3.9

### pyatv

0.9.7

### Device

Apple TV 4K iOS 15

### Additional context

![image](https://user-images.githubusercontent.com/61377476/144842757-36cb3d16-eda9-434f-a0a3-4fa5cf92d6ef.png)
![image](https://user-images.githubusercontent.com/61377476/144842791-eb4c2182-b182-4950-ba3d-34a07a0054ea.png)

**Comment by postlund** [comment]
Please roll back to previous version and await next Home Assistant release (it's this all over again).

**Comment by gvssr** [comment]
Rollback fixed it, I'll wait for the next HA release!

**Comment by postlund** [comment]
So, since 2021.12 is out now, things should be back to normal.
