### ISSUE TITLE
atvscript playing is facing an exception "app is not supported"

### ISSUE THREAD

**Issue by sklever** [postlund/pyatv#1502]
Just installed via `pip install pyatv` scanning is working fine.
Now I want to see what's currently playing

So while executing `atvscript -s 192.168.178.27 playing` I'm facing following error:

```json
{
  "result": "failure",
  "datetime": "2021-12-06T13:33:35.612050+01:00",
  "exception": "app is not supported",
  "stacktrace": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/scripts/atvscript.py\", line 302, in appstart\n    print(args.output(await _handle_command(args, abort_sem, loop)), flush=True)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/scripts/atvscript.py\", line 198, in _handle_command\n    return await _run_command(atv, args, abort_sem, loop)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/scripts/atvscript.py\", line 205, in _run_command\n    return output_playing(await atv.metadata.playing(), atv.metadata.app)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/core/facade.py\", line 193, in app\n    return self.relay(\"app\")\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/core/relayer.py\", line 82, in relay\n    instance = self._find_instance(\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/core/relayer.py\", line 106, in _find_instance\n    raise exceptions.NotSupportedError(f\"{target} is not supported\")\npyatv.exceptions.NotSupportedError: app is not supported\n"
}
```

_further notice:_ while executing `atvscript -s 192.168.178.27 playing` ATV is displaying a pair code, haven't expected this too.

**Comment by postlund** [comment]
Ah, I don't verify the App feature in atvscript. Should fix that. It will work if you pass `--airplay-credentials` though (which you need to do in case you want metadata), assuming you have a device running tvOS.

I will look into the pair code dialog, I think the same thing happened to me as well. It's a separate issue though and I will create a new issue for it later.

**Comment by sklever** [comment]
well same is happening on command `atvscript -s 192.168.178.27 push_updates`

it's correct IP so there is no need for any pair code, isn't it?

**Comment by postlund** [comment]
As I said, you need to provide `--airplay-credentials` for anything to work. From tvOS 15 you can't do anything without authentication.

**Comment by sklever** [comment]
So I tried to pair via `atvscript --id mydeviceID --protocol mrp pair` and it's getting error message:
`{"result": "failure", "datetime": "2021-12-07T11:46:04.204467+01:00", "error": "device_not_found"`

Would you be so kind to name exact atvscript command  for pairing to get credentials?

**Comment by postlund** [comment]
MRP is not used standalone like that anymore, you should use AirPlay instead. Also, `atvremote` is needed for pairing:

    atvremote --id <id> --protocol mrp pair

Then just copy the credentials you get and pass them via `atvscript --airplay-credentials <credentials> ...`.

**Comment by sklever** [comment]
tried `atvremote --id <id> --protocol mrp pair`

when using identifier, not IP address, I'm getting following now:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 719, in _run_application
    return await cli_handler(loop)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 507, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 685, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 176, in pair
    pairing = await pair(conf, self.args.protocol, self.loop, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/__init__.py", line 120, in pair
    raise exceptions.NoServiceError(f"no service available for {protocol}")
pyatv.exceptions.NoServiceError: no service available for Protocol.MRP

>>> An error occurred, full stack trace above
```

when using IP address of ATV instead it getting back following:
`2021-12-07 12:15:51 ERROR [pyatv.scripts.atvremote]: Could not find any Apple TV on current network`

btw: `atvremote --debug --id <id> --protocol airplay pair` is working proper though, but then no luck with `atvscript --airplay-credentials <credentials>`

**Comment by postlund** [comment]
Bah, my bad (was answering quickly on my phone), it should of course be the latter command you tried (with airplay). What error do you get with the airplay credentials?

**Comment by sklever** [comment]
when using 
`atvscript --airplay-credentials 0847872b5f6a298a770a7883d96e522bc344a85883a7ac801e1728e95646efd3:ef73e9cf9aa7ec31b515947d39cd62ad7120c4fcef722caa7deb31c93fe5b19b:31464444464630382d424442442d343143322d383134352d454438373932414634373432:32343565313866632d653235612d343233642d623738372d353361646238626165613362 playing` 

it's getting:
`{"result": "failure", "datetime": "2021-12-07T12:41:21.448793+01:00", "exception": "app is not supported", "stacktrace": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/scripts/atvscript.py\", line 302, in appstart\n    print(args.output(await _handle_command(args, abort_sem, loop)), flush=True)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/scripts/atvscript.py\", line 198, in _handle_command\n    return await _run_command(atv, args, abort_sem, loop)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/scripts/atvscript.py\", line 205, in _run_command\n    return output_playing(await atv.metadata.playing(), atv.metadata.app)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/core/facade.py\", line 193, in app\n    return self.relay(\"app\")\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/core/relayer.py\", line 82, in relay\n    instance = self._find_instance(\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/core/relayer.py\", line 106, in _find_instance\n    raise exceptions.NotSupportedError(f\"{target} is not supported\")\npyatv.exceptions.NotSupportedError: app is not supported\n"}`

**Comment by sklever** [comment]
now it's getting results as 
`{"result": "success", "datetime": "2021-12-07T12:43:30.307578+01:00", "hash": "BEF6CDE8-785E-4CED-A861-F14AE7A066A1", "media_type": "unknown", "device_state": "playing", "title": "20 Jahre Xbox - Die Geschichte von Microsofts erster Konsole", "artist": "Spielewelten", "album": null, "genre": null, "total_time": 3049, "position": 148, "shuffle": "off", "repeat": "off", "series_name": null, "season_number": null, "episode_number": null, "content_identifier": null, "app": "YouTube", "app_id": "com.google.ios.youtube"}`

for some reasons it's not working every time though

**Comment by postlund** [comment]
Right, it's because of the initial bug. If you pair companion (`atvemote -id <...> --protocol companion pair` and set them with `--companion-credentials <credentials>`) it will always work. You shall always give *both* `--airplay-credentials` and `--companion-credentials` every time.

**Comment by sklever** [comment]
ok, here's what I did now:

`atvremote --debug --id F0:B3:EC:07:94:27 --protocol airplay pair --companion-credentials 0847872b5f6a298a770a7883d96e522bc344a85883a7ac801e1728e95646efd3:ef73e9cf9aa7ec31b515947d39cd62ad7120c4fcef722caa7deb31c93fe5b19b:31464444464630382d424442442d343143322d383134352d454438373932414634373432:32343565313866632d653235612d343233642d623738372d353361646238626165613362`

enter pair code, then trying to retrieve what's playing:

`atvscript --airplay-credentials 0847872b5f6a298a770a7883d96e522bc344a85883a7ac801e1728e95646efd3:cd1698bc13987ad8f38f485da8a39976b192ce304367b491cf86caf78fc05bfb:31464444464630382d424442442d343143322d383134352d454438373932414634373432:31346238353035392d643836342d346330622d626539392d623962663963366338386365 playing`

again it's getting error:
`{"result": "failure", "datetime": "2021-12-07T12:54:29.413482+01:00", "exception": "app is not supported", "stacktrace": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/scripts/atvscript.py\", line 302, in appstart\n    print(args.output(await _handle_command(args, abort_sem, loop)), flush=True)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/scripts/atvscript.py\", line 198, in _handle_command\n    return await _run_command(atv, args, abort_sem, loop)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/scripts/atvscript.py\", line 205, in _run_command\n    return output_playing(await atv.metadata.playing(), atv.metadata.app)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/core/facade.py\", line 193, in app\n    return self.relay(\"app\")\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/core/relayer.py\", line 82, in relay\n    instance = self._find_instance(\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/core/relayer.py\", line 106, in _find_instance\n    raise exceptions.NotSupportedError(f\"{target} is not supported\")\npyatv.exceptions.NotSupportedError: app is not supported\n"}`

tried push-updates via 
`atvscript --airplay-credentials 0847872b5f6a298a770a7883d96e522bc344a85883a7ac801e1728e95646efd3:cd1698bc13987ad8f38f485da8a39976b192ce304367b491cf86caf78fc05bfb:31464444464630382d424442442d343143322d383134352d454438373932414634373432:31346238353035392d643836342d346330622d626539392d623962663963366338386365 push-updates`

hereby getting error:
`{"result": "failure", "datetime": "2021-12-07T12:54:03.147092+01:00", "error": "unsupported_command"}`

would be really great to get this back up runnning, many thanks

**Comment by postlund** [comment]
You first get the credentials like this:

    atvremote --debug --id F0:B3:EC:07:94:27 --protocol airplay pair
    atvremote --debug --id F0:B3:EC:07:94:27 --protocol companion pair

Then you call `atvscript` like this:

    atvscript --id F0:B3:EC:07:94:27 --airplay-credentials <airplay credentials> --companion-credentials <companion credentials> playing

You don't have to re-pair, just use the credentials you got from before.

**Comment by sklever** [comment]
hmm, first airplay pair is working as expected
on companion pair I'm getting error:

```
atvremote --debug --id F0:B3:EC:07:94:27 --protocol companion pair
2021-12-07 13:15:55 DEBUG [pyatv.scripts]: Running with pyatv 0.9.7
2021-12-07 13:15:55 DEBUG [pyatv.support.net]: Binding on *:5353
2021-12-07 13:15:55 DEBUG [pyatv.support.net]: Binding on 127.0.0.1:0
2021-12-07 13:15:55 DEBUG [pyatv.support.net]: Binding on 192.168.178.30:0
2021-12-07 13:15:55 DEBUG [pyatv.core.scan]: Auto-discovered Apple TV 4K at 192.168.178.27:7000 via Protocol.AirPlay ({'acl': '0', 'btaddr': 'F0:B3:EC:13:82:9E', 'deviceid': 'F0:B3:EC:07:94:27', 'fex': '1d9/St5/FbwI', 'features': '0x4A7FDFD5,0xBC157FDE', 'flags': '0x18644', 'gid': '94CEEFE7-E9DC-5DE1-B4CF-2E149CE231DC', 'igl': '1', 'gcgl': '1', 'gpn': 'Apple TV 4K', 'psgsz': '3', 'psgtp': '1', 'psgid': '94CEEFE7-E9DC-5DE1-B4CF-2E149CE231DC', 'pgm': '0', 'model': 'AppleTV11,1', 'protovers': '1.1', 'pi': 'c7559852-5300-449a-8b4b-1a53b51820e4', 'psi': '1FDDFF08-BDBD-41C2-8145-ED8792AF4742', 'pk': '9fb49d0b08eeb4b9a4166fdda3453c125eac1a43d7f78bb9817ff7f166a30c30', 'srcvers': '566.25.43', 'osvers': '15.0', 'vv': '2'})
2021-12-07 13:15:55 DEBUG [pyatv.core.scan]: Auto-discovered Apple TV 4K at 192.168.178.27:49152 via Protocol.Companion ({'rpmac': '1', 'rphn': '1022cf8209fc', 'rpfl': '0x367A6', 'rpha': '2743a5ecea97', 'rpmd': 'AppleTV11,1', 'rpvr': '300.66', 'rpad': 'a063623847c9', 'rphi': 'c856eeaa37b2', 'rpba': 'DB:EE:76:99:3B:27', 'rpmrtid': '1FDDFF08-BDBD-41C2-8145-ED8792AF4742'})
2021-12-07 13:15:55 DEBUG [pyatv.core.scan]: Auto-discovered F0B3EC079427@Apple TV 4K at 192.168.178.27:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x4A7FDFD5,0xBC157FDE', 'sf': '0x18644', 'md': '0,1,2', 'am': 'AppleTV11,1', 'pk': '9fb49d0b08eeb4b9a4166fdda3453c125eac1a43d7f78bb9817ff7f166a30c30', 'tp': 'UDP', 'vn': '65537', 'vs': '566.25.43', 'ov': '15.0', 'vv': '2'})
2021-12-07 13:15:55 DEBUG [pyatv.protocols.companion.pairing]: Start pairing Companion
2021-12-07 13:15:55 DEBUG [pyatv.protocols.companion.connection]: Connected to companion device 192.168.178.27:49152
2021-12-07 13:15:55 DEBUG [pyatv.protocols.companion.protocol]: Companion credentials: None
2021-12-07 13:15:55 DEBUG [pyatv.protocols.companion.protocol]: Exchange OPACK: {'_pd': b'\x00\x01\x00\x06\x01\x01', '_pwTy': 1}
2021-12-07 13:15:55 DEBUG [pyatv.protocols.companion.protocol]: Send OPACK: {'_pd': b'\x00\x01\x00\x06\x01\x01', '_pwTy': 1, '_x': 3617}
2021-12-07 13:15:55 DEBUG [pyatv.protocols.companion.connection]: >> Send data (Data=e3435f706476000100060101455f7077547909425f7831210e, FrameType=03)
2021-12-07 13:15:55 DEBUG [pyatv.protocols.companion.connection]: Received data (Data=04000028e2435f65633188e5435f656d5b4e6f6e2d686f6d6520616363657373206e6f7420616c6c6f776564)
2021-12-07 13:15:55 DEBUG [pyatv.protocols.companion.protocol]: Received frame FrameType.PS_Next: b'\xe2C_ec1\x88\xe5C_em[Non-home access not allowed'
2021-12-07 13:15:55 DEBUG [pyatv.protocols.companion.protocol]: Process incoming auth frame (FrameType.PS_Next): {'_ec': 58760, '_em': 'Non-home access not allowed'}
2021-12-07 13:15:55 ERROR [pyatv.scripts.atvremote]: Pairing failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/support/__init__.py", line 33, in error_handler
    return await func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/protocols/companion/auth.py", line 54, in start_pairing
    resp = await self.protocol.exchange_auth(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/protocols/companion/protocol.py", line 145, in exchange_auth
    return await self._exchange_generic_opack(frame_type, data, identifier, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/protocols/companion/protocol.py", line 178, in _exchange_generic_opack
    raise exceptions.ProtocolError(f"Command failed: {unpacked_object['_em']}")
pyatv.exceptions.ProtocolError: Command failed: Non-home access not allowed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 179, in pair
    await self._perform_pairing(pairing)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 189, in _perform_pairing
    await pairing.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/protocols/companion/pairing.py", line 53, in begin
    await error_handler(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyatv/support/__init__.py", line 41, in error_handler
    raise fallback(str(ex)) from ex
pyatv.exceptions.PairingError: Command failed: Non-home access not allowed
2021-12-07 13:15:55 DEBUG [pyatv.protocols.companion.connection]: Closing connection
2021-12-07 13:15:55 DEBUG [pyatv.protocols.companion.connection]: Connection lost to remote device: None
```

**Comment by postlund** [comment]
You need to go to the AirPlay menu on your Apple TV and change so that anyone on the same network is allowed to connect.

**Comment by sklever** [comment]
So it's working now, finally.

Just one more thing: what's correct full statement for `push-updates` then?

**Comment by postlund** [comment]
Same thing but `push_updates` instead of `playing` should work.

**Comment by sklever** [comment]
hahaha, my fault, sorry, used `push-updates` instead of `push_updates` (underscore)
thx working fine for me now

**Comment by postlund** [comment]
Perfect! 👍
