### ISSUE TITLE
Cant Remove Apple TV Integration

### ISSUE THREAD

**Issue by aasquith94** [postlund/pyatv#1511]
### Describe the bug

Apple tv integration was not working right so I went to reinstall. From the home assistant integrations I click the 3 dots and then delete and it does nothing and it logs the error I included. If I go to HACS and try to delete it it says I have to remove it from the HA integrations first.

I have tried in HACS reinstalling many different versions to see if the issue was version specific. No change.

### Error log

```log
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/apple_tv/__init__.py:6 
Integration: Apple TV 
First occurred: 5:27:53 AM (1 occurrences) 
Last logged: 5:27:53 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 71, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 822, in async_remove
    await entry.async_remove(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 478, in async_remove
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 522, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/apple_tv/__init__.py", line 6, in <module>
    from pyatv import connect, exceptions, scan
  File "/usr/local/lib/python3.9/site-packages/pyatv/__init__.py", line 16, in <module>
    from pyatv.protocols import PROTOCOLS
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/__init__.py", line 10, in <module>
    from pyatv.protocols import airplay as airplay_proto
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/airplay/__init__.py", line 24, in <module>
    from pyatv.protocols import mrp
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 44, in <module>
    from pyatv.protocols.mrp import messages, protobuf
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/messages.py", line 8, in <module>
    from pyatv.protocols.mrp import protobuf
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/protobuf/__init__.py", line 6, in <module>
    from .ProtocolMessage_pb2 import ProtocolMessage
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/protobuf/ProtocolMessage_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

```

### How to reproduce the bug?

Not sure how it happened so can not reproduce

### What is expected behavior?

To delete the integration when I click delete

### Operating System

Home Assistant OS

### Python

3.9

### pyatv

Unknown

### Device

Apple TV 4k tvOS 15.1.1

### Additional context

N/A

**Comment by postlund** [comment]
Looks like I have to re-generate my protobuf messages. I'll try to do that soon and make a new release, thanks for reporting. Unfortunately I think you have to remove the config entry manually from `.storage/core.config_entries` to fix this until then.

**Comment by postlund** [comment]
So, while looking at this, I found this issue:

https://github.com/home-assistant/core/issues/59941

I can find similar issues in other project on GitHub and via Google. The gist seems to be that upgrading protobuf (python versions) seems to fix the problem. The question is what version of protobuf you have installed, maybe one of you integrations pull in a very old version somehow? I have managed to run `atvremote` successfullt with protobuf 3.12.0 though, so I'm not sure at all what is going on...

**Comment by postlund** [comment]
If you still have this problem, can you try again with 2.2.0 that I just released?

**Comment by aasquith94** [comment]
That fixed it thanks!

**Comment by postlund** [comment]
Great! 👍
