### ISSUE TITLE
AirPlay play_url /play 404 response

### ISSUE THREAD

**Issue by oownus** [postlund/pyatv#1518]
### Describe the bug

I'm trying to play a video file from a URL, any idea why /play is responding with 404 with valid airplay credentials? Thanks in advance

### Error log

```2021-12-10 00:42:53 DEBUG [pyatv.scripts]: Running with pyatv 0.9.7
2021-12-10 00:42:53 DEBUG [pyatv.support.net]: Binding on *:5353
2021-12-10 00:42:53 DEBUG [pyatv.support.net]: Binding on 127.0.0.1:0
2021-12-10 00:42:53 DEBUG [pyatv.support.net]: Binding on 192.168.1.84:0
2021-12-10 00:42:56 DEBUG [pyatv.core.scan]: Auto-discovered Jay’s MacBook Air at 192.168.1.84:7000 via Protocol.AirPlay ({'act': '2', 'acl': '0', 'deviceid': 'B0:BE:FE:BB:CF:40', 'fex': '1c9/St5PFbgG', 'features': '0x4A7FCFD5,0xB8154FDE', 'rsf': '0x8', 'flags': '0x204', 'gid': '9373AD07-5BF8-4FE5-B643-909B431731AC', 'igl': '0', 'gcgl': '0', 'model': 'MacBookAir10,1', 'at': '4', 'protovers': '1.1', 'pi': 'a8fc50d8-0290-49d1-94ae-d9fe2e7bd289', 'psi': '19BC5597-99C3-4750-B1AF-01228A8B6228', 'pk': 'e5f5eeccb5cae3f90da55b0249b61cac31ae251b6047842c684656c2066b02b6', 'srcvers': '595.13.1'})
2021-12-10 00:42:56 DEBUG [pyatv.core.scan]: Auto-discovered Jay’s MacBook Air at 192.168.1.84:63135 via Protocol.Companion ({'rpmac': '0', 'rphn': 'fca4c9524897', 'rpfl': '0x20000', 'rpha': '21b0c692fb6f', 'rpvr': '310.7.1', 'rpad': '8f1eb49cc3b6', 'rphi': 'dfc4364da1c7', 'rpba': '4B:E2:AF:2B:60:A1'})
2021-12-10 00:42:56 DEBUG [pyatv.core.scan]: Auto-discovered B0BE8331AE40@Jay’s MacBook Air at 192.168.1.84:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x4A7FCFD5,0xB8154FDE', 'sf': '0x204', 'md': '0,1,2', 'am': 'MacBookAir10,1', 'pk': 'e5f5eeccb5cae3f90da55b0249b61cac31ae251b6047842c684656c2066b02b6', 'tp': 'UDP', 'vn': '65537', 'vs': '595.13.1', 'vv': '0'})
2021-12-10 00:42:56 DEBUG [pyatv.core.scan]: Auto-discovered [LG] webOS TV UM7300PUA at 192.168.1.244:7000 via Protocol.AirPlay ({'acl': '0', 'deviceid': '58:28:B4:23:17:BD', 'features': '0x7F8AD0,0x38BCB46', 'rsf': '0x3', 'fv': 'p20.05.10.25', 'flags': '0x244', 'model': '55UM7300PUA', 'manufacturer': 'LG Electronics', 'serialnumber': '912RMTT52513_64:95:6c:46:e6:5d\n', 'protovers': '1.1', 'srcvers': '377.25.06', 'pi': '58:28:B4:23:17:BD', 'psi': '00000000-0000-0000-0000-5828B42317BD', 'gid': '00000000-0000-0000-0000-5828B42317BD', 'gcgl': '0', 'pk': '641e7f20c7919a5c56c352294e1e7630dc0c64a97bbce09c07a306c7848950b9'})
2021-12-10 00:42:56 INFO [pyatv.scripts.atvremote]: Auto-discovered [LG] webOS TV UM7300PUA at 192.168.1.244
2021-12-10 00:42:56 DEBUG [pyatv.core.facade]: Adding handler for protocol Protocol.AirPlay
2021-12-10 00:42:56 DEBUG [pyatv.protocols.airplay]: Remote control not supported by device
2021-12-10 00:42:56 DEBUG [pyatv.core.facade]: Connecting to protocol: Protocol.AirPlay
2021-12-10 00:42:56 DEBUG [pyatv.core.facade]: Connected to protocol: Protocol.AirPlay
2021-12-10 00:42:56 DEBUG [pyatv.core.facade]: Power management not supported by any protocols
NOTE: Push updates are not supported in this configuration
2021-12-10 00:42:56 DEBUG [pyatv.support.http]: Connected to 192.168.1.244
2021-12-10 00:42:56 DEBUG [pyatv.protocols.airplay.auth]: Setting up new AirPlay Pair-Verify procedure with type AuthenticationType.HAP
2021-12-10 00:42:56 DEBUG [pyatv.support.http]: Sending HTTP/1.1 message: b'POST /pair-verify HTTP/1.1\r\nContent-Length: 37\r\nUser-Agent: AirPlay/320.20\r\nConnection: keep-alive\r\nX-Apple-HKP: 3\r\nContent-Type: application/octet-stream\r\n\r\n\x06\x01\x01\x03 \xa7\xc5\xeb\x9c\xc2N\x95\x18\xefVQ\x89\t\x89\x87\xc6E\xa5\xa0\xacX\xbe6\x12W\xf7\x17\x0e\xf9\xc4\x8fW'
2021-12-10 00:42:56 DEBUG [pyatv.support.http]: Received: b'HTTP/1.1 200 OK\r\nContent-Length: 140\r\nContent-Type: application/octet-stream\r\nServer: AirTunes/377.25.06\r\n\r\n\x05e\x01\xec\xde]\x81\x1b\xbd\xbdz\xa8\xfeh\x88\xea\x8c;\xdc\xdc\xaa\x02E\xd8\x95\x01\x03(\xaa=>\xccx\x01\x8d\xa3\x126QuC\x1e\x1e\xd6\xf1E\x03\x9a\x8f\xf7D|\xfa>\xed\xd9\xe5\xc7\x15\xa4z\x0c\xea\xa7[\x9bG\xd0\x9e\xae\x08xw[&\x9302\xa4\x90\xf5X\xa0\xeb\xea,\xf0\x00?\xdd/\x00\r\x1c\x7f2\x93\xfa\xe6\x86\x9b\xec\x92\x06\x01\x02\x03 \x94>\xd3E\xdar\xca\x81\xe0V\xb7\xe8\x9d\xfb\t\x08\x8d%\x14fs.C\xaaL\xc9E\\\xfa\xb7\xeeU'
2021-12-10 00:42:56 DEBUG [pyatv.support.http]: Got HTTP response: HttpResponse(protocol='HTTP', version='1.1', code=200, message='OK', headers={'content-length': '140', 'content-type': 'application/octet-stream', 'server': 'AirTunes/377.25.06'}, body=b'\x05e\x01\xec\xde]\x81\x1b\xbd\xbdz\xa8\xfeh\x88\xea\x8c;\xdc\xdc\xaa\x02E\xd8\x95\x01\x03(\xaa=>\xccx\x01\x8d\xa3\x126QuC\x1e\x1e\xd6\xf1E\x03\x9a\x8f\xf7D|\xfa>\xed\xd9\xe5\xc7\x15\xa4z\x0c\xea\xa7[\x9bG\xd0\x9e\xae\x08xw[&\x9302\xa4\x90\xf5X\xa0\xeb\xea,\xf0\x00?\xdd/\x00\r\x1c\x7f2\x93\xfa\xe6\x86\x9b\xec\x92\x06\x01\x02\x03 \x94>\xd3E\xdar\xca\x81\xe0V\xb7\xe8\x9d\xfb\t\x08\x8d%\x14fs.C\xaaL\xc9E\\\xfa\xb7\xeeU'):
2021-12-10 00:42:56 DEBUG [pyatv.protocols.airplay.auth.hap]: Device (Encrypted=01ecde5d811bbdbd7aa8fe6888ea8c3bdcdcaa0245d895010328aa3d3ecc78018da312365175431e1ed6f145039a8ff7447cfa3eedd9e5c715a47a0ceaa75b9b47d09eae0878775b26933032a490f558a0ebea2cf0003fdd2f000d1c7f3293fae6869bec92, Public=641e7f20c7919a5c56c352294e1e7630dc0c64a97bbce09c07a306c7848950b9)
2021-12-10 00:42:56 DEBUG [pyatv.support.http]: Sending HTTP/1.1 message: b"POST /pair-verify HTTP/1.1\r\nContent-Length: 125\r\nUser-Agent: AirPlay/320.20\r\nConnection: keep-alive\r\nX-Apple-HKP: 3\r\nContent-Type: application/octet-stream\r\n\r\n\x06\x01\x03\x05xa&\xa0\xf3\xd17%\xe5\x02`L\x8f\x98#VHOI\x92!3\xd31\xf5\x1d\xca\xc4\x83\xf9\xaa=\xf7\xa1d%\x9c-\x98\xf3`\xb1\x18\xd3\x1cZ\xed\x1b\xb9>m&\xf4B\x8b\xfdS\xb9\x9aC\x02\x15\xd3^\xe2\x1c)\x1f\x87\x8a*\x93\x0e\x81_\x8e\xae\xb3\xb8\xeb^\xf8QF\xd1\x11\x9d,\x91\xb7\xac=\x08\xa96\xa6r\xaa'\xd1\x94\x8c\xcb\x0c\x91\xed\xfa\x91\xb4\xbd\xb5\xa3\x8a|\xebW\xb4\xf9\xadk\xdf"
2021-12-10 00:42:56 DEBUG [pyatv.support.http]: Received: b'HTTP/1.1 200 OK\r\nContent-Length: 3\r\nContent-Type: application/octet-stream\r\nServer: AirTunes/377.25.06\r\n\r\n\x06\x01\x04'
2021-12-10 00:42:56 DEBUG [pyatv.support.http]: Got HTTP response: HttpResponse(protocol='HTTP', version='1.1', code=200, message='OK', headers={'content-length': '3', 'content-type': 'application/octet-stream', 'server': 'AirTunes/377.25.06'}, body=b'\x06\x01\x04'):
2021-12-10 00:42:56 DEBUG [pyatv.auth.hap_srp]: Keys (Input=1149489059522bdc7817e40b6a6635d633e35b07ea018dc2eb42f60551b6450b, Output=1923171105aff625071b4c8c29561f8766f66113d52f15511696787ebb9ca3d9)
2021-12-10 00:42:56 DEBUG [pyatv.protocols.airplay.player]: Starting to play https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4
2021-12-10 00:42:56 DEBUG [pyatv.support.http]: Sending HTTP/1.1 message: b'POST /play HTTP/1.1\r\nContent-Length: 257\r\nUser-Agent: MediaControl/1.0\r\nContent-Type: application/x-apple-binary-plist\r\n\r\nbplist00\xd3\x01\x02\x03\x04\x05\x06_\x10\x10Content-Location^Start-Position_\x10\x12X-Apple-Session-ID_\x10hhttps://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4\x10\x00_\x10$6505b070-6ac2-4826-b4b5-957c1f272e5d\x08\x0f"1F\xb1\xb3\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xda'
2021-12-10 00:42:56 DEBUG [pyatv.support.http]: Received: b'HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\nServer: AirTunes/377.25.06\r\n\r\n'
2021-12-10 00:42:56 DEBUG [pyatv.support.http]: Got HTTP response: HttpResponse(protocol='HTTP', version='1.1', code=404, message='Not Found', headers={'content-length': '0', 'server': 'AirTunes/377.25.06'}, body=''):
2021-12-10 00:42:56 ERROR [pyatv.scripts.atvremote]: Authentication error: status code: 404
Traceback (most recent call last):
  File "/Users/jay/.local/share/virtualenvs/lgtv-hS2Nr3ac/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 685, in _exec_command
    value = await tmp(*args)
  File "/Users/jay/.local/share/virtualenvs/lgtv-hS2Nr3ac/lib/python3.9/site-packages/pyatv/core/facade.py", line 304, in play_url
    await self.relay("play_url")(url, **kwargs)
  File "/Users/jay/.local/share/virtualenvs/lgtv-hS2Nr3ac/lib/python3.9/site-packages/pyatv/protocols/airplay/__init__.py", line 117, in play_url
    return await self._play_task
  File "/Users/jay/.local/share/virtualenvs/lgtv-hS2Nr3ac/lib/python3.9/site-packages/pyatv/protocols/airplay/player.py", line 61, in play_url
    raise exceptions.AuthenticationError(f"status code: {resp.code}")
pyatv.exceptions.AuthenticationError: status code: 404
2021-12-10 00:42:56 DEBUG [pyatv.scripts.atvremote]: Waiting for 0 remaining tasks
2021-12-10 00:42:56 DEBUG [pyatv.support.http]: Connection closed

```

### How to reproduce the bug?

```
$ atvremote -n "[LG] webOS TV UM7300PUA" --airplay-credentials
641e7f20c7919a5c56c352294e1e7630dc0c64a97bbce09c07a306c7848950b9:fd9efcac8d477cf92f58e1f49f2e06e031c89d4023cb6f930f7540f77de805a3:35383a32383a42343a32333a31373a4244:32333666343966362d613162302d346564392d383030322d313165366333326330663230
--debug
play_url=https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4```

### What is expected behavior?

AirPlay to play video from URL

### Operating System

macOS

### Python

3.9

### pyatv

master

### Device

LG TV 55" UM7300PUA

### Additional context

Trying to play mp4 video from URL on LG TV 55"

**Comment by postlund** [comment]
The exception is a bit misleading as that is obviously not an authentication error (I should fix that). My guess is that your TV does not support the `/play` command. I must say that I am not very confident as to what feature flag corresponds what actual feature in the protocol, but https://openairplay.github.io/airplay-spec/features.html with your feature flags (`0x7F8AD0,0x38BCB46`) suggests that video is not supported. HTTP live streams and audio are supported though (only audio streaming is supported by pyatv). So we are likely out of luck here until I get around supporting video streaming and to be honest, I'm not sure that will ever happen as it is very CPU intensive and hard to do in python. If offloaded to another application, maybe it can be accomplished.

**Comment by postlund** [comment]
Would you mind pasting the result of:

    atvremote -n "[LG] webOS TV UM7300PUA" --airplay-credentials 641e7f20c7919a5c56c352294e1e7630dc0c64a97bbce09c07a306c7848950b9:fd9efcac8d477cf92f58e1f49f2e06e031c89d4023cb6f930f7540f77de805a3:35383a32383a42343a32333a31373a4244:32333666343966362d613162302d346564392d383030322d313165366333326330663230 features

Looks like I have already implemented feature detection in pyatv, just not applying it in Home Assistant. Just want to verify this is the case.

**Comment by oownus** [comment]
```
$ atvremote -n "[LG] webOS TV UM7300PUA" --airplay-credentials 641e7f20c7919a5c56c352294e1e7630dc0c64a97bbce09c07a306c7848950b9:fd9efcac8d477cf92f58e1f49f2e06e031c89d4023cb6f930f7540f77de805a3:35383a32383a42343a32333a31373a4244:32333666343966362d613162302d346564392d383030322d313165366333326330663230 features
NOTE: Push updates are not supported in this configuration
Feature list:
-------------
PlayUrl: Available

Legend:
-------
Available: Supported by device and usable now
Unavailable: Supported by device but not usable now
Unknown: Supported by the device but availability not known
Unsupported: Not supported by this device (or by pyatv)
```

**Comment by postlund** [comment]
Thanks! I might be parsing the flags a bit wrong, I'll have a look at that so at least feature detection is correct.

**Comment by oownus** [comment]
Perhaps that could be the case, pretty bummed to find out that this TV doesn't support PlayUrl feature 😭 
Thanks for the awesome library though

**Comment by postlund** [comment]
Yeah, I totally agree! It's so strange that they aren't focusing more on streaming videos directly from the target device, e.g. via URL. Doing so now usually just breaks everything and makes stuff stop working (like metadata).

**Comment by postlund** [comment]
Can you try if #2079 fixes this for you?
