### ISSUE TITLE
Docker image won't run due to missing requests module

### ISSUE THREAD

**Issue by llamafilm** [postlund/pyatv#1559]
### Describe the bug

The suggested Docker command from the documentation page fails because the Python requests module is missing.

### Error log

```
 % docker run -it --rm --network=host ghcr.io/postlund/pyatv:master atvremote scan
Traceback (most recent call last):
  File "/usr/local/bin/atvremote", line 5, in <module>
    from pyatv.scripts.atvremote import main
  File "/usr/local/lib/python3.9/site-packages/pyatv/__init__.py", line 18, in <module>
    from pyatv.protocols import PROTOCOLS
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/__init__.py", line 14, in <module>
    from pyatv.protocols import raop as raop_proto
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/__init__.py", line 48, in <module>
    from pyatv.protocols.raop.audio_source import AudioSource, open_source
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/audio_source.py", line 16, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Here are the modules included in this image:

```
% docker run -it --rm --network=host ghcr.io/postlund/pyatv:master pip list
Package            Version
------------------ -------
aiohttp            3.8.1
aiosignal          1.2.0
async-timeout      4.0.2
attrs              21.2.0
bitarray           2.3.4
cffi               1.15.0
charset-normalizer 2.0.9
cryptography       36.0.1
frozenlist         1.2.0
idna               3.3
ifaddr             0.1.7
mediafile          0.9.0
miniaudio          1.45
multidict          5.2.0
mutagen            1.45.1
pip                21.2.4
protobuf           3.19.1
pyatv              0.9.8
pycparser          2.21
semantic-version   2.8.5
setuptools         57.5.0
setuptools-rust    1.1.2
six                1.16.0
srptools           1.0.1
typing_extensions  4.0.1
wheel              0.37.0
yarl               1.7.2
zeroconf           0.37.0
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

### How to reproduce the bug?

`docker run -it --rm --network=host ghcr.io/postlund/pyatv:master atvremote scan`

### What is expected behavior?

it should work

### Operating System

macOS

### Python

3.9

### pyatv

master

### Device

n/a

### Additional context

I'm running Docker 4.2.0 on macOS 11.6.

**Comment by postlund** [comment]
Ah, my bad. I will add the dependency right away!

**Comment by postlund** [comment]
Should be fixed from `sha-df6047a`/`master` now, can you verify?

**Comment by llamafilm** [comment]
Confirmed, fixed!

**Comment by postlund** [comment]
Thanks! 👍
