### ISSUE TITLE
TTS not working on Apple TV 4th gen

### ISSUE THREAD

**Issue by alexvandervegt** [postlund/pyatv#157]
When I send a TTS message to my apple tv using latest version of Home Assistant I get the following error:

`2018-09-07 23:36:01 DEBUG (MainThread) [pyatv.airplay.player] AirPlay https://myduckdnsusername.duckdns.org:8123/api/tts_proxy/37bb570100c9f5445b534757ebc613a32df3836d_nl_-_google.mp3 to http://192.168.1.180:7000/play
2018-09-07 23:36:01 DEBUG (MainThread) [pyatv.airplay.player] Playback-info (403): b''
2018-09-07 23:36:01 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 226, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/media_player/apple_tv.py", line 171, in async_play_media
    yield from self.atv.airplay.play_url(media_id)
  File "/usr/local/lib/python3.6/site-packages/pyatv/internal/apple_tv.py", line 467, in play_url
    return (yield from self.player.play_url(url, position))
  File "/usr/local/lib/python3.6/site-packages/pyatv/airplay/player.py", line 46, in play_url
    yield from self._wait_for_media_to_end()
  File "/usr/local/lib/python3.6/site-packages/pyatv/airplay/player.py", line 68, in _wait_for_media_to_end
    parsed = plistlib.loads(data)
  File "/usr/local/lib/python3.6/plistlib.py", line 1024, in loads
    fp, fmt=fmt, use_builtin_types=use_builtin_types, dict_type=dict_type)
  File "/usr/local/lib/python3.6/plistlib.py", line 1009, in load
    raise InvalidFileException()
plistlib.InvalidFileException: Invalid file`

Please let me know if i can help

**Comment by alexvandervegt** [comment]
You were right the credentials were missing, just added them. Now when i enter text the apple tv goes to a black screen with the white spinner. But it never stops loading and it does not play a sound, after a few seconds the screen is back to normaal. But no sound is spoken.

debug log:

`2018-09-08 23:10:30 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=tts, service=google_say, service_data=entity_id=media_player.woonkamer, message=another one>
2018-09-08 23:10:30 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=media_player, service=play_media, service_data=media_content_id=https://myusername.duckdns.org:8123/api/tts_proxy/df35047fffd38a65b8fe6963579254e8b09db25e_nl_-_google.mp3, media_content_type=music, entity_id=['media_player.woonkamer']>
2018-09-08 23:10:30 DEBUG (MainThread) [pyatv.airplay.srp] Verification keys (Private=587b084a9a3f02b2ab8e315de8d344524dfe3784225e5a5c0e125b68d2d4f84e, Public=d2a97e808520d1a6ae5fbaa5021e30c01ecfae666a73a7dafe224c704340a35d)
2018-09-08 23:10:30 DEBUG (MainThread) [pyatv.net] POST URL: http://192.168.1.180:7000/pair-verify
2018-09-08 23:10:30 DEBUG (MainThread) [pyatv.net] -> Data[68]: b'01000000d2a97e808520d1a6ae5fbaa5021e30c01ecfae666a73a7dafe224c704340a35dcc5ebbf0ba0447b96d39b38d83a302eaa6bc6a5168002f14cf14aaebd1d58fd5'
2018-09-08 23:10:30 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sun.sun, old_state=<state sun.sun=below_horizon; next_dawn=2018-09-09T04:31:56+00:00, next_dusk=2018-09-09T18:47:06+00:00, next_midnight=2018-09-08T23:39:22+00:00, next_noon=2018-09-09T11:39:31+00:00, next_rising=2018-09-09T05:06:20+00:00, next_setting=2018-09-09T18:12:42+00:00, elevation=-24.71, azimuth=318.19, friendly_name=Sun @ 2018-09-08T23:08:07.869869+02:00>, new_state=<state sun.sun=below_horizon; next_dawn=2018-09-09T04:31:56+00:00, next_dusk=2018-09-09T18:47:06+00:00, next_midnight=2018-09-08T23:39:22+00:00, next_noon=2018-09-09T11:39:31+00:00, next_rising=2018-09-09T05:06:20+00:00, next_setting=2018-09-09T18:12:42+00:00, elevation=-24.81, azimuth=318.44, friendly_name=Sun @ 2018-09-08T23:08:07.869869+02:00>>
2018-09-08 23:10:30 DEBUG (MainThread) [pyatv.net] <- Data[96]: b'2570f05e501e7033070a9d3e0918cbb4cd37bafa17a85a958972943dd6345071d3e1f503d5dd702cb95cf034636ac2bfbc063d36ad179c4fa7bb4a64c9f933eabce96da4f2043144ae4cac66f29f740497d08e9bd650350d75238353dd2834e0'
2018-09-08 23:10:30 DEBUG (MainThread) [pyatv.airplay.srp] Verify (PublicSecret=2570f05e501e7033070a9d3e0918cbb4cd37bafa17a85a958972943dd6345071, Data=d3e1f503d5dd702cb95cf034636ac2bfbc063d36ad179c4fa7bb4a64c9f933eabce96da4f2043144ae4cac66f29f740497d08e9bd650350d75238353dd2834e0)
2018-09-08 23:10:30 DEBUG (MainThread) [pyatv.airplay.srp] Shared secret (Secret=40299672cd3cacac468f69da56d6aa573fc8dd5f520ec8ef7a638c22311a7940)
2018-09-08 23:10:30 DEBUG (MainThread) [pyatv.airplay.srp] Pair-Verify-AES (Key=2e5969a4cd70e4da78e2119fca7f877d, IV=46b1476208fe85134b59618882b02665)
2018-09-08 23:10:31 DEBUG (MainThread) [pyatv.airplay.srp] Signature (Signature=56ab3dc871335dcefcea518a28f6e447f1da90725fb37ede115f7cb4d131649a92fa0228cc7a2d3c568ceb3a4fe5885f9397385f93779348a3c0aafc9bf49087)
2018-09-08 23:10:31 DEBUG (MainThread) [pyatv.net] POST URL: http://192.168.1.180:7000/pair-verify
2018-09-08 23:10:31 DEBUG (MainThread) [pyatv.net] -> Data[68]: b'0000000056ab3dc871335dcefcea518a28f6e447f1da90725fb37ede115f7cb4d131649a92fa0228cc7a2d3c568ceb3a4fe5885f9397385f93779348a3c0aafc9bf49087'
2018-09-08 23:10:31 DEBUG (MainThread) [pyatv.airplay.player] AirPlay https://myusername.duckdns.org:8123/api/tts_proxy/df35047fffd38a65b8fe6963579254e8b09db25e_nl_-_google.mp3 to http://192.168.1.180:7000/play
2018-09-08 23:10:31 DEBUG (MainThread) [pyatv.daap] _get_request: cmst: [container, dmcp.playstatus]
  mstt: 200 [uint, dmap.status]
  cmsr: 4 [uint, dmcp.serverrevision]
  cafs: 0 [uint, dacp.fullscreen]
  cafe: False [bool, dacp.fullscreenenabled]
  cave: False [bool, dacp.dacpvisualizerenabled]
  cavs: 0 [uint, dacp.visualizer]
  caps: 3 [uint, dacp.playstatus]
  cash: 0 [uint, dacp.shufflestate]
  carp: 0 [uint, dacp.repeatstate]
  caar: 6 [uint, dacp.albumrepeat]
  caas: 2 [uint, dacp.albumshuffle]
  caks: 1 [uint, unknown tag]
  casc: 1 [uint, unknown tag]
  cavc: True [bool, dacp.volumecontrollable]
  casu: 0 [uint, dacp.su]

2018-09-08 23:10:31 DEBUG (MainThread) [pyatv.internal.apple_tv] Waiting for playstatus updates
2018-09-08 23:10:31 DEBUG (MainThread) [pyatv.daap] Already logged in, re-using seasion id 1
2018-09-08 23:10:31 DEBUG (MainThread) [pyatv.net] GET URL: http://192.168.1.180:3689/ctrl-int/1/playstatusupdate?session-id=1&revision-number=4
2018-09-08 23:10:31 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=media_player.woonkamer, old_state=<state media_player.woonkamer=idle; media_duration=0, media_position=0, media_title=Nothing playing, friendly_name=Woonkamer, supported_features=21427 @ 2018-09-08T23:10:14.733117+02:00>, new_state=<state media_player.woonkamer=paused; media_content_type=video, media_duration=0, media_position=0, media_position_updated_at=2018-09-08T23:10:31.598943+02:00, media_title=No title, friendly_name=Woonkamer, entity_picture=/api/media_player_proxy/media_player.woonkamer?token=265cb1a0eab69b6ec619ca763aecea08435acd3d2b2b33aadfdacea17627f5cc&cache=909eeb4ec7d64c3362212b46c2e6d19d5598185652efe0ed9a120fb0b54316bd, supported_features=21427 @ 2018-09-08T23:10:31.600543+02:00>>
2018-09-08 23:10:31 DEBUG (MainThread) [pyatv.airplay.player] Playback-info (200): b'<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict/>\n</plist>\n'
2018-09-08 23:10:31 DEBUG (MainThread) [pyatv.daap] Already logged in, re-using seasion id 1
2018-09-08 23:10:31 DEBUG (MainThread) [pyatv.net] GET URL: http://192.168.1.180:3689/ctrl-int/1/nowplayingartwork?mw=1024&mh=576&session-id=1
2018-09-08 23:10:31 DEBUG (MainThread) [pyatv.daap] Already logged in, re-using seasion id 1
2018-09-08 23:10:31 DEBUG (MainThread) [pyatv.net] GET URL: http://192.168.1.180:3689/ctrl-int/1/nowplayingartwork?mw=1024&mh=576&session-id=1
2018-09-08 23:10:31 DEBUG (MainThread) [pyatv.daap] _get_request: b''
2018-09-08 23:10:31 DEBUG (MainThread) [pyatv.daap] _get_request: b''
2018-09-08 23:10:32 DEBUG (MainThread) [pyatv.daap] _get_request: cmst: [container, dmcp.playstatus]
  mstt: 200 [uint, dmap.status]
  cmsr: 5 [uint, dmcp.serverrevision]
  cafs: 0 [uint, dacp.fullscreen]
  cafe: False [bool, dacp.fullscreenenabled]
  cave: False [bool, dacp.dacpvisualizerenabled]
  cavs: 0 [uint, dacp.visualizer]
  caps: 3 [uint, dacp.playstatus]
  cash: 0 [uint, dacp.shufflestate]
  carp: 0 [uint, dacp.repeatstate]
  caar: 6 [uint, dacp.albumrepeat]
  caas: 2 [uint, dacp.albumshuffle]
  caks: 1 [uint, unknown tag]
  casc: 1 [uint, unknown tag]
  cavc: True [bool, dacp.volumecontrollable]
  casu: 0 [uint, dacp.su]

2018-09-08 23:10:32 DEBUG (MainThread) [pyatv.internal.apple_tv] Waiting for playstatus updates
2018-09-08 23:10:32 DEBUG (MainThread) [pyatv.daap] Already logged in, re-using seasion id 1
2018-09-08 23:10:32 DEBUG (MainThread) [pyatv.net] GET URL: http://192.168.1.180:3689/ctrl-int/1/playstatusupdate?session-id=1&revision-number=5
2018-09-08 23:10:32 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=media_player.woonkamer, old_state=<state media_player.woonkamer=paused; media_content_type=video, media_duration=0, media_position=0, media_position_updated_at=2018-09-08T23:10:31.598943+02:00, media_title=No title, friendly_name=Woonkamer, entity_picture=/api/media_player_proxy/media_player.woonkamer?token=265cb1a0eab69b6ec619ca763aecea08435acd3d2b2b33aadfdacea17627f5cc&cache=909eeb4ec7d64c3362212b46c2e6d19d5598185652efe0ed9a120fb0b54316bd, supported_features=21427 @ 2018-09-08T23:10:31.600543+02:00>, new_state=<state media_player.woonkamer=paused; media_content_type=video, media_duration=0, media_position=0, media_position_updated_at=2018-09-08T23:10:32.216639+02:00, media_title=No title, friendly_name=Woonkamer, entity_picture=/api/media_player_proxy/media_player.woonkamer?token=265cb1a0eab69b6ec619ca763aecea08435acd3d2b2b33aadfdacea17627f5cc&cache=909eeb4ec7d64c3362212b46c2e6d19d5598185652efe0ed9a120fb0b54316bd, supported_features=21427 @ 2018-09-08T23:10:31.600543+02:00>>
2018-09-08 23:10:32 DEBUG (MainThread) [pyatv.airplay.player] Playback-info (200): b'<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict>\n\t<key>readyToPlay</key>\n\t<integer>0</integer>\n</dict>\n</plist>\n'
2018-09-08 23:10:33 DEBUG (MainThread) [pyatv.daap] _get_request: cmst: [container, dmcp.playstatus]
  mstt: 200 [uint, dmap.status]
  cmsr: 6 [uint, dmcp.serverrevision]
  cafs: 0 [uint, dacp.fullscreen]
  cafe: False [bool, dacp.fullscreenenabled]
  cave: False [bool, dacp.dacpvisualizerenabled]
  cavs: 0 [uint, dacp.visualizer]
  caps: 3 [uint, dacp.playstatus]
  cash: 0 [uint, dacp.shufflestate]
  carp: 0 [uint, dacp.repeatstate]
  caar: 6 [uint, dacp.albumrepeat]
  caas: 2 [uint, dacp.albumshuffle]
  cann:  [str, daap.nowplayingtrack]
  cmmk: 1 [uint, dmcp.mediakind]
  caks: 1 [uint, unknown tag]
  casc: 0 [uint, unknown tag]
  cavc: True [bool, dacp.volumecontrollable]
  casu: 0 [uint, dacp.su]

2018-09-08 23:10:33 DEBUG (MainThread) [pyatv.internal.apple_tv] Waiting for playstatus updates
2018-09-08 23:10:33 DEBUG (MainThread) [pyatv.daap] Already logged in, re-using seasion id 1
2018-09-08 23:10:33 DEBUG (MainThread) [pyatv.net] GET URL: http://192.168.1.180:3689/ctrl-int/1/playstatusupdate?session-id=1&revision-number=6
2018-09-08 23:10:33 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=media_player.woonkamer, old_state=<state media_player.woonkamer=paused; media_content_type=video, media_duration=0, media_position=0, media_position_updated_at=2018-09-08T23:10:32.216639+02:00, media_title=No title, friendly_name=Woonkamer, entity_picture=/api/media_player_proxy/media_player.woonkamer?token=265cb1a0eab69b6ec619ca763aecea08435acd3d2b2b33aadfdacea17627f5cc&cache=909eeb4ec7d64c3362212b46c2e6d19d5598185652efe0ed9a120fb0b54316bd, supported_features=21427 @ 2018-09-08T23:10:31.600543+02:00>, new_state=<state media_player.woonkamer=paused; media_duration=0, media_position=0, media_position_updated_at=2018-09-08T23:10:33.496452+02:00, media_title=No title, friendly_name=Woonkamer, entity_picture=/api/media_player_proxy/media_player.woonkamer?token=265cb1a0eab69b6ec619ca763aecea08435acd3d2b2b33aadfdacea17627f5cc&cache=5336294a19f32ff03ef80066fbc3e0f7ba28ec0befbba86e85814c008739d649, supported_features=21427 @ 2018-09-08T23:10:31.600543+02:00>>
2018-09-08 23:10:33 DEBUG (MainThread) [pyatv.daap] Already logged in, re-using seasion id 1
2018-09-08 23:10:33 DEBUG (MainThread) [pyatv.net] GET URL: http://192.168.1.180:3689/ctrl-int/1/nowplayingartwork?mw=1024&mh=576&session-id=1
2018-09-08 23:10:33 DEBUG (MainThread) [pyatv.daap] Already logged in, re-using seasion id 1
2018-09-08 23:10:33 DEBUG (MainThread) [pyatv.net] GET URL: http://192.168.1.180:3689/ctrl-int/1/nowplayingartwork?mw=1024&mh=576&session-id=1
2018-09-08 23:10:33 DEBUG (MainThread) [pyatv.daap] _get_request: b''
2018-09-08 23:10:33 DEBUG (MainThread) [pyatv.airplay.player] Playback-info (200): b'<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict>\n\t<key>duration</key>\n\t<real>0.0</real>\n\t<key>durationCMTime</key>\n\t<dict>\n\t\t<key>epoch</key>\n\t\t<integer>0</integer>\n\t\t<key>flags</key>\n\t\t<integer>17</integer>\n\t\t<key>timescale</key>\n\t\t<integer>0</integer>\n\t\t<key>value</key>\n\t\t<integer>0</integer>\n\t</dict>\n\t<key>loadedTimeRanges</key>\n\t<array>\n\t\t<dict>\n\t\t\t<key>duration</key>\n\t\t\t<real>1.1040000000000001</real>\n\t\t\t<key>durationCMTime</key>\n\t\t\t<dict>\n\t\t\t\t<key>epoch</key>\n\t\t\t\t<integer>0</integer>\n\t\t\t\t<key>flags</key>\n\t\t\t\t<integer>1</integer>\n\t\t\t\t<key>timescale</key>\n\t\t\t\t<integer>24000</integer>\n\t\t\t\t<key>value</key>\n\t\t\t\t<integer>26496</integer>\n\t\t\t</dict>\n\t\t\t<key>start</key>\n\t\t\t<real>0.0</real>\n\t\t\t<key>startCMTime</key>\n\t\t\t<dict>\n\t\t\t\t<key>epoch</key>\n\t\t\t\t<integer>0</integer>\n\t\t\t\t<key>flags</key>\n\t\t\t\t<integer>1</integer>\n\t\t\t\t<key>timescale</key>\n\t\t\t\t<integer>1</integer>\n\t\t\t\t<key>value</key>\n\t\t\t\t<integer>0</integer>\n\t\t\t</dict>\n\t\t</dict>\n\t</array>\n\t<key>playbackBufferEmpty</key>\n\t<false/>\n\t<key>playbackBufferFull</key>\n\t<false/>\n\t<key>playbackLikelyToKeepUp</key>\n\t<true/>\n\t<key>position</key>\n\t<real>0.87607299900000002</real>\n\t<key>positionCMTime</key>\n\t<dict>\n\t\t<key>epoch</key>\n\t\t<integer>0</integer>\n\t\t<key>flags</key>\n\t\t<integer>1</integer>\n\t\t<key>timescale</key>\n\t\t<integer>1000000000</integer>\n\t\t<key>value</key>\n\t\t<integer>876072999</integer>\n\t</dict>\n\t<key>rate</key>\n\t<real>1</real>\n\t<key>readyToPlay</key>\n\t<integer>1</integer>\n\t<key>seekableTimeRanges</key>\n\t<array/>\n</dict>\n</plist>\n'
2018-09-08 23:10:33 DEBUG (MainThread) [pyatv.daap] _get_request: b''
2018-09-08 23:10:33 DEBUG (MainThread) [pyatv.daap] _get_request: cmst: [container, dmcp.playstatus]
  mstt: 200 [uint, dmap.status]
  cmsr: 7 [uint, dmcp.serverrevision]
  cafs: 0 [uint, dacp.fullscreen]
  cafe: False [bool, dacp.fullscreenenabled]
  cave: False [bool, dacp.dacpvisualizerenabled]
  cavs: 0 [uint, dacp.visualizer]
  caps: 3 [uint, dacp.playstatus]
  cash: 0 [uint, dacp.shufflestate]
  carp: 0 [uint, dacp.repeatstate]
  caar: 6 [uint, dacp.albumrepeat]
  caas: 2 [uint, dacp.albumshuffle]
  cann:  [str, daap.nowplayingtrack]
  cmmk: 1 [uint, dmcp.mediakind]
  caks: 1 [uint, unknown tag]
  casc: 0 [uint, unknown tag]
  cavc: True [bool, dacp.volumecontrollable]
  casu: 0 [uint, dacp.su]

2018-09-08 23:10:33 DEBUG (MainThread) [pyatv.internal.apple_tv] Waiting for playstatus updates
2018-09-08 23:10:33 DEBUG (MainThread) [pyatv.daap] Already logged in, re-using seasion id 1
2018-09-08 23:10:33 DEBUG (MainThread) [pyatv.net] GET URL: http://192.168.1.180:3689/ctrl-int/1/playstatusupdate?session-id=1&revision-number=7
2018-09-08 23:10:33 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=media_player.woonkamer, old_state=<state media_player.woonkamer=paused; media_duration=0, media_position=0, media_position_updated_at=2018-09-08T23:10:33.496452+02:00, media_title=No title, friendly_name=Woonkamer, entity_picture=/api/media_player_proxy/media_player.woonkamer?token=265cb1a0eab69b6ec619ca763aecea08435acd3d2b2b33aadfdacea17627f5cc&cache=5336294a19f32ff03ef80066fbc3e0f7ba28ec0befbba86e85814c008739d649, supported_features=21427 @ 2018-09-08T23:10:31.600543+02:00>, new_state=<state media_player.woonkamer=paused; media_duration=0, media_position=0, media_position_updated_at=2018-09-08T23:10:33.858049+02:00, media_title=No title, friendly_name=Woonkamer, entity_picture=/api/media_player_proxy/media_player.woonkamer?token=265cb1a0eab69b6ec619ca763aecea08435acd3d2b2b33aadfdacea17627f5cc&cache=5336294a19f32ff03ef80066fbc3e0f7ba28ec0befbba86e85814c008739d649, supported_features=21427 @ 2018-09-08T23:10:31.600543+02:00>>
2018-09-08 23:10:34 DEBUG (MainThread) [pyatv.daap] _get_request: cmst: [container, dmcp.playstatus]
  mstt: 200 [uint, dmap.status]
  cmsr: 8 [uint, dmcp.serverrevision]
  cafs: 0 [uint, dacp.fullscreen]
  cafe: False [bool, dacp.fullscreenenabled]
  cave: False [bool, dacp.dacpvisualizerenabled]
  cavs: 0 [uint, dacp.visualizer]
  caps: 3 [uint, dacp.playstatus]
  cash: 0 [uint, dacp.shufflestate]
  carp: 0 [uint, dacp.repeatstate]
  caar: 6 [uint, dacp.albumrepeat]
  caas: 2 [uint, dacp.albumshuffle]
  caks: 1 [uint, unknown tag]
  casc: 1 [uint, unknown tag]
  cavc: True [bool, dacp.volumecontrollable]
  casu: 0 [uint, dacp.su]

2018-09-08 23:10:34 DEBUG (MainThread) [pyatv.internal.apple_tv] Waiting for playstatus updates
2018-09-08 23:10:34 DEBUG (MainThread) [pyatv.daap] Already logged in, re-using seasion id 1
2018-09-08 23:10:34 DEBUG (MainThread) [pyatv.net] GET URL: http://192.168.1.180:3689/ctrl-int/1/playstatusupdate?session-id=1&revision-number=8
2018-09-08 23:10:34 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=media_player.woonkamer, old_state=<state media_player.woonkamer=paused; media_duration=0, media_position=0, media_position_updated_at=2018-09-08T23:10:33.858049+02:00, media_title=No title, friendly_name=Woonkamer, entity_picture=/api/media_player_proxy/media_player.woonkamer?token=265cb1a0eab69b6ec619ca763aecea08435acd3d2b2b33aadfdacea17627f5cc&cache=5336294a19f32ff03ef80066fbc3e0f7ba28ec0befbba86e85814c008739d649, supported_features=21427 @ 2018-09-08T23:10:31.600543+02:00>, new_state=<state media_player.woonkamer=paused; media_content_type=video, media_duration=0, media_position=0, media_position_updated_at=2018-09-08T23:10:34.201184+02:00, media_title=No title, friendly_name=Woonkamer, entity_picture=/api/media_player_proxy/media_player.woonkamer?token=265cb1a0eab69b6ec619ca763aecea08435acd3d2b2b33aadfdacea17627f5cc&cache=909eeb4ec7d64c3362212b46c2e6d19d5598185652efe0ed9a120fb0b54316bd, supported_features=21427 @ 2018-09-08T23:10:31.600543+02:00>>
2018-09-08 23:10:34 DEBUG (MainThread) [pyatv.daap] Already logged in, re-using seasion id 1
2018-09-08 23:10:34 DEBUG (MainThread) [pyatv.net] GET URL: http://192.168.1.180:3689/ctrl-int/1/nowplayingartwork?mw=1024&mh=576&session-id=1
2018-09-08 23:10:34 DEBUG (MainThread) [pyatv.daap] Already logged in, re-using seasion id 1
2018-09-08 23:10:34 DEBUG (MainThread) [pyatv.net] GET URL: http://192.168.1.180:3689/ctrl-int/1/nowplayingartwork?mw=1024&mh=576&session-id=1
2018-09-08 23:10:34 DEBUG (MainThread) [pyatv.daap] _get_request: b''
2018-09-08 23:10:34 DEBUG (MainThread) [pyatv.daap] _get_request: b''
2018-09-08 23:10:34 DEBUG (MainThread) [pyatv.airplay.player] Playback-info (200): b'<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict/>\n</plist>\n'
2018-09-08 23:10:34 DEBUG (MainThread) [pyatv.airplay.player] media playback ended
2018-09-08 23:10:34 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_executed[L]>
2018-09-08 23:10:34 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_executed[L]>
`

**Comment by alexvandervegt** [comment]
When i manually enter all the details it is working. Just not when I click the 3 dots in the media player card.

<img width="1129" alt="screen shot 2018-09-08 at 23 26 08" src="https://user-images.githubusercontent.com/3672692/45258783-a8af0280-b3be-11e8-960f-a7b4683ce265.png">

**Comment by alexvandervegt** [comment]
When i use actions in automations like this:

action:
      - service: tts.google_say
        entity_id: media_player.woonkamer
        data:
          message: 'May the Force be with you.'

I only hear "you" at the end or somethimes "may" in the beginning. Then the white loading circle is back end eventually times out.

**Comment by postlund** [comment]
Hmm, this seems a bit strange, I must agree. I know that when using TTS in automations, you might have to add a delay afterwards to give it time to "finish talking". My best guess is that this has something to do with buffering. If you try to speak the same phrase twice, is the result the same? Home Assistant will cache new phrases after it has been spoken, so the first time might take some additional time when the phrase is downloaded.

**Comment by postlund** [comment]
I just tried TTS with latest version of Home Assistant and it seems to work fine. No words missing, at least when using the service and calling from the media_player card. The white spinner however appears afterwards for quite some time, likely because the connection not being closed properly. I've looked at this a bit and it is likely related to the fact that the session in aiohttp is re-used from Home Assistant. Must be solvable somehow without creating a new session.

**Comment by OtherStep** [comment]
I'm testing now with 0.88.2 and Apple TV 4k.  When nothing is playing, TTS works well.  However, when media is playing, I get the spinning circle and black screen then back to media, but no sound.  Also, the pause button in the media player will only pause for a second and then play (like it is sending the command twice), but will play from paused media just fine.

**Comment by fmonday** [comment]
With TVOS 12.2 I'm seeing overall improved ATV functioning, but with TTS, I have the persisting spinning circle as described above by @postlund; in fact in my case it doesn't go away until I intervene. However, pressing the menu button once takes it back to right where it left off, even if media was playing.

**Comment by postlund** [comment]
I'm gonna try to re-test this some day when I have time using just atvremote. If that works I will close this issue as it's not a problem with pyatv, but with Home Assistant (or the way it's using pyatv, as stated above). We need to keep the issue apart.

**Comment by postlund** [comment]
AirPlay streaming was fixed in #226 and was verified to work in #209. So I will finally close this.
