### ISSUE TITLE
Airport Express is discovered, but cannot be paired.

### ISSUE THREAD

**Issue by autoneub** [postlund/pyatv#1581]
### What do you need help with?

Using Home Assistant 2021.12.1 Supervised in VM running on Mac Mini 2012 macOS 10.13.6
Apple TV Beta integration v2.2.0 via HACS
My Gen 2 Airport Express is discovered, but cannot pair.
First attempt was RAOP issue
![Screen Shot 2022-01-04 at 10 38 39 PM](https://user-images.githubusercontent.com/47952561/148170230-72781a95-5370-455c-a35b-a141932d16d6.png)
Now this...
![Screen Shot 2022-01-04 at 11 26 16 PM](https://user-images.githubusercontent.com/47952561/148170521-4c3173d3-9738-47b3-bdf8-ab8f60f98840.png)

The APX has no password set for connecting via AirPlay.
I checked the logs directly after attempting and nothing showed.

Any help you could provide would be appreciated. Thank you for such an incredible integration by the way.

**Comment by postlund** [comment]
You need to open the Home app, go to home settings and allow anyone on the same network to connect to speakers and televisions. That should solve the problem.

**Comment by autoneub** [comment]
Thank you for such a speedy response. 
I currently already have that set. 
I didn't mention, but I also have a couple HomePod minis that paired without issue.
Any other thoughts?

**Comment by postlund** [comment]
Hmm, that's strange. Is the AirPort standalone or added to your home? It would help if you could provide some scan log for me with `atvremote scan`. You need pyatv installed first and if you have docker set up anywhere, it's easiest to use that. You have some instructions here:

https://pyatv.dev/documentation/#installing-pyatv

**Comment by autoneub** [comment]
It's in my "Home" app.
I don't have docker setup but I will try it in a virtual environment and get back to you with scan logs.
Thanks!

**Comment by postlund** [comment]
Great! I've changed my mind, `atvremote --debug scan` would give me more to work with.

**Comment by postlund** [comment]
Did you manage to get any debug logs?

**Comment by autoneub** [comment]
Shoot no. Sorry. My workload has picked up a bit so i haven’t had much time the last couple weeks. Hopefully next week I’ll have some downtime.

**Comment by autoneub** [comment]
Hey I've got the debug scan...
I'm not smart enough to know what all this means, so I can't discern any information that may need to be private.
Am I able to direct message this to you? or will it matter?

**Comment by autoneub** [comment]
Name: Shop Kitty
   Model/SW: AirPort Express (gen 2), AirPortOS 7.8.1
    Address: 192.168.1.133
        MAC: XX:XX:XX:XX:XX:XX
 Deep Sleep: False
Identifiers:
 - XX:XX:XX:XX:XX:XX
 - XXXXXXXXXXXX
Services:
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Disabled
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Disabled

**Comment by autoneub** [comment]
And this gobbldeygook too...

```

2022-02-02 16:09:08 DEBUG [pyatv.core.scan]: Auto-discovered Shop Kitty at 192.168.1.133:7000 via Protocol.AirPlay ({'acl': '1', 'deviceid': 'XX:XX:XX:XX:XX:XX', 'features': '0x445D0A00,0x1C340', 'rsf': '0x0', 'fv': 'p20.78100.3', 'flags': '0x4', 'model': 'AirPort10,115', 'manufacturer': 'Apple Inc.', 'serialnumber': 'C86LN76MDV2R', 'protovers': '1.1', 'srcvers': '366.0', 'pi': 'abdeddef-956c-4b43-b89b-b5c01dc8f2e4', 'gid': 'abdeddef-956c-4b43-b89b-b5c01dc8f2e4', 'gcgl': '0', 'pk': '4695e547ba89762918f7b30d37325e42cf5c4fe3bdf7c494db58f3e134ba13cf'})
2022-02-02 16:09:08 DEBUG [pyatv.core.scan]: Auto-discovered XXXXXXXXXXXX@Shop Kitty at 192.168.1.133:7000 via Protocol.RAOP ({'cn': '0,1', 'da': 'true', 'et': '0,4', 'ft': '0x445D0A00,0x1C340', 'fv': 'p20.78100.3', 'md': '2', 'am': 'AirPort10,115', 'sf': '0x4', 'tp': 'UDP', 'vn': '65537', 'vs': '366.0', 'pk': '4695e547ba89762918f7b30d37325e42cf5c4fe3bdf7c494db58f3e134ba13cf'})
```

**Comment by autoneub** [comment]
I tried to remove the device password in the airport utility, but it wouldn't let me update it without a password in the field.
There is no airplay password required. (this is the device password to change settings).

**Comment by postlund** [comment]
Yeah, I think this is a flag parsing error on my end. If you try for instance `atvremote -s 192.168.1.133 stream_file=https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_1MG.mp3`, does that work?

**Comment by autoneub** [comment]
so I apologize as I'm not super fluent in  command line or linux. 
I installed atvremote via the terminal in my mac mini - the scan sent back the info above.
So I just pasted your above command into the terminal and got this back...

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/support/http.py", line 388, in send_and_receive
    await asyncio.wait_for(event.wait(), timeout=4)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 719, in _run_application
    return await cli_handler(loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 513, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 614, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 662, in _handle_device_command
    return await _exec_command(atv.stream, cmd, True, *cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 685, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/core/facade.py", line 382, in stream_file
    await self.relay("stream_file")(file, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/protocols/raop/__init__.py", line 352, in stream_file
    await client.initialize(self.core.service.properties)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/protocols/raop/raop.py", line 457, in initialize
    await self._setup_session()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/protocols/raop/raop.py", line 486, in _setup_session
    resp = await self.rtsp.setup(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/support/rtsp.py", line 175, in setup
    return await self.exchange("SETUP", headers=headers, body=body)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/support/rtsp.py", line 258, in exchange
    resp = await self.connection.send_and_receive(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/support/http.py", line 391, in send_and_receive
    raise TimeoutError(f"no response to {method} {uri} ({protocol})") from ex
TimeoutError: no response to SETUP rtsp://192.168.1.3/1674132472 (RTSP/1.0)

```
If this was the incorrect thing to do, please let me know what I can do differently. I don't have docker running so I can't help in that way.
Also this isn't a huge deal and I may not be educated enough in this field to even help you. I appreciate your patience.
