### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by samsonrosen** [postlund/pyatv#1589]
### Describe the bug

I'm getting an error 'Illegal Instruction' when I'm running any atvremote commands. I have read the FAQ and performed the following steps but still getting the error.

`pi@homebridge:/var/lib/homebridge $ atvremote
Illegal instruction
pi@homebridge:/var/lib/homebridge $ python3 -c 'import miniaudio'

Illegal instruction
pi@homebridge:/var/lib/homebridge $ 
pi@homebridge:/var/lib/homebridge $ sudo pip3 uninstall miniaudio 
Skipping miniaudio as it is not installed.
pi@homebridge:/var/lib/homebridge $ sudo pip3 install --no-binary :all: miniaudio 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting miniaudio
  Using cached https://files.pythonhosted.org/packages/5b/a0/c1039d2c73988d3ab69766f3f8ef3c1f7cc15d8dc44287ccfa85b9f0390b/miniaudio-1.46.tar.gz
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.7/dist-packages (from miniaudio) (1.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12.0->miniaudio) (2.21)
Skipping bdist_wheel for miniaudio, due to binaries being disabled for it.
Installing collected packages: miniaudio
  Running setup.py install for miniaudio ... -
done
Successfully installed miniaudio-1.46
pi@homebridge:/var/lib/homebridge $ 
pi@homebridge:/var/lib/homebridge $ atvremote
Illegal instruction`

<img width="1321" alt="Screenshot 2022-01-07 at 17 20 25" src="https://user-images.githubusercontent.com/7211878/148582598-7ed7acdb-5b12-4e0a-80a1-ea81bd0ce098.png">

### Error log

```log
Illegal instruction
```

### How to reproduce the bug?

Run a command with atvremote.

### What is expected behavior?

Command to run.

### Operating System

Linux

### Python

3.7

### pyatv

Latest

### Device

Pi Zero W

### Additional context

Installing this for https://github.com/petro-kushchak/homebridge-homepod-radio

**Comment by postlund** [comment]
Can you try if this works:

**Comment by samsonrosen** [comment]
Still getting the same issue actually:

`pi@homebridge:/var/lib/homebridge $ python3 -m venv venv

pi@homebridge:/var/lib/homebridge $ 
pi@homebridge:/var/lib/homebridge $ source venv/bin/activate
(venv) pi@homebridge:/var/lib/homebridge $ pip install pyatv
^CTraceback (most recent call last):
  File "/var/lib/homebridge/venv/lib/python3.7/site-packages/pip/_vendor/__init__.py", line 33, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
ModuleNotFoundError: No module named 'pip._vendor.cachecontrol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/homebridge/venv/bin/pip", line 6, in <module>
    from pip._internal import main
  File "/var/lib/homebridge/venv/lib/python3.7/site-packages/pip/_internal/__init__.py", line 19, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
  File "/var/lib/homebridge/venv/lib/python3.7/site-packages/pip/_vendor/__init__.py", line 64, in <module>
    vendored("cachecontrol")
  File "/var/lib/homebridge/venv/lib/python3.7/site-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/var/lib/homebridge/venv/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/var/lib/homebridge/venv/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/var/lib/homebridge/venv/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/var/lib/homebridge/venv/share/python-wheels/requests-2.21.0-py2.py3-none-any.whl/requests/__init__.py", line 44, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/var/lib/homebridge/venv/share/python-wheels/chardet-3.0.4-py2.py3-none-any.whl/chardet/__init__.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/var/lib/homebridge/venv/share/python-wheels/chardet-3.0.4-py2.py3-none-any.whl/chardet/universaldetector.py", line 47, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/var/lib/homebridge/venv/share/python-wheels/chardet-3.0.4-py2.py3-none-any.whl/chardet/mbcsgroupprober.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
KeyboardInterrupt
(venv) pi@homebridge:/var/lib/homebridge $ sudo pip install pyatv
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyatv
  Downloading https://files.pythonhosted.org/packages/10/a8/25564cd6a99dab0b480ae0ab7edc914912702eb66f4a7bab8e9ae203bf9c/pyatv-0.8.1.tar.gz (1.5MB)
    100% |████████████████████████████████| 1.5MB 15kB/s 
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ymdpbl/pyatv/setup.py", line 4, in <module>
        from pathlib import Path
    ImportError: No module named pathlib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ymdpbl/pyatv/
(venv) pi@homebridge:/var/lib/homebridge $ pip install pyatv
The directory '/home/pi/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/pi/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pyatv in ./venv/lib/python3.7/site-packages (0.9.8)
Requirement already satisfied: ifaddr>=0.1.7 in ./venv/lib/python3.7/site-packages (from pyatv) (0.1.7)
Requirement already satisfied: protobuf<4,>=3.18.0 in ./venv/lib/python3.7/site-packages (from pyatv) (3.19.1)
Requirement already satisfied: zeroconf>=0.28.2 in ./venv/lib/python3.7/site-packages (from pyatv) (0.38.1)
Requirement already satisfied: mediafile>=0.8.1 in ./venv/lib/python3.7/site-packages (from pyatv) (0.9.0)
Requirement already satisfied: bitarray>=2.1.2 in ./venv/lib/python3.7/site-packages (from pyatv) (2.3.5)
Requirement already satisfied: miniaudio>=1.45 in ./venv/lib/python3.7/site-packages (from pyatv) (1.46)
Requirement already satisfied: srptools>=0.2.0 in ./venv/lib/python3.7/site-packages (from pyatv) (1.0.1)
Requirement already satisfied: cryptography>=2.6 in ./venv/lib/python3.7/site-packages (from pyatv) (36.0.1)
Requirement already satisfied: aiohttp<5,>=3.1.0 in ./venv/lib/python3.7/site-packages (from pyatv) (3.8.1)
Requirement already satisfied: six>=1.9 in ./venv/lib/python3.7/site-packages (from mediafile>=0.8.1->pyatv) (1.16.0)
Requirement already satisfied: mutagen>=1.45 in ./venv/lib/python3.7/site-packages (from mediafile>=0.8.1->pyatv) (1.45.1)
Requirement already satisfied: cffi>=1.12.0 in ./venv/lib/python3.7/site-packages (from miniaudio>=1.45->pyatv) (1.15.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./venv/lib/python3.7/site-packages (from aiohttp<5,>=3.1.0->pyatv) (5.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in ./venv/lib/python3.7/site-packages (from aiohttp<5,>=3.1.0->pyatv) (1.7.2)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in ./venv/lib/python3.7/site-packages (from aiohttp<5,>=3.1.0->pyatv) (2.0.10)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./venv/lib/python3.7/site-packages (from aiohttp<5,>=3.1.0->pyatv) (4.0.2)
Requirement already satisfied: typing-extensions>=3.7.4; python_version < "3.8" in ./venv/lib/python3.7/site-packages (from aiohttp<5,>=3.1.0->pyatv) (4.0.1)
Requirement already satisfied: frozenlist>=1.1.1 in ./venv/lib/python3.7/site-packages (from aiohttp<5,>=3.1.0->pyatv) (1.2.0)
Requirement already satisfied: asynctest==0.13.0; python_version < "3.8" in ./venv/lib/python3.7/site-packages (from aiohttp<5,>=3.1.0->pyatv) (0.13.0)
Requirement already satisfied: attrs>=17.3.0 in ./venv/lib/python3.7/site-packages (from aiohttp<5,>=3.1.0->pyatv) (21.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in ./venv/lib/python3.7/site-packages (from aiohttp<5,>=3.1.0->pyatv) (1.2.0)
Requirement already satisfied: pycparser in ./venv/lib/python3.7/site-packages (from cffi>=1.12.0->miniaudio>=1.45->pyatv) (2.21)
Requirement already satisfied: idna>=2.0 in ./venv/lib/python3.7/site-packages (from yarl<2.0,>=1.0->aiohttp<5,>=3.1.0->pyatv) (3.3)
(venv) pi@homebridge:/var/lib/homebridge $ atvremote
Illegal instruction
(venv) pi@homebridge:/var/lib/homebridge $ `

**Comment by samsonrosen** [comment]
Weird, I did some uninstalling and reinstalling and it only works now if I use Sudo? 

`sudo atvremote scan
Scan Results
========================================`

**Comment by postlund** [comment]
You should refrain from ever using sudo when installing python packages. Always use a venv (like I described above) and do not use sudo I this case either.
