### ISSUE TITLE
AppleTV suddenly stopped working the next day.. websocket api and 500 internal server errors... 

### ISSUE THREAD

**Issue by lancercncs1** [postlund/pyatv#1590]
### What do you need help with?

I am on (I believe) the latest version of Home Assistant (12.8), having installed AppleTV (ATV4k 2nd gen) last night. It had discovered my Apple TV, Home Pod, and mac devices. However, during integration, I note that RAOP (airplay) had not been paired correctly. Nevertheless, I got much of Apple TV working, with access to my music library, camera streaming and text to speech capabilities on the dashboard card.  
I turn off my Apple TV  for the evening only to wake up to find a greyed out dashboard card and lost access to my Apple TV media and TTS capabilities. The only thing I can do now is turn Apple TV off.

When I try to open the media and do TTS I get the following errors in my log:

**[281473426794720] RTSP/1.0 method SETUP failed with code 500: Internal Server Error
12:22:38 PM – (ERROR) Home Assistant WebSocket API (custom integration) - message first occurred at 12:13:58 PM and shows up 2 times
[281473426794720] no output device
12:22:33 PM – (ERROR) Home Assistant WebSocket API (custom integration)**

What could have caused these errors and how can I fix them? I also get weird messages that pairing has been disabled on my other discovered devices and they cannot be integrated... I am on the Tailscale VPN and can play my media files in my local directory online.
Platform: Runing HASS installed on Odroid N2+ from Linux Mint 20.1 and RPI 4 machines and iphone.

Here are the logs in more detail.. Thank you very much in advance!

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/apple_tv/media_player.py", line 450, in async_set_volume_level
    await self.atv.audio.set_volume(volume * 100.0)
  File "/usr/local/lib/python3.9/site-packages/pyatv/core/facade.py", line 433, in set_volume
    await self.relay("set_volume")(level)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 732, in set_volume
    raise exceptions.ProtocolError("no output device")
pyatv.exceptions.ProtocolError: no output device
2022-01-08 13:25:57 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281473392300336] no output device
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/apple_tv/media_player.py", line 450, in async_set_volume_level
    await self.atv.audio.set_volume(volume * 100.0)
  File "/usr/local/lib/python3.9/site-packages/pyatv/core/facade.py", line 433, in set_volume
    await self.relay("set_volume")(level)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 732, in set_volume
    raise exceptions.ProtocolError("no output device")
pyatv.exceptions.ProtocolError: no output device
2022-01-08 13:26:04 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281473392300336] RTSP/1.0 method SETUP failed with code 500: Internal Server Error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 200, in async_say_handle
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/apple_tv/media_player.py", line 286, in async_play_media
    await self.atv.stream.stream_file(media_id)
  File "/usr/local/lib/python3.9/site-packages/pyatv/core/facade.py", line 382, in stream_file
    await self.relay("stream_file")(file, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/__init__.py", line 331, in stream_file
    await client.initialize(self.service.properties)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/raop.py", line 454, in initialize
    await self._setup_session()
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/raop.py", line 483, in _setup_session
    resp = await self.rtsp.setup(
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/rtsp.py", line 175, in setup
    return await self.exchange("SETUP", headers=headers, body=body)
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/rtsp.py", line 258, in exchange
    resp = await self.connection.send_and_receive(
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/http.py", line 412, in send_and_receive
    raise exceptions.HttpError(
pyatv.exceptions.HttpError: RTSP/1.0 method SETUP failed with code 500: Internal Server Error`

**Comment by postlund** [comment]
All sorts of things can happen when the device is put to sleep as it will kill the connection to Home Assistant (and other potential clients). Normally Home Assistant will just re-connect and everything work again, but I think there's a bug that might prevent this from happening. Please look for other logs that might be useful. The error you posted likely has to do with RAOP not being set up properly. Does TTS actually work when you have proper control? Also, does reloading the integration restore functionality again?

**Comment by lancercncs1** [comment]
Hi again Pierre and Happy New Year,

Yeah, that's the weird thing. I only was able to get TTS working from the dashboard entity card (it doesn't work now). But even when things were somewhat working, I couldn't make any of my automations based on TTS work.
As for Airplay (RAOP), I don't know if its important, but I have no airplay password and I am allowing everyone on the network to access my Apple TV (same with the Home App).
I have tried uninstalling and re-installing the integration a few times and was never able to restore the previous functionality. Sometimes I install the integration and it struggles to discover the Apple TV. It has just stopped working ever since. :(

I've provided some more logs.. I hope they are somewhat helpful..

Exception in _async_disconnected when dispatching 'apple_tv_disconnected_F0:B3:EC:73:F9:0A': () Traceback (most recent call last): File "/config/custom_components/apple_tv/__init__.py", line 113, in _async_disconnected self.async_device_disconnected() File "/config/custom_components/apple_tv/media_player.py", line 165, in async_device_disconnected self.atv.push_updater.stop() File "/usr/local/lib/python3.9/site-packages/pyatv/support/shield.py", line 71, in _guard_method raise BlockedStateError(f"{func.__name__} is blocked") pyatv.exceptions.BlockedStateError: push_updater is blocked
4:32:09 PM–(ERROR)util/logging.py
Connection lost to Apple TV "Family room"
4:32:09 PM–(WARNING)Apple TV (custom integration)

There is this..

Logger:pyatv.support.http
Source:/usr/local/lib/python3.9/site-packages/pyatv/support/http.py:336
First occurred:4:32:05 PM(1occurrences)
Last logged:4:32:05 PM

Got response without having a request: HttpResponse(protocol='RTSP', version='1.0', code=200, message='OK', headers={'date': 'Sat, 08 Jan 2022 21:32:04 GMT', 'content-length': '55', 'content-type': 'application/x-apple-binary-plist', 'server': 'AirTunes/600.8.41', 'cseq': '4224'}, body=b'bplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14')

The following error ( [281472744140752]
4:12:01 PM–(ERROR)Home Assistant WebSocket API (custom integration)-message first occurred at 2:05:41 PM and shows up 9 times)
expands to...

Logger:homeassistant.components.websocket_api.http.connection
Source:custom_components/apple_tv/media_player.py:409
Integration:Home Assistant WebSocket API([documentation](https://www.home-assistant.io/integrations/websocket_api),[issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred:2:05:41 PM(9occurrences)
Last logged:4:12:01 PM

- [281472744140752]

- [281472751909664]

- [281472730827120]

- [281472723601632]

- [281472723312256]

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/apple_tv/media_player.py", line 409, in async_media_play
    await self.atv.remote_control.play()
  File "/usr/local/lib/python3.9/site-packages/pyatv/core/facade.py", line 76, in play
    return await self.relay("play")()
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 350, in play
    await self._send_command(CommandInfo_pb2.Play)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 319, in _send_command
    resp = await self.protocol.send_and_receive(messages.command(command, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 255, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 267, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

Ramses

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by lancercncs1** [comment]
Some more logs... This time it says certain features are "blocked"

[281472724042992] features is blocked
8:24:04 PM – (ERROR) Home Assistant WebSocket API (custom integration)

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/apple_tv/media_player.py:377
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:24:04 PM (1 occurrences)
Last logged: 8:24:04 PM
`

`[281472724042992] features is blocked
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 200, in async_say_handle
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/apple_tv/media_player.py", line 282, in async_play_media
    elif self._is_feature_available(FeatureName.StreamFile) and (
  File "/config/custom_components/apple_tv/media_player.py", line 377, in _is_feature_available
    return self.atv.features.in_state(FeatureState.Available, feature)
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/shield.py", line 71, in _guard_method
    raise BlockedStateError(f"{func.__name__} is blocked")
pyatv.exceptions.BlockedStateError: features is blocked`

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/apple_tv/media_player.py:450
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:23:58 PM (2 occurrences)
Last logged: 8:23:58 PM

[281472724042992] audio is blocked
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/apple_tv/media_player.py", line 450, in async_set_volume_level
    await self.atv.audio.set_volume(volume * 100.0)
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/shield.py", line 71, in _guard_method
    raise BlockedStateError(f"{func.__name__} is blocked")
pyatv.exceptions.BlockedStateError: audio is blocked`

**Comment by lancercncs1** [comment]
Today (the next day) I delete and reinstall the HASS ATV integration and somehow it recovered some functionality again. I did not get the pairing error this time. I am able to turn on/off Apple TV and go through my various media sources (e.g. hulu, music..etc...
However, I am still unable to do TTS (get "Failed to call google_translate_say.RTSP/1.0 METHOD setup failed with code 500: Internal Server Error") or camera streaming. I also got a disconnection error shortly after this.

Here are the logs:

Logger:homeassistant.components.websocket_api.http.connection

Source:custom_components/apple_tv/media_player.py:286

Integration:Home Assistant WebSocket API([documentation](https://www.home-assistant.io/integrations/websocket_api),[issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))

First occurred:3:39:15 AM(15occurrences)

Last logged:7:44:06 AM

- [281473584487488] RTSP/1.0 method SETUP failed with code 500: Internal Server Error

- [281473345109584] RTSP/1.0 method SETUP failed with code 500: Internal Server Error

- [281473347512064] RTSP/1.0 method SETUP failed with code 500: Internal Server Error

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 200, in async_say_handle
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/apple_tv/media_player.py", line 286, in async_play_media
    await self.atv.stream.stream_file(media_id)
  File "/usr/local/lib/python3.9/site-packages/pyatv/core/facade.py", line 382, in stream_file
    await self.relay("stream_file")(file, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/__init__.py", line 331, in stream_file
    await client.initialize(self.service.properties)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/raop.py", line 454, in initialize
    await self._setup_session()
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/raop.py", line 483, in _setup_session
    resp = await self.rtsp.setup(
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/rtsp.py", line 175, in setup
    return await self.exchange("SETUP", headers=headers, body=body)
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/rtsp.py", line 258, in exchange
    resp = await self.connection.send_and_receive(
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/http.py", line 412, in send_and_receive
    raise exceptions.HttpError(
pyatv.exceptions.HttpError: RTSP/1.0 method SETUP failed with code 500: Internal Server Error

Logger: homeassistant.helpers.service

Source: helpers/service.py:129

First occurred: 7:44:44 AM (2 occurrences)

Last logged: 7:45:02 AM

Unable to find referenced entities media_player.living_room

Logger: homeassistant.util.logging

Source: util/logging.py:105

First occurred: 3:40:04 AM (13 occurrences)

Last logged: 7:45:35 AM

This error originated from a custom integration.

Logger: custom_components.apple_tv

Source: custom_components/apple_tv/__init__.py:165

Integration: Apple TV

First occurred: 4:18:35 AM (11 occurrences)

Last logged: 7:45:35 AM

Connection lost to Apple TV "Family room"

Exception in _async_disconnected when dispatching 'apple_tv_disconnected_F0:B3:EC:73:F9:0A': () Traceback (most recent call last): File "/config/custom_components/apple_tv/__init__.py", line 113, in _async_disconnected self.async_device_disconnected() File "/config/custom_components/apple_tv/media_player.py", line 165, in async_device_disconnected self.atv.push_updater.stop() File "/usr/local/lib/python3.9/site-packages/pyatv/support/shield.py", line 71, in _guard_method raise BlockedStateError(f"{func.__name__} is blocked") pyatv.exceptions.BlockedStateError: push_updater is blocked

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by postlund** [comment]
The problem here is that if you try to play video via AirPlay, I.e. pass a URL to a video to `play_media`, that will break things inside the Apple TV for some reason. Metadata and airplay go bonkers. I claim this to be a bug in tvOS as it's insane that anything for the outside could cause this (they should have proper error handling to deal with this). Rebooting the device is the only work around for this and there's nothing I can about it I'm afraid.

The `BlockedStateError` exception is a known bug and will be fixed shortly.

**Comment by lancercncs1** [comment]
> 

That is weird regarding tvOS.. So the only work around to fixing my video streaming issues is to reboot my HASS server (which is an Odroid N2+)?

**Comment by postlund** [comment]
No, the Apple TV.

**Comment by lancercncs1** [comment]
> No, the Apple TV.

Ah, ok! Thanks! I will try that. Also, looking forward to the elimination of the `BlockedstateError`

**Comment by postlund** [comment]
Did a reboot work?

**Comment by lancercncs1** [comment]
Yeah, reboots helped get things working again.
