### ISSUE TITLE
hass-atv-beta 3.3.0 Airplay Connection Issues Issues

### ISSUE THREAD

**Issue by jcwearn** [postlund/pyatv#1638]
### Describe the bug

I have updated to use the latest version of the Home Assistant Apple TV integration (3.3.0) alongside the recent Home Assistant Core update (2022.2).  Since upgrading the integration is not working as expected.  The media_player entity never updates its state from paused and I get errors when trying to call various services on the Apple TV media player.

I have attached a few relevant error logs. 

UPDATE:  Restarting Home Assistant seems to resolve the issue, but I ideally don't want to have to restart HA each time this issue crops up.

UPDATE: For now I have resolved the issue by creating an automation that calls the `homeassistant.reload_config_entry` for the Apple TV media player once my LG TV's media_player state is set to "on".  Not a real fix, but seems to solve my issue for now.

### Error log

```log
Logger: homeassistant.components.apple_tv
Source: components/apple_tv/__init__.py:307
Integration: Apple TV (documentation, issues)
First occurred: 7:26:58 PM (2 occurrences)
Last logged: 7:27:24 PM

Failed to connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 225, in _connect_loop
    await self._connect(conf)
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 307, in _connect
    self.atv = await connect(conf, self.hass.loop, session=session)
  File "/usr/local/lib/python3.9/site-packages/pyatv/__init__.py", line 135, in connect
    await atv.connect()
  File "/usr/local/lib/python3.9/site-packages/pyatv/core/facade.py", line 565, in connect
    if await setup_data.connect():
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/__init__.py", line 401, in _connect
    await api.connect()
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/api.py", line 121, in connect
    await self._protocol.start()
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/protocol.py", line 101, in start
    await self.connection.connect()
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/connection.py", line 80, in connect
    await self.loop.create_connection(lambda: self, self.host, self.port)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.10.68', 49152)
```

```log
Logger: pyatv.protocols.airplay
Source: /usr/local/lib/python3.9/site-packages/pyatv/protocols/airplay/__init__.py:267
First occurred: 7:26:55 PM (2 occurrences)
Last logged: 7:27:21 PM

Failed to set up remote control channel
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/airplay/__init__.py", line 258, in _connect_rc
    await control.start(str(core.config.address), control_port, credentials)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/airplay/remote_control.py", line 55, in start
    self.connection = await http_connect(address, control_port)
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/http.py", line 556, in http_connect
    _, connection = await loop.create_connection(HttpConnection, address, port)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.10.68', 7000)
```

```log
Logger: homeassistant.components.websocket_api.http.connection
Source: components/apple_tv/media_player.py:415
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:36:43 PM (1 occurrences)
Last logged: 7:36:43 PM

[139814113283664]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 190, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 921, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/media_player.py", line 415, in async_media_play
    await self.atv.remote_control.play()
  File "/usr/local/lib/python3.9/site-packages/pyatv/core/facade.py", line 76, in play
    return await self.relay("play")()
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 354, in play
    await self._send_command(CommandInfo_pb2.Play)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 323, in _send_command
    resp = await self.protocol.send_and_receive(messages.command(command, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 259, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 271, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

### How to reproduce the bug?

Install latest version of Apple TV Home Assistant Integration.

### What is expected behavior?

The media_player exposed by the integration updates it's state when my Apple TV is played/paused/etc.

### Operating System

Home Assistant OS

### Python

3.9

### pyatv

0.9.7

### Device

Apple TV 4k (First Gen) 15.3

### Additional context

The last working version for my setup was the HACS 2.1.0.  Version 2.2.0 did not work for me either.  Though after upgrading Home Assistant Core even going back to HACS version 2.1.0 does not work.

The integration does seem to work intermittently after restarting Home Assistant and  rebooting my Apple TV, but it's definitely having some issues as noted in the above logs.

**Comment by cigas4** [comment]
Same here. Apple TV media player entity state never changes from Paused. Only Volume Up/Down and Power OFF buttons are working.
Although, Homepod works fine.

Apple TV 4K, v15.3
HA core-2022.3.8
Integration v3.0.1

**Comment by postlund** [comment]
Please remove the beta integration and re-test with the integration bundled with Home Assistant.

**Comment by gotschi** [comment]
Sorry I'm late but I believe it works fine in HA > 2022.7 now except for some random timeouts when I restart too fast / restart the device.

Thank you Pierre!

Cannot close but this issue is finished :)

**Comment by postlund** [comment]
Old issue, will close now (do not use beta version).

**Comment by loeffelpan** [comment]
This issue is persistent every time ATV is on standby. Worked around with reloading integration via service call when turning on my TV.

And i'm not using (custom) beta integration.
