### ISSUE TITLE
Is there a way to control volume?

### ISSUE THREAD

**Issue by linkx2252** [postlund/pyatv#1655]
### What do you need help with?

I’m hoping to send volume commands, which I eventually would use in cmdswitch2 -> Homebridge -> HomeKit. 

I don’t care if it’s volume up or down. The use case is just to press it once to turn my sound bar on. 

I currently have a working command for power (on and off). How do I tweak this for volume ? 

`atvremote -s 192.168.0.XXX --airplay-credentials XXXXX turn_off `

**Comment by postlund** [comment]
Yes, you can use either `volume_up`, `volume_down` or `set_volume=X` where X is a percentage to do that (instead of `turn_off`).

**Comment by linkx2252** [comment]
@postlund thanks for the fast response. Any ideas?

```
hoobs@hoobs:~ $ atvremote -s 192.168.0.XXX --airplay-credentials XXXX volume_up
Traceback (most recent call last):
  File "/home/hoobs/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 719, in _run_application
    return await cli_handler(loop)
  File "/home/hoobs/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 513, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/home/hoobs/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 614, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/home/hoobs/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 646, in _handle_device_command
    return await _exec_command(atv.audio, cmd, True, *cmd_args)
  File "/home/hoobs/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 685, in _exec_command
    value = await tmp(*args)
  File "/home/hoobs/.local/lib/python3.7/site-packages/pyatv/core/facade.py", line 413, in volume_up
    return await self.relay("volume_up")()
  File "/home/hoobs/.local/lib/python3.7/site-packages/pyatv/protocols/mrp/__init__.py", line 757, in volume_up
    await asyncio.wait_for(self._volume_event.wait(), timeout=5.0)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

>>> An error occurred, full stack trace above
```

**Comment by linkx2252** [comment]
> Yes, you can use either `volume_up`, `volume_down` or `set_volume=X` where X is a percentage to do that (instead of `turn_off`).

Sorry to bother, just wanted to see if you had any ideas.

**Comment by postlund** [comment]
Sorry about the late reply. Does volume controls work from iOS? If they don't, then pyatv won't work either.

**Comment by linkx2252** [comment]
No worries, thanks for the reply. I wasn't able to get it to work, but it doesn't work in iOS like you said so I think it is an iOS thing and not related to this project.

Either way, I swapped my command to use turn_on instead as I realized the apple tv (or maybe my TV itself) was also turning on the soundbar.
