### ISSUE TITLE
no service available for Protocol.MRP

### ISSUE THREAD

**Issue by Trrw** [postlund/pyatv#1688]
Hello I got this error when I would like to connect:

atvremote scan
```
Scan Results
========================================
       Name: Apple TV Wohnzimmer
   Model/SW: Apple TV 4K, tvOS 15.3
    Address: 192.168.178.XX
        MAC: 6C:4A:85:XX:XX:XX
 Deep Sleep: False
Identifiers:
 - 6C:4A:85:XX:XX:XX
 - 6C4A85XXXXXX
Services:
 - Protocol: Companion, Port: 49152, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: True, Password: None, Pairing: NotNeeded
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: True, Password: None, Pairing: NotNeeded

```

atvremote --id 6C:4A:85:XX:XX:XX --protocol mrp pair
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyatv/scripts/atvremote.py", line 719, in _run_application
    return await cli_handler(loop)
  File "/usr/local/lib/python3.9/dist-packages/pyatv/scripts/atvremote.py", line 507, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
  File "/usr/local/lib/python3.9/dist-packages/pyatv/scripts/atvremote.py", line 685, in _exec_command
    value = await tmp(*args)
  File "/usr/local/lib/python3.9/dist-packages/pyatv/scripts/atvremote.py", line 176, in pair
    pairing = await pair(conf, self.args.protocol, self.loop, **options)
  File "/usr/local/lib/python3.9/dist-packages/pyatv/__init__.py", line 153, in pair
    raise exceptions.NoServiceError(f"no service available for {protocol}")
pyatv.exceptions.NoServiceError: no service available for Protocol.MRP

>>> An error occurred, full stack trace above

```

atvremote --id 6C:4A:85:XX:XX:XX --protocol mrp pair --debug
```
2022-03-15 16:51:23 DEBUG [pyatv.scripts]: Running with pyatv 0.10.0
2022-03-15 16:51:23 DEBUG [pyatv.support.net]: Binding on *:5353
2022-03-15 16:51:23 DEBUG [pyatv.support.net]: Binding on 127.0.0.1:0
2022-03-15 16:51:23 DEBUG [pyatv.support.net]: Binding on 192.168.178.112:0
2022-03-15 16:51:23 DEBUG [pyatv.core.scan]: Auto-discovered Apple TV Wohnzimmer at 192.168.178.97:49152 via Protocol.Companion ({'rpmac': '1', 'rphn': '52a4ebd5782d', 'rpfl': '0xB67AA', 'rpha': 'd362dfbbc992', 'rpmd': 'AppleTV6,2', 'rpvr': '330.5', 'rpad': '519d523b3bfd', 'rphi': '754155d9bfd1', 'rpba': '7C:35:51:50:XX:XX', 'rpmrtid': 'DC2DD085-3A27-499F-981E-A4E493144D68'})
2022-03-15 16:51:23 DEBUG [pyatv.core.scan]: Auto-discovered Apple TV Wohnzimmer at 192.168.178.97:7000 via Protocol.AirPlay ({'acl': '0', 'btaddr': '6C:4A:85:3F:9F:XX', 'deviceid': '6C:4A:85:38:A7:XX', 'fex': '1d9/St5/FbwI', 'features': '0x4A7FDFD5,0xBC157FDE', 'flags': '0x4c4', 'gid': '9F2504F3-FB12-4B96-BDE0-36A68BAD6C41', 'igl': '1', 'gcgl': '1', 'model': 'AppleTV6,2', 'protovers': '1.1', 'pi': 'eb475d24-5c88-4b7a-917c-d88f5b64ec8e', 'psi': 'DC2DD085-3A27-499F-981E-A4E493144D68', 'pk': 'c289fd926dc3bff4f2594f6f1a3d022b87cd237b202407b423b306eb4782b6e4', 'srcvers': '605.1', 'osvers': '15.3', 'vv': '2'})
2022-03-15 16:51:23 DEBUG [pyatv.core.scan]: Auto-discovered 6C4A8538A78B@Apple TV Wohnzimmer at 192.168.178.97:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x4A7FDFD5,0xBC157FDE', 'sf': '0x4c4', 'md': '0,1,2', 'am': 'AppleTV6,2', 'pk': 'c289fd926dc3bff4f2594f6f1a3d022b87cd237b202407b423b306eb4782b6e4', 'tp': 'UDP', 'vn': '65537', 'vs': '605.1', 'ov': '15.3', 'vv': '2'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyatv/scripts/atvremote.py", line 719, in _run_application
    return await cli_handler(loop)
  File "/usr/local/lib/python3.9/dist-packages/pyatv/scripts/atvremote.py", line 507, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
  File "/usr/local/lib/python3.9/dist-packages/pyatv/scripts/atvremote.py", line 685, in _exec_command
    value = await tmp(*args)
  File "/usr/local/lib/python3.9/dist-packages/pyatv/scripts/atvremote.py", line 176, in pair
    pairing = await pair(conf, self.args.protocol, self.loop, **options)
  File "/usr/local/lib/python3.9/dist-packages/pyatv/__init__.py", line 153, in pair
    raise exceptions.NoServiceError(f"no service available for {protocol}")
pyatv.exceptions.NoServiceError: no service available for Protocol.MRP
```

What can I do? Thank you :)

**Comment by postlund** [comment]
As you can see in the scan list, your device does not list MRP as a supported protocol so you shouldn't try to pair (or use) it. Simple as that.

**Comment by postlund** [comment]
You should pair the other supported protocols (airplay, companion and raop) instead and provide the credentials you get.

**Comment by Trrw** [comment]
atvremote --id 6C:4A:85:XX:XX:XX --protocol raop pair works :) thank you
