### ISSUE TITLE
Artist ascii codec error \xeb

### ISSUE THREAD

**Issue by m4rkv5** [postlund/pyatv#1709]
### Describe the bug

Pyatv is working fine except when some songs are playing. Then the script crashes.

### Error log

```log
Traceback (most recent call last):
  File "/homebridge/python/pyatv/scripts/atvremote.py", line 719, in _run_application
    return await cli_handler(loop)
  File "/homebridge/python/pyatv/scripts/atvremote.py", line 513, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/homebridge/python/pyatv/scripts/atvremote.py", line 614, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/homebridge/python/pyatv/scripts/atvremote.py", line 652, in _handle_device_command
    return await _exec_command(atv.metadata, cmd, True, *cmd_args)
  File "/homebridge/python/pyatv/scripts/atvremote.py", line 692, in _exec_command
    _pretty_print(value)
  File "/homebridge/python/pyatv/scripts/atvremote.py", line 710, in _pretty_print
    print(data)
UnicodeEncodeError: 'ascii' codec can't encode character '\xeb' in position 84: ordinal not in range(128)
```

### How to reproduce the bug?

Play Tiësto The Business

### What is expected behavior?

Media type: Music
Device state: Paused
       Title: The Business
      Artist: Tiësto
       Album: ...
       Genre: Dance
    Position: 0/166s (0.0%)
      Repeat: Off
     Shuffle: Off

### Operating System

oznu/docker-homebridge

### Python

3.6

### pyatv

0.9.8

### Device

Apple TV 4k 15.4.1

### Additional context

.

**Comment by postlund** [comment]
I will look into this, thanks for reporting!

**Comment by postlund** [comment]
I'm trying to reproduce this myself and neither Apple Music nor Spotify seems to trigger it. How are you playing the track? I suspect it has to do with your locale being incorrectly set to something non-Unicode compliant. Can you give me some additional details regarding how I would reproduce this using the docker image you mention?

**Comment by m4rkv5** [comment]
I don't use it any longer.  Sequential reading of my Apple TV status result in too high CPU load on my system. If the ascii issue has something to do with my docker image it can be closed.

**Comment by m4rkv5** [comment]
@postlund With push updates it now responds immediately. Thanks for the hint. I am using push updates via atvscript and [node-red-node-daemon](https://flows.nodered.org/node/node-red-node-daemon)

**Comment by postlund** [comment]
That's great to hear! 👍
