### ISSUE TITLE
Google TTS no longer works on Homepod Minis after updating to May Home Assistant

### ISSUE THREAD

**Issue by lancercncs1** [postlund/pyatv#1732]
### Describe the bug

Up until I had updated to the latest version of HA, TTS had been working just fine. 
Now after the latest update, it stopped working on all of my HomePod Minis (all other functionality, including music, is retained).

What may be the issue and how can I resolve it? Thanks! 

### Error log

```log
CLOCK IN OR OUT: Error executing script. Unexpected error for call_service at pos 1: media-source://tts/google_translate?message=Mary, do+not+forget+to+clock+in+or+out
While executing automation automation.clock_out
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 217, in async_say_handle
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/config/custom_components/apple_tv/media_player.py", line 292, in async_play_media
    await self.atv.stream.stream_file(media_id)
  File "/usr/local/lib/python3.9/site-packages/pyatv/core/facade.py", line 382, in stream_file
    await self.relay("stream_file")(file, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/__init__.py", line 371, in stream_file
    audio_file = await open_source(
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/audio_source.py", line 484, in open_source
    return await FileSource.open(source, sample_rate, channels, sample_size)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/audio_source.py", line 428, in open
    src = await loop.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/miniaudio.py", line 929, in decode_file
    filenamebytes = _get_filename_bytes(filename)
  File "/usr/local/lib/python3.9/site-packages/miniaudio.py", line 807, in _get_filename_bytes
    raise FileNotFoundError(filename)
FileNotFoundError: media-source://tts/google_translate?message=Mary,+do+not+forget+to+clock+in+or+out

```

### How to reproduce the bug?

update to latest Home Assistant (5.3 core, Supervisor 05.1)

### What is expected behavior?

my TTS automations should work.

### Operating System

HASS OS

### Python

3.9

### pyatv

the pyatv version that comes with atv-beta 3.0.1

### Device

Apple TV 4K OS 15.4

### Additional context

I had checked that my network settings on HomeKit are correct, "Anyone on the Same Network" ... "Everyone" also works.
I had restarted my Apple TV and Home Assistant and neither of these attempts solved the issue.

**Comment by BRutgers** [comment]
I have the same problem with the homepod mini's in my setup.

**Comment by lancercncs1** [comment]
This problem remains for me even after I followed the advice of the release notes to comment out "base_url" in the google translate yaml block and ensuring that the external URL is my duckdns URL in the Network settings.

**Comment by Gloomyeye** [comment]
Hi,
maybe try the Apple TV integration version of the current Home Assistant version and do not use the custom component beta version. I removed the custom component completely, restarted HA, readded my HomePods and do not have this issue.

**Comment by BRutgers** [comment]
> Hi, maybe try the Apple TV integration version of the current Home Assistant version and do not use the custom component beta version. I removed the custom component completely, restarted HA, readded my HomePods and do not have this issue.

This did the trick, thank you!

**Comment by lancercncs1** [comment]
Interesting! So, did  they fix the official Apple TV integration to work with Apple tv OS 15.X?

**Comment by postlund** [comment]
I will close this now as it was just because of the beta component.
