### ISSUE TITLE
Unstable Behavior when using autodiscover

### ISSUE THREAD

**Issue by martygriffin** [postlund/pyatv#175]
I am using the latest version of pyatvremote with my Appled TV 4k running tvOS 12.1.2.

Commands using the remote cli  work seem to work randomly. I.e somethings 3 in a row work but then 1  succeeds or 1 success and then 3 fail. when it failed I get the following:

`atvremote --debug -a menu`
```
DEBUG: Discovering devices for 3 seconds
DEBUG: Auto-discovered Home Theater at 192.168.1.28:3689 (protocol: 1)
ERROR: Could not find any Apple TV on current network
```
I also tried to connect manually using:

`atvremote --address 192.168.1.28 --device_credentials 00000000-0c30-ce04-d055-b89a323c4b0c --debug -a menu`

but get the following:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyatv-0.4.0.dev0-py3.7.egg/pyatv/__main__.py", line 490, in _run_application
    return await cli_handler(loop)
  File "/usr/local/lib/python3.7/site-packages/pyatv-0.4.0.dev0-py3.7.egg/pyatv/__main__.py", line 315, in cli_handler
    return await _handle_commands(args, loop)
  File "/usr/local/lib/python3.7/site-packages/pyatv-0.4.0.dev0-py3.7.egg/pyatv/__main__.py", line 397, in _handle_commands
    atv = pyatv.connect_to_apple_tv(details, loop, protocol=args.protocol)
  File "/usr/local/lib/python3.7/site-packages/pyatv-0.4.0.dev0-py3.7.egg/pyatv/__init__.py", line 167, in connect_to_apple_tv
    service = _get_service_used_to_connect(details, protocol)
  File "/usr/local/lib/python3.7/site-packages/pyatv-0.4.0.dev0-py3.7.egg/pyatv/__init__.py", line 191, in _get_service_used_to_connect
    'no usable service to connect to')
pyatv.exceptions.NoUsableServiceError: no usable service to connect to

>>> An error occurred, full stack trace above

```

**Comment by kilian579** [comment]
I'm also having troubles with the autodiscover method.
I've never really figured out how the manual connect works.

**Comment by kilian579** [comment]
If i enter `atvremote scan` in the console, my Apple TV is discovered.
However `pyatv.scan_for_apple_tvs` doesn't find anything.

**Comment by postlund** [comment]
These were some usability issues and I have fixed them on master now!
