### ISSUE TITLE
MRP/Airplay pair issue

### ISSUE THREAD

**Issue by AVITPL** [postlund/pyatv#1802]
### What do you need help with?

Hello,

First I would like to thank everyone who has put their time and effort into this project, it is very impressive to see all the code and documentation! 

We have been trying the different protocols to control the AppleTV's, but are running into some issues, mostly on MRP and Airplay. Companion seems to be working fine, but there are some lacking features there, hence we are looking into MRP and Airplay.

We have installed atvremote v0.10.2, and our AppleTV's run tvOS 15.5.1

We tried to pair with the MRP protocol, but this does not work anymore because we run tvOS 15. So then we tried to pair with Airplay, and that gave us an authentication key, as expected. We tried to look through the documentation about using MRP over an Airplay tunnel, but we are not completely sure if we are doing that correctly.

So far we seem to think that the only supported command for Airplay is "Playing", but when we try this, we get the following: Media type : Unknown
Device state: Idle.
We use the following command: atvremote --id 90DD5DA0F8CA --airplay-credentials aefa67d59c426f4ce130c1294206db091d5c6d74ea0dba31f03e00233f132ac7:a8dcb6a11f86ad4621231b022e25811a65a0929e233460fa6e4caeb8dacf5aea:34353241463731352d393437392d343435372d423939342d333538343446374336333632:38616339336232352d633132662d343037332d623138372d643439313930653633326263 playing

if we run the same command with "--debug", we seem to get an HTTP Error. This is the full output:  

atvremote --id 90DD5DA0F8CA --airplay-credentials aefa67d59c426f4ce130c1294206db091d5c6d74ea0dba31f03e00233f132ac7:a8dcb6a11f86ad4621231b022e25811a65a0929e233460fa6e4caeb8dacf5aea:34353241463731352d393437392d343435372d423939342d333538343446374336333632:38616339336232352d633132662d343037332d623138372d643439313930653633326263 playing --debug
2022-07-19 18:03:42 DEBUG [pyatv.scripts]: Running with pyatv 0.10.2
2022-07-19 18:03:42 DEBUG [pyatv.support.net]: Binding on *:5353
2022-07-19 18:03:42 DEBUG [pyatv.support.net]: Binding on 169.254.52.236:0
2022-07-19 18:03:42 DEBUG [pyatv.core.mdns]: Failed to add listener for 169.254.52.236 (ignoring)
2022-07-19 18:03:42 DEBUG [pyatv.support.net]: Binding on 10.10.230.53:0
2022-07-19 18:03:42 DEBUG [pyatv.support.net]: Binding on 169.254.35.95:0
2022-07-19 18:03:42 DEBUG [pyatv.core.mdns]: Failed to add listener for 169.254.35.95 (ignoring)
2022-07-19 18:03:42 DEBUG [pyatv.support.net]: Binding on 169.254.100.113:0
2022-07-19 18:03:42 DEBUG [pyatv.core.mdns]: Failed to add listener for 169.254.100.113 (ignoring)
2022-07-19 18:03:42 DEBUG [pyatv.support.net]: Binding on 192.168.68.1:0
2022-07-19 18:03:42 DEBUG [pyatv.support.net]: Binding on 192.168.171.1:0
2022-07-19 18:03:42 DEBUG [pyatv.support.net]: Binding on 10.10.28.76:0
2022-07-19 18:03:42 DEBUG [pyatv.support.net]: Binding on 169.254.15.10:0
2022-07-19 18:03:42 DEBUG [pyatv.core.mdns]: Failed to add listener for 169.254.15.10 (ignoring)
2022-07-19 18:03:42 DEBUG [pyatv.support.net]: Binding on 127.0.0.1:0
2022-07-19 18:03:42 DEBUG [pyatv.core.scan]: Auto-discovered Music Apple TV at 10.10.230.42:49152 via Protocol.Companion ({'rpmac': '1', 'rphn': '126e05e61b70', 'rpfl': '0xB6782', 'rpmd': 'AppleTV6,2', 'rpvr': '350.2', 'rpmrtid': '452AF715-9479-4457-B994-35844F7C6362', 'rpad': '0b9971c0c71d', 'rpba': 'DA:A6:35:E7:56:B6'})
2022-07-19 18:03:42 DEBUG [pyatv.core.scan]: Auto-discovered Music Apple TV at 10.10.230.42:7000 via Protocol.AirPlay ({'acl': '0', 'btaddr': '90:DD:5D:A1:36:28', 'deviceid': '90:DD:5D:A0:F8:CA', 'fex': '1d9/St5fFbwI', 'features': '0x4A7FDFD5,0xBC155FDE', 'flags': '0xc4', 'gid': '11D030AC-1463-4074-A1F2-DEE24410C4F4', 'igl': '1', 'gcgl': '1', 'model': 'AppleTV6,2', 'protovers': '1.1', 'pi': 'a349b182-5897-4798-98fa-d7fbb3b6ed43', 'psi': '452AF715-9479-4457-B994-35844F7C6362', 'pk': 'd525dbc413a370a6783b4de2170188ae1cc031a5254208eca2bfb70f9995f93f', 'srcvers': '615.12.1', 'osvers': '15.5.1', 'vv': '2'})
2022-07-19 18:03:42 DEBUG [pyatv.protocols.mrp]: Disabling MRP service since tvOS >= 15
2022-07-19 18:03:42 DEBUG [pyatv.core.scan]: Auto-discovered Music Apple TV at 10.10.230.42:49153 via Protocol.MRP ({'modelname': 'Apple TV', 'allowpairing': 'YES', 'bluetoothaddress': "b'\\x90\\xdd]\\xa16('", 'macaddress': '90:dd:5d:a0:f8:ca', 'name': 'Music Apple TV', 'uniqueidentifier': '78AB5E47-15F0-463C-8C91-F67FA39BE8E7', 'systembuildversion': '19L580', 'localairplayreceiverpairingidentity': '452AF715-9479-4457-B994-35844F7C6362'})
2022-07-19 18:03:42 DEBUG [pyatv.core.scan]: Auto-discovered 90DD5DA0F8CA@Music Apple TV at 10.10.230.42:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x4A7FDFD5,0xBC155FDE', 'sf': '0xc4', 'md': '0,1,2', 'am': 'AppleTV6,2', 'pk': 'd525dbc413a370a6783b4de2170188ae1cc031a5254208eca2bfb70f9995f93f', 'tp': 'UDP', 'vn': '65537', 'vs': '615.12.1', 'ov': '15.5.1', 'vv': '2'})
2022-07-19 18:03:42 INFO [pyatv.scripts.atvremote]: Auto-discovered Music Apple TV at 10.10.230.42
2022-07-19 18:03:42 DEBUG [pyatv.core.facade]: Adding handler for protocol Protocol.AirPlay
2022-07-19 18:03:42 DEBUG [pyatv.protocols.airplay]: Remote control channel is supported
2022-07-19 18:03:42 DEBUG [pyatv.core.facade]: Adding handler for protocol Protocol.MRP
2022-07-19 18:03:42 DEBUG [pyatv.protocols.companion]: Not adding Companion as credentials are missing
2022-07-19 18:03:42 DEBUG [pyatv.core.facade]: Adding handler for protocol Protocol.RAOP
2022-07-19 18:03:42 DEBUG [pyatv.core.facade]: Connecting to protocol: Protocol.AirPlay
2022-07-19 18:03:42 DEBUG [pyatv.core.facade]: Connected to protocol: Protocol.AirPlay
2022-07-19 18:03:42 DEBUG [pyatv.core.facade]: Connecting to protocol: Protocol.MRP
2022-07-19 18:03:42 DEBUG [pyatv.protocols.airplay.remote_control]: Setting up remote control connection to 10.10.230.42:7000
2022-07-19 18:03:42 DEBUG [pyatv.support.http]: Connected to 10.10.230.42
2022-07-19 18:03:42 DEBUG [pyatv.support.http]: Sending HTTP/1.1 message: b'POST /pair-verify HTTP/1.1\r\nContent-Length: 37\r\nUser-Agent: AirPlay/320.20\r\nConnection: keep-alive\r\nX-Apple-HKP: 3\r\nContent-Type: application/octet-stream\r\n\r\n\x06\x01\x01\x03 +Y\xa0\xd0D\xb8\x14\xc7"\'uu\xedIf\x9cM\2022-07-19 18:03:42 DEBUG [pyatv.support.http]: Received: b'HTTP/1.1 200 OK\r\nDate: Tue, 19 Jul 2022 15:03:42 GMT\r\nContent-Length: 159\r\nContent-Type: application/octet-stream\r\nServer: AirTunes/615.12.1\r\n\r\n\x05x\x9b\xa64?\x8a\x9e\x8f\x91\x0f\x90\xe6\x85\x8a\xaa\x96"\xef\xe0\xc7,\xde^\x11gm\xa3\\\xfcL?\xa1\x85\xc3\x12*GR\xf1\x1c"PO\x02\x94\x0e\xc4\xeeF}\\\xfbw\xdb{\xd3\xac\xa1\xe4\xe9\x17\x07\xcbt\xdf\xed\xcc\xbe\x9e\xe1\xdef\xaa\x1e!8\xb5^\x95\x1b\x16f\xcb\xb1\xa4\xa9\xcfo\x8c\xac\x1e\x8f\n \xd9!\xe3\xfc\xfd\xba\x0e /\xd3\x06W\xaa6\x85\x02\xd4V\x13sH\xd1\xe1 <\xae\x06\x06\x01\x02\x03 \xb6\xdb\x86H\x88v%\xc1\x8b\xe1\x81\xe7\x0b\x17\xacz\xd7=\x99\x9dP\x15\xaf\xcfh\xa9\xb1p\xaa]\xd9v'
2022-07-19 18:03:42 DEBUG [pyatv.support.http]: Got HTTP response: HttpResponse(protocol='HTTP', version='1.1', code=200, message='OK', headers={'date': 'Tue, 19 Jul 2022 15:03:42 GMT', 'content-length': '159', 'content-type': 'application/octet-stream', 'server': 'AirTunes/615.12.1'}, body=b'\x05x\x9b\xa64?\x8a\x9e\x8f\x91\x0f\x90\xe6\x85\x8a\xaa\x96"\xef\xe0\xc7,\xde^\x11gm\xa3\\\xfcL?\xa1\x85\xc3\x12*GR\xf1\x1c"PO\x02\x94\x0e\xc4\xeeF}\\\xfbw\xdb{\xd3\xac\xa1\xe4\xe9\x17\x07\xcbt\xdf\xed\xcc\xbe\x9e\xe1\xdef\xaa\x1e!8\xb5^\x95\x1b\x16f\xcb\xb1\xa4\xa9\xcfo\x8c\xac\x1e\x8f\n \xd9!\xe3\xfc\xfd\xba\x0e 
/\xd3\x06W\xaa6\x85\x02\xd4V\x13sH\xd1\xe1 <\xae\x06\x06\x01\x02\x03 \xb6\xdb\x86H\x88v%\xc1\x8b\xe1\x81\xe7\x0b\x17\xacz\xd7=\x99\x9dP\x15\xaf\xcfh\xa9\xb1p\xaa]\xd9v'):
2022-07-19 18:03:42 DEBUG [pyatv.protocols.airplay.auth.hap]: Device (Encrypted=9ba6343f8a9e8f910f90e6858aaa9622efe0c72cde5e11676da35cfc4c3fa185c3122a4752f11c22504f02940ec4ee467d5cfb77db7bd3aca1e4e91707cb74dfedccbe9ee1de66aa1e2138b55e951b1666cbb1a4a9cf6f8cac1e8f0a20d921e3fcfdba0e202fd30657aa368502d456137348d1e1203cae06, Public=aefa67d59c426f4ce130c1294206db091d5c6d74ea0dba31f03e00233f132ac7)
2022-07-19 18:03:42 DEBUG [pyatv.support.http]: Sending HTTP/1.1 message: b"POST /pair-verify HTTP/1.1\r\nContent-Length: 125\r\nUser-Agent: AirPlay/320.20\r\nConnection: keep-alive\r\nX-Apple-HKP: 3\r\nContent-Type: application/octet-stream\r\n\r\n\x06\x01\x03\x05x\xcf\xe1b\x7f\xae\x9d\x17\xe7\x05\x7f\x85\x9e.\x8ap\xbb\xbf\x0f\x15Z\x1a\x1f\x88\xd5\x93\xf7\x8d\x90\x86c\xa7\xe7N\xa7\x07\xb7\x0b\x15Q2\xdc\x10\xaf\x04|%\xd6\x9c\xaa>\xd2t\xe1\xbd\x0cH\xc7+\x91'\xe8\xfb\xb5\xc6\x0e\xa95`\x7fp\xd9\xa8\x877L\xa9\xae:\xaf\x91;\x827\xfbVs\xe1\x7f3\xe3\x0c\xf5}\xcci\xc8h\x07\xb5\xa7\x07\x1c\xe4\xa6\x84L-\xc9zD\x18\xdf\xbdO\xd3\x05\xe06\xbd "
2022-07-19 18:03:42 DEBUG [pyatv.support.http]: Received: b'HTTP/1.1 200 OK\r\nDate: Tue, 19 Jul 2022 15:03:42 GMT\r\nContent-Length: 3\r\nContent-Type: application/octet-stream\r\nServer: AirTunes/615.12.1\r\n\r\n\x06\x01\x04'
2022-07-19 18:03:42 DEBUG [pyatv.support.http]: Got HTTP response: HttpResponse(protocol='HTTP', version='1.1', code=200, message='OK', headers={'date': 'Tue, 19 Jul 2022 15:03:42 GMT', 'content-length': '3', 'content-type': 'application/octet-stream', 'server': 'AirTunes/615.12.1'}, body=b'\x06\x01\x04'):
2022-07-19 18:03:42 DEBUG [pyatv.auth.hap_srp]: Keys (Input=2291cebc655880a52e2ea70a0eed83ac887162036254178f885765084ab4a049, Output=9c40dbe4d065681d5d9beff93fcf6e0087bd2a563aad2258681bf50e72d5d63c)
2022-07-19 18:03:42 DEBUG [pyatv.support.http]: Sending RTSP/1.0 message: b'SETUP rtsp://10.10.230.53/1665559978 RTSP/1.0\r\nUser-Agent: AirPlay/540.31\r\nContent-Length: 367\r\nCSeq: 0\r\nDACP-ID: FED568DB068304AC\r\nActive-Remote: 1834153658\r\nClient-Instance: FED568DB068304AC\r\nContent-Type: application/x-apple-binary-plist\r\n\r\nbplist00\xdb\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16XdeviceID_\x10\x13isRemoteControlOnlyZmacAddressUmodelTname^osBuildVersionVosNameYosVersion[sessionUUID]sourceVersion^timingProtocol_\x10\x11FF:EE:DD:CC:BB:AA\t_\x10\x11AA:BB:CC:DD:EE:FFZiPhone10,6UpyatvU18G82YiPhone OSV14.7.1_\x10$1E76B2B4-F2A5-4095-B10B-F20FE9D1215DV550.10TNone\x00\x08\x00\x1f\x00(\x00>\x00I\x00O\x00T\x00c\x00j\x00t\x00\x80\x00\x8e\x00\x9d\x00\xb1\x00\xb2\x00\xc6\x00\xd1\x00\xd7\x00\xdd\x00\xe7\x00\xee\x01\x15\x01\x1c\x00\x00\x00\x00\x00\x00\x02\x01\x00\x00\x00\x00\x00\x00\x00\x17\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01!'
2022-07-19 18:03:42 DEBUG [pyatv.support.http]: Received: b'RTSP/1.0 401 Unauthorized\r\nContent-Length: 0\r\nServer: AirTunes/615.12.1\r\nWWW-Authenticate: Digest realm="airplay", nonce="MTY1ODI0MzAyMiCSIroJoq8wAFnzG1WlqAGW"\r\nCSeq: 0\r\n\r\n'
2022-07-19 18:03:42 DEBU ort.http]: Got RTSP response: HttpResponse(protocol='RTSP', version='1.0', code=401, message='Unauthorized', headers={'content-length': '0', 'server': 'AirTunes/615.12.1', 'www-authenticate': 'Digest realm="airplay", nonce="MTY1ODI0MzAyMiCSIroJoq8wAFnzG1WlqAGW"', 'cseq': '0'}, body=''):
2022-07-19 18:03:42 ERROR [pyatv.protocols.airplay]: Failed to set up remote control channel2
Traceback (most recent call last):
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\protocols\airplay\__init__.py", line 258, in _connect_rc
    await control.start(str(core.config.address), control_port, credentials)
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\protocols\airplay\remote_control.py", line 60, in start
    await self._setup_event_channel(self.connection.remote_ip)
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\protocols\airplay\remote_control.py", line 102, in _setup_event_channel
    resp = await self._setup(
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\support\rtsp.py", line 179, in setup
    return await self.exchange("SETUP", headers=headers, body=body)
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\support\rtsp.py", line 263, in exchange
    resp = await self.connection.send_and_receive(
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\support\http.py", line 406, in send_and_receive
    raise exceptions.AuthenticationError("not authenticated")
pyatv.exceptions.AuthenticationError: not authenticated
2022-07-19 18:03:42 DEBUG [pyatv.core.facade]: Connecting to protocol: Protocol.RAOP
2022-07-19 18:03:42 DEBUG [pyatv.core.facade]: Connected to protocol: Protocol.RAOP
2022-07-19 18:03:42 DEBUG [pyatv.core.facade]: Power management not supported by any protocols
2022-07-19 18:03:42 ERROR [pyatv.scripts.atvremote]: Command 'left' is not supported by device
Traceback (most recent call last):
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\scripts\atvremote.py", line 683, in _exec_command
    value = await tmp(*args)
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\core\facade.py", line 66, in left
    return await self.relay("left")(action=action)
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\core\relayer.py", line 90, in relay
    instance = self._find_instance(
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\core\relayer.py", line 114, in _find_instance
    raise exceptions.NotSupportedError(f"{target} is not supported")
pyatv.exceptions.NotSupportedError: left is not supported
2022-07-19 18:03:42 DEBUG [pyatv.scripts.atvremote]: Waiting for 0 remaining tasks

From the debug output, there seems to be a RTSP stream which gets denied by being "Unauthorized", and at this point the application seems to stop.

As far as we understand it, this is all just using the Airplay protocol to communicate back and forward, but we are not seeing the expected result. 

Then in order to use MRP, we have to somehow create an Airplay tunnel to send MRP command through. According to the news letter, we should just be able to follow the steps in the tutorial, but that does not seem to work for us either.

When we try to pair with the "--protocol mrp pair" command, it just times out and comes back with failed to pair. If we scan the devices, the following line is showed in regards of the services:
Services:
 - Protocol: Companion, Port: 49152, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: True, Password: None, Pairing: NotNeeded
 - Protocol: MRP, Port: 49153, Credentials: None, Requires Password: False, Password: None, Pairing: Optional (Disabled)
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: True, Password: None, Pairing: NotNeeded

Then in attempt to send MRP over Airplay, we have tried to incorporate the authentication key we get when we pair with Airplay. We tried to send them over as "--airplay-credentials" or as "--mrp-credentials" when trying to send commands, but this did not do anything.

For example, if we ran this command:
atvremote --id 90DD5DA0F8CA --airplay-credentials aefa67d59c426f4ce130c1294206db091d5c6d74ea0dba31f03e00233f132ac7:9615d7723723596149a564c0f3036368e2619b16f1230f53f21a71698fc16181:34353241463731352d393437392d343435372d423939342d333538343446374336333632:64623266383532622d376333652d343137362d393536662d626466333831656437653535 left

We would get this output:
2022-07-19 19:47:39 ERROR [pyatv.protocols.airplay]: Failed to set up remote control channel2
Traceback (most recent call last):
  File "c:\users\secondavit\appdata\local\programs\python\python39\lib\asyncio\locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\secondavit\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\support\http.py", line 388, in send_and_receive
    await asyncio.wait_for(event.wait(), timeout=4)
  File "c:\users\secondavit\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\protocols\airplay\__init__.py", line 258, in _connect_rc
    await control.start(str(core.config.address), control_port, credentials)
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\protocols\airplay\remote_control.py", line 60, in start
    await self._setup_event_channel(self.connection.remote_ip)
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\protocols\airplay\remote_control.py", line 102, in _setup_event_channel
    resp = await self._setup(
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\protocols\airplay\remote_control.py", line 90, in _setup
    resp = await self.rtsp.setup(
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\support\rtsp.py", line 179, in setup
    return await self.exchange("SETUP", headers=headers, body=body)
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\support\rtsp.py", line 263, in exchange
    resp = await self.connection.send_and_receive(
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\support\http.py", line 391, in send_and_receive
    raise TimeoutError(f"no response to {method} {uri} ({protocol})") from ex
TimeoutError: no response to SETUP rtsp://10.10.230.53/1450508311 (RTSP/1.0)
2022-07-19 19:47:39 ERROR [pyatv.scripts.atvremote]: Command 'left' is not supported by device
Traceback (most recent call last):
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\scripts\atvremote.py", line 683, in _exec_command
    value = await tmp(*args)
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\core\facade.py", line 66, in left
    return await self.relay("left")(action=action)
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\core\relayer.py", line 90, in relay
    instance = self._find_instance(
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\core\relayer.py", line 114, in _find_instance
    raise exceptions.NotSupportedError(f"{target} is not supported")
pyatv.exceptions.NotSupportedError: left is not supported

Then if we send the same command, but with "--mrp-credentials"  instead of airplay, this would be the output:
2022-07-19 19:49:06 ERROR [pyatv.scripts.atvremote]: Command 'left' is not supported by device
Traceback (most recent call last):
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\scripts\atvremote.py", line 683, in _exec_command
    value = await tmp(*args)
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\core\facade.py", line 66, in left
    return await self.relay("left")(action=action)
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\core\relayer.py", line 90, in relay
    instance = self._find_instance(
  File "C:\Users\SecondAVIT\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyatv\core\relayer.py", line 114, in _find_instance
    raise exceptions.NotSupportedError(f"{target} is not supported")
pyatv.exceptions.NotSupportedError: left is not supported

What would be the standard way of creating an Airplay tunnel to send MRP commands using the atvremote?

If anyone is able to assist us with this, and point us into the right direction, that would be very much appreciated!

If anything is unclear, please let us know.

Kind regards,
Victor

**Comment by postlund** [comment]
Thank you for using pyatv 😊

The fact that MRP is tunneled over AirPlay nowadays is really just a small detail. You only need to pair AirPlay (`atvremote --protocol airplay pair`) and use these credentials when running atvremote, e.g. `atvremote --id <id> --airplay-credentials <credentials you got> playing`. Internally `pyatv` will figure out that the MRP tunnel is supported and set it up.

Generally you want to pair all "enabled" protocols shown by `atvremote scan` and provide credentials for these protocols whenever calling `atvremote` (you can see that MRP is marked as disabled in the scan results). I'm currently working on persistent storage for `pyatv` which can manage credentials for you (and store them in a file). Once that is done you don't have to save or provide the credentials manually, `pyatv` will take care of that automatically. But that's a month or (likely) two-or-so away.

But back to the issue... The credentials you have provided for AirPlay are correct and seems to work. You however have password protection enabled for AirPlay and this is unfortunately only implemented in RAOP so far (used when streaming audio). So until that is implemented also for AirPlay, you need to disable password for AirPlay.

**Comment by AVITPL** [comment]
Hello Postlund,

Thank you very much for your quick reply!

following your instructions, we have now set the password off, we didn't think there was a difference between a set password a randomized one that pops up on the screen. At least that is clear now and it working as expected! We are able to pair with Airplay, companion, and MRP, and seem to be able to use most of the commands. Which is great!

We are still running into an issue with the "playing" command. Previously it would come back with :
Media type : Unknown
Device state: Idle

Now it comes back with: 
  Media type: Unknown
Device state: Idle   
      Repeat: Off    
     Shuffle: Off  

We tried playing with several different applications, and even with using airplay through a phone, but the information is not being retrieved.

I have taken the output of a debug, and put it into a file if you could have a look at that. We were playing "Black Bird" via AppleTV+.

Thank you again for your help!

Kind regards,
Victor Niemann

**Comment by AVITPL** [comment]
[output pyatv Playing.log](https://github.com/postlund/pyatv/files/9147184/output.pyatv.Playing.log)

Sorry I forgot to upload the log file.

**Comment by AVITPL** [comment]
The active player was the Apple TV itself, we used the Apple TV+ app, and played a TV show. We have not used the "play_url", and restart the AppleTV, but did not make a difference.

Attached are two new log files, this time airplaying spotify to the apple TV. Metadata works correctly in the iOS app, and is displayed on the AppleTV screen. 

[debug artist.txt](https://github.com/postlund/pyatv/files/9151120/debug.artist.txt)
[debug playing.txt](https://github.com/postlund/pyatv/files/9151121/debug.playing.txt)

**Comment by postlund** [comment]
I'm referring to the "active" player signaled by the protocol, but it's effectively the same as the app current playing something. Anyways, it looks a bit buggy. I can see this:

```
2022-07-20 17:57:36 DEBUG [pyatv.protocols.airplay.mrp_connection]: << Receive: Protobuf: [setNowPlayingClientMessage] {
  client {
    processIdentifier: 153
    bundleIdentifier: "com.apple.TVAirPlay"
  }
}
uniqueIdentifier: "C5297FE4-928E-4142-9D67-73D229CD7FDA"
1: 46
```

But I can't see that pyatv actually sets that process as active client, which explains why you aren't seeing any metadata. I need to look into why this might happen, it's not unlikely that I need to add some log points and have you re-test it for me.

**Comment by AVITPL** [comment]
Thank you very much for your help!

If you need anything, please feel free to reach out.

**Comment by postlund** [comment]
I have added a few debug statements on the `player_logs` branch, can you try re-running with the version from that branch and attach a log file?

**Comment by AVITPL** [comment]
[pyatv player_logs output.txt](https://github.com/postlund/pyatv/files/9168245/pyatv.player_logs.output.txt)

We have ran your player_logs branch, and gotten this output. I hope this gives you what you need, let me know if you want me to try anything else.

In the mean time, we have installed it on a Ubuntu machine, and surprisingly, on there it works perfectly! I have checked all the installed packages, and versions. Everything is the same and up to date, but it still does not work from my windows machine. We also installed the library on another windows machine, but the same issue occurs on there. So it seems like a windows.

**Comment by postlund** [comment]
It both sounds and looks really strange to me. The protobuf messages have a `type` field indicating the message type. For some messages this field seems to not be set and default to 0. So I'm pretty sure this is a protobuf issue. Can you check which version to have installed on windows and compare that to Ubuntu?

**Comment by AVITPL** [comment]
Windows runs on 4.21.3, and linux runs on 4.21.2.

**Comment by postlund** [comment]
Can you try downgrading the Windows version to 4.21.2 and re-run and see what happens? Possibly also upgrading on Linux and see if you get the same behavior as on Windows?

**Comment by AVITPL** [comment]
Sure no problem, I just updated Linux to 4.21.3 and downgraded Windows to 4.21.2. But the problem remained on the Windows machine but does not occur on the Linux server.

**Comment by postlund** [comment]
Very interesting, thank you for trying! I will look into this further when I can actually spend some time in front of a computer (I'm pretty smartphone bound right now). Will Linux support suffice for you at the moment?

**Comment by Fredde87** [comment]
No worries, appreciate your help with this. Yes it will, ultimately Linux is were I will run it from. I just use Windows and Visual Studio for my development at work so its more convenient to test from.

**Comment by AVITPL** [comment]
No worries, appreciate your help with this. Yes it will, ultimately Linux is were I will run it from. I just use Windows and Visual Studio for my development at work so its more convenient to test from.

**Comment by postlund** [comment]
@AVITPL Would it be possible for you to retry this with latest pyatv? Hopefully it doesn't happen anymore.

**Comment by postlund** [comment]
I will close the due to inactivity, hopefully it works now. Please report back if you have any additional issues.
