### ISSUE TITLE
MRP Protocol Not Pairing - ATV 4k iOS 15.6

### ISSUE THREAD

**Issue by smarthomesydney** [postlund/pyatv#1825]
### Describe the bug

Airplay pairs fine.  MRP Error

pyatv# atvremote --id 50:23:12:44:2C:22 --protocol mrp pair    
Traceback (most recent call last):                                                
  File "/usr/local/lib/python3.9/dist-packages/pyatv/scripts/atvremote.py", line 7
17, in _run_application                                                           
    return await cli_handler(loop)                                                
  File "/usr/local/lib/python3.9/dist-packages/pyatv/scripts/atvremote.py", line 5
05, in cli_handler                                                                
    return await _exec_command(glob_cmds, args.command[0], print_result=False)    
  File "/usr/local/lib/python3.9/dist-packages/pyatv/scripts/atvremote.py", line 6
83, in _exec_command                                                              
    value = await tmp(*args)                                                      
  File "/usr/local/lib/python3.9/dist-packages/pyatv/scripts/atvremote.py", line 1
76, in pair                                                                       
    pairing = await pair(conf, self.args.protocol, self.loop, **options)          
  File "/usr/local/lib/python3.9/dist-packages/pyatv/__init__.py", line 153, in pa
ir                                                                                
    raise exceptions.NoServiceError(f"no service available for {protocol}")       
pyatv.exceptions.NoServiceError: no service available for Protocol.MRP            
                                                                                  
>>> An error occurred, full stack trace above 

DEBUG

atvremote -s 192.168.100.15 --debug --protocol mrp pair                                                     
2022-08-17 12:24:17 DEBUG [pyatv.scripts]: Running with pyatv 0.10.3                                                             
2022-08-17 12:24:17 DEBUG [pyatv.support.knock]: Knocking at port 3689 on 192.168.100.15                                         
2022-08-17 12:24:17 DEBUG [pyatv.support.knock]: Knocking at port 7000 on 192.168.100.15                                         
2022-08-17 12:24:17 DEBUG [pyatv.support.knock]: Knocking at port 49152 on 192.168.100.15                                        
2022-08-17 12:24:17 DEBUG [pyatv.support.knock]: Knocking at port 32498 on 192.168.100.15                                        
2022-08-17 12:24:17 DEBUG [pyatv.core.scan]: Auto-discovered AppleTV at 192.168.100.15:49152 via Protocol.Companion ({'rpmac': '2
', 'rphn': '67164eb857b5', 'rpfl': '0xB6782', 'rpha': '69b622811a91', 'rpmd': 'AppleTV6,2', 'rpvr': '360.4', 'rpad': '7204c4e8286
5', 'rphi': 'e88fc3d79e79', 'rpba': '89:BD:4A:B6:65:40', 'rpmrtid': '964EE819-6C0F-456D-A504-BD36DHD465DD2A'})                     
2022-08-17 12:24:17 DEBUG [pyatv.core.scan]: Auto-discovered AppleTV at 192.168.100.15:7000 via Protocol.AirPlay ({'acl': '0', 'b
taddr': '50:AE:S6:5X:5A:DB', 'deviceid': '50:AE:06:31:2C:D2', 'fex': '1d9/St5fFbwI', 'features': '0x4A7FDFD5,0xBC155FDE', 'flags'
: '0x644', 'gid': 'F80C58D0-1829-4E57-BA69-1FD3167798B3', 'igl': '1', 'gcgl': '1', 'model': 'AppleTV6,2', 'protovers': '1.1', 'pi
': 'c9468405-be07-4149-8964-2ef1hsd76c9f8', 'psi': '964EE819-6C0F-456D-A504-BD3ASJ451DD2A', 'pk': '78dcc12ac781adce33ba7a112122051b
8dd3e34beckjsdksjd901e365fae028bc9', 'srcvers': '620.8.2', 'osvers': '15.6', 'vv': '2'})                                           
2022-08-17 12:24:17 DEBUG [pyatv.core.scan]: Auto-discovered XXXXXXXXXX@AppleTV at 192.168.100.15:7000 via Protocol.RAOP ({'cn'
: '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x4A7FDFD5,0xBC155FDE', 'sf': '0x644', 'md': '0,1,2', 'am': 'AppleTV6,2', 'pk': 
'78dcc12ac781adce33ba7a112122051skdjskdjse34becf8170b901e365fae028bc9', 'tp': 'UDP', 'vn': '65537', 'vs': '620.8.2', 'ov': '15.6', 'v
v': '2'})                                                                                                                        
Traceback (most recent call last):                                                                                               
  File "/usr/local/lib/python3.9/dist-packages/pyatv/scripts/atvremote.py", line 717, in _run_application                        
    return await cli_handler(loop)                                                                                               
  File "/usr/local/lib/python3.9/dist-packages/pyatv/scripts/atvremote.py", line 505, in cli_handler                             
    return await _exec_command(glob_cmds, args.command[0], print_result=False)                                                   
  File "/usr/local/lib/python3.9/dist-packages/pyatv/scripts/atvremote.py", line 683, in _exec_command                           
    value = await tmp(*args)                                                                                                     
  File "/usr/local/lib/python3.9/dist-packages/pyatv/scripts/atvremote.py", line 176, in pair                                    
    pairing = await pair(conf, self.args.protocol, self.loop, **options)                                                         
  File "/usr/local/lib/python3.9/dist-packages/pyatv/__init__.py", line 153, in pair                                             
    raise exceptions.NoServiceError(f"no service available for {protocol}")                                                      
pyatv.exceptions.NoServiceError: no service available for Protocol.MRP                                                           
                                                                                                                                 
>>> An error occurred, full stack trace above 

### Error log

```log
<place log here>
```

### How to reproduce the bug?

happens every time

### What is expected behavior?

pairing successful

### Operating System

linux

### Python

3.9

### pyatv

0.10.3

### Device

ATV 4k iOS 15.6

### Additional context

Airplay Pairs Successfully.
MRP Broken in 0.10.3?

**Comment by postlund** [comment]
No, MRP is tunneled over AirPlay since tvOS 15 so you are not supposed to pair it. It will be taken care of automatically (you can see that it's marked as "disabled" when doing `atvremote scan`).

**Comment by smarthomesydney** [comment]
Ah...  So just Airplay is required for control now?
Is that a Apple change?

May be worth while updating the website to avoid other non technical creating tickets.  Still mentions MRP as the default in the install guides
Tnx

**Comment by smarthomesydney** [comment]
What is the RAOP and Companion protocols used for?

**Comment by postlund** [comment]
Yeah, AirPlay is enough. They introduced that around iOS/tvOS 12 or 13 and used it as default but kept MRP as a separate protocol for compatibility reasons until tvOS 15, where it was removed. As you say, the documentation is a bit vague regarding what to pair and when. Generally you should look at what protocols are supported by a device and if if pairing is required or not, not randomly pair a protocol. My intention is to make this clearer over time, especially when I get the time to introduce persistent storage of credentials. I want to create a separate script that takes care of this automatically, I.e. you run it and it takes care of pairing and stores all credentials, then you don't have to care about entering them ever again.

RAOP is for streaming audio over AirPlay (it's the "audio part" of AirPlay). Companion is the protocol used by control center in iOS, I.e. when you control an Apple TV via the Lock Screen for instance, then companion is used. It also supports a few additional features, like app listing and launching, proper sleep mode as well as some things I haven't implemented yet (screen saver, user profile switching, etc).

More details are here (it's not totally up to date though):

https://pyatv.dev/documentation/supported_features/#companion
