### ISSUE TITLE
atvscript push_update throwing exception in Windows

### ISSUE THREAD

**Issue by dineshpannu** [postlund/pyatv#1845]
### Describe the bug

Getting an exception when running ```atvscript push_updates``` on a Windows system. Seems to be something about Windows STDOUT and the library being used by pyatv.

A similar issue here: https://github.com/KimiNewt/pyshark/issues/193 suggests that simply closing the connection might fix the problem.

The following exception is thrown:
```
"error": "Exception in callback _ProactorReadPipeTransport._loop_reading()", 
"exception": "'_ProactorReadPipeTransport' object has no attribute '_empty_waiter'", 
"stacktrace": "Traceback (most recent call last):
    File "C:\Python310\lib\asyncio\proactor_events.py", line 301, in _loop_reading
        self._read_fut = self._loop._proactor.recv_into(self._sock, self._data)
    File "C:\Python310\lib\asyncio\windows_events.py", line 473, in recv_into
        self._register_with_iocp(conn)
    File "C:\Python310\lib\asyncio\windows_events.py", line 723, in _register_with_iocp
        _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 6] The handle is invalid

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
    File \"C:\\Python310\\lib\\asyncio\\events.py\", line 80, in _run
        self._context.run(self._callback, *self._args)
    File \"C:\\Python310\\lib\\asyncio\\proactor_events.py\", line 311, in _loop_reading
        self._fatal_error(exc, 'Fatal read error on pipe transport')
    File \"C:\\Python310\\lib\\asyncio\\proactor_events.py\", line 131, in _fatal_error
        self._force_close(exc)
    File \"C:\\Python310\\lib\\asyncio\\proactor_events.py\", line 134, in _force_close
        if self._empty_waiter is not None and not self._empty_waiter.done():
AttributeError: '_ProactorReadPipeTransport' object has no attribute '_empty_waiter'
```

### Error log

```log
{"result": "success", "datetime": "2022-09-23T17:21:01.927229+08:00", "power_state": "off"}
{"result": "failure", "datetime": "2022-09-23T17:21:01.928227+08:00", "error": "Exception in callback _ProactorReadPipeTransport._loop_reading()", "exception": "'_ProactorReadPipeTransport' object has no attribute '_empty_waiter'", "stacktrace": "Traceback (most recent call last):\n  File \"C:\\Python310\\lib\\asyncio\\proactor_events.py\", line 301, in _loop_reading\n    self._read_fut = self._loop._proactor.recv_into(self._sock, self._data)\n  File \"C:\\Python310\\lib\\asyncio\\windows_events.py\", line 473, in recv_into\n    self._register_with_iocp(conn)\n  File \"C:\\Python310\\lib\\asyncio\\windows_events.py\", line 723, in _register_with_iocp\n    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)\nOSError: [WinError 6] The handle is invalid\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Python310\\lib\\asyncio\\events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n  File \"C:\\Python310\\lib\\asyncio\\proactor_events.py\", line 311, in _loop_reading\n    self._fatal_error(exc, 'Fatal read error on pipe transport')\n  File \"C:\\Python310\\lib\\asyncio\\proactor_events.py\", line 131, in _fatal_error\n    self._force_close(exc)\n  File \"C:\\Python310\\lib\\asyncio\\proactor_events.py\", line 134, in _force_close\n    if self._empty_waiter is not None and not self._empty_waiter.done():\nAttributeError: '_ProactorReadPipeTransport' object has no attribute '_empty_waiter'\n"}
{"result": "success", "datetime": "2022-09-23T17:21:01.932230+08:00", "hash": "ca496c14642c78af6dd4250191fe175f6dafd72b4c33bcbab43c454aae051da1", "media_type": "unknown", "device_state": "idle", "title": null, "artist": null, "album": null, "genre": null, "total_time": null, "position": null, "shuffle": "off", "repeat": "off", "series_name": null, "season_number": null, "episode_number": null, "content_identifier": null, "app": null, "app_id": null}
{"result": "success", "datetime": "2022-09-23T17:21:01.932230+08:00", "push_updates": "finished"}
{"result": "failure", "datetime": "2022-09-23T17:21:01.958353+08:00", "error": "Task was destroyed but it is pending!"}
```

### How to reproduce the bug?

Run ```atvscript.exe --id [id] --airplay-credentions [credentials] push_updates``` on a Windows machine. Same behaviour in Command Prompt and PowerShell.

### What is expected behavior?

I was hoping it would run without exiting.

### Operating System

Windows 10

### Python

3.10

### pyatv

0.10.3

### Device

Apple TV 4K (gen2), tvOS 16.0

### Additional context

I see the same behaviour querying a Apple TV 4K, tvOS 15.6 also.

**Comment by postlund** [comment]
Can you try if changing event loop policy to use selector instead:

```python
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```
