### ISSUE TITLE
installation failed on synology nas

### ISSUE THREAD

**Issue by marcotwin34** [postlund/pyatv#1846]
### What do you need help with?

Hello, i have try many time to install pyatv for my Home Assistant. But unfortunately all my try failed with same issue, i have try to debug it, but my knowledge is limited here and i can't find or point the issue. 

Does someone help with this : 

DSM 7.1-42661 Update 4 
Realtek RTD1296 SoC ( ARM V7/8 )
Linux 4.4.180+ #42661  aarch64 GNU/Linux synology_rtd1296_ds218

sudo pip install pyatv
Collecting pyatv
  Using cached pyatv-0.10.3-py3-none-any.whl (402 kB)
Collecting chacha20poly1305-reuseable>=0.0.3
  Using cached chacha20poly1305_reuseable-0.0.4-py3-none-any.whl (10 kB)
Collecting protobuf>=3.19.3
  Downloading protobuf-4.21.6-cp37-abi3-manylinux2014_aarch64.whl (403 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 403.7/403.7 kB 4.3 MB/s eta 0:00:00
Collecting cryptography>=36.0.2
  Using cached cryptography-38.0.1-cp36-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.manylinux_2_24_aarch64.whl (3.7 MB)
Collecting miniaudio>=1.45
  Using cached miniaudio-1.52.tar.gz (676 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      /usr/lib/python3.8/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      /usr/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-mtfv3yj6/miniaudio_4fa7192e0b0843e38b199870072359bc/setup.py", line 20, in <module>
          setup(
        File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
          self.finalize_options()
        File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 900, in finalize_options
          ep(self)
        File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-install-mtfv3yj6/miniaudio_4fa7192e0b0843e38b199870072359bc/.eggs/cffi-1.15.1-py3.8-linux-aarch64.egg/cffi/setuptools_ext.py", line 219, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/tmp/pip-install-mtfv3yj6/miniaudio_4fa7192e0b0843e38b199870072359bc/.eggs/cffi-1.15.1-py3.8-linux-aarch64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "/tmp/pip-install-mtfv3yj6/miniaudio_4fa7192e0b0843e38b199870072359bc/.eggs/cffi-1.15.1-py3.8-linux-aarch64.egg/cffi/setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "build_ffi_module.py", line 805, in <module>
          ffibuilder = FFI()
        File "/tmp/pip-install-mtfv3yj6/miniaudio_4fa7192e0b0843e38b199870072359bc/.eggs/cffi-1.15.1-py3.8-linux-aarch64.egg/cffi/api.py", line 48, in __init__
          import _cffi_backend as backend
      ImportError: /tmp/pip-install-mtfv3yj6/miniaudio_4fa7192e0b0843e38b199870072359bc/.eggs/cffi-1.15.1-py3.8-linux-aarch64.egg/_cffi_backend.cpython-38-aarch64-linux-gnu.so: failed to map segment from shared object
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Thanks for your help

**Comment by marcotwin34** [comment]
Did somebody can help ?

Thx

**Comment by postlund** [comment]
Can you try this again and see if latest miniaudio works better?

**Comment by postlund** [comment]
I strongly believe latest miniaudio fixes this, will close issue. Please open again if problem persists.
