### ISSUE TITLE
Getting error message when pairing w/ new Apple TV

### ISSUE THREAD

**Issue by linkx2252** [postlund/pyatv#1867]
### What do you need help with?

Was able to do this just fine with old apple tv. Trying to do this with new apple tv...scan shows it, but when I try to pair I get this error message

```
XX@mini ~ % atvremote --id XX:XX:XX:XX:XX:XX --protocol mrp pair
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 719, in _run_application
    return await cli_handler(loop)
  File "/opt/homebrew/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 507, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
  File "/opt/homebrew/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 685, in _exec_command
    value = await tmp(*args)
  File "/opt/homebrew/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 176, in pair
    pairing = await pair(conf, self.args.protocol, self.loop, **options)
  File "/opt/homebrew/lib/python3.9/site-packages/pyatv/__init__.py", line 153, in pair
    raise exceptions.NoServiceError(f"no service available for {protocol}")
pyatv.exceptions.NoServiceError: no service available for Protocol.MRP

>>> An error occurred, full stack trace above
```

Any ideas on this error?

**Comment by virtzilla** [comment]
Seeing the same thing with an AppleTV 4K (gen 2) upgraded to tvOS 16.1. I have paired it on prior tvOS versions (but not sure which update it broke in).

**Comment by nigels0** [comment]
Yes, Same here with Gen2 AppleTV 4K with TV)S 16.2

**Comment by postlund** [comment]
From tvOS 16 you should not pair MRP anymore. If you run `atvremote scan`, you notice that the service is marked as "disabled". Just pair all other protocols, especially AirPlay as that is carrying MRP now.

**Comment by blaze005** [comment]
`atvremote --id [id here] --protocol companion pair`

**Comment by postlund** [comment]
I'll close this as it's not really an error.
