### ISSUE TITLE
pyatv

### ISSUE THREAD

**Issue by keithbrayuk** [postlund/pyatv#1880]
### Describe the bug

Got status 401 with message: UNAUTHORIZED: THE REQUEST REQUIRES USER AUTHENTICATION

when playing some radio web url`s i am getting a 401 error 

these sources play ok:

Pirate FM MP3
media-source://radio_browser/8306414a-6122-4641-bec6-43ba97c44a2c

Pirate FM AAC
media-source://radio_browser/d3a2a389-7d30-4144-8032-a4778e3b7fd8

BBC Radio 1
media-source://radio_browser/25e503c7-5897-4371-a84f-9c37b62256eb

these do not play ok.

Heart Radio Cornwall
media-source://radio_browser/96231699-0601-11e8-ae97-52543be04c81

Capital London

media-source://radio_browser/96200095-0601-11e8-ae97-52543be04c81

### Error log

2022-11-20 18:40:45.041 INFO (MainThread) [homeassistant.components.script.heart_radio_cornwall] Heart Radio Cornwall: Running script sequence
2022-11-20 18:40:45.042 INFO (MainThread) [homeassistant.components.script.heart_radio_cornwall] Heart Radio Cornwall: Executing step call service
2022-11-20 18:40:45.094 INFO (MainThread) [homeassistant.components.script.heart_radio_cornwall] Heart Radio Cornwall: Executing step delay 0:00:02.030000
2022-11-20 18:40:47.128 INFO (MainThread) [homeassistant.components.script.heart_radio_cornwall] Heart Radio Cornwall: Executing step call service
2022-11-20 18:40:47.133 DEBUG (MainThread) [homeassistant.components.apple_tv.media_player] Streaming https://media-ice.musicradio.com/HeartCornwallMP3 via RAOP
2022-11-20 18:40:49.322 ERROR (MainThread) [homeassistant.components.script.heart_radio_cornwall] Heart Radio Cornwall: Error executing script. Unexpected error for call_service at pos 3: Got status 401 with message: UNAUTHORIZED: THE REQUEST REQUIRES USER AUTHENTICATION
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyatv/protocols/raop/audio_source.py", line 362, in open
    stream_generator = await loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/miniaudio.py", line 1265, in stream_any
    raise DecodeError("failed to init decoder", result)
miniaudio.DecodeError: ('failed to init decoder', -17)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/media_player.py", line 292, in async_play_media
    await self.atv.stream.stream_file(media_id)
  File "/usr/local/lib/python3.10/site-packages/pyatv/core/facade.py", line 392, in stream_file
    await self.relay("stream_file")(file, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyatv/protocols/raop/__init__.py", line 371, in stream_file
    audio_file = await open_source(
  File "/usr/local/lib/python3.10/site-packages/pyatv/protocols/raop/audio_source.py", line 483, in open_source
    return await InternetSource.open(source, sample_rate, channels, sample_size)
  File "/usr/local/lib/python3.10/site-packages/pyatv/protocols/raop/audio_source.py", line 375, in open
    raise ProtocolError(source.error_message) from ex
pyatv.exceptions.ProtocolError: Got status 401 with message: UNAUTHORIZED: THE REQUEST REQUIRES USER AUTHENTICATION
2022-11-20 18:40:49.348 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [546956136832] Got status 401 with message: UNAUTHORIZED: THE REQUEST REQUIRES USER AUTHENTICATION
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyatv/protocols/raop/audio_source.py", line 362, in open
    stream_generator = await loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/miniaudio.py", line 1265, in stream_any
    raise DecodeError("failed to init decoder", result)
miniaudio.DecodeError: ('failed to init decoder', -17)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 495, in _service_handler
    await self.async_turn_on(variables=service.data, context=service.context)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 454, in async_turn_on
    await coro
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 484, in _async_run
    return await self.script.async_run(script_vars, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/media_player.py", line 292, in async_play_media
    await self.atv.stream.stream_file(media_id)
  File "/usr/local/lib/python3.10/site-packages/pyatv/core/facade.py", line 392, in stream_file
    await self.relay("stream_file")(file, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyatv/protocols/raop/__init__.py", line 371, in stream_file
    audio_file = await open_source(
  File "/usr/local/lib/python3.10/site-packages/pyatv/protocols/raop/audio_source.py", line 483, in open_source
    return await InternetSource.open(source, sample_rate, channels, sample_size)
  File "/usr/local/lib/python3.10/site-packages/pyatv/protocols/raop/audio_source.py", line 375, in open
    raise ProtocolError(source.error_message) from ex
pyatv.exceptions.ProtocolError: Got status 401 with message: UNAUTHORIZED: THE REQUEST REQUIRES USER AUTHENTICATION

### How to reproduce the bug?

try play the following to AppleTV or Home Pod 

Heart Radio Cornwall
media-source://radio_browser/96231699-0601-11e8-ae97-52543be04c81

Capital London

media-source://radio_browser/96200095-0601-11e8-ae97-52543be04c81

### What is expected behavior?

to play the radio url

### Operating System

Home assistant build

### Python

Other

### pyatv

latest 

### Device

Apple Homepod

### Additional context

none

**Comment by postlund** [comment]
Is this still an issue?
