### ISSUE TITLE
Connection timeout after ~3 Minutes

### ISSUE THREAD

**Issue by kilian579** [postlund/pyatv#1906]
### What to investigate?

When using pyatv as a remote control, I get regular timeouts. They usually appear every 3-5 Minutes. I've "fixed" it by forcing a reconnect after a `connection_lost` event, or any error I receive, after calling remote control functions. This still results in a ~10 second lag, until I can use the remote control again and is not optimal. There are several issues here:

**The `connection_lost` event:**
it seems only to be triggered, when a function was called right before it. So the typical process is 

> some remote_control_function (1st attempt, blocked) -> `connection_lost` -> reconnecting process (~10 second lag) -> remote_control_function (2nd attempt)

However I was hoping the `connection_lost` might trigger at the time, when I'm not calling any function, so the reconnect can happen before I'm using the remote control again.

**The timeout error:**
It usually looks something like this

```

pyatv.protocols.mrp.protocol - WARNING - There were 1 outstanding requests
root - ERROR - '7A674885-FB6E-4318-AE58-31C0A60A6216'
Traceback (most recent call last):
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 274, in _receive
    await semaphore.acquire()
  File "/usr/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
  File "/usr/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/usr/lib/python3.9/asyncio/futures.py", line 196, in result
    raise exc
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 274, in _receive
    await semaphore.acquire()
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/dev_apple_tv/devices/control_apple_tv.py", line 176, in __async_call
    await self._control_dict[control_string]()
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/core/facade.py", line 106, in select
    return await self.relay("select")(action=action)
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 387, in select
    await _send_hid_key(self.protocol, "select", action)
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 297, in _send_hid_key
    await _do_press(keycode, False)
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 290, in _do_press
    await protocol.send_and_receive(messages.create(protobuf.GENERIC_MESSAGE))
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 261, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 277, in _receive
    del self._outstanding[identifier]
KeyError: '7A674885-FB6E-4318-AE58-31C0A60A6216'
root - INFO - Log file run_remote2023-01-27_12-53-48.json
root - INFO - Click: Right  ['Right', 'Down', 'Left', 'Up', 'Select', 'Menu', 'Home', 'VOLUME', 'backback']
root - INFO - Click: Menu  ['Right', 'Down', 'Left', 'Up', 'Select', 'Menu', 'Home', 'VOLUME', 'backback']
pyatv.protocols.mrp.protocol - WARNING - There were 1 outstanding requests
root - ERROR - 'EF7FD0F8-1776-4657-8389-8036165E6522'
Traceback (most recent call last):
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 274, in _receive
    await semaphore.acquire()
  File "/usr/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
  File "/usr/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/usr/lib/python3.9/asyncio/futures.py", line 196, in result
    raise exc
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 274, in _receive
    await semaphore.acquire()
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/dev_apple_tv/devices/control_apple_tv.py", line 176, in __async_call
    await self._control_dict[control_string]()
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/core/facade.py", line 111, in menu
    return await self.relay("menu")(action=action)
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 391, in menu
    await _send_hid_key(self.protocol, "menu", action)
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 297, in _send_hid_key
    await _do_press(keycode, False)
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 290, in _do_press
    await protocol.send_and_receive(messages.create(protobuf.GENERIC_MESSAGE))
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 261, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 277, in _receive
    del self._outstanding[identifier]
KeyError: 'EF7FD0F8-1776-4657-8389-8036165E6522'
```

It seems to be triggered by a KeyError of a key (eg. 'EF7FD0F8-1776-4657-8389-8036165E6522'), that can usually be found, but is unavailable due to a timeout.

### Expected outcome

I'm trying to find out how to keep the connection alive in a user friendly way. Regular lags of ~10 seconds are not really comfortable for a remote control. 

My idea was to create a keep_alive method, which sends a request to the ATV, to check if the connection is still alive. But using methods like `metadata.playing()` would be a misuse of them. 

Would you suggest any other way?

**Comment by HWiese1980** [comment]
I'm experiencing TimeoutErrors as well when calling the `remote.send_command` service. It starts working again when I reload the integration... for a short period. Then it stops working again.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyatv/protocols/mrp/protocol.py", line 274, in _receive
    await semaphore.acquire()
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 216, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/remote.py", line 69, in async_send_command
    await attr_value()
  File "/usr/local/lib/python3.10/site-packages/pyatv/core/facade.py", line 128, in home
    return await self.relay("home")(action=action)
  File "/usr/local/lib/python3.10/site-packages/pyatv/protocols/mrp/__init__.py", line 403, in home
    await _send_hid_key(self.protocol, "home", action)
  File "/usr/local/lib/python3.10/site-packages/pyatv/protocols/mrp/__init__.py", line 297, in _send_hid_key
    await _do_press(keycode, False)
  File "/usr/local/lib/python3.10/site-packages/pyatv/protocols/mrp/__init__.py", line 290, in _do_press
    await protocol.send_and_receive(messages.create(protobuf.GENERIC_MESSAGE))
  File "/usr/local/lib/python3.10/site-packages/pyatv/protocols/mrp/protocol.py", line 261, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/usr/local/lib/python3.10/site-packages/pyatv/protocols/mrp/protocol.py", line 273, in _receive
    async with async_timeout.timeout(timeout):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

**Comment by postlund** [comment]
I think you are seeing two different errors to start with. @kilian579 do you have any blocking calls in your code? There's already a keep-alive mechanism built in, so you shouldn't do that yourself.

**Comment by regan-karlewicz** [comment]
@kilian579 I recently ran into this exact same issue. The root cause was that my asyncio event loop that was used to setup the pyatv connection had stopped running. The event loop must be kept running for the life time of the connection.

Hope this helps!
