### ISSUE TITLE
Connection fails/ times out — Failed to set up remote control channel

### ISSUE THREAD

**Issue by AKValle26** [postlund/pyatv#1909]
### Describe the bug

Started yesterday.  `atvremote` now fails to connect to AppleTV.  No errors in logs, just eventually times out

Log excerpt

```
2023-01-30 21:03:03 DEBUG [pyatv.core.scan]: Auto-discovered Living Room at 192.168.50.40:49154 via Protocol.Companion ({'rpmac': '2', 'rphn': '367175d11dad', 'rpfl': '0xB6782', 'rpha': '85a25a28da1a', 'rpmd': 'AppleTV11,1', 'rpvr': '420.5', 'rpad': 'da611e5fd1f1', 'rphi': '80212b7b8831', 'rpba': '51:52:E6:71:9B:69', 'rpmrtid': 'D7E17B25-2C2F-42E5-A033-1E4323BE2C66'})
2023-01-30 21:03:03 DEBUG [pyatv.core.scan]: Auto-discovered Living Room at 192.168.50.40:7000 via Protocol.AirPlay ({'acl': '0', 'btaddr': '00:00:00:00:00:00', 'deviceid': 'EC:A9:07:21:56:FD', 'fex': '1d9/St5/FbwooQ', 'features': '0x4A7FDFD5,0xBC157FDE', 'flags': '0x18644', 'gid': 'AEA48E47-6E38-4C2B-BD43-AB92931134A9', 'igl': '1', 'gcgl': '1', 'model': 'AppleTV11,1', 'protovers': '1.1', 'pi': '9f4d0ece-d94b-449d-9150-17adfbef5021', 'psi': 'D7E17B25-2C2F-42E5-A033-1E4323BE2C66', 'pk': '2104851f2e3cf6e546b5cce1b98450716d2cbd4ab9a7d660364745dcab309807', 'srcvers': '670.6.2', 'osvers': '16.2', 'vv': '2'})
2023-01-30 21:03:03 DEBUG [pyatv.core.scan]: Auto-discovered ECA9072156FD@Living Room at 192.168.50.40:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x4A7FDFD5,0xBC157FDE', 'sf': '0x18644', 'md': '0,1,2', 'am': 'AppleTV11,1', 'pk': '2104851f2e3cf6e546b5cce1b98450716d2cbd4ab9a7d660364745dcab309807', 'tp': 'UDP', 'vn': '65537', 'vs': '670.6.2', 'ov': '16.2', 'vv': '2'})
2023-01-30 21:03:03 INFO [pyatv.scripts.atvremote]: Auto-discovered Living Room at 192.168.50.40
2023-01-30 21:03:03 DEBUG [pyatv.core.facade]: Adding handler for protocol Protocol.AirPlay
2023-01-30 21:03:03 DEBUG [pyatv.protocols.airplay]: Remote control channel is supported
2023-01-30 21:03:03 DEBUG [pyatv.core.facade]: Adding handler for protocol Protocol.MRP
2023-01-30 21:03:03 DEBUG [pyatv.protocols.companion]: Not adding Companion as credentials are missing
2023-01-30 21:03:03 DEBUG [pyatv.core.facade]: Adding handler for protocol Protocol.MRP
2023-01-30 21:03:03 DEBUG [pyatv.core.facade]: Adding handler for protocol Protocol.RAOP
2023-01-30 21:03:03 DEBUG [pyatv.core.facade]: Connecting to protocol: Protocol.AirPlay
2023-01-30 21:03:03 DEBUG [pyatv.core.facade]: Connected to protocol: Protocol.AirPlay
2023-01-30 21:03:03 DEBUG [pyatv.core.facade]: Connecting to protocol: Protocol.MRP
2023-01-30 21:03:03 DEBUG [pyatv.protocols.airplay.remote_control]: Setting up remote control connection to 192.168.50.40:7000
```

```
2023-01-30 21:05:16 ERROR [pyatv.protocols.airplay]: Failed to set up remote control channel
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/airplay/__init__.py", line 258, in _connect_rc
    await control.start(str(core.config.address), control_port, credentials)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/airplay/remote_control.py", line 55, in start
    self.connection = await http_connect(address, control_port)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/support/http.py", line 558, in http_connect
    _, connection = await loop.create_connection(HttpConnection, address, port)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.50.40', 7000)
2023-01-30 21:05:16 DEBUG [pyatv.core.facade]: Connecting to protocol: Protocol.MRP
```

### Error log

```log
<place log here>
```

### How to reproduce the bug?

Try a command

### What is expected behavior?

Connects successfully & command runs 

### Operating System

Linux (homebridge raspberry pi image)

### Python

3.9

### pyatv

atvremote --version atvremote 0.10.3

### Device

Apple TV 4k gen 2 OS 16.2

### Additional context

.

**Comment by steve28** [comment]
I have this too.  I haven't been able to make it happen, but it I believe it might be some combo of the ATV restarting (say, for an update) and/or HA restarting.  My logs look the same as above when it occurs for me as well.

If I reboot the ATV, then everything works again.

**Comment by postlund** [comment]
When this happens, does it eventually recover? Does it work in iOS? Just want to make sure it's a pyatv problem and not an Apple TV problem.

**Comment by postlund** [comment]
Still a problem you see regularly?

**Comment by postlund** [comment]
Please report back if problem persists, will close issue now.
