### ISSUE TITLE
TTS google_translate to Homepod mini with Apple TV integration is buggy

### ISSUE THREAD

**Issue by dkkr23** [postlund/pyatv#1931]
### Describe the bug

TTS with google_translate into homepod mini using Apple TV integration does not work, and if try it again immediately after it fails with an error, it works. Seems the response to the request to connect times out. I'm running home assistant core on a mac.

### Error log

```log
Logger: homeassistant.components.websocket_api.http.connectionSource: components/apple_tv/media_player.py:292Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))First occurred: 2:09:14 PM (14 occurrences)Last logged: 4:30:37 PM

[5033700768] no response to ANNOUNCE rtsp://192.168.0.100/1141637291 (RTSP/1.0)

[5033700768] no response to ANNOUNCE rtsp://192.168.0.100/4145601167 (RTSP/1.0)

[4698499216] no response to ANNOUNCE rtsp://192.168.0.100/3928547785 (RTSP/1.0)

[4698499216] no response to ANNOUNCE rtsp://192.168.0.100/1918093030 (RTSP/1.0)

[4698499216] no response to ANNOUNCE rtsp://192.168.0.100/488201790 (RTSP/1.0)

Traceback (most recent call last): File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/pyatv/support/http.py", line 390, in send_and_receive await event.wait() File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/locks.py", line 214, in wait await fut asyncio.exceptions.CancelledError During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/pyatv/support/http.py", line 389, in send_and_receive async with async_timeout.timeout(4): File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__ self._do_exit(exc_type) File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit raise asyncio.TimeoutError asyncio.exceptions.TimeoutError The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response await func(hass, connection, msg) File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/components/websocket_api/commands.py", line 646, in handle_execute_script await script_obj.async_run(msg.get("variables"), context=context) File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/script.py", line 1524, in async_run await asyncio.shield(run.async_run()) File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/script.py", line 409, in async_run await self._async_step(log_exceptions=False) File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/script.py", line 453, in _async_step self._handle_exception( File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/script.py", line 476, in _handle_exception raise exception File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/script.py", line 451, in _async_step await getattr(self, handler)() File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/script.py", line 684, in _async_call_service_step await service_task File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/core.py", line 1787, in async_call task.result() File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/core.py", line 1824, in _execute_service await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)( File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/components/tts/__init__.py", line 217, in async_say_handle await hass.services.async_call( File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/core.py", line 1787, in async_call task.result() File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/core.py", line 1824, in _execute_service await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)( File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_component.py", line 213, in handle_service await service.entity_service_call( File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/service.py", line 680, in entity_service_call future.result() # pop exception if have File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 968, in async_request_call await coro File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/service.py", line 720, in _handle_entity_call await result File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/homeassistant/components/apple_tv/media_player.py", line 292, in async_play_media await self.atv.stream.stream_file(media_id) File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/pyatv/core/facade.py", line 392, in stream_file await self.relay("stream_file")(file, **kwargs) File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/pyatv/protocols/raop/__init__.py", line 352, in stream_file await client.initialize(self.core.service.properties) File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/pyatv/protocols/raop/raop.py", line 457, in initialize await self._setup_session() File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/pyatv/protocols/raop/raop.py", line 479, in _setup_session await self.rtsp.announce( File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/pyatv/support/rtsp.py", line 153, in announce response = await self.exchange( File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/pyatv/support/rtsp.py", line 265, in exchange resp = await self.connection.send_and_receive( File "/Users/dr/Documents/homeassistant/lib/python3.10/site-packages/pyatv/support/http.py", line 393, in send_and_receive raise TimeoutError(f"no response to {method} {uri} ({protocol})") from ex TimeoutError: no response to ANNOUNCE rtsp://192.168.0.100/3776511979 (RTSP/1.0)



Logger: pyatv.support.httpSource: runner.py:128First occurred: 14:09:18 (28 occurrences)Last logged: 16:30:41

Got response without having a request: HttpResponse(protocol='RTSP', version='1.0', code=200, message='OK', headers={'date': 'Sun, 26 Feb 2023 14:29:37 GMT', 'content-length': '55', 'content-type': 'application/x-apple-binary-plist', 'server': 'AirTunes/680.19.2', 'cseq': '98'}, body=b'bplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14')

Got response without having a request: HttpResponse(protocol='RTSP', version='1.0', code=200, message='OK', headers={'date': 'Sun, 26 Feb 2023 14:30:17 GMT', 'content-length': '0', 'server': 'AirTunes/680.19.2', 'cseq': '1'}, body='')

Got response without having a request: HttpResponse(protocol='RTSP', version='1.0', code=200, message='OK', headers={'date': 'Sun, 26 Feb 2023 14:30:17 GMT', 'content-length': '55', 'content-type': 'application/x-apple-binary-plist', 'server': 'AirTunes/680.19.2', 'cseq': '15'}, body=b'bplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14')

Got response without having a request: HttpResponse(protocol='RTSP', version='1.0', code=200, message='OK', headers={'date': 'Sun, 26 Feb 2023 14:30:41 GMT', 'content-length': '0', 'server': 'AirTunes/680.19.2', 'cseq': '1'}, body='')

Got response without having a request: HttpResponse(protocol='RTSP', version='1.0', code=200, message='OK', headers={'date': 'Sun, 26 Feb 2023 14:30:41 GMT', 'content-length': '55', 'content-type': 'application/x-apple-binary-plist', 'server': 'AirTunes/680.19.2', 'cseq': '7'}, body=b'bplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14')



Logger: homeassistant.components.apple_tvSource: components/apple_tv/__init__.py:169Integration: Apple TV ([documentation](https://www.home-assistant.io/integrations/apple_tv), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+apple_tv%22))First occurred: 2:09:22 PM (14 occurrences)Last logged: 4:30:45 PM

Connection lost to Apple TV "Loft"

Connection lost to Apple TV "Main Room"
```

### How to reproduce the bug?

When I try calling tts with google_translate to a homepod mini. If I try immediately after it fails the first time, it works

### What is expected behavior?

tts google_translate on homepod mini should work on the first request

### Operating System

macOS

### Python

3.10

### pyatv

0.10.3

### Device

Homepod mini version 16.4

### Additional context

None

**Comment by dkkr23** [comment]
This issue related to ios 16.4 beta. If you downgrade to the latest stable version, it works perfectly

**Comment by jpconfessor** [comment]
this is still broken in the public release of 16.4
