### ISSUE TITLE
failed to install ARMv7 OrangePI PC Ubuntu

### ISSUE THREAD

**Issue by IvanIvanerov** [postlund/pyatv#1937]
### Describe the bug

can't install
pls help

### Error log

```log
pip install pyatv
Collecting pyatv
  Downloading pyatv-0.10.3-py3-none-any.whl (402 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 402.1/402.1 kB 811.8 kB/s eta 0:00:00
Collecting ifaddr>=0.1.7
  Using cached ifaddr-0.2.0-py3-none-any.whl (12 kB)
Collecting zeroconf>=0.38.1
  Using cached zeroconf-0.47.3-cp39-cp39-manylinux_2_23_armv7l.whl
Collecting protobuf>=3.19.3
  Downloading protobuf-4.22.0-py3-none-any.whl (172 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.8/172.8 kB 1.4 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.9/site-packages (from pyatv) (2.28.2)
Requirement already satisfied: async-timeout>=4.0.2 in /usr/local/lib/python3.9/site-packages (from pyatv) (4.0.2)
Collecting bitarray>=2.1.2
  Downloading bitarray-2.7.3.tar.gz (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.6/123.6 kB 1.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: aiohttp<5,>=3.8.1 in /usr/local/lib/python3.9/site-packages (from pyatv) (3.8.4)
Collecting mediafile>=0.8.1
  Downloading mediafile-0.11.0-py3-none-any.whl (21 kB)
Collecting srptools>=0.2.0
  Downloading srptools-1.0.1-py2.py3-none-any.whl (13 kB)
Collecting chacha20poly1305-reuseable>=0.0.3
  Downloading chacha20poly1305_reuseable-0.0.4-py3-none-any.whl (10 kB)
Collecting cryptography>=36.0.2
  Downloading cryptography-39.0.2.tar.gz (604 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 604.3/604.3 kB 2.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting miniaudio>=1.45
  Downloading miniaudio-1.55.tar.gz (685 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 685.7/685.7 kB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [6 lines of output]
            usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
               or: setup.py --help [cmd1 cmd2 ...]
               or: setup.py --help-commands
               or: setup.py cmd --help
      
            error: invalid command 'bdist_wheel'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cffi
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "/usr/local/lib/python3.9/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpgbefbpjr', '--quiet', 'cffi>=1.12.0']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-aaieeabh/miniaudio_9c46262085fa4338a0b4271ab1ec33bb/setup.py", line 20, in <module>
          setup(
        File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 164, in setup
          _install_setup_requires(attrs)
        File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 699, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 779, in resolve
          dist = best[req.key] = env.best_match(
        File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1064, in best_match
          return self.obtain(req, installer)
        File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1076, in obtain
          return installer(requirement)
        File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/usr/local/lib/python3.9/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpgbefbpjr', '--quiet', 'cffi>=1.12.0']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

### How to reproduce the bug?

install attempt

### What is expected behavior?

-

### Operating System

Ubuntu

### Python

3.9

### pyatv

0.8.2

### Device

-

### Additional context

-

**Comment by postlund** [comment]
Try `pip install bdist_wheel` first.

**Comment by postlund** [comment]
I assume that the command above fixed it, otherwise re-open the issue.
