### ISSUE TITLE
AppleTV14,1, Unknown OS 16.4 fails with power_state command

### ISSUE THREAD

**Issue by mag911** [postlund/pyatv#1949]
### Describe the bug

atvremote scan finds the following:
Name: Apple TV
Model/SW: AppleTV14,1, Unknown OS 16.4
Address: 192.168.1.100
MAC: A8:51:AB:xx:xx:xx
Deep Sleep: False
Identifiers:
 - A8:51:AB:xx:xx:xx
 - A851ABxxxxxx
Services:
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: Companion, Port: 49160, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
However, atvremote --id A851ABxxxxxx power_state gives:
atvremote --id A851ABxxxxxx power_state
2023-04-07 11:48:52 ERROR [pyatv.scripts.atvremote]: Command 'power_state' is not supported by device
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 677, in _exec_command
    tmp = getattr(obj, command)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/support/shield.py", line 72, in _guard_method
    return func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/core/facade.py", line 348, in power_state
    return self.relay("power_state")
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/core/relayer.py", line 90, in relay
    instance = self._find_instance(
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/core/relayer.py", line 114, in _find_instance
    raise exceptions.NotSupportedError(f"{target} is not supported")
pyatv.exceptions.NotSupportedError: power_state is not supported

### Error log

```log
ERROR [pyatv.scripts.atvremote]: Command 'power_state' is not supported by device
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 677, in _exec_command
    tmp = getattr(obj, command)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/support/shield.py", line 72, in _guard_method
    return func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/core/facade.py", line 348, in power_state
    return self.relay("power_state")
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/core/relayer.py", line 90, in relay
    instance = self._find_instance(
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/core/relayer.py", line 114, in _find_instance
    raise exceptions.NotSupportedError(f"{target} is not supported")
pyatv.exceptions.NotSupportedError: power_state is not supported
```

### How to reproduce the bug?

Using the very latest Apple TV (Apple TV 4K Wi‐Fi + Ethernet with 128GB storage, Part Number: MN893X/A), run atvremote scan, then atvremote ... power_state against the relevant device.

### What is expected behavior?

In testing against a Homepod mini, also on my network .. atvremote --id 94EA32xxxxxx power_state
PowerState.On

### Operating System

Official HomeBridge Raspberry Pi Image

### Python

3.9

### pyatv

0.10.3

### Device

Apple TV 4K Wi‐Fi + Ethernet with 128GB storage, 16.4

### Additional context

n/a

**Comment by mag911** [comment]
Partially fixed. After updating convert.py, interfaces.py, const.py, device_info.py, I can get atvremote to scan and report the AppleTV14,1 as a 4K Gen 3 device, but requesting a power_state still fails:
Name: Apple TV
Model/SW: Apple TV 4K (gen3), tvOS 16.4
Address: 192.168.1.100
```
2023-04-07 14:10:37 ERROR [pyatv.scripts.atvremote]: Command 'power_state' is not supported by device
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 677, in _exec_command
    tmp = getattr(obj, command)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/support/shield.py", line 72, in _guard_method
    return func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/core/facade.py", line 348, in power_state
    return self.relay("power_state")
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/core/relayer.py", line 90, in relay
    instance = self._find_instance(
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/core/relayer.py", line 114, in _find_instance
    raise exceptions.NotSupportedError(f"{target} is not supported")
pyatv.exceptions.NotSupportedError: power_state is not supported
```

**Comment by postlund** [comment]
You need to pair and provide credentials for a protocol supporting `power_state`, e.g. AirPlay in the case of Apple TV running tvOS 15 or later. So basically:

```raw
$ atvremote --id <id> --protocol airplay pair
```
Follow instructions and insert the credentials you get here:

```raw
$ atvremote --id <id> --airplay-credentials <credentials> playing
```
If you want full functionality, you should repeat for each protocol reported by a scan (and provide multiple `--xxx-credentials` arguments).

I will take care of updating hardware and operating system reported a bit later.

**Comment by mag911** [comment]
Whoo Hoo! Awesome. Thank you very much, that worked. Tack så mycket.
