### ISSUE TITLE
Stopped working with hass 2023.5 beta

### ISSUE THREAD

**Issue by jscherry** [postlund/pyatv#1980]
### Describe the bug

Fails to load after upgrade to 2023.5 beta

### Error log

logger: homeassistant.setup
Source: setup.py:206
First occurred: 6:43:58 PM (1 occurrences)
Last logged: 6:43:58 PM

Setup failed for custom integration apple_tv: Requirements for apple_tv not found: ['pyatv==0.10.0'].

### How to reproduce the bug?

install 2023.5 beta

### What is expected behavior?

Load and run like before

### Operating System

Linux Home assistant os

### Python

3.6

### pyatv

unknown

### Device

Apple TV 4k 16.5

### Additional context

logger: homeassistant.setup
Source: setup.py:206
First occurred: 6:43:58 PM (1 occurrences)
Last logged: 6:43:58 PM

Setup failed for custom integration apple_tv: Requirements for apple_tv not found: ['pyatv==0.10.0'].

**Comment by sweetw0r** [comment]
@postlund could you please take a look as the code owner?

**Comment by postlund** [comment]
This is not a pyatv problem, this has something to do with pyatv and pip. I have no idea why this is happening, but you should open an issue Home Assistant instead.

**Comment by sweetw0r** [comment]
Thanks for quick turnaround @postlund. 
@jscherry Would you please do the honors?

**Comment by FrancoLoco** [comment]
I also have this problem.

**Comment by FrancoLoco** [comment]
I  have this workaround which is annoying to do but works for the moment:

Add-Ons -> SSH & Web Terminal (unprotected mode)

docker exec -it homeassistant bash

 cd /usr/local/lib/python3.10/site-packages

rm -rf pyatv*

pip install pyatv==0.10.0

restart home assistant

**Comment by sweetw0r** [comment]
Workaround works. Confirmed. Thanks @FrancoLoco

**Comment by FrancoLoco** [comment]
I ended up going with the official apple tv integration and it seems to work fine now, so I suggest uninstalling the beta hacs apple tv

**Comment by jamesfk** [comment]
Confirm also having the problem. Would be great to get a fix as I use app launching and other functionality unique in the Beta in some automations. Fingers crossed :)

**Comment by FrancoLoco** [comment]
> Confirm also having the problem. Would be great to get a fix as I use app launching and other functionality unique in the Beta in some automations. Fingers crossed :)

I just tried with the official version and I can still start applications or also remote control like everything I had with the beta from what I see.. I think it's actually the same project with just a few versions more.

**Comment by GitHubxtsnl** [comment]
> I have this workaround which is annoying to do but works for the moment:
> 
> Add-Ons -> SSH & Web Terminal (unprotected mode)
> 
> docker exec -it homeassistant bash
> 
> cd /usr/local/lib/python3.10/site-packages
> 
> rm -rf pyatv*
> 
> pip install pyatv==0.10.0
> 
> restart home assistant

I tried this one but it fails with the following error:

```
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [88 lines of output]
      /usr/lib/python3.10/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      /usr/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
        error: subprocess-exited-with-error

        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [41 lines of output]
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'libffi', required by 'virtual:world', not found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'libffi', required by 'virtual:world', not found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'libffi', required by 'virtual:world', not found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'libffi', required by 'virtual:world', not found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'libffi', required by 'virtual:world', not found

                No working compiler found, or bogus compiler options passed to
                the compiler from Python's standard "distutils" module.  See
                the error messages above.  Likely, the problem is not related
                to CFFI but generic to the setup.py of any Python package that
                tries to compile C code.  (Hints: on OS/X 10.8, for errors about
                -mno-fused-madd see http://stackoverflow.com/questions/22313407/
                Otherwise, see https://wiki.python.org/moin/CompLangPython or
                the IRC channel #python on irc.libera.chat.)

                Trying to continue anyway.  If you are trying to install CFFI from
                a build done in a different context, you can ignore this warning.

            /usr/lib/python3.10/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
              warnings.warn(msg, warning_class)
            usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
               or: setup.py --help [cmd1 cmd2 ...]
               or: setup.py --help-commands
               or: setup.py cmd --help

            error: invalid command 'bdist_wheel'
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cffi
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "/usr/lib/python3.10/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmphppbprx4', '--quiet', 'cffi>=1.12.0']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7e6m0qh0/miniaudio_450d82844bac48ffaf93b1730afed194/setup.py", line 20, in <module>
          setup(
        File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/usr/lib/python3.10/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmphppbprx4', '--quiet', 'cffi>=1.12.0']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by postlund** [comment]
@GitHubxtsnl You are missing the wheel dependency (`pip install wheel`).

I'm gonna close this now as it's not a pyatv issue. Not sure if anyone opened an issue over at Home Assistant or if it has solved itself by now, but hope so.
