### ISSUE TITLE
No usable service to connect to

### ISSUE THREAD

**Issue by raufis27** [postlund/pyatv#212]
**Describe the bug**
# atvremote --id vv869cd061111 --address 192..... --device_credentials 00000000-3f3c-f959-e5db-.... pause
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 492, in _run_application
    return await cli_handler(loop)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 316, in cli_handler
    return await _handle_commands(args, loop)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 399, in _handle_commands
    details, loop, protocol=args.protocol)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__init__.py", line 184, in connect_to_apple_tv
    service = _get_service_used_to_connect(details, protocol)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__init__.py", line 208, in _get_service_used_to_connect
    'no usable service to connect to')
pyatv.exceptions.NoUsableServiceError: no usable service to connect to

**System Setup (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python: 3.6.2
 - pyatv: atvremote 0.4.0a1

**Additional context**
Recently upgraded to the latest TVOS and pyatv
atvremote scan
Scan Results
========================================
    Name: Living Room
 Address: 192....
      Id: vv869cd061111
Services:
 - Protocol: MRP, Port: 49153, Credentials: None
 - Protocol: AirPlay, Port: 7000

**Comment by postlund** [comment]
Are you sure the device is is correct? It's supposed to be the MAC-address, so "vv" doesn't seem to be alright.

**Comment by raufis27** [comment]
Yes sorry, I changed Mac address and IP address on purpose. Security paranoid IT guy.

**Comment by raufis27** [comment]
Name: Living Room
 Address: 
      Id: c869cd08126d
Services:
 - Protocol: MRP, Port: 49153, Credentials: None
 - Protocol: AirPlay, Port: 7000

root@rihub:/home/riadmin# atvremote --id c869cd08126d --address 192..... pause
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 492, in _run_application
    return await cli_handler(loop)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 316, in cli_handler
    return await _handle_commands(args, loop)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 399, in _handle_commands
    details, loop, protocol=args.protocol)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__init__.py", line 184, in connect_to_apple_tv
    service = _get_service_used_to_connect(details, protocol)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__init__.py", line 208, in _get_service_used_to_connect
    'no usable service to connect to')
pyatv.exceptions.NoUsableServiceError: no usable service to connect to

>>> An error occurred, full stack trace above

**Comment by postlund** [comment]
Right, makes sense. You either have to specify `-a` or `--protocol mrp`. Should be enough, assuming your device is ok with not pairing.

**Comment by raufis27** [comment]
using -a I was getting this error : ERROR: Could not find any Apple TV on current network. 
atvremote scan: 
    Name: Living Room
 Address: .....
      Id: ....
Services:
 - Protocol: AirPlay, Port: 7000

Then I restarted Apple TV. And now it works. I guess this issue can be closed.
