### ISSUE TITLE
ScreenSaver Activation Fails

### ISSUE THREAD

**Issue by Ghawken** [postlund/pyatv#2139]
### Describe the bug

Hi
Thanks for ongoing work.
Testing out activate ScreenSaver on AppleTV 4k Gen 2 OS 16.6
& Fails with below appearing the relevant exception logging

### Error log

```log
Traceback (most recent call last):
  File "plugin.py", line 507, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyatv/core/facade.py", line 190, in screensaver
    return await self.relay("screensaver")()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyatv/protocols/companion/__init__.py", line 349, in screensaver
    await self._press_button(HidCommand.Screensaver)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyatv/protocols/companion/__init__.py", line 357, in _press_button
    await self.api.hid_command(False, command)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyatv/protocols/companion/api.py", line 279, in hid_command
    await self._send_command(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyatv/protocols/companion/api.py", line 174, in _send_command
    raise exceptions.ProtocolError(f"Command {identifier} failed") from ex
pyatv.exceptions.ProtocolError: Command _hidC failed

  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyatv/core/facade.py", line 190, in screensaver
    return await self.relay("screensaver")()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyatv/protocols/companion/__init__.py", line 349, in screensaver
    await self._press_button(HidCommand.Screensaver)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyatv/protocols/companion/__init__.py", line 357, in _press_button
    await self.api.hid_command(False, command)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyatv/protocols/companion/api.py", line 279, in hid_command
    await self._send_command(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyatv/protocols/companion/api.py", line 174, in _send_command
    raise exceptions.ProtocolError(f"Command {identifier} failed") from ex
pyatv.exceptions.ProtocolError: Command _hidC failed 

```

### How to reproduce the bug?

Run Active Screen Saver Command

### What is expected behavior?

Screen Saver Activates

### Operating System

macOS

### Python

3.10

### pyatv

0.13.4

### Device

AppleTV 4k Gen 2 OS 16.6

### Additional context

Thanks!

**Comment by postlund** [comment]
Does this always fail for you? I have seen similar issues in case my TV is not on, I.e. no HDMI output. But it seems to normally work otherwise.

**Comment by Ghawken** [comment]
Yeah - it does seem to.  Have tried with 2 different appleTV devices, and this particularly one quite a bit.

Initally thought maybe was because was already on screensaver, but checked and wasn’t that.
Just checked now, is on, select App worked, and then screensaver activate - same error.
Other companion remote commands work.

Not an OS16 thing?

**Comment by maxileith** [comment]
Hi guys,

I have the exact same issue. The command always fails, no matter if the ATV is turned on or off.

```bash
❯ ./user_storage/appletv-enhanced/.venv/bin/atvremote --scan-hosts "192.168.0.15" --companion-credentials `cat ./user_storage/appletv-enhanced/XXXXXXXXXXXX/credentials.txt` --airplay-credentials `cat ./user_storage/appletv-enhanced/XXXXXXXXXXXX/credentials.txt` screensaver
Traceback (most recent call last):
  File "/home/maxileith/.pyenv/versions/3.13.0/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/maxileith/.pyenv/versions/3.13.0/lib/python3.13/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/maxileith/Downloads/homebridge-appletv-enhanced/user_storage/appletv-enhanced/.venv/lib/python3.13/site-packages/pyatv/protocols/companion/api.py", line 172, in _send_command
    resp = await self._protocol.exchange_opack(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/home/maxileith/Downloads/homebridge-appletv-enhanced/user_storage/appletv-enhanced/.venv/lib/python3.13/site-packages/pyatv/protocols/companion/protocol.py", line 153, in exchange_opack
    return await self._exchange_generic_opack(frame_type, data, identifier, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxileith/Downloads/homebridge-appletv-enhanced/user_storage/appletv-enhanced/.venv/lib/python3.13/site-packages/pyatv/protocols/companion/protocol.py", line 166, in _exchange_generic_opack
    unpacked_object = await self._queues[identifier].wait(timeout)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxileith/Downloads/homebridge-appletv-enhanced/user_storage/appletv-enhanced/.venv/lib/python3.13/site-packages/pyatv/support/collections.py", line 161, in wait
    await asyncio.wait_for(self._event.wait(), timeout)
  File "/home/maxileith/.pyenv/versions/3.13.0/lib/python3.13/asyncio/tasks.py", line 506, in wait_for
    async with timeouts.timeout(timeout):
               ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/maxileith/.pyenv/versions/3.13.0/lib/python3.13/asyncio/timeouts.py", line 116, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/maxileith/Downloads/homebridge-appletv-enhanced/user_storage/appletv-enhanced/.venv/lib/python3.13/site-packages/pyatv/scripts/atvremote.py", line 997, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxileith/Downloads/homebridge-appletv-enhanced/user_storage/appletv-enhanced/.venv/lib/python3.13/site-packages/pyatv/scripts/atvremote.py", line 726, in cli_handler
    return await _handle_commands(args, config, storage, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxileith/Downloads/homebridge-appletv-enhanced/user_storage/appletv-enhanced/.venv/lib/python3.13/site-packages/pyatv/scripts/atvremote.py", line 876, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, storage, loop)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxileith/Downloads/homebridge-appletv-enhanced/user_storage/appletv-enhanced/.venv/lib/python3.13/site-packages/pyatv/scripts/atvremote.py", line 919, in _handle_device_command
    return await _exec_command(atv.remote_control, cmd, True, *cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxileith/Downloads/homebridge-appletv-enhanced/user_storage/appletv-enhanced/.venv/lib/python3.13/site-packages/pyatv/scripts/atvremote.py", line 964, in _exec_command
    value = await tmp(*args)
            ^^^^^^^^^^^^^^^^
  File "/home/maxileith/Downloads/homebridge-appletv-enhanced/user_storage/appletv-enhanced/.venv/lib/python3.13/site-packages/pyatv/core/facade.py", line 194, in screensaver
    return await self.relay("screensaver")()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxileith/Downloads/homebridge-appletv-enhanced/user_storage/appletv-enhanced/.venv/lib/python3.13/site-packages/pyatv/protocols/companion/__init__.py", line 378, in screensaver
    await self._press_button(HidCommand.Screensaver)
  File "/home/maxileith/Downloads/homebridge-appletv-enhanced/user_storage/appletv-enhanced/.venv/lib/python3.13/site-packages/pyatv/protocols/companion/__init__.py", line 387, in _press_button
    await self.api.hid_command(True, command)
  File "/home/maxileith/Downloads/homebridge-appletv-enhanced/user_storage/appletv-enhanced/.venv/lib/python3.13/site-packages/pyatv/protocols/companion/api.py", line 290, in hid_command
    await self._send_command(
        "_hidC", {"_hBtS": 1 if down else 2, "_hidC": command.value}
    )
  File "/home/maxileith/Downloads/homebridge-appletv-enhanced/user_storage/appletv-enhanced/.venv/lib/python3.13/site-packages/pyatv/protocols/companion/api.py", line 183, in _send_command
    raise exceptions.ProtocolError(f"Command {identifier} failed") from ex
pyatv.exceptions.ProtocolError: Command _hidC failed

>>> An error occurred, full stack trace above
```

**Comment by maxileith** [comment]
fyi, I am connected via wifi. My ATV does not have an ethernet port so I cannot test via ethernet.
