### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by lorenzoCuevas** [postlund/pyatv#2379]
### Describe the bug

Hi,
I'm trying to run atvremote scan to pair with my Apple TV but I keep receiving this error:

### Error log

 atvremote scan
Traceback (most recent call last):
  File "/home/pi/.local/bin/atvremote", line 5, in <module>
    from pyatv.scripts.atvremote import main
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/__init__.py", line 18, in <module>
    from pyatv.core.scan import (
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/core/scan.py", line 39, in <module>
    from pyatv.helpers import get_unique_id
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/helpers.py", line 6, in <module>
    import miniaudio
  File "/home/pi/.local/lib/python3.9/site-packages/miniaudio.py", line 22, in <module>
    from _miniaudio import ffi, lib
ImportError: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /home/pi/.local/lib/python3.9/site-packages/_miniaudio.abi3.so)

### How to reproduce the bug?

atvremote scan

### What is expected behavior?

atvremote wizard
Looking for devices...
Found the following devices:
    Name                      Model                    Address
--  ------------------------  -----------------------  -----------
 1  Receiver+                 airupnp                  10.0.10.200
 2  Receiver                  RX-V773                  10.0.10.82
 3  Pierre's AirPort Express  AirPort Express (gen 2)  10.0.10.168
 4  FakeATV                   Unknown                  10.0.10.254
 5  Vardagsrum                Apple TV 4K              10.0.10.81
 6  Apple TV                  Apple TV 3               10.0.10.83
Enter index of device to set up (q to quit): 4
Starting to set up FakeATV
Starting to pair Protocol.MRP
Enter PIN on screen: 1111
Successfully paired Protocol.MRP, moving on...
Pairing finished, trying to connect and get some metadata...
Currently playing:
  Media type: Music
Device state: Playing
       Title: Never Gonna Give You Up
      Artist: Rick Astley
    Position: 1/213s (0.0%)
      Repeat: Off
     Shuffle: Off
Device is now set up!

### Operating System

Raspbian

### Python

Other

### pyatv

0.14.5

### Device

Apple TV HD 

### Additional context

is there any way to fix this?

**Comment by IsakTheHacker** [comment]
I think this issue is caused by running pyatv on a less supported platform. As you can see in the error log, pyatv depends on the package `miniaudio` (search it up on PyPI) which is a native module written in C. There are some precompiled wheels distributed directly from PyPI but perhaps not for your architecture. Since the error log says something about glibc 2.29 you could try installing that version and see if that resolves it. Also make sure that you have gcc installed properly on your Raspberry Pi. I'm here to help :)

**Comment by postlund** [comment]
The wheel for miniaudio is not compatible with your platform. It might work if you tell pip to not use the wheel but compile it from source instead.

https://stackoverflow.com/a/64650405

**Comment by postlund** [comment]
This might be fixed now, please give it a go (upgrade miniaudio).
