### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'EVP_CIPHER_CTX_ctrl'。macbook pro m1芯片笔记本，使用pyenv安装的python无法使用，

### ISSUE THREAD

**Issue by helberg1984** [postlund/pyatv#2451]
### Describe the bug

你好，感谢开发付出！
我使用macbook pro m1芯片笔记本，用pyenv安装的3.11.9版本的python，运行atvremote wizard出现以下错误，我查了很多资料，不知道为什么。难道是因为芯片不兼容吗？还是其他什么问题，我重新安装了openssl，还有cryptography，没有什么用，一直报错。求助，感谢！

### Error log

-> % atvremote wizard
Traceback (most recent call last):
  File "/Users/Usermax/.pyenv/versions/3.12.4/bin/atvremote", line 5, in <module>
    from pyatv.scripts.atvremote import main
  File "/Users/Usermax/.pyenv/versions/3.12.4/lib/python3.12/site-packages/pyatv/__init__.py", line 26, in <module>
    from pyatv.protocols import PROTOCOLS
  File "/Users/Usermax/.pyenv/versions/3.12.4/lib/python3.12/site-packages/pyatv/protocols/__init__.py", line 10, in <module>
    from pyatv.protocols import airplay as airplay_proto
  File "/Users/Usermax/.pyenv/versions/3.12.4/lib/python3.12/site-packages/pyatv/protocols/airplay/__init__.py", line 28, in <module>
    from pyatv.protocols import mrp
  File "/Users/Usermax/.pyenv/versions/3.12.4/lib/python3.12/site-packages/pyatv/protocols/mrp/__init__.py", line 14, in <module>
    from pyatv.auth.hap_srp import SRPAuthHandler
  File "/Users/Usermax/.pyenv/versions/3.12.4/lib/python3.12/site-packages/pyatv/auth/hap_srp.py", line 27, in <module>
    from pyatv.support import chacha20, log_binary, opack
  File "/Users/Usermax/.pyenv/versions/3.12.4/lib/python3.12/site-packages/pyatv/support/chacha20.py", line 4, in <module>
    from chacha20poly1305_reuseable import ChaCha20Poly1305Reusable as ChaCha20Poly1305
  File "src/chacha20poly1305_reuseable/__init__.py", line 21, in init chacha20poly1305_reuseable
AttributeError: module 'lib' has no attribute 'EVP_CIPHER_CTX_ctrl'

### How to reproduce the bug?

这是占位文字。

### What is expected behavior?

这是占位文字。

### Operating System

macos

### Python

3.11

### pyatv

0.14.5

### Device

home pod mini

### Additional context

这是占位文字。

**Comment by postlund** [comment]
Please rewrite issue in English.

**Comment by helberg1984** [comment]
Hello, thank you for your hard work!

I am using a MacBook Pro with an M1 chip and have installed Python version 3.11.9 using pyenv. When running `atvremote wizard`, the following error occurs. I have searched a lot of resources but don't know why. Could it be due to chip incompatibility? Or is it something else? I have reinstalled OpenSSL and cryptography, but it hasn't helped, and the error persists. Please help, thank you!

**Comment by NebzHB** [comment]
Dears,

I'm having the same issue with current stable branch : 

```
Traceback (most recent call last):
File "/var/www/html/plugins/aTVremote/resources/atvremote/bin/atvremote", line 5, in <module>
from pyatv.scripts.atvremote import main
File "/var/www/html/plugins/aTVremote/resources/atvremote/lib/python3.9/site-packages/pyatv/__init__.py", line 26, in <module>
from pyatv.protocols import PROTOCOLS
File "/var/www/html/plugins/aTVremote/resources/atvremote/lib/python3.9/site-packages/pyatv/protocols/__init__.py", line 10, in <module>
from pyatv.protocols import airplay as airplay_proto
File "/var/www/html/plugins/aTVremote/resources/atvremote/lib/python3.9/site-packages/pyatv/protocols/airplay/__init__.py", line 28, in <module>
from pyatv.protocols import mrp
File "/var/www/html/plugins/aTVremote/resources/atvremote/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 14, in <module>
from pyatv.auth.hap_srp import SRPAuthHandler
File "/var/www/html/plugins/aTVremote/resources/atvremote/lib/python3.9/site-packages/pyatv/auth/hap_srp.py", line 27, in <module>
from pyatv.support import chacha20, log_binary, opack
File "/var/www/html/plugins/aTVremote/resources/atvremote/lib/python3.9/site-packages/pyatv/support/chacha20.py", line 4, in <module>
from chacha20poly1305_reuseable import ChaCha20Poly1305Reusable as ChaCha20Poly1305
File "src/chacha20poly1305_reuseable/__init__.py", line 21, in init chacha20poly1305_reuseable
AttributeError: module 'lib' has no attribute 'EVP_CIPHER_CTX_ctrl'
```

**Comment by arnog23** [comment]
Hello,

Same issue for me with the latest version.

```
Traceback (most recent call last):
File "/var/www/html/plugins/aTVremote/resources/atvremote/bin/atvremote", line 5, in <module>
from pyatv.scripts.atvremote import main
File "/var/www/html/plugins/aTVremote/resources/atvremote/lib/python3.9/site-packages/pyatv/__init__.py", line 26, in <module>
from pyatv.protocols import PROTOCOLS
File "/var/www/html/plugins/aTVremote/resources/atvremote/lib/python3.9/site-packages/pyatv/protocols/__init__.py", line 10, in <module>
from pyatv.protocols import airplay as airplay_proto
File "/var/www/html/plugins/aTVremote/resources/atvremote/lib/python3.9/site-packages/pyatv/protocols/airplay/__init__.py", line 28, in <module>
from pyatv.protocols import mrp
File "/var/www/html/plugins/aTVremote/resources/atvremote/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 14, in <module>
from pyatv.auth.hap_srp import SRPAuthHandler
File "/var/www/html/plugins/aTVremote/resources/atvremote/lib/python3.9/site-packages/pyatv/auth/hap_srp.py", line 27, in <module>
from pyatv.support import chacha20, log_binary, opack
File "/var/www/html/plugins/aTVremote/resources/atvremote/lib/python3.9/site-packages/pyatv/support/chacha20.py", line 7, in <module>
from chacha20poly1305_reuseable import ChaCha20Poly1305Reusable as ChaCha20Poly1305
File "src/chacha20poly1305_reuseable/__init__.py", line 21, in init chacha20poly1305_reuseable
AttributeError: module 'lib' has no attribute 'EVP_CIPHER_CTX_ctrl'
```

**Comment by postlund** [comment]
@bdraco Have you experienced this?

**Comment by bdraco** [comment]
bump cryptography to 43.0.0 and bump chacha20poly1305_reuseable to the latest

**Comment by bdraco** [comment]
There is a breaking change in cryptography 43.0.0

**Comment by postlund** [comment]
Ah, great! I will bump lowest supported versions!

**Comment by postlund** [comment]
I just merged #2458 that should fix this. Please give it a spin.

**Comment by NebzHB** [comment]
indeed, it works :) thx for quick reaction !

**Comment by arnog23** [comment]
Thanks for fixing it quickly.

**Comment by PuzzledUser** [comment]
I just first time installed pyatv with  `pip3 install pyatv` and ran `/home/pi/.local/bin/atvremote scan` and got an error chain with the same concluding error:
```
/home/pi/.local/lib/python3.7/site-packages/pyatv/auth/hap_srp.py:10: CryptographyDeprecationWarning: Python 3.7 is no longer supported by the Python core team and support for it is deprecated in cryptography. A future release of cryptography will remove support for Python 3.7.
  from cryptography.exceptions import InvalidSignature
Traceback (most recent call last):
  File "/home/pi/.local/bin/atvremote", line 6, in <module>
    from pyatv.scripts.atvremote import main
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/__init__.py", line 24, in <module>
    from pyatv.protocols import PROTOCOLS
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/protocols/__init__.py", line 10, in <module>
    from pyatv.protocols import airplay as airplay_proto
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/protocols/airplay/__init__.py", line 28, in <module>
    from pyatv.protocols import mrp
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/protocols/mrp/__init__.py", line 11, in <module>
    from pyatv.auth.hap_srp import SRPAuthHandler
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/auth/hap_srp.py", line 27, in <module>
    from pyatv.support import chacha20, log_binary
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/support/chacha20.py", line 2, in <module>
    from chacha20poly1305_reuseable import ChaCha20Poly1305Reusable as ChaCha20Poly1305
  File "src/chacha20poly1305_reuseable/__init__.py", line 22, in init chacha20poly1305_reuseable
AttributeError: module 'lib' has no attribute 'EVP_CIPHER_CTX_ctrl'
```
Running without parameters (or with --version, --help, -h etc) bombs in the same way. Is this related, or a different issue I should raise?

**Comment by postlund** [comment]
@PuzzledUser Probably yes. You are also running an old and unsupported version on python and that might be part of the problem (the required versions of dependencies of pyatv might not be compatible).

**Comment by PuzzledUser** [comment]
@postlund thanks: 
```
$ pip3 show cryptography
Name: cryptography
Version: 44.0.0
Summary: cryptography is a package which provides cryptographic recipes and primitives to Python developers.
Home-page: None
Author: The cryptography developers <cryptography-dev@python.org>
Author-email: The Python Cryptographic Authority and individual contributors <cryptography-dev@python.org>
License: Apache-2.0 OR BSD-3-Clause
Location: /home/pi/.local/lib/python3.7/site-packages
Requires: cffi
Required-by: pyatv, chacha20poly1305-reuseable
```
OK, so I wonder which package of those just installed are not right

**Comment by postlund** [comment]
@PuzzledUser Yoh need to upgrade chacha20poly1305_reuseable as well.

@bdraco If I understand correctly, chacha20poly1305_reuseable is not really needed anymore as the functionality has been merged back to cryptography, right?
