### ISSUE TITLE
Pairing not allowed, even though allow access: Everyone

### ISSUE THREAD

**Issue by astubbs** [postlund/pyatv#2495]
### What do you need help with?

Version: 0.15.0

Trying to use https://github.com/maxileith/homebridge-appletv-enhanced, but can't pair: "Pairing not allowed". Here's my issue report: https://github.com/maxileith/homebridge-appletv-enhanced/issues/459.

So I thought I'd try get `pyatv` working directly. Same error.

I have the Apple TV, under settings, AirPlay and HomeKit: Allow Access: Everyone.

```
astubbs@TONYSM2 ~/D/minidsp.arm64-apple-darwin [SIGINT]> atvremote wizard -v --debug
2024-09-05 12:00:43 DEBUG [pyatv.scripts]: Running with pyatv 0.15.0
2024-09-05 12:00:43 DEBUG [pyatv.storage.file_storage]: Loading settings from /Users/astubbs/.pyatv.conf
Looking for devices...
2024-09-05 12:00:43 DEBUG [pyatv.support.net]: Binding on *:5353
2024-09-05 12:00:43 DEBUG [pyatv.support.net]: Binding on 127.0.0.1:0
2024-09-05 12:00:43 DEBUG [pyatv.support.net]: Binding on 192.168.1.244:0
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered TV Sony at 192.168.1.152:7000 via Protocol.AirPlay ({'acl': '0', 'deviceid': '7D:9F:06:FC:2E:66', 'features': '0x7F8AD0,0x18BCF46', 'fex': '0Ip/AEbPiwFABA', 'rsf': '0x3', 'fv': 'p20.6.7546.0865', 'at': '0x1', 'flags': '0x644', 'model': 'XR-98X90L', 'integrator': 'SONY', 'manufacturer': 'Sony', 'serialnumber': '1920211', 'protovers': '1.1', 'srcvers': '377.40.00', 'pi': '7D:9F:06:FC:2E:66', 'psi': '00000000-0000-0000-0000-7D9F06FC2E66', 'gid': '00000000-0000-0000-0000-7D9F06FC2E66', 'gcgl': '0', 'pk': '06b4b8a93c30492ee69c4355540e9968d7280f5d3cc804f875dd7635e6909c26'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered Lounge at 192.168.1.156:49153 via Protocol.Companion ({'rpmac': '1', 'rphn': '2770fa6b26de', 'rpfl': '0x627B2', 'rpha': 'fc25b881a472', 'rpmd': 'AudioAccessory1,1', 'rpvr': '580.4', 'rpad': '1fa6522d6ad6', 'rphi': 'de1c5bf7696c', 'rpba': 'C6:52:A5:86:4E:31'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered Lounge at 192.168.1.156:7000 via Protocol.AirPlay ({'acl': '0', 'btaddr': '7D:20:2C:A0:7D:7E', 'deviceid': 'D4:90:9C:D2:0E:A7', 'c': '1', 'fex': 'AMp/StBLNbwQoQY', 'features': '0x4A7FCA00,0xBC354BD0', 'flags': '0x88404', 'gid': 'F2ECBD5D-221F-4C6D-827D-A40690D5E411+94696A8D-791C-4551-8693-2C97D8ADF2CC', 'igl': '1', 'gcgl': '1', 'model': 'AudioAccessory1,1', 'protovers': '1.1', 'pi': '28e33079-3777-4e05-8790-85c47dacb359', 'psi': 'F92F7E2C-1DD0-42BD-A127-8FBAEA1EFAFD', 'pk': 'b57bbea85a78dbbe2bceddf9a8aa55e532e39baad83824938d847261a037d5d0', 'srcvers': '775.3.1', 'osvers': '17.6', 'vv': '1'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered D4909CD20EA7@Lounge at 192.168.1.156:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x4A7FCA00,0xBC354BD0', 'sf': '0x88404', 'md': '0,1,2', 'am': 'AudioAccessory1,1', 'pk': 'b57bbea85a78dbbe2bceddf9a8aa55e532e39baad83824938d847261a037d5d0', 'tp': 'UDP', 'vn': '65537', 'vs': '775.3.1', 'ov': '17.6', 'vv': '1'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered 800A805C7A48@Z9X PRO(Living room) at 192.168.1.26:9581 via Protocol.RAOP ({'vv': '2', 'ss': '16', 'sv': 'false', 'ch': '2', 'pw': 'false', 'cn': '0,1,2,3', 'am': 'AppleTV2,1', 'ft': '0x5A7FDE00,0x1E', 'et': '0,3,5', 'rhd': '5.6.0.0', 'txtvers': '1', 'sf': '0x4', 'md': '0,1,2', 'vn': '65537', 'pk': 'b07727d6f6cd6e08b58ede525ec3cdeaa252ad9f683feb212ef8a205246554e7', 'tp': 'UDP', 'da': 'true', 'vs': '220.68', 'sr': '44100'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered Z9X PRO(Living room) at 192.168.1.26:9580 via Protocol.AirPlay ({'vv': '2', 'ss': '16', 'ch': '2', 'pw': '0', 'flags': '0x4', 'srcvers': '220.68', 'cn': '0,1,2,3', 'deviceid': '80:0A:80:5C:7A:48', 'rhd': '2.1.0.0', 'features': '0x5A7FDE00,0x1E', 'md': '0,1,2', 'pi': '2e388006-13ba-4041-9a67-25dd4a43d536', 'model': 'AppleTV3,1', 'pk': '0a4809a0076e28b31d6569675d8b21113409b06159aadf077d6110ac022830a2', 'sr': '44100'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered Antony’s M2 MacBook Pro (2) at 192.168.1.244:7000 via Protocol.AirPlay ({'act': '2', 'acl': '0', 'deviceid': '5C:E9:1E:C1:62:26', 'fex': '1c9/St5PF7g2IQQ', 'features': '0x4A7FCFD5,0xB8174FDE', 'rsf': '0x8', 'flags': '0x204', 'gid': '17061FA3-22E4-4960-8FCB-4244A430B591', 'igl': '0', 'gcgl': '0', 'model': 'Mac14,10', 'at': '4', 'protovers': '1.1', 'pi': '00000000-0000-0000-0000-f099b637d793', 'psi': '3FB27F0C-76C8-4F08-A104-AA046854D4BC', 'pk': '6707b57750e650a18d2641e75f9c384dee116f6b6ec773f63caff7eaf323a3d8', 'srcvers': '775.3.1'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered Antony’s M2 MacBook Pro at 192.168.1.244:55606 via Protocol.Companion ({'rpmac': '0', 'rphn': '2ae1937a5d66', 'rpfl': '0x20000', 'rpha': 'af9b0398e997', 'rpvr': '580.4', 'rpad': '233e301f7201', 'rphi': 'ffc8561c1dd4', 'rpba': 'AE:D6:8E:56:5C:11'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered 5CE91EC16226@Antony’s M2 MacBook Pro (2) at 192.168.1.244:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x4A7FCFD5,0xB8174FDE', 'sf': '0x204', 'md': '0,1,2', 'am': 'Mac14,10', 'pk': '6707b57750e650a18d2641e75f9c384dee116f6b6ec773f63caff7eaf323a3d8', 'tp': 'UDP', 'vn': '65537', 'vs': '775.3.1', 'vv': '0'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered Denon AVC-X3800H at 192.168.1.17:7000 via Protocol.AirPlay ({'acl': '0', 'deviceid': '00:06:78:C8:DE:D3', 'features': '0x445F8A00,0x1C340', 'rsf': '0x0', 'fv': 'p20.3.34.240', 'flags': '0x404', 'model': 'Denon AVC-X3800H', 'manufacturer': 'Denon', 'serialnumber': 'DBYQ102203864', 'protovers': '1.1', 'srcvers': '366.0', 'pi': '00:06:78:C8:DE:D3', 'gid': '00:06:78:C8:DE:D3', 'gcgl': '0', 'pk': 'd5fea4a74c8ca148526020ba0c5fe01bae78fbee20409bf70f0d117dd5b11997'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered 000678C8DED3@Denon AVC-X3800H at 192.168.1.17:7000 via Protocol.RAOP ({'cn': '0,1', 'da': 'true', 'et': '0,4', 'ft': '0x445F8A00,0x1C340', 'fv': 'p20.3.34.240', 'md': '0,1,2', 'am': 'Denon AVC-X3800H', 'sf': '0x404', 'tp': 'UDP', 'vn': '65537', 'vs': '366.0', 'pk': 'd5fea4a74c8ca148526020ba0c5fe01bae78fbee20409bf70f0d117dd5b11997'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered Kitchen at 192.168.1.93:49153 via Protocol.Companion ({'rpmac': '1', 'rphn': 'f8c5999a101a', 'rpfl': '0x627B2', 'rpha': 'c4805ab81e88', 'rpmd': 'AudioAccessory1,1', 'rpvr': '580.4', 'rpad': 'b5e084e25ea8', 'rphi': '76a80ce5093e', 'rpba': 'EF:56:3A:C2:FF:C3'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered Kitchen at 192.168.1.93:7000 via Protocol.AirPlay ({'acl': '0', 'btaddr': '71:DA:60:FB:06:13', 'deviceid': 'D4:90:9C:D8:54:77', 'c': '1', 'fex': 'AMp/StBLNbwQoQY', 'features': '0x4A7FCA00,0xBC354BD0', 'flags': '0x88404', 'gid': 'F0E035D6-FF25-461D-96D9-45A164986D71+C20FAAC7-60A5-4D14-A860-AA1025D2964E', 'igl': '1', 'gcgl': '1', 'model': 'AudioAccessory1,1', 'protovers': '1.1', 'pi': 'd1a875f4-ee1c-4cb8-a539-a77c997bc0e2', 'psi': '5D6BF6CC-5B98-4F80-8DCA-56817165D3DC', 'pk': 'a460d975e563ebda007977d104736c09056424f9fa75ce02b28961efb68a33f9', 'srcvers': '775.3.1', 'osvers': '17.6', 'vv': '1'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered D4909CD85477@Kitchen at 192.168.1.93:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x4A7FCA00,0xBC354BD0', 'sf': '0x88404', 'md': '0,1,2', 'am': 'AudioAccessory1,1', 'pk': 'a460d975e563ebda007977d104736c09056424f9fa75ce02b28961efb68a33f9', 'tp': 'UDP', 'vn': '65537', 'vs': '775.3.1', 'ov': '17.6', 'vv': '1'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered Bedroom at 192.168.1.167:7000 via Protocol.AirPlay ({'acl': '0', 'btaddr': '75:C7:FF:5F:43:A3', 'deviceid': '94:EA:32:88:34:6C', 'c': '1', 'fex': 'AMp/StBLNbwQoQY', 'features': '0x4A7FCA00,0xBC354BD0', 'flags': '0x98404', 'gid': '838D11F4-A98F-5A37-BE92-48BF07D79E58+1+5F816FBE-FBB0-4925-B1A6-A5A3194042C9', 'igl': '1', 'gcgl': '1', 'gpn': 'Bedroom', 'tsid': '838D11F4-A98F-5A37-BE92-48BF07D79E58', 'tsm': '1', 'model': 'AudioAccessory5,1', 'protovers': '1.1', 'pi': '40b5eec8-becc-41fd-a4e1-6b689543c6ff', 'psi': 'CF92ECD2-6566-45F7-9C8D-76BA9AA27B6E', 'pk': '9ec017e3b9c9c0c6cdccf3c53538860908fa7088ed99b595b6065da29f03b011', 'srcvers': '775.3.1', 'osvers': '17.6', 'vv': '1'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered Bedroom at 192.168.1.167:49154 via Protocol.Companion ({'rpmac': '2', 'rphn': '529fa02de837', 'rpfl': '0x627B2', 'rpha': 'cb77a9289956', 'rpmd': 'AudioAccessory5,1', 'rpvr': '580.4', 'rpad': '11717bcfa2d3', 'rphi': '2f9544344b8e', 'rpba': '95:02:8B:CC:42:AB'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered 94EA3288346C@Bedroom at 192.168.1.167:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x4A7FCA00,0xBC354BD0', 'sf': '0x98404', 'md': '0,1,2', 'am': 'AudioAccessory5,1', 'pk': '9ec017e3b9c9c0c6cdccf3c53538860908fa7088ed99b595b6065da29f03b011', 'tp': 'UDP', 'vn': '65537', 'vs': '775.3.1', 'ov': '17.6', 'vv': '1'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered Children’s at 192.168.1.249:49153 via Protocol.Companion ({'rpmac': '2', 'rphn': 'd5b65fc9d276', 'rpfl': '0x627B2', 'rpha': '073a96992187', 'rpmd': 'AudioAccessory5,1', 'rpvr': '580.4', 'rpad': 'a578815e9210', 'rphi': '8a1c6f8bda0f', 'rpba': '95:84:E8:35:94:0E'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered Children’s at 192.168.1.249:7000 via Protocol.AirPlay ({'acl': '0', 'btaddr': '62:CF:0D:43:0F:6C', 'deviceid': '94:EA:32:A9:12:E4', 'c': '1', 'fex': 'AMp/StBLNbwQoQY', 'features': '0x4A7FCA00,0xBC354BD0', 'flags': '0x9a404', 'gid': '838D11F4-A98F-5A37-BE92-48BF07D79E58+0+54A598CF-0E3F-453E-BE40-0B10882B1506', 'igl': '1', 'gcgl': '1', 'gpn': 'Bedroom', 'tsid': '838D11F4-A98F-5A37-BE92-48BF07D79E58', 'tsm': '1', 'model': 'AudioAccessory5,1', 'protovers': '1.1', 'pi': '53d24668-7c8b-4b1b-af9a-ca9ce77d1e7c', 'psi': '25FED78E-0102-4381-B27E-CD159A3784D3', 'pk': '7f802943570d83cb4ab8fe722119df72f1ab87172fbea667c710308e4904f603', 'srcvers': '775.3.1', 'osvers': '17.6', 'vv': '1'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered 94EA32A912E4@Children’s at 192.168.1.249:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x4A7FCA00,0xBC354BD0', 'sf': '0x9a404', 'md': '0,1,2', 'am': 'AudioAccessory5,1', 'pk': '7f802943570d83cb4ab8fe722119df72f1ab87172fbea667c710308e4904f603', 'tp': 'UDP', 'vn': '65537', 'vs': '775.3.1', 'ov': '17.6', 'vv': '1'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered Hal 9001 at 192.168.1.60:49153 via Protocol.Companion ({'rpmac': '1', 'rphn': '0955ba8a5dd3', 'rpfl': '0xB67A2', 'rpha': 'd3b0d290f13a', 'rpmd': 'AppleTV6,2', 'rpvr': '580.4', 'rpad': '048fd19a8d7a', 'rphi': 'f52e4cce36a6', 'rpba': '8F:69:25:F4:78:CD', 'rpmrtid': '91E41E97-2568-4C48-8BCA-90CE25A98F28'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered Hal 9001 at 192.168.1.60:7000 via Protocol.AirPlay ({'acl': '0', 'btaddr': '47:DE:68:15:BB:64', 'deviceid': 'DC:56:E7:56:60:1A', 'fex': '1d9/St5fF7w4oQY', 'features': '0x4A7FDFD5,0xBC175FDE', 'flags': '0x18644', 'gid': '32FFE23A-49A2-40C9-8718-FD030A5E8E82', 'igl': '1', 'gcgl': '1', 'model': 'AppleTV6,2', 'protovers': '1.1', 'pi': '3655021c-4ec6-4775-9ba5-87feb4ba7287', 'psi': '91E41E97-2568-4C48-8BCA-90CE25A98F28', 'pk': '0390fbb64e3033dd72e718d6f73755fa698fd687a73c3496ba925b48161dd80e', 'srcvers': '775.3.1', 'osvers': '17.6.1', 'vv': '1'})
2024-09-05 12:00:48 DEBUG [pyatv.protocols.mrp]: Disabling MRP service since tvOS >= 15
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered Hal 9001 at 192.168.1.60:49166 via Protocol.MRP ({'modelname': 'Apple TV', 'allowpairing': 'NO', 'bluetoothaddress': "b'\\xdcV\\xe7V`\\x19'", 'macaddress': 'dc:56:e7:56:60:1a', 'name': 'Hal 9001', 'uniqueidentifier': '5BBEFCD6-24D8-44BB-A424-A0E018EE830D', 'systembuildversion': '21M80', 'localairplayreceiverpairingidentity': '91E41E97-2568-4C48-8BCA-90CE25A98F28'})
2024-09-05 12:00:48 DEBUG [pyatv.core.scan]: Auto-discovered DC56E756601A@Hal 9001 at 192.168.1.60:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x4A7FDFD5,0xBC175FDE', 'sf': '0x18644', 'md': '0,1,2', 'am': 'AppleTV6,2', 'pk': '0390fbb64e3033dd72e718d6f73755fa698fd687a73c3496ba925b48161dd80e', 'tp': 'UDP', 'vn': '65537', 'vs': '775.3.1', 'ov': '17.6.1', 'vv': '1'})
Found the following devices:
    Name                         Model             Address
--  ---------------------------  ----------------  -------------
 1  TV Sony                      XR-98X90L         192.168.1.152
 2  Lounge                       HomePod           192.168.1.156
 3  Z9X PRO(Living room)         Apple TV 2        192.168.1.26
 4  Antony’s M2 MacBook Pro (2)  Mac14,10          192.168.1.244
 5  Denon AVC-X3800H             Denon AVC-X3800H  192.168.1.17
 6  Kitchen                      HomePod           192.168.1.93
 7  Bedroom                      HomePod Mini      192.168.1.167
 8  Children’s                   HomePod Mini      192.168.1.249
 9  Hal 9001                     Apple TV 4K       192.168.1.60
Enter index of device to set up (q to quit): 9
Starting to set up Hal 9001
Starting to pair Protocol.Companion
2024-09-05 12:00:55 DEBUG [pyatv.protocols.companion.pairing]: Start pairing Companion
2024-09-05 12:00:55 DEBUG [pyatv.protocols.companion.connection]: Connected to companion device 192.168.1.60:49153
2024-09-05 12:00:55 DEBUG [pyatv.protocols.companion.protocol]: Companion credentials: None
2024-09-05 12:00:55 DEBUG [pyatv.protocols.companion.protocol]: Exchange OPACK: {'_pd': b'\x00\x01\x00\x06\x01\x01', '_pwTy': 1}
2024-09-05 12:00:55 DEBUG [pyatv.protocols.companion.protocol]: Send OPACK: {'_pd': b'\x00\x01\x00\x06\x01\x01', '_pwTy': 1, '_x': 37381}
2024-09-05 12:00:55 DEBUG [pyatv.protocols.companion.connection]: >> Send data (Data=e3435f706476000100060101455f7077547909425f78310592, FrameType=03)
2024-09-05 12:00:55 DEBUG [pyatv.protocols.companion.connection]: Received data (Data=04000020e2435f65633188e5435f656d5350616972696e67206e6f7420616c6c6f776564)
2024-09-05 12:00:55 DEBUG [pyatv.protocols.companion.protocol]: Received frame FrameType.PS_Next: b'\xe2C_ec1\x88\xe5C_emSPairing not allowed'
2024-09-05 12:00:55 DEBUG [pyatv.protocols.companion.protocol]: Process incoming auth frame (FrameType.PS_Next): {'_ec': 58760, '_em': 'Pairing not allowed'}
Traceback (most recent call last):
  File "/Users/astubbs/.local/pipx/venvs/pyatv/lib/python3.12/site-packages/pyatv/support/__init__.py", line 71, in error_handler
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/astubbs/.local/pipx/venvs/pyatv/lib/python3.12/site-packages/pyatv/protocols/companion/auth.py", line 54, in start_pairing
    resp = await self.protocol.exchange_auth(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/astubbs/.local/pipx/venvs/pyatv/lib/python3.12/site-packages/pyatv/protocols/companion/protocol.py", line 141, in exchange_auth
    return await self._exchange_generic_opack(frame_type, data, identifier, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/astubbs/.local/pipx/venvs/pyatv/lib/python3.12/site-packages/pyatv/protocols/companion/protocol.py", line 174, in _exchange_generic_opack
    raise exceptions.ProtocolError(f"Command failed: {unpacked_object['_em']}")
pyatv.exceptions.ProtocolError: Command failed: Pairing not allowed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/astubbs/.local/pipx/venvs/pyatv/lib/python3.12/site-packages/pyatv/scripts/atvremote.py", line 997, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/astubbs/.local/pipx/venvs/pyatv/lib/python3.12/site-packages/pyatv/scripts/atvremote.py", line 720, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/astubbs/.local/pipx/venvs/pyatv/lib/python3.12/site-packages/pyatv/scripts/atvremote.py", line 964, in _exec_command
    value = await tmp(*args)
            ^^^^^^^^^^^^^^^^
  File "/Users/astubbs/.local/pipx/venvs/pyatv/lib/python3.12/site-packages/pyatv/scripts/atvremote.py", line 286, in wizard
    await self._wizard_pair(conf, service)
  File "/Users/astubbs/.local/pipx/venvs/pyatv/lib/python3.12/site-packages/pyatv/scripts/atvremote.py", line 341, in _wizard_pair
    await pairing.begin()
  File "/Users/astubbs/.local/pipx/venvs/pyatv/lib/python3.12/site-packages/pyatv/protocols/companion/pairing.py", line 48, in begin
    await error_handler(
  File "/Users/astubbs/.local/pipx/venvs/pyatv/lib/python3.12/site-packages/pyatv/support/__init__.py", line 77, in error_handler
    raise fallback(str(ex)) from ex
pyatv.exceptions.PairingError: Command failed: Pairing not allowed

>>> An error occurred, full stack trace above
2024-09-05 12:00:55 ERROR [asyncio]: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x106f559d0>
astubbs@TONYSM2 ~/D/minidsp.arm64-apple-darwin [1]>
```

**Comment by astubbs** [comment]
Ah ha! Found this gem here, all good now! https://github.com/home-assistant/core/issues/113374#issuecomment-2048378316
