### ISSUE TITLE
Error in HA logs

### ISSUE THREAD

**Issue by sayam93** [postlund/pyatv#2582]
### Describe the bug

Saw the error in my HA logs. Also, volume control from HA doesn't work.

### Error log

```log
Logger: pyatv.core.protocol
Source: /usr/local/lib/python3.13/site-packages/pyatv/core/protocol.py:110
First occurred: 3:32:21 PM (1 occurrences)
Last logged: 3:32:21 PM

error during dispatch
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pyatv/protocols/companion/api.py", line 172, in _send_command
    resp = await self._protocol.exchange_opack(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pyatv/protocols/companion/protocol.py", line 153, in exchange_opack
    return await self._exchange_generic_opack(frame_type, data, identifier, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyatv/protocols/companion/protocol.py", line 166, in _exchange_generic_opack
    unpacked_object = await self._queues[identifier].wait(timeout)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyatv/support/collections.py", line 161, in wait
    await asyncio.wait_for(self._event.wait(), timeout)
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 506, in wait_for
    async with timeouts.timeout(timeout):
               ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/timeouts.py", line 116, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pyatv/core/protocol.py", line 106, in _call_listener
    await func
  File "/usr/local/lib/python3.13/site-packages/pyatv/protocols/companion/__init__.py", line 421, in _handle_control_flag_update
    resp = await self.api.mediacontrol_command(MediaControlCommand.GetVolume)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyatv/protocols/companion/api.py", line 382, in mediacontrol_command
    return await self._send_command("_mcc", {"_mcc": command.value, **(args or {})})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyatv/protocols/companion/api.py", line 183, in _send_command
    raise exceptions.ProtocolError(f"Command {identifier} failed") from ex
pyatv.exceptions.ProtocolError: Command _mcc failed
```

### How to reproduce the bug?

Error in HA Logs

### What is expected behavior?

Error in HA Logs

### Operating System

HAOS 14

### Python

3.13

### pyatv

0.16.0

### Device

Apple TV 4K tvOS 18

### Additional context

I got this error in my logs in HA Core 2024.12.0

**Comment by sayam93** [comment]
@postlund

**Comment by madonzy** [comment]
I have the same error

**Comment by madonzy** [comment]
also, Apple TV integration worked fine, but then I ran one automation that by mistake, streamed from two sources (TTS and Radio), and after that I was not able to AirPlay from HA to my AppleTV. Restart of HA and AppleTV didn't help. Also, reinstalling AppleTV integration didn't help.
