### ISSUE TITLE
Pairing is required for AirPlay

### ISSUE THREAD

**Issue by glassbase** [postlund/pyatv#283]
**Describe the bug**
Integration asks MRP code which displays on TV and goes away... then “Pairing is required for AirPlay. Please input a PIN code displayed on screen.” I don’t get prompt on TV for this code. 

**To Reproduce**
See above

**Expected behavior**
Code prompt
Or some other workaround?

**System Setup (please complete the following information):**
 - OS: [e.g. Debian] Docker, HA 0.102.2
 - Python: [e.g. 3.6.2] 3.7.4
 - pyatv: [e.g. 0.3.10] 4

**Additional context**
None

**Comment by postlund** [comment]
Can you get some debug logs? It's hard to tell what is happening otherwise.

**Comment by glassbase** [comment]
```
2019-11-26 09:27:25 WARNING (MainThread) [pyatv] Failed to resolve _airplay._tcp.local. (Pioneer._airplay._tcp.local.)
2019-11-26 09:27:34 ERROR (MainThread) [custom_components.apple_tv.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/apple_tv/config_flow.py", line 177, in async_step_pair_with_pin
    return await self.async_begin_pairing()
  File "/config/custom_components/apple_tv/config_flow.py", line 133, in async_begin_pairing
    await self._pairing.close()
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/pairing.py", line 32, in close
    await self.connection.close()
TypeError: object NoneType can't be used in 'await' expression
2019-11-26 09:27:53 ERROR (MainThread) [custom_components.apple_tv.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/apple_tv/config_flow.py", line 175, in async_step_pair_with_pin
    await self._pairing.finish()
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/pairing.py", line 50, in finish
    str(await self.pairing_procedure.finish_pairing(self.pin_code))
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/auth.py", line 61, in finish_pairing
    msg, generate_identifier=False)
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/protocol.py", line 145, in send_and_receive
    await self._connect_and_encrypt()
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/protocol.py", line 122, in _connect_and_encrypt
    await self.start()
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/protocol.py", line 71, in start
    await self.send_and_receive(msg)
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/protocol.py", line 145, in send_and_receive
    await self._connect_and_encrypt()
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/protocol.py", line 133, in _connect_and_encrypt
    await pair_verifier.verify_credentials()
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/auth.py", line 99, in verify_credentials
    msg, generate_identifier=False)
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/protocol.py", line 161, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/protocol.py", line 170, in _receive
    semaphore.acquire(), timeout, loop=self.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

*I have a old Pioneer amp/receiver that has AirPlay but only the old version that only works with audio since iOS 8 or 9 or 10 - whenever Apple made the last major AirPlay changes. Not sure why it even appears in logs since I manually typed my AppleTV IP address into integrations prompt. Maybe it is a reason for this error?*

**Comment by postlund** [comment]
You see the same issue as in #279 #281. It is fixed in the update I just pushed. Please update the component and try again! 😄 

It's the same AirPlay service no matter what device (it's not a "special" Apple TV-version of AirPlay). So it will be found because of that. I might filter devices with only AirPlay available in the future, but for now you will see.

Before connecting, `pyatv` will scan for *all* devices and services it can find and pick out the one you want. This is how the Home Assistant component will handle if a device changes IP-address or port number for instance. So it is normal and expected behavior.

**Comment by glassbase** [comment]
Ok I will. I did check their issues but mine didn’t say the same error so I assumed it was something different. Will report back soon. Thanks

**Comment by glassbase** [comment]
Working now
