### ISSUE TITLE
Support continuous async scanning for devices

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#293]
**Short feature/function description**
Currently you must initiate a scan every time you want to find a device. It would be nice to have a callback-based scanning interface that continuously scan in the background and report back new devices as they are found. This would simplify re-discovery when a device "disappears", for instance after a reboot, as this  currently requires calling `pyatv.scan` with some interval until the device is found. Using the method described here would just call some function when the device is available again.

**What needs to be done?**

- [ ] Define listener interface, e.g. `interface.ScanListener`
- [ ] Either add a new method, e.g. `pyatv.scan_continuously` or add a `listener` argument to existing `pyatv.scan` method
- [ ] Add tests and documentation

**Is this a breaking change?**
No

**Anything else worth knowing?**
No

**Comment by jdebardi** [comment]
I'll comment here as my issue is almost directly related in that I've already done this feature out of band.

I have created a script run via cronjob which runs a scan and collects IP Address/Port/ID form my Apple TV's every minute in a local file.
Then my other scripts which send commands can use this cached data to avoid scan time.

My problem, is the latest atvremote (0.4.0a9) is now ignoring the Address/Port inputs and wasting time scanning anyway so my command inputs are VERY slow. It also means that in the case of an occasional failed scan, the command fails to be sent.

Can you please revert atvremote to not scan when it is passed Address/Port parameters (and ideally not require the ID in that case either as it's irrelevant)?

I'm using bash so have no interest in a direct pyatv implementation, atvremote worked fine for years until MRP came along (thanks Apple!).

So my command looks like this and takes 3-4 seconds to complete (should be instant);
`/usr/local/bin/atvremote  home_hold --address 10.11.12.205 --port 49152 --id 70F7A0EF-F01F-47B3-878C-6A3E61E41E11 --protocol mrp`

I want it to look like this;
`/usr/local/bin/atvremote  home_hold --address 10.11.12.205 --port 49152 --protocol mrp`


Thanks for all your work on this project!

**Comment by postlund** [comment]
Just specify `--manual` and you get the old behavior 👍

**Comment by postlund** [comment]
And I guess this should be added to the documentation for `atvremote` as well.

**Comment by jdebardi** [comment]
Amazing! Thanks! Yea I looked at --help but as you say, it's not mentioned.

There is still a significant delay even with --manual and it still requires the device id (crashes if not supplied)

`/usr/local/bin/atvremote  home_hold select --address 10.11.12.205 --port 49152 --protocol mrp --manual
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 533, in _run_application
    return await cli_handler(loop)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 364, in cli_handler
    return await _handle_commands(args, loop)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 442, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__init__.py", line 139, in connect
    raise exceptions.DeviceIdMissingError("no device identifier")
pyatv.exceptions.DeviceIdMissingError: no device identifier

>>> An error occurred, full stack trace above
`

**Comment by postlund** [comment]
Just specify anything as `--id` (it doesn't matter since you don't use it). After that it should work instantly as before.

**Comment by jdebardi** [comment]
Still a 3 second delay, but much better than a full scan time and saves finding the ID - thanks again.

`/usr/local/bin/atvremote  top_menu --address 10.11.12.205 --port 49152 --protocol mrp --id 123 --manual`

**Comment by postlund** [comment]
If you get a delay, then it's probably network related or something because there's no additional delay in`atvremote`. For me it works just fine:
```shell
$ time atvremote --address 10.0.10.81 --port 49152 --protocol mrp --id test playing --manual
Media type: Unknown
Play state: Idle

real 0m0.680s
user 0m0.600s
sys 0m0.040s
```
Try running with `--debug` to hunt it down.

**Comment by jdebardi** [comment]
All of the time is at startup before it prints anything - probably my python environment being slow for some reason. No worries, I'll live with it for now.

**Comment by postlund** [comment]
> All of the time is at startup before it prints anything - probably my python environment being slow for some reason. No worries, I'll live with it for now.

Yeah, if it's that early it's probably some host resolution issues or something. That's usually the case. Or something with IPv6.

**Comment by IsakTheHacker** [comment]
This is a really good idea! Is this still on the roadmap
