### ISSUE TITLE
Streaming cameras from HA doesn't work

### ISSUE THREAD

**Issue by dwradcliffe** [postlund/pyatv#313]
**Describe the bug**
Attempting to stream a camera from Home Assistant to my Apple TV. I get an error in Home Assistant.

```
2019-12-08 22:32:25 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139999896750672] Invalid file
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1236, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 348, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 372, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 687, in async_handle_play_stream_service
    DOMAIN_MP, SERVICE_PLAY_MEDIA, data, blocking=True, context=service_call.context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1236, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 348, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 372, in _handle_service_platform_call
    await func(entity, data)
  File "/config/custom_components/apple_tv/media_player.py", line 188, in async_play_media
    await self.atv.airplay.play_url(media_id)
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/__init__.py", line 68, in play_url
    return await player.play_url(url, position)
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/player.py", line 43, in play_url
    await self._wait_for_media_to_end()
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/player.py", line 60, in _wait_for_media_to_end
    parsed = plistlib.loads(data)
  File "/usr/local/lib/python3.7/plistlib.py", line 959, in loads
    fp, fmt=fmt, use_builtin_types=use_builtin_types, dict_type=dict_type)
  File "/usr/local/lib/python3.7/plistlib.py", line 944, in load
    raise InvalidFileException()
plistlib.InvalidFileException: Invalid file
```

**To Reproduce**

Call service: `camera.play_stream` with:
```
entity_id: camera.front_door
media_player: media_player.living_room_atv
```

**Expected behavior**

The stream should show up. I confirmed that it works if I run the same service with my Sony/Android TV as the media_player.

**System Setup (please complete the following information):**
 - OS: Host OS is Ubuntu, running inside official Home Assistant docker image (`homeassistant/home-assistant:0.102.3`)
 - Python: 3.7.4
 - pyatv: 0.4.0a9

**Comment by postlund** [comment]
AirPlay isssues has been reported in #209 as well, but it worked with `atvremote`. I'm not sure if the camera stream requires authentication (but I don't think so), maybe you could try to play the stream with `atvremote` so we can see if that works? You would have to add a log printout to pyatv (or in `play_media` in the component) yourself to get the URL or use wireshark to sniff it out.

**Comment by postlund** [comment]
See issue #315, should be related.

**Comment by Veldkornet** [comment]
FYI, I have no problems with this with version 5d0488c (pyatv: 0.4.0a9), all working fine. 

Tested with Foscam and Ubiquiti cameras.

**Comment by postlund** [comment]
Thanks for reporting @Veldkornet!

@dwradcliffe Can you try to remove the integration, make sure you have the latest update of the component, add it via Integrations again and make another try?

**Comment by Veldkornet** [comment]
So, it seems that I broke it :)
Now I also get an invalid file error.

It was working fine, then eventually after a couple of executions (of me showing off how well it works), it stopped. I have an automation that, if the doorbell rings (and the AppleTV is playing) then it will pause the AppleTV and stream the video from the door to the TV.  This was working perfectly... then all of a sudden stopped.... and I can't get it to work again.... rebooted HomeAssistant, rebooted the AppleTV... nada...

```
2019-12-10 20:36:04 ERROR (MainThread) [homeassistant.components.automation] Error while executing automation automation.doorbell_tv_on_stream_appletv. Unknown error for call_service at pos 2: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 437, in action
    await script_obj.async_run(variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 190, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 274, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 357, in _async_call_service
    context=context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 97, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1236, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 348, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 372, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 687, in async_handle_play_stream_service
    DOMAIN_MP, SERVICE_PLAY_MEDIA, data, blocking=True, context=service_call.context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1236, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 348, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 372, in _handle_service_platform_call
    await func(entity, data)
  File "/config/custom_components/apple_tv/media_player.py", line 188, in async_play_media
    await self.atv.airplay.play_url(media_id)
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/__init__.py", line 68, in play_url
    return await player.play_url(url, position)
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/player.py", line 43, in play_url
    await self._wait_for_media_to_end()
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/player.py", line 60, in _wait_for_media_to_end
    parsed = plistlib.loads(data)
  File "/usr/local/lib/python3.7/plistlib.py", line 959, in loads
    fp, fmt=fmt, use_builtin_types=use_builtin_types, dict_type=dict_type)
  File "/usr/local/lib/python3.7/plistlib.py", line 944, in load
    raise InvalidFileException()
plistlib.InvalidFileException: Invalid file
```

And if I just call the service directly in developer tools:

```
2019-12-10 20:47:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.547358827344] Invalid file
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1236, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 348, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 372, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 687, in async_handle_play_stream_service
    DOMAIN_MP, SERVICE_PLAY_MEDIA, data, blocking=True, context=service_call.context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1236, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 348, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 372, in _handle_service_platform_call
    await func(entity, data)
  File "/config/custom_components/apple_tv/media_player.py", line 188, in async_play_media
    await self.atv.airplay.play_url(media_id)
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/__init__.py", line 68, in play_url
    return await player.play_url(url, position)
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/player.py", line 43, in play_url
    await self._wait_for_media_to_end()
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/player.py", line 60, in _wait_for_media_to_end
    parsed = plistlib.loads(data)
  File "/usr/local/lib/python3.7/plistlib.py", line 959, in loads2019-12-10 20:47:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.547358827344] Invalid file
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1236, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 348, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 372, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 687, in async_handle_play_stream_service
    DOMAIN_MP, SERVICE_PLAY_MEDIA, data, blocking=True, context=service_call.context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1236, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 348, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 372, in _handle_service_platform_call
    await func(entity, data)
  File "/config/custom_components/apple_tv/media_player.py", line 188, in async_play_media
    await self.atv.airplay.play_url(media_id)
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/__init__.py", line 68, in play_url
    return await player.play_url(url, position)
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/player.py", line 43, in play_url
    await self._wait_for_media_to_end()
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/player.py", line 60, in _wait_for_media_to_end
    parsed = plistlib.loads(data)
  File "/usr/local/lib/python3.7/plistlib.py", line 959, in loads
    fp, fmt=fmt, use_builtin_types=use_builtin_types, dict_type=dict_type)
  File "/usr/local/lib/python3.7/plistlib.py", line 944, in load
    raise InvalidFileException()
plistlib.InvalidFileException: Invalid file
```

**Comment by postlund** [comment]
> So, it seems that I broke it :)
> Now I also get an invalid file error.
> 
> It was working fine, then eventually after a couple of executions (of me showing off how well it works), it stopped. I have an automation that, if the doorbell rings (and the AppleTV is playing) then it will pause the AppleTV and stream the video from the door to the TV. This was working perfectly... then all of a sudden stopped.... and I can't get it to work again.... rebooted HomeAssistant, rebooted the AppleTV... nada...

Pretty peculiar actually. The only thing I can really think of is that the Apple TV perhaps invalidate the credentials for some reason? Can you extract your airplay credentials from `core.config_entries` and try with `atvremote`, just to see what happens?

**Comment by Veldkornet** [comment]
Same thing with `atvremote`. I tried with the camera's rtsp url as well as a youtube url and a soundjay mp3 url, all the same error.

I will say that the first time I tried (after removing and re-adding the integration), I got no error. The screen just flashed black. then I tried again, and from then on all I got was the error below.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyatv/__main__.py", line 533, in _run_application
    return await cli_handler(loop)
  File "/usr/local/lib/python3.7/site-packages/pyatv/__main__.py", line 357, in cli_handler
    return await _handle_commands(args, loop)
  File "/usr/local/lib/python3.7/site-packages/pyatv/__main__.py", line 448, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/usr/local/lib/python3.7/site-packages/pyatv/__main__.py", line 486, in _handle_device_command
    atv.airplay, cmd, True, *cmd_args))
  File "/usr/local/lib/python3.7/site-packages/pyatv/__main__.py", line 499, in _exec_command
    value = await tmp(*args)
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/__init__.py", line 68, in play_url
    return await player.play_url(url, position)
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/player.py", line 43, in play_url
    await self._wait_for_media_to_end()
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/player.py", line 60, in _wait_for_media_to_end
    parsed = plistlib.loads(data)
  File "/usr/local/lib/python3.7/plistlib.py", line 959, in loads
    fp, fmt=fmt, use_builtin_types=use_builtin_types, dict_type=dict_type)
  File "/usr/local/lib/python3.7/plistlib.py", line 944, in load
    raise InvalidFileException()
plistlib.InvalidFileException: Invalid file
```

**Comment by postlund** [comment]
> Same thing with `atvremote`. I tried with the camera's rtsp url as well as a sample mp4 URL, Youtube URL and a .mp3 URL. The mp3 URL worked twice, then also started giving the same error, none of the video URL's worked, and gave the error below.
> 
> `atvremote -i <identifier> -n <name> --airplay-credentials <airplay_credentials> -v --debug play_url=https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_5mb.mp4`
> 
> `atvremote -i <identifier> -n <name> --airplay-credentials <airplay_credentials> -v --debug play_url=https://www.sample-videos.com/video123/mkv/720/big_buck_bunny_720p_5mb.mkv`
> 
> `atvremote -i <identifier> -n <name> --airplay-credentials <airplay_credentials> -v --debug play_url=https://www.sample-videos.com/video123/3gp/144/big_buck_bunny_144p_5mb.3gp`
> 
> `atvremote -i <identifier> -n <name> --airplay-credentials <airplay_credentials> -v --debug play_url=https://www.soundjay.com/ambient/boarding-accouncement-1.mp3`

I tried playing the last one (announcement mp3) a couple of times (manually aborting `atvremote` after a few seconds each time) and I can actually reproduce. Will see if I wan do anything with that. Maybe the device is in a "busy" state and can't accept AirPlay streams at the time, so it bails out.

> This one gave a different error, but I guess that's probably due to the format:
> 
> `atvremote -i <identifier> -n <name> --airplay-credentials <airplay_credentials> -v --debug play_url=https://www.sample-videos.com/video123/flv/720/big_buck_bunny_720p_5mb.flv`
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/pyatv/__main__.py", line 533, in _run_application
>     return await cli_handler(loop)
>   File "/usr/local/lib/python3.7/site-packages/pyatv/__main__.py", line 354, in cli_handler
>     if not await _autodiscover_device(args, loop):
>   File "/usr/local/lib/python3.7/site-packages/pyatv/__main__.py", line 376, in _autodiscover_device
>     args, args.scan_timeout, loop, protocol=args.protocol)
>   File "/usr/local/lib/python3.7/site-packages/pyatv/__main__.py", line 58, in _scan_for_device
>     return devices[0]
> IndexError: list index out of range
> ```

This can be seen as a bug, perhaps. It is a very odd case. It should mean that a device was found via its identifier by filtering was done on name afterwards, but the specified name did not match the actual name of the device.

**Comment by postlund** [comment]
Ok, so I don't know the underlying reason as to why this happens (but my educated guess is that the device is not ready/is in some strange state). As a hack I added a simple retry-loop that makes a few restart to stream if error code 500 is returned. It seemed to recover after the first failure, so hopefullt that is good enough. I can make a PR for this and maybe you can verify if it works (using `atvremote` to begin with, @Veldkornet?

**Comment by postlund** [comment]
PR @ #322 reset for testing. Should produce an error printout (for now) when the issue happens but immediately recover:
```shell
atvremote --airplay-credentials `cat aplay` --address 10.0.10.81 --port 49152 --protocol mrp --manual --id test play_url=https://www.soundjay.com/ambient/boarding-accouncement-1.mp3
ERROR: Failed to stream https://www.soundjay.com/ambient/boarding-accouncement-1.mp3, retrying
```

**Comment by Veldkornet** [comment]
So far so good! I was just testing with the `camera.play_stream` service as well as my automations, all working. My AppleTV did also update to tvOS 13.3 this morning, not sure if that also helped.
Also, I noticed the following in my logs, but the video played instantly every time without me seeing any types of pauses or anything:

```
2019-12-11 20:12:12 ERROR (MainThread) [pyatv.airplay.player] Failed to stream https://hassio.example.com:8123/api/hls/<some_long_string>/playlist.m3u8, retrying
2019-12-11 20:12:38 ERROR (MainThread) [pyatv.airplay.player] Failed to stream https://hassio.example.com:8123/api/hls/<some_long_string>/playlist.m3u8, retrying
2019-12-11 20:13:27 ERROR (MainThread) [pyatv.airplay.player] Failed to stream https://hassio.example.com:8123/api/hls/<some_long_string>/playlist.m3u8, retrying
2019-12-11 20:15:33 ERROR (MainThread) [pyatv.airplay.player] Failed to stream https://hassio.example.com:8123/api/hls/<some_long_string>/playlist.m3u8, retrying
```

**Comment by postlund** [comment]
Great, that probably means that it recovers after a few retries at least. I'm gonna add a short delay between each retry, add retry counter and change from ERROR to DEBUG log. I just used ERROR now to make it very clear in the log when a retry happened.

**Comment by postlund** [comment]
@dwradcliffe Can you update to the latest version of the component and try again? Hopefully it will work better now.

**Comment by postlund** [comment]
I believe this is fixed, re-open or write a new issue if problem persists.
