### ISSUE TITLE
DMAP monitoring unreliable since moving to Wi-Fi

### ISSUE THREAD

**Issue by nriley** [postlund/pyatv#346]
**Describe the bug**
Since I switched an Apple TV 3 from Ethernet to Wi-Fi, monitoring it via `atvremote` only seems to work about half the time.

**To Reproduce**
I am monitoring the Apple TV via:

`/usr/local/bin/atvremote --id [...] --dmap-credentials [...] --protocol dmap playing`

About half the time, it works:

```
On Sat, 28 Dec 2019 11:00:29, status succeeded (0) -- Media type: Unknown
Device state: Idle
    Shuffle: False.
```

The other half the time, I get:

```
On Sat, 28 Dec 2019 10:57:28, status failed (1) -- Traceback (most recent call last):
 File "/usr/local/lib/python3.5/dist-packages/pyatv/__main__.py", line 538, in _run_application
   return await cli_handler(loop)
 File "/usr/local/lib/python3.5/dist-packages/pyatv/__main__.py", line 367, in cli_handler
   return await _handle_commands(args, config, loop)
 File "/usr/local/lib/python3.5/dist-packages/pyatv/__main__.py", line 447, in _handle_commands
   atv = await connect(config, loop, protocol=args.protocol)
 File "/usr/local/lib/python3.5/dist-packages/pyatv/__init__.py", line 160, in connect
   await atv.connect()
 File "/usr/local/lib/python3.5/dist-packages/pyatv/dmap/daap.py", line 51, in login
   resp = await self._do(_login_request, is_login=True)
 File "/usr/local/lib/python3.5/dist-packages/pyatv/dmap/daap.py", line 83, in _do
   resp, status = await action()
 File "/usr/local/lib/python3.5/dist-packages/pyatv/dmap/daap.py", line 48, in _login_request
   session=False, login_id=True),
 File "/usr/local/lib/python3.5/dist-packages/pyatv/dmap/daap.py", line 108, in _mkurl
   if re.match(r'0x[0-9a-fA-F]{16}', self._login_id):
 File "/usr/lib/python3.5/re.py", line 163, in match
   return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

An error occurred, full stack trace above
ERROR: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fcd09395f98>.
```

**Expected behavior**
Either success or a more comprehensible error message.

**System Setup (please complete the following information):**
 - OS: Debian
 - Python: 3.5.3
 - pyatv: from master

**Comment by postlund** [comment]
I tried to dig a bit deeper into this and the error message is, indeed, not very good here (#247). The only explanation I can find where this would happen is if the credentials are None. I thought I understood but now I don't... Can you add a debug log in _mkurl, printing `self._login_id`?

**Comment by nriley** [comment]
I ran it from the command line rather than from Monit and I now see an additional error:

```
self._login_id: None
```

I also tried using `--address` rather than `--id` and got the same error.

**Comment by postlund** [comment]
Unless you also specify `--manual`, a scan will always be performed first. You should try adding that.

**Comment by nriley** [comment]
Thanks. Using `--manual` seems to work around the problem and I always get `self._login_id` output.  It would be useful if you got an error trying to use `--address` without `--manual` however.

**Comment by postlund** [comment]
Yes, that would probably be good. I just changed to this behavior, so it's new. If you run without `--manual`, everything is discovered via scanning and you can only override credentials. With `--manual` you can/must provide everything. This should be made more clear and better error messages should be added. We can keep this issue open until I have fixed that.

**Comment by postlund** [comment]
@nriley Would you consider testning with unicast scanning that I recently introduced? That way you don't have to specify anything manually and you get the same speed more or less. This will ensure that the port is correct at all times.

```
$ atvremote --scan-hosts 192.168.2.26 --dmap-credentials [...] --protocol dmap ...

**Comment by postlund** [comment]
I believe this issue is related to #375. When the home sharing service is found, it is all good since HSGID is there. But when it is not found, then credentials are not loaded from command line and authentication fails.

**Comment by postlund** [comment]
I believe this to be fixed now. Please re-open if problem persists.

**Comment by hmaeda** [comment]
I am getting a similar issue where `self._login_id `is `None`

Below are the results when running `atvremote scan`

```
pi@raspberrypi:~/atv_test $ atvremote scan
/home/pi/.local/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py:173: CryptographyDeprecationWarning: OpenSSL version 1.0.2 is no longer supported by the OpenSSL project, please upgrade. The next version of cryptography will drop support for it.
  warnings.warn(
Scan Results
========================================
       Name: Apple TV (3)
   Model/SW: 3 ATV SW 8.4.4
    Address: 11.11.11.11
        MAC: xx:xx:xx:xx:xx:xx
 Deep Sleep: False
Identifiers:
 - xx:xx:xx:xx:xx:xx
 - yyyyyyyyyyyyy
Services:
 - Protocol: AirPlay, Port: 7000, Credentials: None
 - Protocol: DMAP, Port: 3689, Credentials: None

```
However when trying to check what is playing i get the following error:
N.B. I added in a few print statements (for `self._login_id `and `login_id`) to try and debug the error, so the line number might not match, but the error is very similar to the above
```
pi@raspberrypi:~/atv_test $ atvremote --manual --address 192.168.8.105 --port 3689 --protocol dmap --id 98:D6:BB:24:F3:A5 playing
/home/pi/.local/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py:173: CryptographyDeprecationWarning: OpenSSL version 1.0.2 is no longer supported by the OpenSSL project, please upgrade. The next version of cryptography will drop support for it.
  warnings.warn(
None
True
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 657, in _run_application
    return await cli_handler(loop)
  File "/usr/local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 476, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/usr/local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 561, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol)
  File "/usr/local/lib/python3.9/site-packages/pyatv/__init__.py", line 76, in connect
    await atv.connect()
  File "/usr/local/lib/python3.9/site-packages/pyatv/dmap/__init__.py", line 612, in connect
    await self._requester.login()
  File "/usr/local/lib/python3.9/site-packages/pyatv/dmap/daap.py", line 97, in login
    resp = await self._do(_login_request, is_login=True)
  File "/usr/local/lib/python3.9/site-packages/pyatv/dmap/daap.py", line 129, in _do
    resp, status = await action()
  File "/usr/local/lib/python3.9/site-packages/pyatv/dmap/daap.py", line 92, in _login_request
    url = self._mkurl("login?[AUTH]&hasFP=1", session=False, login_id=True)
  File "/usr/local/lib/python3.9/site-packages/pyatv/dmap/daap.py", line 158, in _mkurl
    if re.match(r"0x[0-9A-Fa-f]{16}", self._login_id):
  File "/usr/local/lib/python3.9/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

>>> An error occurred, full stack trace above
2020-10-07 15:35:34 ERROR: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x754ca238>
```
Any help in resolving would be much appreciated
