### ISSUE TITLE
Looks like it's not working anymore after upgrading to 0.104

### ISSUE THREAD

**Issue by rafdalb** [postlund/pyatv#379]
**Describe the bug**
Doesn't work anymore after the upgrade

**To Reproduce**
Upgrade to 0.104

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: [e.g. Debian]
 - Python: [e.g. 3.6.2]
 - pyatv: [e.g. 0.3.10]

**Additional context**
Logs I see
2020-01-16 20:31:29 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Bedroom for apple_tv                                                                                  
Traceback (most recent call last):                                                                                                                                                                 
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 215, in async_setup                                                                                                          
    hass, self                                                                                                                                                                                     
  File "/config/custom_components/apple_tv/__init__.py", line 42, in async_setup_entry                                                                                                             
    address = entry.data[CONF_ADDRESS]                                                                                                                                                             
KeyError: 'address'                                                                                                                                                                                
2020-01-16 20:31:29 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Living for apple_tv                                                                                   
Traceback (most recent call last):                                                                                                                                                                 
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 215, in async_setup                                                                                                          
    hass, self                                                                                                                                                                                     
  File "/config/custom_components/apple_tv/__init__.py", line 42, in async_setup_entry                                                                                                             
    address = entry.data[CONF_ADDRESS]                                                                                                                                                             
KeyError: 'address'

**Comment by rafdalb** [comment]
Sorry, removing and adding the devices fixed the issue. Closing the bug

**Comment by postlund** [comment]
Yeah, this was a breaking change. I didn't document it good enough in the change log, sorry about that (my bad)!

**Comment by rafdalb** [comment]
No problem, good thing is it worked.

Thanks.
