### ISSUE TITLE
Hass crashes after Apple TV power off

### ISSUE THREAD

**Issue by am80l** [postlund/pyatv#381]
Hey hope this bug is going to the right place, I just installed the beta apple tv custom component via HACS yesterday and all was working great! At night I went to run my sleep routine, which shuts off the apple TV, and all of HASS came crashing down. 

**Describe the bug**
When using homeassistant.turn_off service to turn off the apple tv media player, hass starts slowing down, throwing error messages, until eventually fails.

**To Reproduce**
Use homeassistant.turn_off service to turn  off an Apple TV

**Expected behavior**
Apple TV stops playing and shuts off. ( I believe that was the original behavior)

**System Setup (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Hassio 195
 - Hass 0.104.1
 - Installed beta component via HACS

**Additional context**
I didn't see any errors pertaining to the component itself, mostly just side effects seemingly e.g. entities taking too long to update.

**Comment by postlund** [comment]
This sounds bad, obviously. I suspect an uncaught exception in the connection loop, even if that sounds unlikely as well. Can you enable these logs and see if you can reproduce the crash:
```yaml

logger:
  logs:
    pyatv: debug
    custom_components.apple_tv: debug
```

**Comment by am80l** [comment]
Sure thing, I was able to reproduce it two more times, the behavior seems pretty consistent.

These are the logs from immediately after hitting the powerbutton on the media_player in lovelace UI. After this point, device trackers stop responding and eventually hass crashes after a minute or so.

There were inordinate amounts of packet data that i needed to strip to post this, i replaced those packet fields with [ STRIPPED ]

```
2020-01-18 14:38:18 DEBUG (MainThread) [pyatv.mrp.connection] >> Send (Data=0820122430373833663065302d393431632d343062302d386361392d6330653339316332323363362000aa02160800100121000000000000f0bf290000000000007940)
2020-01-18 14:38:18 DEBUG (MainThread) [pyatv.mrp.connection] >> Send (Encrypted=ed1e853e81980392ee0aaf442923241ccf648e2b307e8d53f7766823ad4ec203ee70cc22ccc4f3f3abf5bf5b1f31cf277a932d7981bc3ccd352238caf6f35aa5c1d9933c4aa30506f0ef91e6a69c154cd470d9)
2020-01-18 14:38:18 DEBUG (MainThread) [pyatv.mrp.connection] >> Send: Protobuf=type: PLAYBACK_QUEUE_REQUEST_MESSAGE
identifier: "0783f0e0-941c-40b0-8ca9-c0e391c223c6"
priority: 0
[playbackQueueRequestMessage] {
  location: 0
  length: 1
  artworkWidth: -1
  artworkHeight: 400
}

2020-01-18 14:38:18 DEBUG (MainThread) [pyatv.mrp.connection] << Receive [STRIPPED]
2020-01-18 14:38:18 DEBUG (MainThread) [pyatv.mrp.connection] Require 78038 bytes but only 8685 in buffer
2020-01-18 14:38:18 DEBUG (MainThread) [pyatv.mrp.connection] << Receive [STRIPPED]
2020-01-18 14:38:18 DEBUG (MainThread) [pyatv.mrp.connection] Require 78038 bytes but only 53573 in buffer
2020-01-18 14:38:18 DEBUG (MainThread) [pyatv.mrp.connection] << Receive [STRIPPED]
2020-01-18 14:38:19 DEBUG (MainThread) [pyatv.mrp.connection] << Receive [STRIPPED]
2020-01-18 14:38:19 DEBUG (MainThread) [pyatv.mrp.connection] << Receive: Protobuf=type: SET_STATE_MESSAGE
identifier: "0783f0e0-941c-40b0-8ca9-c0e391c223c6"
priority: 0
[setStateMessage] {
  playbackQueue {
    location: 0
    contentItems {
      identifier: "com.apple.avkit.178.dc312782"
      artworkData: [STRIPPED]
    }
    requestId: "633A5372-874F-4F8E-BCD1-9A48BB7692A8"
  }
  playerPath {
    origin {
      type: Local
      displayName: "Living room"
      identifier: 1280262988
    }
    client {
      processIdentifier: 178
      bundleIdentifier: "com.hulu.plus"
    }
    player {
      identifier: "MediaRemote-DefaultPlayer"
      displayName: "Default Player"
    }
  }
  request {
    location: 0
    length: 1
    artworkWidth: -1.0
    artworkHeight: 400.0
    requestID: "633A5372-874F-4F8E-BCD1-9A48BB7692A8"
  }
}

2020-01-18 14:38:19 DEBUG (MainThread) [pyatv.mrp.connection] << Receive [STRIPPED]
2020-01-18 14:38:19 DEBUG (MainThread) [pyatv.mrp.connection] << Receive: Protobuf=type: TRANSACTION_MESSAGE
priority: 0
[transactionMessage] {
  name: 2
  packets {
    packets {
      key {
        identifier: "com.apple.avkit.178.dc312782"
      }
      packetData: [STRIPPED]
      identifier: "379B65B9-07E7-446D-9D42-4755F13E04F1"
      totalLength: 77677
      totalWritePosition: 0
    }
  }
}

2020-01-18 14:38:19 DEBUG (MainThread) [pyatv.mrp.connection] >> Send (Data=0820122464633538353066362d376435612d346164612d393032312d3730323663633335346266382000aa02160800100121000000000000f0bf290000000000007940)
2020-01-18 14:38:19 DEBUG (MainThread) [pyatv.mrp.connection] >> Send (Encrypted=278aaa1286e5dd3de0df92cc74e70752f20508949124d1c85b1cf530dc110e459913030d2141058c69bdec0081061c75479a7a02ed3cded3e1b6199b9a5581aad71804a6b6b8c160df020d82e49ef20f1eafb1)
2020-01-18 14:38:19 DEBUG (MainThread) [pyatv.mrp.connection] >> Send: Protobuf=type: PLAYBACK_QUEUE_REQUEST_MESSAGE
identifier: "dc5850f6-7d5a-4ada-9021-7026cc354bf8"
priority: 0
[playbackQueueRequestMessage] {
  location: 0
  length: 1
  artworkWidth: -1
  artworkHeight: 400
}

2020-01-18 14:38:19 DEBUG (MainThread) [pyatv.mrp.connection] << Receive [STRIPPED]
2020-01-18 14:38:20 DEBUG (MainThread) [pyatv.mrp.connection] << Receive [STRIPPED]
2020-01-18 14:38:20 DEBUG (MainThread) [pyatv.mrp.connection] << Receive: Protobuf=type: SET_STATE_MESSAGE
identifier: "dc5850f6-7d5a-4ada-9021-7026cc354bf8"
priority: 0
[setStateMessage] {
  playbackQueue {
    location: 0
    contentItems {
      identifier: "com.apple.avkit.178.dc312782"
      artworkData: [STRIPPED]
    }
    requestId: "05EFF5A2-A2AC-47D5-A81F-55749F2817E1"
  }
  playerPath {
    origin {
      type: Local
      displayName: "Living room"
      identifier: 1280262988
    }
    client {
      processIdentifier: 178
      bundleIdentifier: "com.hulu.plus"
    }
    player {
      identifier: "MediaRemote-DefaultPlayer"
      displayName: "Default Player"
    }
  }
  request {
    location: 0
    length: 1
    artworkWidth: -1.0
    artworkHeight: 400.0
    requestID: "05EFF5A2-A2AC-47D5-A81F-55749F2817E1"
  }
}

2020-01-18 14:38:20 DEBUG (MainThread) [pyatv.mrp.connection] << Receive [STRIPPED]
2020-01-18 14:38:20 DEBUG (MainThread) [pyatv.mrp.connection] << Receive: Protobuf=type: TRANSACTION_MESSAGE
priority: 0
[transactionMessage] {
  name: 2
  packets {
    packets {
      key {
        identifier: "com.apple.avkit.178.dc312782"
      }
      packetData: [STRIPPED]
2020-01-18 14:38:22 WARNING (SyncWorker_0) [homeassistant.components.homekit.util] ['AUTO', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10] does not contain the speed setting off as its first element. Assuming that AUTO is equivalent to 'off'.
2020-01-18 14:38:22 WARNING (SyncWorker_0) [homeassistant.components.homekit.util] ['AUTO', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10] does not contain the speed setting off as its first element. Assuming that AUTO is equivalent to 'off'.
2020-01-18 14:38:24 DEBUG (MainThread) [pyatv.mrp.connection] Disconnected from device: None
2020-01-18 14:38:24 ERROR (MainThread) [plexwebsocket] Websocket disconnected
2020-01-18 14:38:25 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/huesensor/sensor.py", line 265, in update_bridge
    available = await update_api(bridge.api.sensors)
  File "/config/custom_components/huesensor/sensor.py", line 239, in update_api
    await api.update()
  File "/usr/local/lib/python3.7/site-packages/aiohue/api.py", line 12, in update
    raw = await self._request('get', self._path)
  File "/usr/local/lib/python3.7/site-packages/aiohue/bridge.py", line 68, in request
    async with self.websession.request(method, url, json=json) as res:
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
2020-01-18 14:38:25 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hue/light.py", line 205, in async_update_items
    await bridge.async_request_call(api.update())
  File "/usr/src/homeassistant/homeassistant/components/hue/bridge.py", line 103, in async_request_call
    return await coro
  File "/usr/local/lib/python3.7/site-packages/aiohue/api.py", line 12, in update
    raw = await self._request('get', self._path)
  File "/usr/local/lib/python3.7/site-packages/aiohue/bridge.py", line 68, in request
    async with self.websession.request(method, url, json=json) as res:
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
2020-01-18 14:38:26 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/huesensor/sensor.py", line 265, in update_bridge
    available = await update_api(bridge.api.sensors)
  File "/config/custom_components/huesensor/sensor.py", line 239, in update_api
    await api.update()
  File "/usr/local/lib/python3.7/site-packages/aiohue/api.py", line 12, in update
    raw = await self._request('get', self._path)
  File "/usr/local/lib/python3.7/site-packages/aiohue/bridge.py", line 68, in request
    async with self.websession.request(method, url, json=json) as res:
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
2020-01-18 14:38:27 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/huesensor/sensor.py", line 265, in update_bridge
    available = await update_api(bridge.api.sensors)
  File "/config/custom_components/huesensor/sensor.py", line 239, in update_api
    await api.update()
  File "/usr/local/lib/python3.7/site-packages/aiohue/api.py", line 12, in update
    raw = await self._request('get', self._path)
  File "/usr/local/lib/python3.7/site-packages/aiohue/bridge.py", line 68, in request
    async with self.websession.request(method, url, json=json) as res:
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed

```

**Comment by postlund** [comment]
Perfect! Quick look: same issue as in #382.

**Comment by postlund** [comment]
New version of component is out, please try it out and let me know if problem is solved.

**Comment by am80l** [comment]
I downloaded the new version and repeated the steps as described, and HASS no longer crashes with the new changes. Awesome!

The turn_off behavior still isn't working quite as expected however. After a turn_off call, HASS treats the entity as turned off, but on the apple TV itself, media continues to play normally, but that is a separate issue. I would consider this bug closed. Thank you!

**Comment by postlund** [comment]
Great that it worked! 👍 

Hmm, that doesn't sound right. There is no (and has never been) explicit "stop" action coded into either `pyatv` or the Apple TV component. Must have been som strange behavior. Are you sure that it worked like that?
