### ISSUE TITLE
Get playback status from airport express (Airplay)

### ISSUE THREAD

**Issue by wormiedk** [postlund/pyatv#384]
**What feature would you like?**
Get status of playback for airport express. I can already find it using pyatv command:
atvremote scan:
       Name: AirportExpressAlrum
    Address: 10.0.1.69
Identifiers:
 - 54:E4:3A:E5:63:xx
Services:
 - Protocol: AirPlay, Port: 7000, Credentials: None

However it seems I cannot interact with anything but apple tvs :(

./atvremote --id 54:E4:3A:E5:63:xx playing
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/__main__.py", line 557, in _run_application
    return await cli_handler(loop)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/__main__.py", line 386, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/__main__.py", line 466, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/__init__.py", line 229, in connect
    service = config.main_service(protocol=protocol)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/conf.py", line 76, in main_service
    'no service to connect to')
pyatv.exceptions.NoServiceError: no service to connect to

>>> An error occurred, full stack trace above

**Describe the solution you'd like**
Make pyatv work with airplay for airport express. My usage scenario is to get metadata from an airport express connected to my receiver. Further I would like to know when the airport express is receiving an audio stream to automatically turn on receiver.

**Any other information to share?**
I think I saw an earlier answer regarding airplay support stating that other packages support it. However I have searched low and high without finding a package that works :(
I have tried:
https://github.com/benvanik/node-airplay (unmaintained since 2014)
https://github.com/watson/airplayer (unmaintained since 2016, allegedly only supports apple tv but I could not get it to work)
https://github.com/cnelson/python-airplay (unmaintained since 2016, allegedly only supports apple tv I could only get a "false" response to all command airport express / apple tv)

**Comment by postlund** [comment]
Yes, this has been up for discussion before. My stance is really that "pure" AirPlay is out of scope of this library. This is a library for the Apple TV and the only reason why AirPlay support is there is for streaming autio/video from a URL. But...today I gave it another thought.

Maybe it could be implemented quite nicely but I would have to toss around the interface a bit, because `pyatv.connect` returns an `interface.AppleTV` instance, which has `interface.AirPlay` to interact with AirPlay. This wouldn't make any sense for a pure AirPlay device.

I think I will have to give some additional thinking. It might be possible to do something good with this. I'm up for discussion if you/someone wants to implement support for it. I can give some assistance on how I would like to see it in place.
