### ISSUE TITLE
Constant Log  - [custom_components.apple_tv] Failed to connect

### ISSUE THREAD

**Issue by grantclem** [postlund/pyatv#436]
**Describe the bug**
**Constantly logged - seems related to report 104**

2020-02-10 09:38:02 ERROR (MainThread) [custom_components.apple_tv] Failed to connect
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/apple_tv/__init__.py", line 211, in _connect_loop
    conf = await self._scan()
  File "/home/homeassistant/.homeassistant/custom_components/apple_tv/__init__.py", line 264, in _scan
    address = self.config_entry.data[CONF_ADDRESS]
KeyError: 'address'
2020-02-10 09:38:03 ERROR (MainThread) [custom_components.apple_tv] Failed to connect
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/apple_tv/__init__.py", line 211, in _connect_loop
    conf = await self._scan()
  File "/home/homeassistant/.homeassistant/custom_components/apple_tv/__init__.py", line 264, in _scan
    address = self.config_entry.data[CONF_ADDRESS]
KeyError: 'address'
2020-02-10 09:38:03 ERROR (MainThread) [custom_components.apple_tv] Failed to connect
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/apple_tv/__init__.py", line 211, in _connect_loop
    conf = await self._scan()
  File "/home/homeassistant/.homeassistant/custom_components/apple_tv/__init__.py", line 264, in _scan
    address = self.config_entry.data[CONF_ADDRESS]
KeyError: 'address'

**To Reproduce**

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: [Debian]/ VE
 - Python: [3.7.5rc1]
 - pyatv: [7ec122f]
- HA [0.105.2]

**Additional context**
Steps taken - as suggested in bug report #379 , removed integration and entities, rebooted device, re-install.

**Comment by postlund** [comment]
There must have been something left in the configuration after you removed it. Did you restart Home Assistant after removal? Full unloading is not implemented currently as the `remote` component does not support config flows yet, so it cannot be done until I move it into the Home Assistant Core source tree. It basically means that you have to restart Home Assistant after removing the integration before adding it again.

**Comment by grantclem** [comment]
Hi, yes defiantly rebooted the device after removing the integration and orphaned entities.  Sorry I cannot offer much more.

**Comment by postlund** [comment]
Seems very strange, still. Can you remove the integration (and orphaned entities), shut down home assistant and look in `.storage/core.config_entries` and see if the device is still there? You can search for apple_tv.

**Comment by postlund** [comment]
Did you get any chance to re-verify this? The code path will only run when a config entry exists in your configuration, so there must be some left-overs.

**Comment by grantclem** [comment]
Hi Pierre,

Apologies, yes all is working ok now, the Apple TV integration was not showing at one stage and once it re-appeared all was fine.  Thanks

**Comment by postlund** [comment]
Perfect, thanks for replying so fast 👍
