### ISSUE TITLE
Error with Homeassistant 0.107 beta

### ISSUE THREAD

**Issue by Krocko** [postlund/pyatv#499]
**Describe the bug**
With homeassistant 0.107.0b0 I get the following error:
**To Reproduce**

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: Homeassistant in Synology Docker, Supervisor 209
 - Python: 3.7
 - pyatv: 0.4.0a16 update 2

**Additional context**
```
Logger: custom_components.apple_tv
Source: custom_components/apple_tv/__init__.py:325 
First occured: 11:20:49 (17 occurences) 
Last logged: 12:40:24

Failed to connect
Traceback (most recent call last):
  File "/config/custom_components/apple_tv/__init__.py", line 208, in _connect_loop
    await self._connect(conf)
  File "/config/custom_components/apple_tv/__init__.py", line 296, in _connect
    self.address_updated(str(conf.address))
  File "/config/custom_components/apple_tv/__init__.py", line 325, in address_updated
    self.config_entry.data[CONF_ADDRESS] = address
TypeError: 'mappingproxy' object does not support item assignment
```

**Comment by Krocko** [comment]
```
Logger: homeassistant.components.recorder
Source: components/recorder/__init__.py:378 
Integration: recorder (documentation, issues) 
First occured: 14:30:41 (1 occurences) 
Last logged: 14:30:41

Event is not JSON serializable: <Event platform_discovered[L]: service=load_platform.remote, platform=apple_tv, discovered=address=XXX.XXX.XX.XX, credentials=2=7f70b5d6df90243737bab63a2f5dbff14884fe8081f51f77ee5ed9bef3ef920c:d36207b2c4a137e3924e317a1a609e4e39fec635e62e3ef5c5d91fa643d8b106:61653833626136642d336463352d343965612d613266372d396238363138373561353034:66656335663966322d326437362d346134352d396464362d373131303563386565663763, 3=530F3D2C55AF155D:738766E435D0AF0C68CABE315D685912F438A24AF8F6DE1D9DA2D716D4A7F7F3, identifier=876A6B91-1588-457D-8C8B-85AED5DACB93, name=AppleTV, protocol=2>

**Comment by postlund** [comment]
This is with custom component from hass-atv-beta repo, right?

**Comment by Krocko** [comment]
it is version ` fc79765`from hacs.

**Comment by Krocko** [comment]
Hi @postlund.
Have you any news?
Or do you need more info?

**Comment by postlund** [comment]
@Krocko Not yet, will have some time tomorrow.

**Comment by postlund** [comment]
I think I know the problem, will test and verify tonight.

**Comment by Krocko** [comment]
Thank you very much for your work.

**Comment by postlund** [comment]
@Krocko Just pushed an update, hopefully works again now!

**Comment by Krocko** [comment]
Thank you. It is working again.

**Comment by postlund** [comment]
👍
