### ISSUE TITLE
MessageToString() got an unexpected keyword argument 'print_unknown_fields'

### ISSUE THREAD

**Issue by codylv7** [postlund/pyatv#510]
**Describe the bug**
Error in log
**To Reproduce**
Only upgraded to 107.0 and installed latest component
**Expected behavior**

**System Setup (please complete the following information):**
 - OS: Docker
 - Python: ?
 - pyatv: ?

**Additional context**
```
TypeError: MessageToString() got an unexpected keyword argument 'print_unknown_fields'
2020-03-18 11:56:00 ERROR (MainThread) [pyatv.mrp.connection] Failed to handle message
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/connection.py", line 106, in data_received
    self._handle_message(data)
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/connection.py", line 117, in _handle_message
    log_protobuf(_LOGGER, '<< Receive: Protobuf', parsed)
  File "/usr/local/lib/python3.7/site-packages/pyatv/support.py", line 57, in log_protobuf
    message, print_unknown_fields=True).splitlines()
TypeError: MessageToString() got an unexpected keyword argument 'print_unknown_fields'
```

**Comment by postlund** [comment]
I will release pyatv 0.5.0 soon which fixes this soon (#508). Home Assistant pins version 3.6.1 of protobuf but pyatv used to require 3.8.0 or later. So I made a workaround for that.

**Comment by codylv7** [comment]
Awesome, thank you!

**Comment by postlund** [comment]
@codylv7 Release 0.5.0 is out and I have updated the component so it should work now. Please give it a spin and report back! 👍

**Comment by codylv7** [comment]
Good now!  Thank you
