### ISSUE TITLE
ATVremote old version only

### ISSUE THREAD

**Issue by quanticware** [postlund/pyatv#546]
Hello,
I know it's not a atvremote problem, but linux.

On my ubuntu 18.04 container I did `pip install pyatv` and I have 0.5 version and works.
On my debian 9 strech home automation server, I did `pip3 install pyatv`and I have only the 0.3.12 version.

On my debian I need to have python2.7 by default.

What I can do to have atvremote 0.5?

Thanks

**Comment by postlund** [comment]
I don't think pip will upgrade packages by default, so you should specify `--upgrade`:

```shell
$ pip3 install --upgrade pyatv
```

**Comment by quanticware** [comment]
No more, stuck to 0.3.12.

```
user@home:~$ pip3 install --upgrade pyatv
Collecting pyatv
  Using cached https://files.pythonhosted.org/packages/23/c6/dd976cb24e5b9034cf5a967c8076ee559595e1b53a45721ef7ba9deb2d32/pyatv-0.5.0-py3-none-any.whl
Collecting cryptography>=1.8.1 (from pyatv)
  Using cached https://files.pythonhosted.org/packages/45/73/d18a8884de8bffdcda475728008b5b13be7fbef40a2acc81a0d5d524175d/cryptography-2.8-cp34-abi3-manylinux1_x86_64.whl
Collecting protobuf>=3.6.0 (from pyatv)
  Using cached https://files.pythonhosted.org/packages/ef/56/10999d97e62eba72a12ebd147d806fa702ab82a620e28f6bc3e5d2c59e34/protobuf-3.11.3-cp35-cp35m-manylinux1_x86_64.whl
Collecting netifaces>=0.10.0 (from pyatv)
  Using cached https://files.pythonhosted.org/packages/6f/66/2df3d5cb0e18eccf0f798f7a31601678fc3578ce560fa5b897d791e3f835/netifaces-0.10.9-cp35-cp35m-manylinux1_x86_64.whl
Collecting aiozeroconf>=0.1.8 (from pyatv)
Collecting srptools>=0.2.0 (from pyatv)
  Using cached https://files.pythonhosted.org/packages/54/6d/b1d42918fc721545d6ba92e6a77e414bc5eda9f4c1c352d8836632499024/srptools-1.0.0-py2.py3-none-any.whl
Collecting aiohttp<4,>=3.0.1 (from pyatv)
  Using cached https://files.pythonhosted.org/packages/60/90/60bf09ad2e8c827e3a71f77c43ff7be17c9d397d33baeae7cdf0435139b2/aiohttp-3.6.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting six>=1.4.1 (from cryptography>=1.8.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography>=1.8.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/d6/7f/7acc85c478f5056b98c9961a31697b1e53fbec158ee5f723097e1c355660/cffi-1.14.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting setuptools (from protobuf>=3.6.0->pyatv)
  Using cached https://files.pythonhosted.org/packages/a0/df/635cdb901ee4a8a42ec68e480c49f85f4c59e8816effbf57d9e6ee8b3588/setuptools-46.1.3-py3-none-any.whl
Collecting attrs>=17.3.0 (from aiohttp<4,>=3.0.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting idna-ssl>=1.0; python_version < "3.7" (from aiohttp<4,>=3.0.1->pyatv)
Collecting multidict<5.0,>=4.5 (from aiohttp<4,>=3.0.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/18/a2/41cfebb8c3f7d49a2421192a0f9f3de3d2bc59d59cbdd55985cca1490dd2/multidict-4.7.5-cp35-cp35m-manylinux1_x86_64.whl
Collecting yarl<2.0,>=1.0 (from aiohttp<4,>=3.0.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/e8/e2/bc1c3aa2b1394c6e4128edddee55e11267d707b3390bf5a7c6be96c796f8/yarl-1.4.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting typing-extensions>=3.6.5; python_version < "3.7" (from aiohttp<4,>=3.0.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/03/92/705fe8aca27678e01bbdd7738173b8e7df0088a2202c80352f664630d638/typing_extensions-3.7.4.1-py3-none-any.whl
Collecting async-timeout<4.0,>=3.0 (from aiohttp<4,>=3.0.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Collecting chardet<4.0,>=2.0 (from aiohttp<4,>=3.0.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=1.8.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Collecting idna>=2.0 (from idna-ssl>=1.0; python_version < "3.7"->aiohttp<4,>=3.0.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl
Installing collected packages: six, pycparser, cffi, cryptography, setuptools, protobuf, netifaces, aiozeroconf, srptools, attrs, idna, idna-ssl, multidict, yarl, typing-extensions, async-timeout, chardet, aiohttp, pyatv
Successfully installed aiohttp-3.6.2 aiozeroconf-0.1.8 async-timeout-3.0.1 attrs-19.3.0 cffi-1.14.0 chardet-3.0.4 cryptography-2.8 idna-2.9 idna-ssl-1.1.0 multidict-4.7.5 netifaces-0.10.9 protobuf-3.11.3 pyatv-0.5.0 pycparser-2.20 setuptools-46.1.3 six-1.14.0 srptools-1.0.0 typing-extensions-3.7.4.1 yarl-1.4.2
user@home:~$ atvremote --version
atvremote 0.3.12
```

**Comment by postlund** [comment]
You might have multiple versions installed. Try running `pip unistall pyatv` a couple of times until no version is installed. Then install pyatv again.

**Comment by quanticware** [comment]
I tried already but unable to install.
I tried to create virtualenv.

```
(atvremote) user@home:~$ pip install pyatv
Requirement already satisfied: pyatv in ./atvremote/lib/python3.5/site-packages (0.5.0)
Requirement already satisfied: aiozeroconf>=0.1.8 in ./atvremote/lib/python3.5/site-packages (from pyatv) (0.1.8)
Requirement already satisfied: srptools>=0.2.0 in ./atvremote/lib/python3.5/site-packages (from pyatv) (1.0.0)
Requirement already satisfied: protobuf>=3.6.0 in ./atvremote/lib/python3.5/site-packages (from pyatv) (3.11.3)
Requirement already satisfied: cryptography>=1.8.1 in ./atvremote/lib/python3.5/site-packages (from pyatv) (2.8)
Requirement already satisfied: netifaces>=0.10.0 in ./atvremote/lib/python3.5/site-packages (from pyatv) (0.10.9)
Requirement already satisfied: aiohttp<4,>=3.0.1 in ./atvremote/lib/python3.5/site-packages (from pyatv) (3.6.2)
Requirement already satisfied: six in ./atvremote/lib/python3.5/site-packages (from srptools>=0.2.0->pyatv) (1.14.0)
Requirement already satisfied: setuptools in ./atvremote/lib/python3.5/site-packages (from protobuf>=3.6.0->pyatv) (46.1.3)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in ./atvremote/lib/python3.5/site-packages (from cryptography>=1.8.1->pyatv) (1.14.0)
Requirement already satisfied: typing-extensions>=3.6.5; python_version < "3.7" in ./atvremote/lib/python3.5/site-packages (from aiohttp<4,>=3.0.1->pyatv) (3.7.4.1)
Requirement already satisfied: multidict<5.0,>=4.5 in ./atvremote/lib/python3.5/site-packages (from aiohttp<4,>=3.0.1->pyatv) (4.7.5)
Requirement already satisfied: yarl<2.0,>=1.0 in ./atvremote/lib/python3.5/site-packages (from aiohttp<4,>=3.0.1->pyatv) (1.4.2)
Requirement already satisfied: chardet<4.0,>=2.0 in ./atvremote/lib/python3.5/site-packages (from aiohttp<4,>=3.0.1->pyatv) (3.0.4)
Requirement already satisfied: async-timeout<4.0,>=3.0 in ./atvremote/lib/python3.5/site-packages (from aiohttp<4,>=3.0.1->pyatv) (3.0.1)
Requirement already satisfied: idna-ssl>=1.0; python_version < "3.7" in ./atvremote/lib/python3.5/site-packages (from aiohttp<4,>=3.0.1->pyatv) (1.1.0)
Requirement already satisfied: attrs>=17.3.0 in ./atvremote/lib/python3.5/site-packages (from aiohttp<4,>=3.0.1->pyatv) (19.3.0)
Requirement already satisfied: pycparser in ./atvremote/lib/python3.5/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=1.8.1->pyatv) (2.20)
Requirement already satisfied: idna>=2.0 in ./atvremote/lib/python3.5/site-packages (from yarl<2.0,>=1.0->aiohttp<4,>=3.0.1->pyatv) (2.9)
(atvremote) user@home:~$ atvremote --version
Traceback (most recent call last):
  File "/home/user/atvremote/bin/atvremote", line 5, in <module>
    from pyatv.scripts.atvremote import main
  File "/home/user/atvremote/local/lib/python3.5/site-packages/pyatv/__init__.py", line 261
    scanner: BaseScanner
           ^
SyntaxError: invalid syntax
(atvremote) user@home:~
```

I have an error when I start atvremote any commands.

```
Traceback (most recent call last):
  File "/home/user/atvremote/bin/atvremote", line 5, in <module>
    from pyatv.scripts.atvremote import main
  File "/home/user/atvremote/local/lib/python3.5/site-packages/pyatv/__init__.py", line 261
    scanner: BaseScanner
           ^
SyntaxError: invalid syntax
```

**Comment by postlund** [comment]
You need python 3.6.

**Comment by quanticware** [comment]
python 3.6.9 compiled and installed.
```
jeedom@jeedom-maison:~$ atvremote
Traceback (most recent call last):
  File "/usr/local/bin/atvremote", line 7, in <module>
    from pyatv.scripts.atvremote import main
ModuleNotFoundError: No module named 'pyatv'
```
I change symbolic link of /usr/bin/python3 > /usr/bin/local/python3.6

I tried in venv and It's work. 

But I needed to have it on host, because I don't how to launch atvremote outside of venv.

Thanks

**Comment by postlund** [comment]
You can run <venv path>/bin/atvrmote directly without having to "enter" the venv. That should work.

**Comment by quanticware** [comment]
Yeaaaah! It's works.

Thanks!
