### ISSUE TITLE
Timeouts occurs for services some times

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#595]
**Describe the bug**
Some times a timeout occurs for a request, similar like this from #444:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/__main__.py", line 565, in _run_application
    return await cli_handler(loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/__main__.py", line 388, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/__main__.py", line 480, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/__main__.py", line 517, in _handle_device_command
    return (await _exec_command(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/__main__.py", line 531, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/airplay/__init__.py", line 71, in play_url
    player = await self._player(session)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/airplay/__init__.py", line 51, in _player
    await verifier.verify_authed()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/airplay/auth.py", line 88, in verify_authed
    resp = await self._send(self.srp.verify1(), 'verify1')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/airplay/auth.py", line 100, in _send
    resp, code = await self.http.post_data(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/net.py", line 76, in post_data
    raise ex
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/net.py", line 64, in post_data
    resp = await self._session.post(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/helpers.py", line 596, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

Lately I've been looking a lot into power management and device sleeping. Most Apple devices goes to sleep after a while and use a Bonjour Sleep proxy to manage that. It will automatically wake up the device when a (zeroconf) service is requested from it, e.g. connecting via DMAP, MRP or AirPlay. So it is rather transparent to the end-user. The wake up time can however be quite long, up towards 20s is something I have seen. Timeout in `pyatv` is currently set to ten seconds, so things might fail with a timeout (like the one above) because the device hasn't woken up yet.

I've written a lot about this in #580 and I will continue my journey to improve this. This issue is mostly to shed som light on the problem.

**To Reproduce**
Wait for the device to go to sleep (I just ping it and wait for ICMP redirects), then try to access playing information for instance:

```shell
$ atvremote --id 2DF2E7507639C269 --debug playing
2020-04-17 15:44:39 DEBUG: Discovering devices for 3 seconds
2020-04-17 15:44:40 DEBUG: Auto-discovered Vardagsrum at 10.0.10.81:49152 (Protocol.MRP)
2020-04-17 15:44:40 DEBUG: Auto-discovered Vardagsrum at 10.0.10.81:7000 (Protocol.AirPlay)
2020-04-17 15:44:40 DEBUG: Auto-discovered My Music on a6b98bcd-forked-daapd at 10.0.10.200:3689 (Protocol.DMAP)
2020-04-17 15:44:40 DEBUG: Auto-discovered Kontor at 10.0.10.101:7000 (Protocol.AirPlay)
2020-04-17 15:44:40 DEBUG: Auto-discovered Apple TV (2) at 10.0.10.100:7000 (Protocol.AirPlay)
2020-04-17 15:44:40 DEBUG: Auto-discovered Apple TV at 10.0.10.100:3689 (Protocol.DMAP)
2020-04-17 15:44:40 DEBUG: Auto-discovered Apple TV at 10.0.10.100:3689 (Protocol.DMAP)
2020-04-17 15:44:42 INFO: Auto-discovered None at None
2020-04-17 15:44:42 DEBUG: No AirPlay credentials loaded
2020-04-17 15:44:42 DEBUG: GET URL: http://10.0.10.100:3689/login?hsgid=00000000-1125-ff3b-7f12-8518bf3e4c0e&hasFP=1
Traceback (most recent call last):
  File "/home/postlund/pyatv_dev/pyatv/pyatv/scripts/atvremote.py", line 641, in _run_application
    return await cli_handler(loop)
  File "/home/postlund/pyatv_dev/pyatv/pyatv/scripts/atvremote.py", line 455, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/home/postlund/pyatv_dev/pyatv/pyatv/scripts/atvremote.py", line 545, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol)
  File "/home/postlund/pyatv_dev/pyatv/pyatv/__init__.py", line 307, in connect
    await atv.connect()
  File "/home/postlund/pyatv_dev/pyatv/pyatv/dmap/__init__.py", line 605, in connect
    await self._requester.login()
  File "/home/postlund/pyatv_dev/pyatv/pyatv/dmap/daap.py", line 96, in login
    resp = await self._do(_login_request, is_login=True)
  File "/home/postlund/pyatv_dev/pyatv/pyatv/dmap/daap.py", line 127, in _do
    resp, status = await action()
  File "/home/postlund/pyatv_dev/pyatv/pyatv/support/net.py", line 74, in get_data
    raise ex
  File "/home/postlund/pyatv_dev/pyatv/pyatv/support/net.py", line 61, in get_data
    resp = await self._session.get(
  File "/home/postlund/pyatv_dev/pyatv/lib/python3.8/site-packages/aiohttp/client.py", line 582, in _request
    break
  File "/home/postlund/pyatv_dev/pyatv/lib/python3.8/site-packages/aiohttp/helpers.py", line 586, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

>>> An error occurred, full stack trace above
2020-04-17 15:44:53 ERROR: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fc00b69bfa0>
```

**Expected behavior**
Device should be woken up and information retrieved (here it is with higher timeout):

```
$ atvremote --id 2DF2E7507639C269 --debug playing
2020-04-17 15:37:20 DEBUG: Discovering devices for 3 seconds
2020-04-17 15:37:21 DEBUG: Auto-discovered My Music on a6b98bcd-forked-daapd at 10.0.10.200:3689 (Protocol.DMAP)
2020-04-17 15:37:21 DEBUG: Auto-discovered Vardagsrum at 10.0.10.81:49152 (Protocol.MRP)
2020-04-17 15:37:21 DEBUG: Auto-discovered Vardagsrum at 10.0.10.81:7000 (Protocol.AirPlay)
2020-04-17 15:37:21 DEBUG: Auto-discovered Kontor at 10.0.10.101:7000 (Protocol.AirPlay)
2020-04-17 15:37:21 DEBUG: Auto-discovered Apple TV (2) at 10.0.10.100:7000 (Protocol.AirPlay)
2020-04-17 15:37:21 DEBUG: Auto-discovered Apple TV at 10.0.10.100:3689 (Protocol.DMAP)
2020-04-17 15:37:21 DEBUG: Auto-discovered Apple TV at 10.0.10.100:3689 (Protocol.DMAP)
2020-04-17 15:37:23 INFO: Auto-discovered None at None
2020-04-17 15:37:23 DEBUG: No AirPlay credentials loaded
2020-04-17 15:37:23 DEBUG: GET URL: http://10.0.10.100:3689/login?hsgid=00000000-1125-ff3b-7f12-8518bf3e4c0e&hasFP=1
2020-04-17 15:37:39 DEBUG: _login_request: mlog: [container, dmap.loginresponse]
  mstt: 200 [uint, dmap.status]
  mlid: 218104921 [uint, dmap.sessionid]

2020-04-17 15:37:39 INFO: Logged in and got session id 218104921
2020-04-17 15:37:39 DEBUG: Already logged in, re-using seasion id 218104921
2020-04-17 15:37:39 DEBUG: GET URL: http://10.0.10.100:3689/ctrl-int/1/playstatusupdate?session-id=218104921&revision-number=0
2020-04-17 15:37:39 DEBUG: _get_request: cmst: [container, dmcp.playstatus]
  mstt: 200 [uint, dmap.status]
  cmsr: 18 [uint, dmcp.serverrevision]

  Media type: Unknown
Device state: Idle
      Repeat: Off
     Shuffle: Off
2020-04-17 15:37:39 DEBUG: Connection was closed properly
```

Notice the 13s gap in time for the GET request.

**System Setup (please complete the following information):**
 - OS: any
 - Python: any
 - pyatv: any
- Apple TV: any

**Additional context**
I will publish a PR with a higher timeout to fix this. It will however not solve the issue when unicast scanning is used solely.

**Comment by postlund** [comment]
Mitigations are now in place. Here is for regular scanning:

```shell
$ atvremote --id xxx --debug playing
2020-04-21 10:38:38 DEBUG: Discovering devices for 3 seconds
2020-04-21 10:38:39 DEBUG: Auto-discovered My Music on a6b98bcd-forked-daapd at 10.0.10.200:3689 (Protocol.DMAP)
2020-04-21 10:38:39 DEBUG: Auto-discovered Kontor at 10.0.10.101:7000 (Protocol.AirPlay)
2020-04-21 10:38:39 DEBUG: Auto-discovered Vardagsrum at 10.0.10.81:49152 (Protocol.MRP)
2020-04-21 10:38:39 DEBUG: Auto-discovered Vardagsrum at 10.0.10.81:7000 (Protocol.AirPlay)
2020-04-21 10:38:39 DEBUG: Auto-discovered Apple TV (2) at 10.0.10.100:7000 (Protocol.AirPlay)
2020-04-21 10:38:39 DEBUG: Auto-discovered Apple TV at 10.0.10.100:3689 (Protocol.DMAP)
2020-04-21 10:38:39 DEBUG: Auto-discovered Apple TV at 10.0.10.100:3689 (Protocol.DMAP)
2020-04-21 10:38:41 INFO: Auto-discovered Apple TV (2) at 10.0.10.100
2020-04-21 10:38:41 DEBUG: No AirPlay credentials loaded
2020-04-21 10:38:41 DEBUG: GET URL: http://10.0.10.100:3689/login?hsgid=yyy&hasFP=1
2020-04-21 10:38:56 DEBUG: Response: status=200, headers=[Date=Tue, 21 Apr 2020 08:40:53 GMT, DAAP-Server=iTunes/11.1b37 (OS X), Content-Type=application/x-dmap-tagged, Content-Length=47, Content-Encoding=gzip]
2020-04-21 10:38:56 DEBUG: << GET (Data=6d6c6f67000000186d73747400000004000000c86d6c69640000000456002515)
2020-04-21 10:38:56 DEBUG: _login_request: mlog: [container, dmap.loginresponse]
  mstt: 200 [uint, dmap.status]
  mlid: 1442850069 [uint, dmap.sessionid]

2020-04-21 10:38:56 INFO: Logged in and got session id 1442850069
2020-04-21 10:38:56 DEBUG: Already logged in, re-using seasion id 1442850069
2020-04-21 10:38:56 DEBUG: GET URL: http://10.0.10.100:3689/ctrl-int/1/playstatusupdate?session-id=1442850069&revision-number=0
2020-04-21 10:38:56 DEBUG: Response: status=200, headers=[Date=Tue, 21 Apr 2020 08:40:53 GMT, DAAP-Server=iTunes/11.1b37 (OS X), Content-Type=application/x-dmap-tagged, Content-Length=41, Content-Encoding=gzip]
2020-04-21 10:38:56 DEBUG: << GET (Data=636d7374000000186d73747400000004000000c8636d73720000000400000012)
2020-04-21 10:38:56 DEBUG: _get_request: cmst: [container, dmcp.playstatus]
  mstt: 200 [uint, dmap.status]
  cmsr: 18 [uint, dmcp.serverrevision]

  Media type: Unknown
Device state: Idle
      Repeat: Off
     Shuffle: Off
2020-04-21 10:38:56 DEBUG: Connection was closed properly
```

Same for unicast scanning (longer timeout needs to be specified, 30s should be ok):

```shell
$ atvremote -s 10.0.10.100 --debug -t 30 playing
2020-04-21 10:37:51 DEBUG: Knocking at port 3689 on 10.0.10.100
2020-04-21 10:37:51 DEBUG: Knocking at port 7000 on 10.0.10.100
2020-04-21 10:37:51 DEBUG: Knocking at port 49152 on 10.0.10.100
2020-04-21 10:37:51 DEBUG: Knocking at port 32498 on 10.0.10.100
2020-04-21 10:37:51 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:37:52 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:37:53 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:37:53 DEBUG: Knocking at port 3689 on 10.0.10.100
2020-04-21 10:37:53 DEBUG: Knocking at port 7000 on 10.0.10.100
2020-04-21 10:37:53 DEBUG: Knocking at port 49152 on 10.0.10.100
2020-04-21 10:37:53 DEBUG: Knocking at port 32498 on 10.0.10.100
2020-04-21 10:37:54 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:37:55 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:37:55 DEBUG: Knocking at port 3689 on 10.0.10.100
2020-04-21 10:37:55 DEBUG: Knocking at port 7000 on 10.0.10.100
2020-04-21 10:37:55 DEBUG: Knocking at port 49152 on 10.0.10.100
2020-04-21 10:37:55 DEBUG: Knocking at port 32498 on 10.0.10.100
2020-04-21 10:37:56 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:37:57 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:37:58 DEBUG: Knocking at port 3689 on 10.0.10.100
2020-04-21 10:37:58 DEBUG: Knocking at port 7000 on 10.0.10.100
2020-04-21 10:37:58 DEBUG: Knocking at port 49152 on 10.0.10.100
2020-04-21 10:37:58 DEBUG: Knocking at port 32498 on 10.0.10.100
2020-04-21 10:37:58 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:37:59 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:38:00 DEBUG: Knocking at port 3689 on 10.0.10.100
2020-04-21 10:38:00 DEBUG: Knocking at port 7000 on 10.0.10.100
2020-04-21 10:38:00 DEBUG: Knocking at port 49152 on 10.0.10.100
2020-04-21 10:38:00 DEBUG: Knocking at port 32498 on 10.0.10.100
2020-04-21 10:38:00 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:38:01 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:38:02 DEBUG: Knocking at port 3689 on 10.0.10.100
2020-04-21 10:38:02 DEBUG: Knocking at port 7000 on 10.0.10.100
2020-04-21 10:38:02 DEBUG: Knocking at port 49152 on 10.0.10.100
2020-04-21 10:38:02 DEBUG: Knocking at port 32498 on 10.0.10.100
2020-04-21 10:38:02 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:38:03 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:38:04 DEBUG: Knocking at port 3689 on 10.0.10.100
2020-04-21 10:38:04 DEBUG: Knocking at port 7000 on 10.0.10.100
2020-04-21 10:38:04 DEBUG: Knocking at port 49152 on 10.0.10.100
2020-04-21 10:38:04 DEBUG: Knocking at port 32498 on 10.0.10.100
2020-04-21 10:38:04 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:38:05 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:38:06 DEBUG: Knocking at port 3689 on 10.0.10.100
2020-04-21 10:38:06 DEBUG: Knocking at port 7000 on 10.0.10.100
2020-04-21 10:38:06 DEBUG: Knocking at port 49152 on 10.0.10.100
2020-04-21 10:38:06 DEBUG: Knocking at port 32498 on 10.0.10.100
2020-04-21 10:38:06 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:38:07 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:38:08 DEBUG: Knocking at port 3689 on 10.0.10.100
2020-04-21 10:38:08 DEBUG: Knocking at port 7000 on 10.0.10.100
2020-04-21 10:38:08 DEBUG: Knocking at port 49152 on 10.0.10.100
2020-04-21 10:38:08 DEBUG: Knocking at port 32498 on 10.0.10.100
2020-04-21 10:38:08 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:38:09 DEBUG: Sending DNS request to 10.0.10.100 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65045f746370056c6f63616c0000ff80010e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-04-21 10:38:09 DEBUG: Received DNS response from 10.0.10.100 (Data=35ff840000030003000000090b5f6170706c6574762d7632045f746370056c6f63616c0000ff80010b5f746f7563682d61626c65c01800ff8001085f616972706c6179c01800ff8001c03a000c00010000000a00100d4170706c65c2a0545620283229c03ac028000c00010000000a00131032444632453735303736333943323639c028c00c000c00010000000a00131032444632453735303736333943323639c00cc055002100010000000a0012000000001b58094170706c6554562d32c01dc055001000010000000a00dc1a64657669636569643d37303a37333a43423a44363a34313a30391766656174757265733d307835413746464646372c307...)
2020-04-21 10:38:09 DEBUG: Cleaning up after UDNS request
2020-04-21 10:38:09 DEBUG: Cleaning up after UDNS request
2020-04-21 10:38:09 DEBUG: Auto-discovered Apple TV (2) at 10.0.10.100:7000 (Protocol.AirPlay)
2020-04-21 10:38:09 DEBUG: Auto-discovered Apple TV at 10.0.10.100:3689 (Protocol.DMAP)
2020-04-21 10:38:09 DEBUG: Auto-discovered Apple TV at 10.0.10.100:3689 (Protocol.DMAP)
2020-04-21 10:38:09 INFO: Auto-discovered Apple TV (2) at 10.0.10.100
2020-04-21 10:38:09 DEBUG: No AirPlay credentials loaded
2020-04-21 10:38:09 DEBUG: GET URL: http://10.0.10.100:3689/login?hsgid=yyy&hasFP=1
2020-04-21 10:38:09 DEBUG: Response: status=200, headers=[Date=Tue, 21 Apr 2020 08:40:07 GMT, DAAP-Server=iTunes/11.1b37 (OS X), Content-Type=application/x-dmap-tagged, Content-Length=47, Content-Encoding=gzip]
2020-04-21 10:38:09 DEBUG: << GET (Data=6d6c6f67000000186d73747400000004000000c86d6c69640000000440cb4693)
2020-04-21 10:38:09 DEBUG: _login_request: mlog: [container, dmap.loginresponse]
  mstt: 200 [uint, dmap.status]
  mlid: 1087063699 [uint, dmap.sessionid]

2020-04-21 10:38:09 INFO: Logged in and got session id 1087063699
2020-04-21 10:38:09 DEBUG: Already logged in, re-using seasion id 1087063699
2020-04-21 10:38:09 DEBUG: GET URL: http://10.0.10.100:3689/ctrl-int/1/playstatusupdate?session-id=1087063699&revision-number=0
2020-04-21 10:38:09 DEBUG: Response: status=200, headers=[Date=Tue, 21 Apr 2020 08:40:07 GMT, DAAP-Server=iTunes/11.1b37 (OS X), Content-Type=application/x-dmap-tagged, Content-Length=41, Content-Encoding=gzip]
2020-04-21 10:38:09 DEBUG: << GET (Data=636d7374000000186d73747400000004000000c8636d73720000000400000012)
2020-04-21 10:38:09 DEBUG: _get_request: cmst: [container, dmcp.playstatus]
  mstt: 200 [uint, dmap.status]
  cmsr: 18 [uint, dmcp.serverrevision]

  Media type: Unknown
Device state: Idle
      Repeat: Off
     Shuffle: Off
2020-04-21 10:38:09 DEBUG: Connection was closed properly
```

So I believe this is "solved" in some sense now. New issues will have to be created in case something doesn't work.
