### ISSUE TITLE
Error streaming camera to AppleTV

### ISSUE THREAD

**Issue by chrischerman** [postlund/pyatv#679]
**Describe the bug**
This has worked in previous version of the pyatv implementation via HACS, but has been broken in the last version or two.  I would try to install previous versions of the integration, but with the new HACS interface, I'm unsure of how to do that.  When working I'm able to stream a live camera feed to the AppleTV.  Currently I get the following errors (after I removed and readded the AppleTV within HA and restarted HA):

Log Details (ERROR)

Logger: homeassistant.core
Source: custom_components/apple_tv/media_player.py:192
First occurred: 10:06:41 AM (1 occurrences)
Last logged: 10:06:41 AM
Error executing service: <ServiceCall media_player.play_media (c:8f9394b72d9144779b73788801c4417b): entity_id=['media_player.apple_tv_upstairs'], media_type=application/vnd.apple.mpegurl, media_id=http://192.168.1.235:8123/api/hls/75813c2ae7ffcc9e5fc3dbc507f5f4cd963dac6eb08e4c71a2320405fb77bbe3/playlist.m3u8>

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1269, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/config/custom_components/apple_tv/media_player.py", line 192, in async_play_media
    await self.atv.stream.play_url(media_id)
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/__init__.py", line 98, in play_url
    return await self._play_task
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/player.py", line 46, in play_url
    data=plistlib.dumps(body, fmt=plistlib.FMT_BINARY),
  File "/usr/local/lib/python3.7/site-packages/pyatv/support/net.py", line 117, in post_data
    raise ex
  File "/usr/local/lib/python3.7/site-packages/pyatv/support/net.py", line 101, in post_data
    timeout=DEFAULT_TIMEOUT if timeout is None else timeout,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 582, in _request
    break
  File "/usr/local/lib/python3.7/site-packages/aiohttp/helpers.py", line 586, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

**To Reproduce**

Play camera stream to AppleTV

**Expected behavior**

Stream plays

**System Setup (please complete the following information):**
 - OS: Docker on top of Ubuntu
 - Python: 3.7
 - pyatv: 0.6.1 update 3
- Apple TV: Apple TV 4K tvOS 13.4

**Additional context**

**Comment by chrischerman** [comment]
This is the wrong project.

**Comment by chrischerman** [comment]
Maybe not, sorry.

**Comment by postlund** [comment]
Just to be sure, is the integration working properly (e.g. updating state of what is playing) when you start streaming?

**Comment by chrischerman** [comment]
It appears that I had some issues with AirPlay on the Apple TV.  After a reboot and some additional troubleshooting, it appears I have it going again.

**Comment by postlund** [comment]
Ok, "great" one might say. Just because I'm curious, did you see the airplay problems on other devices as well (if you tried that) or just with pyatv?

**Comment by chrischerman** [comment]
I was able to discover the airplay issue by using my iPhone and trying to Airplay to the AppleTV.  When it didn't work I figured I had other issues going on.  So I don't think it was anything to do with this integration.  Love this functionality, thanks for your help!

**Comment by postlund** [comment]
I have experienced similar situations with airplay as well in the past, it's not a 100% reliable. But at least good that a restart solved it.
