### ISSUE TITLE
Unable to prepare setup for platform apple_tv.media_player

### ISSUE THREAD

**Issue by bboudewijns** [postlund/pyatv#686]
**Describe the bug**
Unable to install the beta plugin. Installation trough HACS completes without issues. Afterward I can add the integration, the two pin codes appear on the TV, I enter them and immediately I get an error in home assistant. 

Logfile reads:
`2020-06-03 23:12:27 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform apple_tv.media_player: Platform not found (cannot import name 'MediaPlayerEntity' from 'homeassistant.components.media_player' (/usr/src/homeassistant/homeassistant/components/media_player/__init__.py)).`

```
2020-06-03 23:12:27 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Woonkamer for remote
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/remote/__init__.py", line 117, in async_setup_entry
    return await cast(EntityComponent, hass.data[DOMAIN]).async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 154, in async_setup_entry
    platform_type,
  File "/usr/src/homeassistant/homeassistant/setup.py", line 247, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 279, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/apple_tv/remote.py", line 24, in <module>
    class AppleTVRemote(remote.RemoteEntity):
AttributeError: module 'homeassistant.components.remote' has no attribute 'RemoteEntity'
```

**To Reproduce**

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: HassOS 109.6
 - Python: 3.7.7
 - pyatv: 0.6.1 Update 3
- Apple TV: Apple TV 4K tvOS 13.4

**Additional context**
Have had a temporary install of Chamberlain's apple-tv-mrp integration. But completely uninstalled before trying your integration.

Thank in advance.

**Comment by postlund** [comment]
You need to upgrade to Home Assistant 0.110. The beta will always target that version first and foremost.

**Comment by bboudewijns** [comment]
Thanks for your quick reply! I will try again in a few days. I had some issues with 0.110 last week so downgraded for the moment back to 109.

**Comment by postlund** [comment]
Sure thing! Should work after the upgrade.

**Comment by postlund** [comment]
Did you manage to test after an upgrade?

**Comment by bboudewijns** [comment]
I tried last week and indeed it is working now. Thanks a lot!
