### ISSUE TITLE
is not in any local subnet

### ISSUE THREAD

**Issue by robinostlund** [postlund/pyatv#690]
Hi,
I am running home assistant in docker in an own network.
The host that it is running on is on the same network as the apple tv but when i try to add the apple tv i get this:

```
2020-06-04 15:02:49 ERROR (MainThread) [custom_components.apple_tv.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/apple_tv/config_flow.py", line 143, in async_step_user
    await self.async_find_device()
  File "/config/custom_components/apple_tv/config_flow.py", line 217, in async_find_device
    self.unique_id, self.hass.loop, cache=self.scan_result
  File "/config/custom_components/apple_tv/config_flow.py", line 75, in device_scan
    scan_result = await scan(loop, hosts=hosts, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/pyatv/__init__.py", line 286, in scan
    devices = (await scanner.discover(timeout)).values()
  File "/usr/local/lib/python3.7/site-packages/pyatv/__init__.py", line 202, in discover
    *[self._get_services(host, timeout) for host in self.hosts]
  File "/usr/local/lib/python3.7/site-packages/pyatv/__init__.py", line 216, in _get_services
    self.loop, str(host), services, port=port, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/pyatv/support/udns.py", line 271, in request
    f"address {address} is not in any local subnet"
pyatv.exceptions.NonLocalSubnetError: address 192.168.XXX.XXX is not in any local subnet
```

Would it be possible to implement so it would be possible to add apple tvs on other subnets?

Brg
Robin

**Comment by postlund** [comment]
You can add Apple TVs on other subnets if they are discovered via Zeroconf, e.g. they are on the same subnet or you use an mDNS relayer of some sort. But it's not possible to add them using unicast scanning (like when you enter the IP address in the device field) due to restrictions in how zeroconf works (it is only meant to be used on a *local* network). Details are here (last paragraph):

https://pyatv.dev/documentation/concepts/#scanning

**Comment by postlund** [comment]
Not much I can do about this, so will close the issue. Feel free to re-open if you have additional questions.
