### ISSUE TITLE
tvOS 14 Broken pyatv.  Running v0.7.0

### ISSUE THREAD

**Issue by smarthomesydney** [postlund/pyatv#791]
**cli keeps crashing randomly after a few commands**

**install tvOS 14 and run cli from terminal.  after 2-5 commands.  the app crashes**

```
**pyatv> wake_up
2020-08-13 13:39:01 ERROR: Unknown command: wake_up
pyatv> wakeup  
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py:614: DeprecationWarning: Call to deprecated function wakeup.
  value = await tmp(*args)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 648, in _run_application
    return await cli_handler(loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 460, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 558, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 580, in _handle_device_command
    return await _exec_command(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 614, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 228, in cli
    await _handle_device_command(self.args, command, self.atv, self.loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 585, in _handle_device_command
    return await _exec_command(atv.remote_control, cmd, True, *cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 614, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 263, in wakeup
    await self._press_key("wakeup", InputAction.SingleTap)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 154, in _press_key
    await _do_press(keycode, False)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 137, in _do_press
    await self.protocol.send_and_receive(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 138, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 146, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

>>> An error occurred, full stack trace above**
```

**System Setup (please complete the following information):**
 - OS: OSX
 - Python: [e.g. 3.8.3 ]
 - pyatv: [e.g. 0.7.0]
- Apple TV: [Apple TV 4K tvOS 14 and Apple TV HD tvOS 14]

**It looks like code is broken.  wakeup, power_on/off, suspend.  The command is actioned, but the cli is broken post the below warning??

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py:614: DeprecationWarning: Call to deprecated function wakeup.**

**Comment by postlund** [comment]
How does it work with general commands, like play, pause, next, etc? Both `wake_up` and `suspend` are as you noted deprecated and will be removed soon. They don't work as expected so we should not consider them. It should however work with `turn_on`/`turn_off`, but there's a known issue where the device stops responding like this that I have not figured out yet. Would expect the same thing to happen on tvOS 13.

**Comment by smarthomesydney** [comment]
**Suspend still works if you can remove the warning or clean up code**
suspend still works and executes, but post working, cause the cli to close

pyatv> suspend
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py:614: DeprecationWarning: Call to deprecated function suspend.
  value = await tmp(*args)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 648, in _run_application
    return await cli_handler(loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 460, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 558, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 580, in _handle_device_command
    return await _exec_command(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 614, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 228, in cli
    await _handle_device_command(self.args, command, self.atv, self.loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 585, in _handle_device_command
    return await _exec_command(atv.remote_control, cmd, True, *cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 614, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 258, in suspend
    await self._press_key("suspend", InputAction.SingleTap)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 154, in _press_key
    await _do_press(keycode, False)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 137, in _do_press
    await self.protocol.send_and_receive(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 138, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 146, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError


**WAKE_UP doesn't work**
2020-08-13 19:14:51 ERROR: Unknown command: wake_up

**Turn_off and turn_on don't execute at all.**

**TURN OFF**
pyatv> turn_off
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py:531: DeprecationWarning: Call to deprecated function home_hold.
  await self.remote.home_hold()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 648, in _run_application
    return await cli_handler(loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 460, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 558, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 580, in _handle_device_command
    return await _exec_command(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 614, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 228, in cli
    await _handle_device_command(self.args, command, self.atv, self.loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 591, in _handle_device_command
    return await _exec_command(atv.power, cmd, True, *cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 614, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 531, in turn_off
    await self.remote.home_hold()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 249, in home_hold
    await self._press_key("home", InputAction.Hold)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 159, in _press_key
    await _do_press(keycode, True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 137, in _do_press
    await self.protocol.send_and_receive(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 138, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 146, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

>>> An error occurred, full stack trace above

**TURN_ON**

pyatv> turn_on
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 648, in _run_application
    return await cli_handler(loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 460, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 558, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 580, in _handle_device_command
    return await _exec_command(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 614, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 228, in cli
    await _handle_device_command(self.args, command, self.atv, self.loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 591, in _handle_device_command
    return await _exec_command(atv.power, cmd, True, *cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 614, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 524, in turn_on
    await self.protocol.send_and_receive(messages.wake_device())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 138, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 146, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

>>> An error occurred, full stack trace above

**Comment by smarthomesydney** [comment]
atvremote -n Vardagsrum -s 10.0.10.81 features

Feature list:
-------------
Up: Available
Down: Available
Left: Available
Right: Available
Play: Unavailable
PlayPause: Unavailable
Pause: Unavailable
Stop: Unavailable
Next: Unavailable
Previous: Unavailable
Select: Available
Menu: Available
VolumeUp: Unavailable
VolumeDown: Unavailable
Home: Available
HomeHold: Available
TopMenu: Available
SkipForward: Unavailable
SkipBackward: Unavailable
SetPosition: Unavailable
SetShuffle: Unavailable
SetRepeat: Unavailable
Title: Unavailable
Artist: Unavailable
Album: Unavailable
Genre: Unavailable
TotalTime: Unavailable
Position: Unavailable
Shuffle: Unavailable
Repeat: Unavailable
Artwork: Unavailable
App: Unavailable
PlayUrl: Available
PowerState: Available
TurnOn: Available
TurnOff: Available

**Comment by postlund** [comment]
What you are posting here is exactly the reason why `suspend` (and `wake_up`) are being deprecated: they don't work in the way one might expect. Sending suspend *will* put the device to some kind of sleep, but it is unclear how to actually wake it up properly again. From mine and other people's experience, if a device is suspended it will not be woken up when using the remote app for instance. In my case, not even the physical remote worked until I did `wake_up` again. The Apple TV doesn't seem to close the TCP connection properly when using the command either, that is why the cli hangs. Also, `suspend` does not work with CEC either, which a lot of people seem to be using.

**Comment by smarthomesydney** [comment]
Turn on, off don't appear to be working in the code with tvOS 14 and even after 2/3 play pause commands the cli crashes. 

I would use standard single commands.  But I see a 5 second delay on commands issues directly and not via the CLI

**Comment by smarthomesydney** [comment]
wakeup and suspend still work.  (**suspend** actually puts the ATV to sleep and can be woken up via wakeup or turn_on and iOS Remote App or IR)
turn_on still works
**turn_off is broken** and a weird one.  It only turns off the front LED.  the ATV continues to operate.  Pressing menu or home on the remote returns the LED.  

All commands seem to break your CLI.
Even play, pause after 2+ commands are requested.  Time out error and others.

**All the below error with direct command and kill CLI also.**
Up: Kills CLI first command, but works
Down: Kills CLI first command, but works.  Also caused screen to flicker (like someone was pressing up/down rapidly and physical remote didn't fix.  reboot needed.
Left: Kills CLI first command, also caused front led to go out.  Also caused screen to flicker and put ATV into continuous left action (like someone was pressing left key continuesly and physical remote did fix.
Right: Kills CLI first command, also caused front led to go out.  Also caused screen to flicker and put ATV into continuous left action (like someone was pressing right key continuesly and physical remote did fix.
Play: Works.  No Errors
play_pause: Works.  No Errors
Pause: Works.  No Errors
Stop: Execute with no errors, but no action taken
Next: Execute with no errors, but no action taken
Previous: Execute with no errors, but no action taken
Select: Boken and kils CLI
Menu: Kills CLI first command, but works
VolumeUp: Boken and kils CLI
VolumeDown: Boken and kils CLI
Home: Boken and kils CLI
HomeHold: Boken and kils CLI
top_menu: (equivalent to holding home key) brings up the side screen which shows time, date, users (which you can select/change user from this menu) Sleep all connected devices (which doesn't turn off TV), now playing, airplay devices and search
SkipForward: Execute with no errors, but no action taken
SkipBackward: Execute with no errors, but no action taken
SetPosition: Boken and kils CLI
SetShuffle: Boken and kils CLI
SetRepeat: Boken and kils CLI
Title: Works.  No Errors (only for Apple Music, not Spotify etc)
Artist: Works.  No Errors (only for Apple Music, not Spotify etc)
Album: Works.  No Errors (only for Apple Music, not Spotify etc)
Genre: Works.  No Errors (only for Apple Music, not Spotify etc)
Total_Time: executes, but no output
Position:  executes, but no output
Shuffle: works and shows shuffle on/off
Repeat: works and shows repeat on/off
Artwork: not tested
App: not tested
PlayUrl: not tested
power_state: works and shows power on/off
turn_on: Kills CLI first command, but works
turn_off: Broken and a weird one.  It only turns off the front LED.  the ATV continues to operate.  Pressing menu or home on the remote returns the LED.  

Do you need me to help out with logs, can I help with anything?

**Comment by smarthomesydney** [comment]
pyatv> turn_on
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 648, in _run_application
    return await cli_handler(loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 460, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 558, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 580, in _handle_device_command
    return await _exec_command(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 614, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 228, in cli
    await _handle_device_command(self.args, command, self.atv, self.loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 591, in _handle_device_command
    return await _exec_command(atv.power, cmd, True, *cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 614, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 524, in **turn_on**
    await self.protocol.send_and_receive(messages.wake_device())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 138, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 146, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError


**atvremote --id 60:13:3B:dD:D2:s4 --mrp-credentials xxxx home**
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 648, in _run_application
    return await cli_handler(loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 460, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 558, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 585, in _handle_device_command
    return await _exec_command(atv.remote_control, cmd, True, *cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 614, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 244, in home
    await self._press_key("home", action)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 154, in _press_key
    await _do_press(keycode, False)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 137, in _do_press
    await self.protocol.send_and_receive(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 138, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 146, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError


**atvremote --id 60:13:3B:dD:D2:s4 --mrp-credentials xxxx up**
2020-08-14 18:40:47 WARNING: Received ContentItemUpdate for unknown player com.apple.TVMusic
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 648, in _run_application
    return await cli_handler(loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 460, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 558, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 585, in _handle_device_command
    return await _exec_command(atv.remote_control, cmd, True, *cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 614, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 179, in up
    await self._press_key("up", action)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 154, in _press_key
    await _do_press(keycode, False)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 137, in _do_press
    await self.protocol.send_and_receive(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 138, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 146, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError


**atvremote --id 60:13:3B:dD:D2:s4 --mrp-credentials xxxx right**
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 648, in _run_application
    return await cli_handler(loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 460, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 558, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 585, in _handle_device_command
    return await _exec_command(atv.remote_control, cmd, True, *cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 614, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 191, in right
    await self._press_key("right", action)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 154, in _press_key
    await _do_press(keycode, False)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 137, in _do_press
    await self.protocol.send_and_receive(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 138, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 146, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

**Comment by postlund** [comment]
If the connection breaks when executing some of the basic commands, like `up` or `down`, then we have another problem that we should look into first. That should not happen. I guess calling commands one at the time with for instance `atvremote -s <ip> up` works? The `turn_off` turns of the device by navigating to sleep in action center (like when you long press menu and press select or so). If regular commands doesn't work properly I would guess this could fail to.

**Comment by evanreichard** [comment]
tvOS 14 doesn't appear to actually "ACK" the HID commands. (I don't know what this looks like on a non tvOS 14 box, though) It throws an exception on the receiving part and the ATV still thinks that the button is pressed down (cause it never gets to the button release command). Had to switch the HID commands from the protocol `def send_and_receive` to `def send` and (most things) work. `atvproxy` with my Apple Watch doesn't show any indication that the Apple TV "ACKS" the button presses, so this is probably a tvOS 14 thing.

Im slowly working on a fork that supports tvOS 14 [here](https://github.com/evanreichard/pyatv/l). As of now I have the following working (in atvremote):

- up / down / left / right
- play_pause / select / home
- volume_up / volume_down (CEC working)
- turn_on / turn_off (CEC working)
- wakeup / suspend (no CEC, as expected)
- playing / push_updates

For whatever reason my iPhone X (iOS 14 beta 3) / iPad Pro 3 (iOS 13.5) with the Command Center ATV Remote can't find the `atvproxy` instance, but my Apple Watch and the separate (outdated) App will - so debugging the more complicated things is difficult.

**Comment by evanreichard** [comment]
I have this issue even after rebooting my ATV4K iOS 14. Based on the logs, I believe this is due to using `send_and_receive` [here](https://github.com/postlund/pyatv/blob/master/pyatv/mrp/__init__.py#L137-L147). Switch to `send` and it works as desired for me.

Based on the logs I captured, I never saw a response. Not sure if it's an iOS 14 thing, or something else.

**Comment by postlund** [comment]
@evanreichard Sounds reasonable enough. Too bad they removed support for that though. Question is if this has always been the case for all release of tvOS 14 so far, or if it's really new. And will the behavior remain in the final release... I'm fine with moving to un-acknowledged mode, so I guess we can do that.

**Comment by postlund** [comment]
I created #800 that should solve this, please try it out. I'm not really sure about `power_off`, we might have to add a sleep there.

**Comment by evanreichard** [comment]
That works for me. `turn_off` and `turn_on` both work as well (with CEC, too - properly turning my TV and Receiver on/off)

However, `turn_on` throws a `concurrent.futures._base.TimeoutError` exception due to [this line](https://github.com/postlund/pyatv/blob/no_ack_hid/pyatv/mrp/__init__.py#L524). Changing that to just `send` allows it to work without throwing the exception.

**Comment by postlund** [comment]
It's so strange that they made this change, but I guess we'll just have to adapt. Made the suggested change and pushed and update, so it should hopefully work now. Feel free to re-test! I'm gonna verify with tvOS 13 later tonight.

**Comment by postlund** [comment]
Tested on tvOS 13 and it works fine. Will merge PR once it passes.

**Comment by postlund** [comment]
@smarthomesydney Should be fixed on master now. Please give it a spin!
