### ISSUE TITLE
mdns errors

### ISSUE THREAD

**Issue by tommyjlong** [postlund/pyatv#809]
**Describe the bug**
At HA restart, getting pyatv mdns.py error that is repeated several times (36 times).
Very repeatable.

**To Reproduce**

**Expected behavior**
No errors.  Don't recall seeing these errors prior to upgrading to latest custom component.

**System Setup (please complete the following information):**
 - OS: [e.g. Debian] Ubuntu 18.0.4
 - Python: [e.g. 3.6.2] 3.7.5
 - pyatv: [e.g. 0.3.10] 0.3.7.1;  
 - HACS Custom Apple TV Beta component version: 31c334e; HA 0.114.2.
- Apple TV: [e.g. Apple TV 4K tvOS 13.4] 4th Gen AppleTV; tv0S 13.4.8

**Additional context**
Log Output
```
2020-08-18 13:54:06 ERROR (MainThread) [pyatv.support.mdns] exception during data handling
Traceback (most recent call last):
  File "/opt/homeassistant/venv_3.7/lib/python3.7/site-packages/pyatv/support/mdns.py", line 384, in datagram_received
    delegate.datagram_received(data, addr)
  File "/opt/homeassistant/venv_3.7/lib/python3.7/site-packages/pyatv/support/mdns.py", line 483, in datagram_received
    services = parse_services(DnsMessage().unpack(data))
  File "/opt/homeassistant/venv_3.7/lib/python3.7/site-packages/pyatv/support/mdns.py", line 180, in unpack
    raise NotImplementedError("nscount > 0")
NotImplementedError: nscount > 0
```

**Comment by postlund** [comment]
They should not be harmful in any way, but annoying to see in the log. It is fixed in #802 and will be fixed once I push a release and update the component.

**Comment by postlund** [comment]
Update pushed with bumped pyatv version, which includes #802. Please give it a try and close this issue if it works!

**Comment by tommyjlong** [comment]
The exceptions reported earlier are no longer present.

The following may not be related, but just in case, I wanted to report that I do see the following 
(Note: 172.17.0.1 is an invalid address on my network):
```
........snipped....
2020-08-24 13:24:20 DEBUG (MainThread) [pyatv.support.net] Binding on 172.17.0.1:0
2020-08-24 13:24:20 DEBUG (MainThread) [pyatv.support.mdns] Adding socket <socket.socket fd=68, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('172.17.0.1', 55122)>
2020-08-24 13:24:20 DEBUG (MainThread) [pyatv.support.net] Binding on 172.17.0.1:0
2020-08-24 13:24:20 DEBUG (MainThread) [pyatv.support.mdns] Adding socket <socket.socket fd=70, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('172.17.0.1', 40046)>
2020-08-24 13:24:20 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
2020-08-24 13:24:20 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
2020-08-24 13:24:21 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
2020-08-24 13:24:21 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
2020-08-24 13:24:21 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
2020-08-24 13:24:21 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
2020-08-24 13:24:22 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
2020-08-24 13:24:22 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
2020-08-24 13:24:22 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
2020-08-24 13:24:22 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
2020-08-24 13:24:23 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
2020-08-24 13:24:23 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
2020-08-24 13:24:23 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
2020-08-24 13:24:23 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
2020-08-24 13:24:23 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
2020-08-24 13:24:23 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
2020-08-24 13:24:24 DEBUG (MainThread) [pyatv.support.mdns] Error during MDNS lookup: [Errno 22] Invalid argument
```

**Comment by postlund** [comment]
That's good 👍

Yeah, I've seen them too. I do believe they have something to do with certain interfaces not supporting multicast or something. I will look into that in due time. I assume you run in docker? The 172.17.x.x range is usually used inside the docker container.

**Comment by tommyjlong** [comment]
Thanks. I'll look into docker.  I think I have one instance still running that I no longer use.  I'll go ahead and close this.
