### ISSUE TITLE
Airplay service is not available with TTS

### ISSUE THREAD

**Issue by RienduPre** [postlund/pyatv#845]
I get the error below when I use TTS with Airplay.

`Logger: homeassistant.components.websocket_api.http.connection.2851336424
Source: custom_components/apple_tv/media_player.py:192
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:47:35 PM (9 occurrences)
Last logged: 2:25:23 PM

AirPlay service is not available
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 180, in async_say_handle
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 459, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 655, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 490, in _handle_entity_call
    await result
  File "/config/custom_components/apple_tv/media_player.py", line 192, in async_play_media
    await self.atv.stream.play_url(media_id)
  File "/usr/local/lib/python3.8/site-packages/pyatv/airplay/__init__.py", line 81, in play_url
    raise exceptions.NotSupportedError("AirPlay service is not available")
pyatv.exceptions.NotSupportedError: AirPlay service is not available
Connection lost. Reconnecting…
`

I Run HASSIO on a RPI4 with all the latest version of the related software

**Comment by postlund** [comment]
It means the AirPlay service was not found when setting up the integration. Is it enabled properly on your Apple TV? Does it work on other devices?

**Comment by RienduPre** [comment]
Yes, I have no issues with Airplay at all, besides with this add-on.

I deinstalled the plugin and now TTS is working (in combination with Forked-daapd)

**Comment by postlund** [comment]
Hmm, that's strange. Did you get to enter a pin code for AirPlay when adding a device?

**Comment by postlund** [comment]
Bump
