### ISSUE TITLE
Decode errors in MDNS responses

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#853]
**Describe the bug**
Sometimes the following exception appears:

```
2020-10-08 07:33:10 ERROR (MainThread) [pyatv.support.mdns] exception during data handling
Traceback (most recent call last):
  File "/ha/pyatv/pyatv/support/mdns.py", line 399, in datagram_received
    delegate.datagram_received(data, addr)
  File "/ha/pyatv/pyatv/support/mdns.py", line 501, in datagram_received
    services = parse_services(DnsMessage().unpack(data))
  File "/ha/pyatv/pyatv/support/mdns.py", line 186, in unpack
    ptr, data = unpack_rr(ptr, msg)
  File "/ha/pyatv/pyatv/support/mdns.py", line 149, in unpack_rr
    rd_data, _ = qname_decode(rd_data, msg)
  File "/ha/pyatv/pyatv/support/mdns.py", line 103, in qname_decode
    return ".".join([x.decode("utf-8") for x in name_components]), rest[1:]
  File "/ha/pyatv/pyatv/support/mdns.py", line 103, in <listcomp>
    return ".".join([x.decode("utf-8") for x in name_components]), rest[1:]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 45: invalid start byte
```

I probably lack support for something. For the time being I will suppress it (but log) in order to lessen the spam.

**To Reproduce**
It happens from time to time when scanning. I guess it's from another device on the network, so it depends on if it responds or not.

**Expected behavior**
No exception.

**System Setup (please complete the following information):**
 - OS: any
 - Python: any
 - pyatv: 0.7.0-
- Apple TV: Apple TV 4K tvOS 14.0.1

**Additional context**

**Comment by postlund** [comment]
I'll close this as it probably isn't relevant anymore with changes from @paxswill.
