### ISSUE TITLE
inspect.getargspec has been deprecated

### ISSUE THREAD

**Issue by balloob** [postlund/pyatv#891]
**Describe the bug**

https://docs.python.org/3/library/inspect.html#inspect.getargspec

`inspect.getargspec` has been depreacted since Python 3.0 and causes the following error:

```
 venv/lib/python3.7/site-packages/pyatv/support/__init__.py:19
venv/lib/python3.7/site-packages/pyatv/support/__init__.py:19
  /__w/core/core/venv/lib/python3.7/site-packages/pyatv/support/__init__.py:19: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
    _HAS_PRINT_UNKNOWN = "print_unknown_fields" in inspect.getargspec(MessageToString).args
```

**To Reproduce**

```
$ python3 -Werror -c'from pyatv import support'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/paulus/dev/hass/core/venv/lib/python3.8/site-packages/pyatv/__init__.py", line 10, in <module>
    from pyatv import conf, exceptions, interface
  File "/home/paulus/dev/hass/core/venv/lib/python3.8/site-packages/pyatv/conf.py", line 15, in <module>
    from pyatv.support.device_info import lookup_model, lookup_version
  File "/home/paulus/dev/hass/core/venv/lib/python3.8/site-packages/pyatv/support/__init__.py", line 19, in <module>
    _HAS_PRINT_UNKNOWN = "print_unknown_fields" in inspect.getargspec(MessageToString).args
  File "/usr/lib/python3.8/inspect.py", line 1077, in getargspec
    warnings.warn("inspect.getargspec() is deprecated since Python 3.0, "
DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
```

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: [e.g. Debian]
 - Python: [e.g. 3.6.2]
 - pyatv: [e.g. 0.3.10]
- Apple TV: [e.g. Apple TV 4K tvOS 13.4]

**Additional context**

**Comment by postlund** [comment]
You can bump pyatv to 0.7.4 to fix this now if you want, or just wait a day or two until I make a new release with some bug fixes I would like included for 1.0.

**Comment by balloob** [comment]
I can wait :) It's just something I noticed in the CI output and I'm trying to get our warnings down.

**Comment by postlund** [comment]
New release out and PR open for a bump:

https://github.com/home-assistant/core/pull/44051

**Comment by postlund** [comment]
We should be able to close this, no?

**Comment by balloob** [comment]
Thanks 👍
