### ISSUE TITLE
Yet another TimeoutError problem

### ISSUE THREAD

**Issue by mschwartz** [postlund/pyatv#929]
**Describe the bug**

```
atvremote -n THEATER playing
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 489, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mschwartz/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 657, in _run_application
    return await cli_handler(loop)
  File "/home/mschwartz/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 469, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/home/mschwartz/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 561, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol)
  File "/home/mschwartz/.local/lib/python3.9/site-packages/pyatv/__init__.py", line 76, in connect
    await atv.connect()
  File "/home/mschwartz/.local/lib/python3.9/site-packages/pyatv/mrp/__init__.py", line 704, in connect
    await self._protocol.start()
  File "/home/mschwartz/.local/lib/python3.9/site-packages/pyatv/mrp/protocol.py", line 66, in start
    self.device_info = await self.send_and_receive(msg)
  File "/home/mschwartz/.local/lib/python3.9/site-packages/pyatv/mrp/protocol.py", line 138, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/home/mschwartz/.local/lib/python3.9/site-packages/pyatv/mrp/protocol.py", line 146, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 491, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

>>> An error occurred, full stack trace above
2021-01-13 15:21:14 ERROR: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5003e87cd0>
```

**To Reproduce**

This is a 4K AppleTV.  This code worked a few days ago, maybe stopped when  I rebooted my Mac.

**Expected behavior**

Should show now playing info

**System Setup (please complete the following information):**
 - OS: [e.g. Debian] MacOS Big Sur
 - Python: [e.g. 3.6.2]
 - pyatv: [e.g. 0.3.10]
- Apple TV: [e.g. Apple TV 4K tvOS 14.2]

**Additional context**

```
atvremote scan
Scan Results
========================================
       Name: THEATER
   Model/SW: 4K tvOS 14.3 build 18K561
    Address: 192.168.100.14
        MAC: 40:CB:C0:C2:6A:12
 Deep Sleep: False
Identifiers:
 - 40:CB:C0:C2:6A:12
 -
Services:
 - Protocol: AirPlay, Port: 7000, Credentials: None
 - Protocol: MRP, Port: 53630, Credentials: None
```

Note that I don't see an identifier like I do with the other ATVs on my network.  Just a MAC address.

**Comment by mschwartz** [comment]
A second 4K ATV works fine.

**Comment by mschwartz** [comment]
Rebooting my ATVs seems to have fixed this.

Good for future reference.
