### ISSUE TITLE
Power cycled Apple TV, now cant control it.

### ISSUE THREAD

**Issue by victorsarkisyan** [postlund/pyatv#996]
**Describe the bug**
Apple TV is no longer being controlled and I get an error in HASS server logs. I tried removing the integration and restarted services, didnt help. I removed integration and then rebooted HASS and that didnt help. 

When I try to readd the integration it detects the Apple TV and then when it asks me to submit to show me the pin codes on the apple tv, the modal spins and spins then says Aborted.
```log
Logger: homeassistant.components.apple_tv.config_flow
Source: components/apple_tv/config_flow.py:247
Integration: Apple TV (documentation, issues)
First occurred: 9:41:58 PM (2 occurrences)
Last logged: 9:43:16 PM

Authentication problem
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 177, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyatv/support/__init__.py", line 31, in error_handler
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyatv/mrp/auth.py", line 34, in start_pairing
    await self.protocol.start(skip_initial_messages=True)
  File "/usr/local/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 92, in start
    self.device_info = await self.send_and_receive(msg)
  File "/usr/local/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 169, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/usr/local/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 180, in _receive
    del self._outstanding[identifier]
KeyError: '658731F6-57D5-48B0-8926-07D95132E0AC'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/config_flow.py", line 247, in async_begin_pairing
    await self.pairing.begin()
  File "/usr/local/lib/python3.8/site-packages/pyatv/support/__init__.py", line 39, in error_handler
    raise fallback(str(ex)) from ex
pyatv.exceptions.PairingError: '658731F6-57D5-48B0-8926-07D95132E0AC'
```
**To Reproduce**

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: Home Assistant Image on VM
 - Python: 3.8
 - pyatv: Unknown
- Apple TV: Apple TV HD

**Additional context**

**Comment by postlund** [comment]
Do you get any other errors in the log? Can't tell much from this. Would be great if you enabled debug logs for at least `pyatv` so I can help troubleshoot further.

**Comment by victorsarkisyan** [comment]
I turned off airplay from the apple tv settings and turned it back on and then was able to reauthenticate to HA again. Thanks!

**Comment by mikesalz** [comment]
This sounds very similar to this issue -
https://github.com/home-assistant/core/issues/48901

**Comment by Ripper2909** [comment]
> I turned off airplay from the apple tv settings and turned it back on and then was able to reauthenticate to HA again. Thanks!

Hi, did it completely fix the issue since your post ? Thanks

**Comment by victorsarkisyan** [comment]
> > I turned off airplay from the apple tv settings and turned it back on and then was able to reauthenticate to HA again. Thanks!
> 
> Hi, did it completely fix the issue since your post ? Thanks

Yes this did. I've been able to control apple TV since removing airplay and reenacting it
